### ISSUE TITLE
Crash when loading the world (server)

### ISSUE THREAD

**Issue by quantumsheep** [rwtema/extrautilities_old_issues#1016]
I'm changing the version from alpha-1.0.1 to alpha-1.1.0a on my server but when I connect on the server I get this error:

`[Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassCastException: net.minecraft.block.state.BlockStateContainer$StateImplementation cannot be cast to com.rwtema.extrautils2.backend.model.XUBlockState
    at com.rwtema.extrautils2.tile.XUTile.getBlockState(XUTile.java:179) ~[XUTile.class:?]
    at com.rwtema.extrautils2.tile.XUTile.markForUpdate(XUTile.java:305) ~[XUTile.class:?]
    at com.rwtema.extrautils2.tile.TileCrafter.preOperate(TileCrafter.java:272) ~[TileCrafter.class:?]
    at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:48) ~[TileAdvInteractor.class:?]
    at net.minecraft.world.World.func_72939_s(World.java:1804) ~[aid.class:?]
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619) ~[ls.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
    ... 4 more`

Crash Report: http://pastebin.com/ekrwZUPS

I've deleted the block with the coordinates but I think there is anothers blocks like them in the world... Need to fix!

**Comment by xChitose** [comment]
Quick question: Does this happen upon loading a new world?

**Comment by quantumsheep** [comment]
Nope, just the world with the older version

**Comment by quantumsheep** [comment]
I think this guy have the same error: https://github.com/rwtema/extrautilities/issues/1012

**Comment by xChitose** [comment]
My guess is that if it doesn't happen in a new world, then it can't be a block that is generated in the world. 

If you can remember which blocks / setup you were using in extrautils2, can you reproduce the error? 

Also, it could be more than one block depending on what you've said from your previous comment.

**Comment by quantumsheep** [comment]
When I've do the modpack update, the server had a lot of ID error (http://imgur.com/a/74rYf).
Same in singleplayer.

If I can found where this problem come from, I think I can fix the error with ExtraUtils2

**Comment by quantumsheep** [comment]
Same error if I delete all the configs files...

**Comment by xChitose** [comment]
So, you went into a new world, and was able to get the same error, am I correct?

**Comment by quantumsheep** [comment]
Ok, i've try some stuff, the error seems came from a Crafter with him ID changed (ID error I get). ExtraUtils2 try to see if this block had a configuration (Inventory, redstone mode, etc..). Because the IDs get changed, ExtraUtils can't reconize the block and crash...

Sorry if I've used bad English, I don't speak english perfectly :p

**Comment by quantumsheep** [comment]
I try do reproduce the error and I get an error from Immerssive Engineering xD

I think this is just the ID error ;)
I'm trying to fix it and I tell you if I can!

**Comment by xChitose** [comment]
You're fine! 

I just know how annoying ticking block entity errors can be. 

And also, if it is the crafter, try the new world and see if using the crafter causes the crash.

**Comment by quantumsheep** [comment]
The crafter doesn't crash if the world is created from the newer version, I'm sure that's this ID glitch!

**Comment by xChitose** [comment]
It is possible that the ID changes since ver. 1.1.0a adds a ton of new blocks and features, so it's safe to say that if you want to play the new version, you'll have to open a new world.

**Comment by quantumsheep** [comment]
Anyway that's crazy, 1.10.2 don't use numeric ID but letters ID, it sould not doing that! I try with the older version and I tell you

**Comment by xChitose** [comment]
What do you mean letter id?

**Comment by quantumsheep** [comment]
like minecraft:air, before the 1.7.10, that's "0"

**Comment by xChitose** [comment]
Yeah that's the item name but the id is still 0 and stone is still 1 according to the 1.10.2 documents.

**Comment by xChitose** [comment]
For example, Stone, Granite, Diorite, etc all are classified under stone and all share the id 1, but their data values are different (1, 2, 3, etc).

**Comment by quantumsheep** [comment]
I've found the problem!!!! Chisel have backwarded the versions, that's why I get the errors, you mod is perfectly coded :p

**Comment by quantumsheep** [comment]
these are metada not ID

**Comment by quantumsheep** [comment]
https://minecraft.curseforge.com/projects/chisel?comment=187

**Comment by quantumsheep** [comment]
That's the error! Thanks chisel :(

**Comment by quantumsheep** [comment]
https://minecraft.curseforge.com/projects/chisel?comment=178

**Comment by xChitose** [comment]
Glad you've found the issue!

**Comment by quantumsheep** [comment]
I found the issue but Chisel can't be updated because it's not on Curse T-T

**Comment by xChitose** [comment]
Really? 

You sure it's not just a version that isn't listed on curse?

**Comment by quantumsheep** [comment]
Yea i'm sure, that's a deleted version... Idk why they do that cuz I have no issue with it...

I think a big glitch that corrupt the world but why deleting the version? :(

**Comment by xChitose** [comment]
I suppose so people wouldn't accidently upgrade/downgrade and corrupt their worlds.

**Comment by quantumsheep** [comment]
anyway, that's fixed! https://github.com/Chisel-Team/Chisel/issues/252#issuecomment-252454453
