### ISSUE TITLE
Crash Log when placing Quantum Quarry Version 1.10.2 Alpha 1.1.0b

### ISSUE THREAD

**Issue by Cycomantis** [rwtema/extrautilities_old_issues#1026]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.15-ex110.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/10/16 10:40 AM
Description: Unexpected error

java.lang.NoClassDefFoundError: com/rwtema/extrautils2/power/energy/XUEnergyStorage
    at com.rwtema.extrautils2.quarry.TileQuarry.<init>(TileQuarry.java:84)
    at com.rwtema.extrautils2.quarry.BlockQuarry.createTileEntity(BlockQuarry.java:90)
    at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:621)
    at net.minecraft.world.World.func_180501_a(World.java:331)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:165)
    at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:454)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.rwtema.extrautils2.power.energy.XUEnergyStorage
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 21 more
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/energy/EnergyStorage
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 23 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.energy.EnergyStorage
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 27 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.rwtema.extrautils2.quarry.TileQuarry.<init>(TileQuarry.java:84)
    at com.rwtema.extrautils2.quarry.BlockQuarry.createTileEntity(BlockQuarry.java:90)
    at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:621)
    at net.minecraft.world.World.func_180501_a(World.java:331)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:165)
    at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54)
    at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:454)
    at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
    at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
    at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['Cycomantis'/97, l='MpServer', x=-518.86, y=64.00, z=566.60]]
    Chunk stats: MultiplayerChunkCache: 571, 571
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-485,4,563), Chunk: (at 11,0,3 in -31,35; contains blocks -496,0,560 to -481,255,575), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
    Level time: 3518 game time, 3518 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 47 total; [EntityBat['Bat'/9089, l='MpServer', x=-555.32, y=50.10, z=621.20], EntityVillager['Villager'/66, l='MpServer', x=-446.56, y=65.00, z=527.49], EntityVillager['Villager'/67, l='MpServer', x=-447.47, y=65.00, z=551.28], EntityItem['item.tile.sapling.oak'/24583, l='MpServer', x=-506.88, y=70.00, z=586.88], EntityBat['Bat'/9, l='MpServer', x=-590.25, y=12.10, z=521.25], EntityBat['Bat'/10, l='MpServer', x=-590.25, y=12.10, z=521.25], EntityItem['item.tile.flower2.tulipOrange'/12, l='MpServer', x=-564.78, y=64.00, z=581.49], EntityItem['item.tile.sapling.oak'/2764, l='MpServer', x=-507.08, y=70.00, z=589.93], EntityItem['item.tile.flower2.tulipWhite'/13, l='MpServer', x=-565.67, y=64.00, z=579.77], EntityChicken['Chicken'/14, l='MpServer', x=-574.83, y=64.00, z=622.33], EntityChicken['Chicken'/17, l='MpServer', x=-550.50, y=64.00, z=619.50], EntityBat['Bat'/18, l='MpServer', x=-550.85, y=46.10, z=639.34], EntityItem['item.item.seeds'/19, l='MpServer', x=-529.32, y=64.00, z=582.32], EntityItem['item.item.seeds'/20, l='MpServer', x=-525.72, y=64.00, z=584.80], EntityItem['item.item.seeds'/21, l='MpServer', x=-526.92, y=64.00, z=584.90], EntityBat['Bat'/24853, l='MpServer', x=-590.59, y=12.00, z=521.25], EntitySquid['Squid'/22, l='MpServer', x=-522.40, y=62.00, z=591.60], EntityPig['Pig'/23, l='MpServer', x=-527.38, y=64.00, z=616.71], EntityBat['Bat'/13079, l='MpServer', x=-590.66, y=11.10, z=520.37], EntityItem['item.tile.flower2.houstonia'/24, l='MpServer', x=-521.80, y=63.00, z=625.66], EntityItem['item.tile.sapling.oak'/30, l='MpServer', x=-510.13, y=64.00, z=587.13], EntityChicken['Chicken'/31, l='MpServer', x=-503.50, y=64.00, z=637.50], EntityChicken['Chicken'/34, l='MpServer', x=-480.50, y=64.00, z=501.50], EntityVillager['Villager'/35, l='MpServer', x=-480.27, y=65.00, z=539.50], EntityVillager['Villager'/36, l='MpServer', x=-491.48, y=64.00, z=535.43], EntityVillager['Villager'/37, l='MpServer', x=-492.41, y=65.00, z=529.76], EntityVillager['Villager'/38, l='MpServer', x=-493.47, y=64.94, z=528.40], EntityVillager['Villager'/39, l='MpServer', x=-487.66, y=64.00, z=544.59], EntityVillager['Villager'/40, l='MpServer', x=-470.70, y=67.00, z=523.30], EntityVillager['Villager'/41, l='MpServer', x=-474.62, y=63.94, z=540.45], EntityVillager['Villager'/42, l='MpServer', x=-473.42, y=64.00, z=539.51], EntityVillager['Villager'/43, l='MpServer', x=-454.64, y=64.00, z=544.59], EntityItem['item.item.potatoPoisonous'/44, l='MpServer', x=-478.52, y=65.00, z=565.61], EntityVillager['Villager'/45, l='MpServer', x=-475.88, y=65.00, z=569.30], EntityVillager['Villager'/46, l='MpServer', x=-479.49, y=64.94, z=561.71], EntityBat['Bat'/8942, l='MpServer', x=-558.30, y=49.97, z=620.00], EntityVillager['Villager'/47, l='MpServer', x=-479.42, y=64.94, z=560.48], EntityVillager['Villager'/51, l='MpServer', x=-459.50, y=65.00, z=528.50], EntityVillager['Villager'/52, l='MpServer', x=-463.50, y=64.00, z=530.63], EntityVillager['Villager'/53, l='MpServer', x=-457.50, y=66.00, z=541.50], EntityVillager['Villager'/54, l='MpServer', x=-449.50, y=65.00, z=528.50], EntityVillager['Villager'/55, l='MpServer', x=-449.33, y=64.00, z=537.50], EntityVillager['Villager'/56, l='MpServer', x=-452.69, y=64.94, z=556.46], EntityVillager['Villager'/57, l='MpServer', x=-451.37, y=64.94, z=556.51], EntityVillager['Villager'/58, l='MpServer', x=-464.38, y=63.94, z=567.32], EntitySquid['Squid'/26299, l='MpServer', x=-526.50, y=63.00, z=590.50], EntityPlayerSP['Cycomantis'/97, l='MpServer', x=-518.86, y=64.00, z=566.60]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 4698977336 bytes (4481 MB) / 5967446016 bytes (5691 MB) up to 5967446016 bytes (5691 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -Xms6G
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2073 30 mods loaded, 30 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2073.jar) 
    UCHIJAAAA   Forge{12.18.1.2073} [Minecraft Forge](forge-1.10.2-12.18.1.2073.jar) 
    UCHIJAAAA   bagginses{2.4.2d} [Bagginses](Bagginses-1.10.2-3.0.4b.jar) 
    UCHIJAAAA   Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7.jar) 
    UCHIJAAAA   chisel{MC1.9.4-0.0.6.33} [Chisel](Chisel-MC1.9.4-0.0.6.33.jar) 
    UCHIJAAAA   chiselsandbits{12.1} [Chisels & Bits](chiselsandbits-12.1.jar) 
    UCHIJAAAA   IC2{2.6.15-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.15-ex110.jar) 
    UCHIJAAAA   CompactSolars{5.0.4.328} [Compact Solar Arrays](CompactSolars-1.10.2-5.0.4.328-universal.jar) 
    UCHIJAAAA   ComputerCraft{1.80pr0} [ComputerCraft](ComputerCraft1.80pr0.jar) 
    UCHIJAAAA   D3Core{1.3.0.59} [DÂ³Core](D3Core-1.9.4-1.3.0.59.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.54-beta} [EnderCore](EnderCore-1.10.2-0.4.1.54-beta.jar) 
    UCHIJAAAA   JEI{3.9.3.252} [Just Enough Items](jei_1.10.2-3.9.3.252.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.107_beta} [Ender IO](EnderIO-1.10.2-3.0.1.107_beta.jar) 
    UCHIJAAAA   shetiphiancore{3.3.0} [ShetiPhian-Core](shetiphiancore-1.10.0-3.3.0.jar) 
    UCHIJAAAA   endertanks{1.4.1} [EnderTanks](endertanks-1.10.0-1.4.1.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.1.0b.jar) 
    UCHIJAAAA   ftbl{2.1.0} [FTBLib](FTBLib-1.9.4-2.1.0-pre3.jar) 
    UCHIJAAAA   ftbu{2.1.0} [FTBUtilities](FTBUtilities-1.9.4-2.1.0-pre3.jar) 
    UCHIJAAAA   gravestone{1.5.5} [Gravestone](GraveStone Mod 1.5.5.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   ironchest{1.10.2-7.0.9.796} [Iron Chest](ironchest-1.10.2-7.0.9.796.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJAAAA   jeresources{0.4.8.48} [Just Enough Resources](JustEnoughResources-1.10.2-0.4.8.48.jar) 
    UCHIJAAAA   Lumberjack{1.3.1.39} [Lumberjack](Lumberjack-1.9.4-1.3.1.39.jar) 
    UCHIJAAAA   ProjectE{1.10.2-PE1.0.6B} [ProjectE](ProjectE-1.10.2-PE1.0.6B.jar) 
    UCHIJAAAA   rftools{5.22} [RFTools](rftools-1.10-5.22.jar) 
    UCHIJAAAA   StorageDrawers{1.10.2-3.2.7} [Storage Drawers](StorageDrawers-1.10.2-3.2.7.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.8} [Waila Harvestability](WailaHarvestability-mc1.10.2-1.1.8.jar) 
    Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.15-ex110.jar)

FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 373.06' Renderer: 'GeForce GT 750M/PCIe/SSE2'
    D3Core: Debug: false Silliness: true AprilFools: true PastPost:true
    EnderIO: No known problems detected.
    Detailed RF API diagnostics:
                  \* RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/EnergyStorage.class
                  \* RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/IEnergyConnection.class
                  \* RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/IEnergyContainerItem.class
                  \* RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/IEnergyHandler.class
                  \* RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/IEnergyProvider.class
                  \* RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/IEnergyReceiver.class
                  \* RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/IEnergyStorage.class
                  \* RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/ItemEnergyContainer.class
                  \* RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/TileEnergyHandler.class
                  \* RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Warren/AppData/Roaming/.minecraft/mods/mcjtylib-1.10-2.0.2.jar!/cofh/api/energy/TileEnergyHandler.class

```
Launched Version: 1.10.2-forge1.10.2-12.18.1.2073
LWJGL: 2.9.4
OpenGL: GeForce GT 750M/PCIe/SSE2 GL version 4.5.0 NVIDIA 373.06, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-4702MQ CPU @ 2.20GHz
```

**Comment by Cycomantis** [comment]
Forge Bug, fixed in current version.
