### ISSUE TITLE
[1.10.2] Losing Access To Mechanical Crafters & Quarries

### ISSUE THREAD

**Issue by nephatrine** [rwtema/extrautilities_old_issues#1028]
This may end up being the same root cause as issue #1023 as they are both regarding access issues, but I'm having a slightly different issue than reported there. When clients connect to the server they sometimes are losing access to their ExU2 machinery (Mechanical Crafters and Quarries mostly are what we're trying to use). This does not occur every single time and seems intermittent. I think the issue is this error which occurs as they leave the server (again, not every time):

```
[15:23:06] [Server thread/ERROR] [FML]: A TileEntity XU2:TileCrafter(com.rwtema.extrautils2.tile.TileCrafter) has thrown an exception during loading, its state cannot be restored. Report this to the mod author
java.lang.NullPointerException
        at com.rwtema.extrautils2.utils.datastructures.NBTSerializable$NBTEnum.deserializeNBT(NBTSerializable.java:215) ~[NBTSerializable$NBTEnum.class:?]
        at com.rwtema.extrautils2.utils.datastructures.NBTSerializable$NBTEnum.deserializeNBT(NBTSerializable.java:197) ~[NBTSerializable$NBTEnum.class:?]
        at com.rwtema.extrautils2.tile.XUTile.func_145839_a(XUTile.java:123) ~[XUTile.class:?]
        at com.rwtema.extrautils2.tile.TilePower.func_145839_a(TilePower.java:80) ~[TilePower.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
```

Once that happens then when they log back in they cannot access the blocks.

Maybe until it is resolved can we get a config option to just disable the protection/xu_powersharing entirely? We're a cooperative server and it's just a hindrance to us anyways.

Using extrautils2-1.10.2-alpha-1.1.0b and forge 12.18.1.2094.

**Comment by ghost** [comment]
I'm having the same issue. Every time I log back in to my world all of my "Mechanical" blocks deny me access. Breaking them resets their ownership. However, since **upgrades are lost** with block breaks it's getting quite annoying.

**Comment by nephatrine** [comment]
Yeah, another user on my server lost a silk touch enchant he had on the quarry because he had to break and replace it.

**Comment by SeasonalFerret** [comment]
Is this not added yet? I've got a private server between just me and my friend that I leave on for him, but turn off when we're both offline. That means when I get on in the morning and it's just me, I have no access to any of our mechanical blocks and I have to loose the upgrades every day or just wait until he gets on so he can give me access.

When will we get a config option to disable this xu_powersharing bullcrap entirely?
