### ISSUE TITLE
Crash When any Version Above 1.0.1 is Added with Random Things

### ISSUE THREAD

**Issue by cjburkey01** [rwtema/extrautilities_old_issues#1032]
Random things seems to work unless any Extra Utilities version above 1.0.1 is installed, there are a lot of other mods that crash as well.

Edit: Optifine and Extra Utilities combined appear to be the issue: [according to this comment by Lumien](https://minecraft.curseforge.com/projects/random-things?comment=225).

```
java.lang.NullPointerException: Initializing game
    at lumien.randomthings.client.models.blocks.ModelCubeAll.vertexToInts(ModelCubeAll.java:58)
    at lumien.randomthings.client.models.blocks.ModelCubeAll.createSidedBakedQuad(ModelCubeAll.java:68)
    at lumien.randomthings.client.models.blocks.ModelCubeAll.<init>(ModelCubeAll.java:41)
    at lumien.randomthings.client.models.blocks.ModelFluidDisplay.<init>(ModelFluidDisplay.java:35)
    at lumien.randomthings.handler.RTEventHandler.modelBake(RTEventHandler.java:362)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_538_RTEventHandler_modelBake_ModelBakeEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:400)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:122)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:499)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

**Comment by cjburkey01** [comment]
According to Lumien, it's a conflict between Extra Utilities 2 and Optifine: http://pastebin.com/wMKmi1n3 on Curseforge: https://minecraft.curseforge.com/projects/random-things?comment=225

**Comment by Andre--D** [comment]
There is a new Optifine Preview :

OptiFine 1.10.2_HD_U_C4_pre
- fixed Forge compatibility (Extra Utilities 2 crash)
- ..
- ..

**Comment by cjburkey01** [comment]
I'll try that, thank you
