### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by NosajDraw** [rwtema/extrautilities_old_issues#1081]
My server running HermitPack 1.2.0 is crashing at random intervals (of days) with:

java.lang.ArithmeticException: / by zero
	at com.rwtema.extrautils2.power.energy.EnergyTransfer.onServerTick(EnergyTransfer.java:119)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_283_EnergyTransfer_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

Full crash report : http://pastebin.com/RGhQZuiA

**Comment by Ricket** [comment]
I just hit the same in my server. I am running `Direwolf20-1.10 v1.3.2`, which has `extrautils2-1.10.2-1.1.3c.jar`.

```
[19:12:55] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@70a612e0:
java.lang.ArithmeticException: / by zero
        at com.rwtema.extrautils2.power.energy.EnergyTransfer.onServerTick(EnergyTransfer.java:119) ~[EnergyTransfer.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_381_EnergyTransfer_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

It crashed in the middle of an AromaBackup backup operation; not sure if this was just coincidence or if that was a cause. There was one user on the server at the time of crash.

**Comment by GizmoTheGreen** [comment]
Apparantly still a thing in extrautils2-1.10.2-1.2.0.jar, modpack Age of Engineering.
Just had a crash during the night. first time it happened during a months playtime though.

**Comment by kingchills** [comment]
I also just had this happen for the first time. 
Age of Engineering (MP Server) 1.1.1c
Extra Utilities 2 2-1.10.2-1.2.0
Forge 12.18.3.2477
I can post logs if it's helpful
