### ISSUE TITLE
Power Gen in Unloaded Chunks Crash

### ISSUE THREAD

**Issue by darkshadow543** [rwtema/extrautilities_old_issues#1103]
Upon Loading a world this crash occurs, can't get into my world

java.lang.ClassCastException: net.minecraft.block.state.BlockStateContainer$StateImplementation cannot be cast to com.rwtema.extrautils2.backend.model.XUBlockState
	at com.rwtema.extrautils2.tile.XUTile.getBlockState(XUTile.java:197)
	at com.rwtema.extrautils2.tile.TilePassiveGenerator.getMultiplier(TilePassiveGenerator.java:30)
	at com.rwtema.extrautils2.power.UnloadedChunkPower.rebuild(UnloadedChunkPower.java:50)
	at com.rwtema.extrautils2.power.PowerManager.tick(PowerManager.java:375)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1264_PowerManager_tick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Watchful1** [comment]
Seconding this. Full crash log.

http://pastebin.com/i8UQVD3h

**Comment by Watchful1** [comment]
Also happens on latest, 1.1.0

http://pastebin.com/0wyxKH9F

**Comment by Watchful1** [comment]
Same in 1.1.1

http://pastebin.com/2MSNX7C8

**Comment by ghost** [comment]
You should also upload the corresponding logs from the logs folder. They show what was going on in the game before it crashed.

**Comment by andr9528** [comment]
my issue looks alot like the one above, only thing different is, that i know my generators are all chunkloaded by FTBUtilities

using minecraft 1.10.2, extrautils2 v. 1.1.2, FTBUtilites v. 1.10.2-3.1.4 forge v. 12.18.3.2185

http://pastebin.com/NeeaM9m4

before sending the comment i updated FTBUtilties to v. 1.10.2-3.2.1 (alpha version), doing so gave me the exact same crash as darkshadow543
