### ISSUE TITLE
[Crash][1.1.1] Mechanical User + Solidified Experience (AA)

### ISSUE THREAD

**Issue by Yusunoha** [rwtema/extrautilities_old_issues#1134]
I booted the newest DW20 pack version for 1.10.2 today, version 1.1.0, which is currently in beta and uses Extra Utilities 1.1.1, and I now crash when using the Mechanical User with Solidified Experience from Actually Additions.

whenever I crash, I need to use MCEdit to remove the Mechanical User before I'm able to reload the world.
the settings I'm using for the Mechanical User is "Upper left slot only", "right click" and "use item".

the crashlog that I get is
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  LoadingPlugin (Quark-r1.0-60.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-7.jar)
  IC2core (industrialcraft-2-2.6.105-ex110.jar)
  DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 12/2/16 3:22 PM
Description: Ticking block entity

java.lang.RuntimeException: Error while interacting with block minecraft:air with 1xitem.actuallyadditions.itemSolidifiedExperience@0. Method:GENERIC_CLICK  Button:RIGHT_CLICK
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:303)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:67)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:386)
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:166)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:303)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:67)

-- Block entity being ticked --
Details:
	Name: XU2:TileUse // com.rwtema.extrautils2.tile.TileUse
	Block type: ID #1864 (tile.ExtraUtils2:User // com.rwtema.extrautils2.blocks.BlockAdvInteractor.Use)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (-128,64,-744), Chunk: (at 0,4,8 in -8,-47; contains blocks -128,0,-752 to -113,255,-737), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Actual block type: ID #1864 (tile.ExtraUtils2:User // com.rwtema.extrautils2.blocks.BlockAdvInteractor.Use)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)

-- Affected level --
Details:
	Level name: Creative World
	All players: 1 total; [EntityPlayerMP['Yusunoha'/234, l='Creative World', x=-125.85, y=64.00, z=-741.13]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 6510305610896560777
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 3;minecraft:bedrock,59*minecraft:stone,4*minecraft:sandstone;1;decoration
	Level spawn location: World: (-105,4,-743), Chunk: (at 7,0,9 in -7,-47; contains blocks -112,0,-752 to -97,255,-737), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 2381743 game time, 5047977 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 13823 (now: false), thunder time: 8329 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1277706272 bytes (1218 MB) / 3976200192 bytes (3792 MB) up to 3976200192 bytes (3792 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2171 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2171.jar) 
	UCHIJAAAA	Forge{12.18.2.2171} [Minecraft Forge] (forge-1.10.2-12.18.2.2171.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv4-alpha-7} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	OpenComputers|Core{1.6.0.4} [OpenComputers (Core)] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAA	actuallyadditions{1.10.2-r85} [Actually Additions] (ActuallyAdditions-1.10.2-r85.jar) 
	UCHIJAAAA	Baubles{1.3.6} [Baubles] (Baubles-1.10.2-1.3.6.jar) 
	UCHIJAAAA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJAAAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJAAAA	appliedenergistics2{rv4-alpha-7} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-7.jar) 
	UCHIJAAAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJAAAA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJAAAA	Quark{r1.0-60} [Quark] (Quark-r1.0-60.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCHIJAAAA	betterbuilderswands{0.6.5} [Better Builder's Wands] (BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2109} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2109-universal.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.1.0-68} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-68.jar) 
	UCHIJAAAA	bookshelf{1.4.3.338} [Bookshelf] (Bookshelf-1.10.2-1.4.3.338.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.3.145} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.145-universal.jar) 
	UCHIJAAAA	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.0} [Chameleon] (Chameleon-1.10-2.2.0.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJAAAA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJAAAA	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCHIJAAAA	CodeChickenCore{2.3.5.91} [CodeChicken Core] (CodeChickenCore-1.10.2-2.3.5.91-universal.jar) 
	UCHIJAAAA	IC2{2.6.105-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.105-ex110.jar) 
	UCHIJAAAA	CompactSolars{5.0.5.329} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.5.329-universal.jar) 
	UCHIJAAAA	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCHIJAAAA	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	darkutils{1.1.6.99} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.99.jar) 
	UCHIJAAAA	forestry{5.2.16.330} [Forestry] (forestry_1.10.2-5.2.16.330.jar) 
	UCHIJAAAA	eleccore{1.6.345} [ElecCore] (ElecCore-1.10.2-1.6.345.jar) 
	UCHIJAAAA	EnderStorage{2.1.5.84} [EnderStorage] (EnderStorage-1.10.2-2.1.5.84-universal.jar) 
	UCHIJAAAA	OpenComputers{1.6.0.4} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.4.jar) 
	UCHIJAAAA	deepresonance{1.3.1} [DeepResonance] (deepresonance-1.10-1.3.1.jar) 
	UCHIJAAAA	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.60-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.60-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.138_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.138_beta.jar) 
	UCHIJAAAA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.1.jar) 
	UCHIJAAAA	zerocore{1.10.2-0.0.8.1} [Zero CORE] (zerocore-1.10.2-0.0.8.1.jar) 
	UCHIJAAAA	bigreactors{0.4.5.19} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.19.jar) 
	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.5.jar) 
	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCHIJAAAA	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.2.197} [Mantle] (Mantle-1.10.2-1.1.2.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJAAAA	immersiveengineering{0.10-51} [Immersive Engineering] (ImmersiveEngineering-0.10-51.jar) 
	UCHIJAAAA	inventorysorter{0.10.0+42} [Simple Inventory sorting] (inventorysorter-1.10-0.10.0+42.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.19} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.19.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.3.1} [JourneyMap] (journeymap-1.10.2-5.3.1.jar) 
	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJAAAA	mercurius{1.0.1} [Mercurius] (Mercurius-1.10.2-1.0.2.jar) 
	UCHIJAAAA	Morpheus{1.10.2-3.1.12} [Morpheus] (Morpheus-1.10.2-3.1.12.jar) 
	UCHIJAAAA	notenoughwands{1.4.0} [Not Enough Wands] (notenoughwands-1.10-1.4.0.jar) 
	UCHIJAAAA	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHIJAAAA	rangedpumps{0.3} [Ranged Pumps] (rangedpumps-0.3.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.5.5} [Storage Drawers] (StorageDrawers-1.10.2-3.5.5.jar) 
	UCHIJAAAA	refinedstorage{1.2.8} [Refined Storage] (refinedstorage-1.2.8.jar) 
	UCHIJAAAA	ResourceLoader{1.5.1} [Resource Loader] (ResourceLoader-MC1.9.4-1.5.1.jar) 
	UCHIJAAAA	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHIJAAAA	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCHIJAAAA	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCHIJAAAA	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJAAAA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJAAAA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
LoadingPlugin (Quark-r1.0-60.jar)
  vazkii.quark.base.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.145-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.60-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  li.cil.oc.common.asm.ClassTransformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
AppEngCore (appliedenergistics2-rv4-alpha-7.jar)
  appeng.coremod.asm.ASMIntegration
IC2core (industrialcraft-2-2.6.105-ex110.jar)
  
DepLoader (CodeChickenCore-1.10.2-2.3.5.91-universal.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv4-alpha-7 for Forge 12.18.2.2139
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/pc/Documents/Programma's/Minecraft/Curse/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/pc/Documents/Programma's/Minecraft/Curse/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/pc/Documents/Programma's/Minecraft/Curse/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/pc/Documents/Programma's/Minecraft/Curse/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/pc/Documents/Programma's/Minecraft/Curse/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/pc/Documents/Programma's/Minecraft/Curse/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/pc/Documents/Programma's/Minecraft/Curse/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/pc/Documents/Programma's/Minecraft/Curse/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/pc/Documents/Programma's/Minecraft/Curse/Minecraft/Instances/FTB%20Presents%20Direwolf20%201.10/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Yusunoha'/234, l='Creative World', x=-125.85, y=64.00, z=-741.13]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by georgo** [comment]
Happened to me as well. In 1.0.0 of pack it worked as expected. After upgrade to 1.1.0 everytime chunk load and mechanical user was trying to right click Solidified Experience, server crashes.

**Comment by ghost** [comment]
Happened to me too

**Comment by dirk251272** [comment]
I tinkered with it for todays episode of my modded series and you can actually get it working properly. The User will crash only with the last Solidified Experience in it. Make sure you have always more than 1 Solidified Experience in the User and you should be good to go.

**Comment by MvanRietschoten** [comment]
Happend to me too.
