### ISSUE TITLE
Crash java.lang.IllegalAccessError w/ TConstruct 1.10.2-1.1.3 installed

### ISSUE THREAD

**Issue by darkphan** [rwtema/extrautilities_old_issues#1156]
java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147962_a([[IIII)[[I from class com.rwtema.extrautils2.textures.SpriteLoader
	at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Full crashlog: http://pastebin.com/HE7gAQQT

**Comment by BozoJim** [comment]
I received this error for both 1.1.3 and 1.1.3a. I had to revert to 1.1.2 to successfully launch.

**Comment by Zarepheth** [comment]
I'm getting the same error, with the same stack trace using v1.1.3a.

**Comment by Hjaldar** [comment]
Workaround: Add CodeChickenLib (as per #1167).

**Comment by jem991** [comment]
Hi! I don't now why but if you add -Xmn256m java arguments fix this issue

**Comment by Zarepheth** [comment]
@jem991 Adding the the Garbage Collection Nursery size attribute (-Xmn) made no difference for me. But @Hjaldar is suggesting CodeChickenLib, so I'll give that a try and see what happens.

**Comment by Zarepheth** [comment]
@Hjaldar 's recommendation to add CodeChickenLib fixed the problem for me. It looks like the newer version of Extra Utilities now has a dependency upon CodeChickenLib.

**Comment by jem991** [comment]
Oo! Draconic evolution already add codechickenlib. I missed this point.

**Comment by KnightMiner** [comment]
It is not a dependency, it seems CodeChickenLib just happens to add the same AT that seems to be broken in Extra Utilities, or somehow is fixing the AT here
