### ISSUE TITLE
1.10.2 Client crash with 1.1.3a

### ISSUE THREAD

**Issue by bloodyraoul** [rwtema/extrautilities_old_issues#1158]
java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147962_a([[IIII)[[I from class com.rwtema.extrautils2.textures.SpriteLoader
	at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:205)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:149)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ghost** [comment]
Yep, I'm having the same problem with 1.1.3 and 1.1.3a. I had to revert to 1.1.2 to even launch the game.

**Comment by garath77** [comment]
Same problem here too.

**Comment by Dragnier** [comment]
Having this as well.

**Comment by b0bst3r** [comment]
Any of you using resourcepacks, if so please edit your post saying which one?

**Comment by ghost** [comment]
Faithful, yes.

**Comment by bloodyraoul** [comment]
No resource pack for me

**Comment by b0bst3r** [comment]
Can you please post full crash logs (well not post but upload to http://pastebin.ubuntu.com/ and link back)?

**Comment by ghost** [comment]
Complete crash log: https://gist.github.com/HellishINC/e0ca5cb39594327921e5232c7f726c74

No optifine, No resource packs.

**Comment by TheDarkPreacher** [comment]
same issue here, no resource pack. paste link follows.

http://pastebin.com/GMviGn7i

**Comment by Tsyklop** [comment]
same problem

**Comment by Hjaldar** [comment]
Potential Duplicate of #1156. Workaround: Add CodeChickenLib (as per #1167).

**Comment by jem991** [comment]
Hi! I don't now why but if you add -Xmn256m java arguments fix this issue
