### ISSUE TITLE
Mech user crash when right clicking solidified experience from Actually Additions

### ISSUE THREAD

**Issue by callmebackdraft** [rwtema/extrautilities_old_issues#1159]
Short hand crash report below: 
full in link: http://pastebin.com/FvjGgYZy

java.lang.RuntimeException: Error while interacting with block minecraft:air with 1xitem.actuallyadditions.itemSolidifiedExperience@0. Method:GENERIC_CLICK  Button:RIGHT_CLICK
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:303)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:67)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:386)
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:166)
	... 8 more

**Comment by jpeaglesandkatz** [comment]
Experiencing the same problem and now I cannot load my world anymore.

Thanks

**Comment by callmebackdraft** [comment]
@substernl i used mcedit to delete the mech user from my world, now it loads just fine again

**Comment by jpeaglesandkatz** [comment]
I used a backup restore but yeah was also looking to fix it with mcedit.

Shame we whould have to revert to those drastic actions but seeing extra utils 2 is still in alpha state I'm not surprised.
