### ISSUE TITLE
Crash of client server Extra utils 2 and actually additions SolifiedExperience

### ISSUE THREAD

**Issue by jpeaglesandkatz** [rwtema/extrautilities_old_issues#1164]
extrautils2-1.10.2-alpha-1.2.2 (but happens in previous normal release version as well)
ActuallyAdditions-1.10.2-r90

Put solifiedexperience in the mechanical user. Hard crash. And now I cannot load my world again as it keeps erroring.

[code]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (sampler-1.66.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.2.76-universal.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.7.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  LoadingPlugin (Quark-r1.1-65.jar)
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-8.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.0.178-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  SFRCore (SolarFluxReborn_1.10.2-1.5r.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 12/17/16 11:45 AM
Description: Ticking block entity

java.lang.RuntimeException: Error while interacting with block minecraft:air with 1xitem.actuallyadditions.itemSolidifiedExperience@0. Method:GENERIC_CLICK  Button:RIGHT_CLICK
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:303)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:64)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:386)
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:167)
	... 8 more

[/code]

**Comment by ghost** [comment]
Backup first.

Go into your config folder and edit Froge.cfg

`   # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false`

Set it to true, load up the world, exit, set it to false.

**Comment by mboogerd** [comment]
I have just encountered this problem as well. Luckily my backup was recent enough, but @HellishINC 's method allowed me some fast trial-and-error. Here's some additional observations:

- _configuration independent_: update method errors whether configured to generic use or use item
- _item dependent_: it does not crash for me when using bone meal, but it does when using solidified experience
- _moment of crash_: it consistently crashes (5 out of 5 times) when one of its slots contains a stack of solidified-experience of size 1, and it uses that last item. If I make sure that any slot in use never completely empties, it seems to continue running without problem (consumed 3 times at least half a stack). The actual (crashing) use of the solidified-experience seems successful though, as the orb does appear.

Hope this helps tracking the cause of the problem. Thanks in advance for all your efforts!

(btw: for completeness, I am experiencing this issue using extrautils2-1.10.2-1.1.1.jar)
