### ISSUE TITLE
java.lang.RuntimeException extrautils2-1.10.2-1.1.3a

### ISSUE THREAD

**Issue by SDUBZ** [rwtema/extrautilities_old_issues#1165]
java.lang.RuntimeException: Error while interacting with block minecraft:air with 1xitem.lootbags_itemlootbag[@ffffff]. Method:ENTITY  Button:RIGHT_CLICK

    at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:303)
    at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:67)
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

Caused by..

java.lang.NullPointerException: 

    at mca.packets.PacketInteractWithPlayerC.<init>(PacketInteractWithPlayerC.java:41)
    at mca.core.forge.EventHooksForge.entityInteractEventHandler(EventHooksForge.java:221)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_0_EventHooksForge_entityInteractEventHandler_EntityInteract.invoke(.dynamic:-1)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.common.ForgeHooks.onInteractEntity(ForgeHooks.java:1008)
    at net.minecraft.entity.player.EntityPlayer.func_184822_a(EntityPlayer.java:1158)
    at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:294)

**Comment by Gunner76th** [comment]
Please upload the entire crash report. There is information within the entire crash report that mod authors need to see to help understand the nature of the crash.

**Comment by Gunner76th** [comment]
Also, your crash states that it was caused by mca, which is Minecraft Comes Alive. In addition you are referencing Loot bags which is also not part of Extra Utilities. 

Please post the entire crash report either to gist, psatebin, or using the upload file option.

**Comment by ProsperCraft** [comment]
We are having the same issue-

https://gist.github.com/ProsperCraft/ed9b7846511633f40a1b084321bdb15c

**Comment by Gunner76th** [comment]
@SDUBZ Do you have the full crash report for this issue with which you are able to supply? Have you found out the cause and a possible solution for this issue? Your post is now over 7 months old and you have provided no feedback on it. 

As a pack developer I am rather interested in this issue, its causes, and possible solutions. I am also sure that the mod authors would appreciate as much information as you can give them, and not just a snippet of the crash report that you thought was the only part they needed. Please keep in mind that authors need the entire report, not just a snippet taken out of context to fit your thoughts on what caused the issue.

**Comment by ProsperCraft** [comment]
@Gunner76th Find my crash report in the Gist linked above.

**Comment by Gunner76th** [comment]
I was referring to the original poster who only provided a small piece of
the crash report.

**Comment by ProsperCraft** [comment]
Here is another one, it happens repeatedly whenever the player logs in- 
https://gist.github.com/ProsperCraft/45a9b0b18ef1ad97b8bb4fd7cf834877

**Comment by SDUBZ** [comment]
oh sorry @Gunner76th it was a player  over loading a mechanical user with toast to feed a auto ex compressum sieve that caused the crash from the mech user but i took the clients save and fixed it myself and told them not to do it again
