### ISSUE TITLE
sprite crash

### ISSUE THREAD

**Issue by wesleybruce** [rwtema/extrautilities_old_issues#1177]
I'm getting a crash on texture render stage with the latest two versions. I have the beta version of ex Nihilo Adscensio but that may not be the cause. There are a few other new beta mods in the list. it is happening with 1.1.3a and 1.1.3 It is not happening with 1.1.2 It's an odd mix of mods but that's the point. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.128-ex110.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 12/20/16 7:41 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147962_a([[IIII)[[I from class com.rwtema.extrautils2.textures.SpriteLoader
	at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 863626872 bytes (823 MB) / 3143630848 bytes (2998 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJA	appliedenergistics2-core{rv4-alpha-9} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	actuallyadditions{1.10.2-r90} [Actually Additions] (ActuallyAdditions-1.10.2-r90.jar) 
	UCHIJA	appliedenergistics2{rv4-alpha-9} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-9.jar) 
	UCHIJA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJA	bdlib{1.12.2.17} [BD Lib] (bdlib-1.12.2.17-mc1.10.2.jar) 
	UCHIJA	betterbuilderswands{0.9.1} [Better Builder's Wands] (BetterBuildersWands-0.9.1-1.10.2r179+093cd65.jar) 
	UCHIJA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJA	chickens{4.0} [Chickens] (chickens-4.0.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHIJA	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHIJA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJA	chiselsandbits{12.8} [Chisels & Bits] (chiselsandbits-12.8.jar) 
	UCHIJA	claybucket{1.1} [Clay Bucket] (ClayBucket-1.9.4-1.1.jar) 
	UCHIJA	IC2{2.6.128-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.128-ex110.jar) 
	UCHIJA	compactsolars{1.0} [Compact Solar Arrays] (CompactSolars-1.10.2-5.0.6.330-universal.jar) 
	UCHIJA	cookingforblockheads{4.2.26} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.26.jar) 
	UCHIJA	ding{1.0.1} [Ding] (Ding-1.10.2-1.0.1.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.61-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.61-beta.jar) 
	UCHIJA	endercrop{1.9-1.2-1836} [Ender Crop] (endercrop-1.9.4-1.3.1.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	EnderIO{1.10.2-3.0.1.144_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.144_beta.jar) 
	UCHIJA	exnihiloadscensio{0.1.5} [Ex Nihilo Adscensio] (exnihiloadscensio-1.10.2-0.1.8.jar) 
	UCHIJA	excompressum{2.0.56} [Ex Compressum] (ExCompressum_1.10.2-2.0.56.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3.jar) 
	UCHIJA	ezwastelands{1.10.2-1.0} [EzWastelands] (ezwastelands-1.10.2-1.0.jar) 
	UCHIJA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJA	forestry{5.2.16.340} [Forestry] (forestry_1.10.2-5.2.16.340.jar) 
	UCHIJA	gendustry{1.6.4.24} [GenDustry] (gendustry-1.6.4.24-mc1.10.2.jar) 
	UCHIJA	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHIJA	hatchery{1.0.0} [Hatchery] (hatchery-1.10.2-0.1.15.jar) 
	UCHIJA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJA	immersiveengineering{0.10-53} [Immersive Engineering] (ImmersiveEngineering-0.10-53.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	itemscroller{0.8.0} [Item Scroller] (itemscroller-1.10.2-0.8.0.jar) 
	UCHIJA	JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
	UCHIJA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJA	journeymap{1.10.2-5.3.2} [JourneyMap] (journeymap-1.10.2-5.3.2.jar) 
	UCHIJA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
	UCHIJA	morebees{1.10.2-1.1.6} [More Bees] (morebees-1.10.2-1.1.6.jar) 
	UCHIJA	morechickens{1.0.0} [More Chickens] (MoreChickens-1.10.2-1.0.6.jar) 
	UCHIJA	mysticalcrops{2.0} [Mystical Crops] (Mystical Crops-1.8.8.jar) 
	UCHIJA	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.10.2).jar) 
	UCHIJA	notenoughwands{1.5.2} [Not Enough Wands] (notenoughwands-1.1x-1.5.2.jar) 
	UCHIJA	packingtape{0.6.0} [Packing Tape] (PackingTape-1.10.2-0.6.0.jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJA	rftools{5.71} [RFTools] (rftools-1.1x-5.71.jar) 
	UCHIJA	woodenshears{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Shears] (SBM-WoodenShears-1.10.2-0.0.1b2-universal.jar) 
	UCHIJA	simplebarrels{1.25h} [Simple Barrels] (simplebarrels-1.10.2-2002-1.25h.jar) 
	UCHIJA	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5e.jar) 
	UCHIJA	simplegenerators{1.10.2-0.10.5c} [Simple Generators] (simplegenerators-1.10.2-0.10.5c.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.5.14} [Storage Drawers] (StorageDrawers-1.10.2-3.5.14.jar) 
	UCHIJA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHIJA	tp{1.0.0} [Tiny Progressions] (tinyprogressions-1.10.2-1.0.13.jar) 
	UCHIJA	treegrowingsimulator{0.0.4} [Tree Growing Simulator 2016] (TreeGrowingSimulator2016-0.0.4.jar) 
	UCHIJA	cavecraft{TSON Craft 3 - 1.9.4} [TSON Craft] (TSON Craft 4.0.1.jar) 
	UCHIJA	VeinMiner{0.35.1_1.9-f4a2566} [Vein Miner] (VeinMiner-0.35.1-1.9r584+f4a2566.jar) 
	UCHIJA	VeinMinerModSupport{0.35.1_1.9-f4a2566} [Mod Support] (VeinMiner-0.35.1-1.9r584+f4a2566.jar) 
	UCHIJA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCHIJA	waterstrainer{1.3.2} [Water Strainer] (WaterStrainer-1.9.4-1.3.2.jar) 
	UCHIJA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHIJA	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.128-ex110.jar)
  
AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  appeng.coremod.asm.ASMIntegration
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13447 Compatibility Profile Context 16.300.2301.0' Renderer: 'AMD Radeon R7 340'
	AE2 Version: alpha rv4-alpha-9 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (29) from ActuallyAdditions-1.10.2-r90.jar
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-alpha-9.jar
		* Baubles|API (1.3.1.2) from Baubles-1.10.2-1.3.8.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.7.7.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.7.7.jar
		* ChiselsAndBitsAPI (12.5.0) from chiselsandbits-12.8.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ExCompressum_1.10.2-2.0.56.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.5e.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from ActuallyAdditions-1.10.2-r90.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.5e.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.5e.jar
		* compatlayer (0.1.4) from compatlayer-1.10-0.1.4.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.144_beta.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.144_beta.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.144_beta.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.144_beta.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.16.340.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.16.340.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.4.24-mc1.10.2.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-53.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-53.jar
		* jeresources|API (0.5.8.98) from JustEnoughResources-1.10.2-0.5.8.98.jar
		* journeymap|client-api (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.3.2.jar
		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.3.2.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.13.6.387.jar
		* mcjtylib_ng (2.3.1) from mcjtylib-1.1x-2.3.1.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.14.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.14.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.14.jar
		* StorageDrawersAPI|inventory (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.14.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.14.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.14.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.14.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.14.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.14.jar
		* valkyrielib.api (1.10.2-0.10.5d) from valkyrielib-1.10.2-0.10.5e.jar
		* VeinMinerApi (0.3) from VeinMiner-0.35.1-1.9r584+f4a2566.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/wesle/OneDrive/Documents/Curse/Minecraft/Instances/extest/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/wesle/OneDrive/Documents/Curse/Minecraft/Instances/extest/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/wesle/OneDrive/Documents/Curse/Minecraft/Instances/extest/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/wesle/OneDrive/Documents/Curse/Minecraft/Instances/extest/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/wesle/OneDrive/Documents/Curse/Minecraft/Instances/extest/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/wesle/OneDrive/Documents/Curse/Minecraft/Instances/extest/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/wesle/OneDrive/Documents/Curse/Minecraft/Instances/extest/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/wesle/OneDrive/Documents/Curse/Minecraft/Instances/extest/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/wesle/OneDrive/Documents/Curse/Minecraft/Instances/extest/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	AE2 Integration: IC2:ON, RC:OFF, RF:OFF, RFItem:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF
	Launched Version: forge-12.18.3.2185
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 340 GL version 4.5.13447 Compatibility Profile Context 16.300.2301.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A10-7800 Radeon R7, 12 Compute Cores 4C+8G

**Comment by Hjaldar** [comment]
Potential Duplicate of #1156. Workaround: Add CodeChickenLib (as per #1167).
