### ISSUE TITLE
[BUG] Mechanical user crash

### ISSUE THREAD

**Issue by Bellwar** [rwtema/extrautilities_old_issues#1182]
I would not post it if it would not work at the beginning, but it crashed after little time so I'm not sure. Also will link this on Actually Additions.  I don't know who's problem it is. 

I tried to delete the block with forge but it just crashes then with saying some basic problems in MC. So that didn't help.

Running latest Forge, AA 1.10.2-r93, ExU 1.1.3a

Here is part of the crash log.
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.128-ex110.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.2.76-universal.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.0.178-universal.jar)
  LoadingPlugin (Quark-r1.1-66.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  SFRCore (SolarFluxReborn_1.10.2-1.6r.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 12/22/16 3:47 PM
Description: Ticking block entity

java.lang.RuntimeException: Error while interacting with block minecraft:air with 1xitem.actuallyadditions.itemSolidifiedExperience@0. Method:GENERIC_CLICK  Button:RIGHT_CLICK
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:303)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:67)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.PlayerInteractionManager.func_187250_a(PlayerInteractionManager.java:386)
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:166)
	... 8 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.rwtema.extrautils2.tile.TileUse.operate(TileUse.java:303)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:67)

-- Block entity being ticked --
Details:
	Name: XU2:TileUse // com.rwtema.extrautils2.tile.TileUse
	Block type: ID #1864 (tile.ExtraUtils2:User // com.rwtema.extrautils2.blocks.BlockAdvInteractor.Use)
	Block data value: 5 / 0x5 / 0b0101
	Block location: World: (135,55,-316), Chunk: (at 7,3,4 in 8,-20; contains blocks 128,0,-320 to 143,255,-305), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Actual block type: ID #1864 (tile.ExtraUtils2:User // com.rwtema.extrautils2.blocks.BlockAdvInteractor.Use)
	Actual block data value: 5 / 0x5 / 0b0101
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

**Comment by xannor** [comment]
I just had a similar error on server restart with a tinkers smeltery drain. I had to mcedit the entity and remove it to get the world to stay loaded.

https://gist.github.com/xannor/7795ee32482f48b3b533069244f4131c

Edit: it seems my issue is due to a recent minecolonies update that broke right click, might be a similar issue for you as well.
