### ISSUE TITLE
Sprite Loader Crash

### ISSUE THREAD

**Issue by Traverse-Joe** [rwtema/extrautilities_old_issues#1197]
http://pastebin.com/Jjuh7ASA
---- Minecraft Crash Report ----
 
WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  IC2core (industrialcraft-2-2.6.128-ex110.jar)
  ForgelinPlugin (Forgelin-1.1.0.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-15.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  SFRCore (SolarFluxReborn_1.10.2-1.6r.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.339.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  BiomeTweakerCore (BiomeTweaker-1.10.2-2.1.230.jar)
Contact their authors BEFORE contacting forge
 
// Why did you do that?
 
Time: 12/30/16 6:26 AM
Description: Initializing game
 
java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147962_a([[IIII)[[I from class com.rwtema.extrautils2.textures.SpriteLoader
    at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
    at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- Head --
Thread: Client thread
Stacktrace:
    at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
    at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
 
-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by miuirussia** [comment]
Confirm it, latest version (1.1.3c)

**Comment by Zarepheth** [comment]
I'm having the same problem with 1.1.3a and 1.1.3c.
Same stack trace as @EmoKiba despite having a different load out of CoreMods.

The game crashes before the main menu is displayed. Reverting to 1.1.2 enables game play.

**Comment by Traverse-Joe** [comment]
Agreed on Latest Version 1.1.3c it still throws the same Crash

**Comment by BuriedOstrichStudio** [comment]
I get this error but when I play sky factory 3 which has version 1.1.3a it dose not chrash

**Comment by knubbis93** [comment]
i get this crash aswell

**Comment by dritz56** [comment]
Tried what Zarepheth did and 1.1.2 does not crash
