### ISSUE TITLE
Mod incompatible with other mod? Crash Report

### ISSUE THREAD

**Issue by Araton10** [rwtema/extrautilities_old_issues#1213]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.62-beta.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 1/6/17 12:18 AM
Description: Initializing game

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureAtlasSprite.func_147962_a([[IIII)[[I from class com.rwtema.extrautils2.textures.SpriteLoader
	at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:88)
	at com.rwtema.extrautils2.textures.SpriteLoaderProcessing.load(SpriteLoaderProcessing.java:59)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
	at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:340)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_102, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 764611040 bytes (729 MB) / 2843738112 bytes (2712 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 69 mods loaded, 69 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJA	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185-universal.jar) 
	UCHIJA	actuallyadditions{1.10.2-r97} [Actually Additions] (ActuallyAdditions-1.10.2-r97.jar) 
	UCHIJA	IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
	UCHIJA	advanced_solar_panels{4.0.4} [Advanced Solar Panels] (Advanced Solar Panels-4.0.4.jar) 
	UCHIJA	JEI{3.14.1.397} [Just Enough Items] (jei_1.10.2-3.14.1.397.jar) 
	UCHIJA	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UCHIJA	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHIJA	bdlib{1.12.2.17} [BD Lib] (bdlib-1.12.2.17-mc1.10.2.jar) 
	UCHIJA	betterbuilderswands{0.9.3} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.9.3.187+c619800.jar) 
	UCHIJA	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHIJA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJA	MineTweaker3{3.0.16} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.16.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.16.jar) 
	UCHIJA	forestry{5.2.16.347} [Forestry] (forestry_1.10.2-5.2.16.347.jar) 
	UCHIJA	eleccore{1.6.360} [ElecCore] (ElecCore-1.10.2-1.6.360.jar) 
	UCHIJA	deepresonance{1.4.2} [DeepResonance] (deepresonance-1.1x-1.4.2.jar) 
	UCHIJA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCHIJA	endercore{1.10.2-0.4.1.62-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.62-beta.jar) 
	UCHIJA	EnderIO{1.10.2-3.1.156} [Ender IO] (EnderIO-1.10.2-3.1.156.jar) 
	UCHIJA	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3c.jar) 
	UCHIJA	zerocore{1.10.2-0.0.8.2} [Zero CORE] (zerocore-1.10.2-0.0.8.2.jar) 
	UCHIJA	bigreactors{1.10.2-0.4.5.23} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.23.jar) 
	UCHIJA	gendustry{1.6.5.27} [GenDustry] (gendustry-1.6.5.27-mc1.10.2.jar) 
	UCHIJA	advgenerators{0.9.20.19} [Advanced Generators] (generators-0.9.20.19-mc1.10.2.jar) 
	UCHIJA	gravestone{1.5.10} [Gravestone] (GraveStone Mod 1.5.10.jar) 
	UCHIJA	gravisuite{3.0.1} [Gravitation Suite] (Gravitation Suite-3.0.1.jar) 
	UCHIJA	hammercore{1.1.8} [Hammer Core] (HammerCore_1.10.2-1.1.8.jar) 
	UCHIJA	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJA	immersiveengineering{0.10-54} [Immersive Engineering] (ImmersiveEngineering-0.10-54.jar) 
	UCHIJA	ironbackpacks{1.10.2-2.2.21} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.21.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
	UCHIJA	journeymap{1.10.2-5.3.3} [JourneyMap] (journeymap-1.10.2-5.3.3.jar) 
	UCHIJA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJA	mtlib{@VERSION@} [MTLib] (MTLib-1.0.0.jar) 
	UCHIJA	modtweaker{2.0.8} [Mod Tweaker] (ModTweaker2-2.0.8.jar) 
	UCHIJA	morebees{1.10.2-1.2} [More Bees] (morebees-1.10.2-1.2.jar) 
	UCHIJA	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHIJA	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCHIJA	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCHIJA	quantumflux{2.0.11} [QuantumFlux] (quantumflux-1.10.2-2.0.11.jar) 
	UCHIJA	reborncore{2.8.5.79} [RebornCore] (RebornCore-1.10.2-2.8.5.79-universal.jar) 
	UCHIJA	quantumstorage{3.2.17} [QuantumStorage] (QuantumStorage-1.10.2-3.2.17.jar) 
	UCHIJA	reborncore-mcmultipart{2.8.5.79} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.8.5.79-universal.jar) 
	UCHIJA	refinedrelocation{@VERSION@} [Refined Relocation] (RefinedRelocation-mc1.10.2-2.1.18.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.5.16} [Storage Drawers] (StorageDrawers-1.10.2-3.5.16.jar) 
	UCHIJA	refinedstorage{1.2.14} [Refined Storage] (refinedstorage-1.2.14.jar) 
	UCHIJA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJA	RTG{4.1.2.1} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.1.jar) 
	UCHIJA	valkyrielib{1.10.2-0.10.5d} [Valkyrie Lib] (valkyrielib-1.10.2-0.10.5e.jar) 
	UCHIJA	simplegenerators{1.10.2-0.10.5c} [Simple Generators] (simplegenerators-1.10.2-0.10.5c.jar) 
	UCHIJA	simplyconveyors{2.0.3} [Simply Conveyors] (SimplyConveyors-1.3.1.jar) 
	UCHIJA	simplyjetpacks{2.0.3.26} [Simply Jetpacks 2] (SimplyJetpacks2-1.10.2-2.0.3.26 (1).jar) 
	UCHIJA	subcommonlib{1.1.3.0} [Subaraki's Common Library] (sublib-1.10.2-1.1.3.0.jar) 
	UCHIJA	techreborn{1.4.16.133} [TechReborn] (TechReborn-1.10.2-1.4.16.133-universal.jar) 
	UCHIJA	telepads{1.10.2 v1.0.0.2} [Telepads] (telepads-1.10.2-v1.0.0.2.jar) 
	UCHIJA	theoneprobe{1.3.3} [The One Probe] (theoneprobe-1.10-1.3.3.jar) 
	UCHIJA	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCHIJA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJA	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJA	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJA	waterpower{0.4.6} [WaterPower] (WaterPower-1.10.2-0.4.6.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
EnderCorePlugin (EnderCore-1.10.2-0.4.1.62-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.54' Renderer: 'GeForce GTX 660/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (29) from ActuallyAdditions-1.10.2-r97.jar
		* Baubles|API (1.3.1.2) from Baubles-1.10.2-1.3.8.jar
		* bigreactors|API (4.0.1) from ExtremeReactors-1.10.2-0.4.5.23.jar
		* BotaniaAPI (85) from Botania r1.9-339.jar
		* CoFHAPI (1.8.9R1.2.0B1) from ImmersiveEngineering-0.10-54.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.2.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.2.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.2.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.2.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from valkyrielib-1.10.2-0.10.5e.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.10.2-1.6.53.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.2.jar
		* compatlayer (0.1.6) from compatlayer-1.10-0.1.6.jar
		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.0.8.2.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.0.8.2.jar
		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.0.8.2.jar
		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.0.8.2.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.0.8.2.jar
		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.0.8.2.jar
		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.0.8.2.jar
		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.0.8.2.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.2.jar
		* ElecCoreAPI (1.0) from ElecCore-1.10.2-1.6.360.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.10.2-1.6.360.jar
		* EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.1.156.jar
		* EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.1.156.jar
		* EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.1.156.jar
		* EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.1.156.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.16.347.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.16.347.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.27-mc1.10.2.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-54.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-54.jar
		* IronBackpacks|API (0.5) from IronBackpacks-1.10.2-2.2.21.jar
		* jeresources|API (0.5.8.98) from JustEnoughResources-1.10.2-0.5.8.98.jar
		* journeymap|client-api (1.3) from journeymap-1.10.2-5.3.3.jar
		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.3.3.jar
		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.3.3.jar
		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.3.3.jar
		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.3.3.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.1.397.jar
		* mcjtylib_ng (2.3.1) from mcjtylib-1.1x-2.3.1.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from zerocore-1.10.2-0.0.8.2.jar
		* PsiAPI (2) from Psi-r1.0-42.jar
		* reborncoreAPI (2.8.5.79) from RebornCore-1.10.2-2.8.5.79-universal.jar
		* reborncoreAPI|Fuel (2.8.5.79) from RebornCore-1.10.2-2.8.5.79-universal.jar
		* reborncoreAPI|Power (2.8.5.79) from RebornCore-1.10.2-2.8.5.79-universal.jar
		* reborncoreAPI|Recipe (2.8.5.79) from RebornCore-1.10.2-2.8.5.79-universal.jar
		* reborncoreAPI|Tile (2.8.5.79) from RebornCore-1.10.2-2.8.5.79-universal.jar
		* RefinedRelocationAPI (2.0.0) from RefinedRelocation-mc1.10.2-2.1.18.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.16.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.16.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.16.jar
		* StorageDrawersAPI|inventory (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.16.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.16.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.16.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.16.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.16.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.5.16.jar
		* techrebornAPI (1.4.16.133) from TechReborn-1.10.2-1.4.16.133-universal.jar
		* valkyrielib.api (1.10.2-0.10.5d) from valkyrielib-1.10.2-0.10.5e.jar
		* VeinMinerApi (0.3) from VeinMiner-1.9-0.35.3.595+a46c1b0.jar
		* zerocore|API|multiblock (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.2.jar
		* zerocore|API|multiblock|rectangular (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.2.jar
		* zerocore|API|multiblock|validation (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.2.jar
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/piano/Desktop/MultiMC/instances/Jet%203.5/minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/piano/Desktop/MultiMC/instances/Jet%203.5/minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/piano/Desktop/MultiMC/instances/Jet%203.5/minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/piano/Desktop/MultiMC/instances/Jet%203.5/minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/piano/Desktop/MultiMC/instances/Jet%203.5/minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/piano/Desktop/MultiMC/instances/Jet%203.5/minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/piano/Desktop/MultiMC/instances/Jet%203.5/minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/piano/Desktop/MultiMC/instances/Jet%203.5/minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/piano/Desktop/MultiMC/instances/Jet%203.5/minecraft/mods/mcjtylib-1.1x-2.3.1.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.54, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz

**Comment by MortisLegati** [comment]
Having exactly the same issue with the latest version.

**Comment by ShneekeyTheLost** [comment]
Here's the weird thing: install CodeChickenLib 1.8+... it starts working again. I'm betting both TiCon and ExUtil try for the same resource when doing rendering and fight over it, CCL handles it for them.
