### ISSUE TITLE
1.1.3c Extra Utilities 2 Crash when Detecting Tinkers Construct 2

### ISSUE THREAD

**Issue by Gr8umbreon** [rwtema/extrautilities_old_issues#1219]
This is the crash report I got when loading up a modpack with the most recent Extra Utilities 2 1.10.2 v1.1.3c

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.0.178-universal.jar)
  Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  LoadingPlugin (Quark-r1.1-68.jar)
  LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 1/7/17 8:11 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from ExtraUtils2 (ExtraUtils2)
Caused by: java.lang.NoSuchMethodError: slimeknights.tconstruct.library.materials.BowMaterialStats.<init>(FFF)V
	at com.rwtema.extrautils2.modcompat.tcon.TConstructIntegration$1.addStats(TConstructIntegration.java:79)
	at com.rwtema.extrautils2.modcompat.tcon.TConstructIntegration.init(TConstructIntegration.java:165)
	at com.rwtema.extrautils2.backend.entries.EntryHandler.init(EntryHandler.java:76)
	at com.rwtema.extrautils2.ExtraUtils2.init(ExtraUtils2.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 906603184 bytes (864 MB) / 2839019520 bytes (2707 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 Optifine OptiFine_1.10.2_HD_U_D4 79 mods loaded, 79 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	additionalresources{0.1.1} [Additional Resources] (additionalresources-1.9.4-0.2.0.28+47cd0bd.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHI	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHI	AppleCore{2.1.0} [AppleCore] (AppleCore-mc1.10.2-2.1.0.jar) 
	UCHI	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHI	audiodeath{0.6.3_1.9-1311200} [Audio Death] (audiodeath-1.9-0.6.3.47+1311200.jar) 
	UCHI	Psi{r1.0-42} [Psi] (Psi-r1.0-42.jar) 
	UCHI	Quark{r1.1-68} [Quark] (Quark-r1.1-68.jar) 
	UCHI	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHI	Baubles{1.3.8} [Baubles] (Baubles-1.10.2-1.3.8.jar) 
	UCHI	betterquesting{1.3.180} [Better Questing] (BetterQuesting-1.3.180.jar) 
	UCHI	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHI	BloodMagic{1.9.4-2.1.0-69} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-69.jar) 
	UCHI	Botania{r1.9-339} [Botania] (Botania r1.9-339.jar) 
	UCHI	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHI	mcmultipart{2.0.0_88} [MCMultiPart] (MCMultiPart-experimental-2.0.0_88-universal.jar) 
	UCHI	CharsetLib{0.3.0-pre15} [â€½] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetAudio{0.3.0-pre15} [â™«] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetCarts{0.3.0-pre15} [U] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetDecoration{0.3.0-pre15} [âš?] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetDrama{0.3.0-pre15} [!] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetFarming{0.3.0-pre15} [;] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetGates{0.3.0-pre15} [&] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetPipes{0.3.0-pre15} [|] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetStorage{0.3.0-pre15} [#] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetTweaks{0.3.0-pre15} [*] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetWires{0.3.0-pre15} [+] (Charset-0.3.0-pre15.jar) 
	UCHI	CharsetWrench{0.3.0-pre15} [/] (Charset-0.3.0-pre15.jar) 
	UCHI	chisel{MC1.10.2-0.0.7.7} [Chisel] (Chisel-MC1.10.2-0.0.7.7.jar) 
	UCHI	chiselsandbits{12.9} [Chisels & Bits] (chiselsandbits-12.9.jar) 
	UCHI	CodeChickenLib{2.5.0.178} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHI	CodeChickenCore{2.4.0.100} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.100-universal.jar) 
	UCHI	NashornLib{1.9.4-1.8.77-1.3.1} [Nashorn Library] (NashornLib-1.9.4-1.8.77-1.3.1.8.jar) 
	UCHI	craftingharmonics{1.9.4_1.10_1.10.2-1.5.7} [Crafting Harmonics] (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar) 
	UCHI	cyberware{beta-0.2.6} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.6.jar) 
	UCHI	easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
	UCHI	EnderStorage{2.2.0.96} [EnderStorage] (EnderStorage-1.10.2-2.2.0.96-universal.jar) 
	UCHI	mantle{1.10.2-1.1.2.197} [Mantle] (Mantle-1.10.2-1.1.2.jar) 
	UCHI	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHI	immersiveengineering{0.10-54} [Immersive Engineering] (ImmersiveEngineering-0.10-54.jar) 
	UCHI	Mekanism{9.2.1} [Mekanism] (Mekanism-1.10.2-9.2.1.295.jar) 
	UCHI	exnihiloomnia{1.2.4} [Ex Nihilo Omnia] (exnihiloomnia-1.2.4.jar) 
	UCHI	excompressum{2.0.56} [Ex Compressum] (ExCompressum_1.10.2-2.0.56.jar) 
	UCHE	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-1.1.3c.jar) 
	UCHI	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHI	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHI	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.2.3.jar) 
	UCHI	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.2.4.jar) 
	UCHI	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHI	Lockdown{${mod_version}} [Lockdown] (Lockdown-1.10.2-5.0.0-universal.jar) 
	UCHI	MekanismGenerators{9.2.1} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.1.295.jar) 
	UCHI	MekanismTools{9.2.1} [MekanismTools] (MekanismTools-1.10.2-9.2.1.295.jar) 
	UCHI	Morpheus{1.10.2-3.1.13} [Morpheus] (Morpheus-1.10.2-3.1.13.jar) 
	UCHI	mxtune{0.3.1.0-dev.10} [mxTune] (mxtune-1.10.2-0.3.1.0-dev.10.jar) 
	UCHI	mychunkloader{1.9.4-1.10.2-03} [My Chunk Loader] (Mychunkloader-1.9.4-1.10.2-03.jar) 
	UCHI	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHI	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCHI	ProjectE{1.10.2-PE1.1.1B} [ProjectE] (ProjectE-1.10.2-PE1.1.1B.jar) 
	UCHI	psionup{15.1} [PSIonic Upgrades] (PSIonicUpgrades-r1.15.jar) 
	UCHI	StorageDrawers{1.10.2-3.5.16} [Storage Drawers] (StorageDrawers-1.10.2-3.5.16.jar) 
	UCHI	refinedstorage{1.2.16} [Refined Storage] (refinedstorage-1.2.16.jar) 
	UCHI	xreliquary{1.10.2-1.3.3.615} [Reliquary] (Reliquary-1.10.2-1.3.3.615.jar) 
	UCHI	rftools{5.75} [RFTools] (rftools-1.1x-5.75.jar) 
	UCHI	rftoolscontrol{1.6.3} [RFTools Control] (rftoolsctrl-1.1x-1.6.3.jar) 
	UCHI	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHI	soulshardstow{1.10.2-2.6.7-48} [Soul Shards - The Old Ways] (SoulShards-TOW-1.10.2-2.6.7-48.jar) 
	UCHI	SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.6.jar) 
	UCHI	bq_standard{1.3.92} [Standard Expansion] (StandardExpansion-1.3.92.jar) 
	UCHI	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
	UCHI	totemic{1.9.4-0.7.9.1} [Totemic] (Totemic-1.9.4-0.7.9.1.jar) 
	UCHI	treechopper{1.1.1a} [Tree Chopper] (TreeChopper-1.10.2-1.1.1a.jar) 
	UCHI	treegrowingsimulator{0.0.4} [Tree Growing Simulator 2016] (TreeGrowingSimulator2016-0.0.4.jar) 
	UCHI	VeinMiner{0.34.1_1.9-73be663} [Vein Miner] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHI	VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support] (VeinMiner-0.34.1-1.9r571+73be663.jar) 
	UCHI	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.1.213.jar) 
	UCHI	wawla{2.3.1.213} [What Are We Looking At] (Wawla-1.10.2-2.3.1.213.jar) 
	Loaded coremods (and transformers): 
Crafting Harmonics Core (craftingharmonics-1.9.4_1.10_1.10.2-1.5.7.42.jar)
  org.winterblade.minecraft.harmony.asm.PotionRemovedHookTransformer
AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.0.178-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.BlockStateLoaderTransformer
Ar_CorePlugin (additionalresources-1.9.4-0.2.0.28+47cd0bd.jar)
  
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  team.chisel.common.asm.ChiselTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Quark-r1.1-68.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingHook (Mekanism-1.10.2-9.2.1.295.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 21.20.16.4526' Renderer: 'Intel(R) HD Graphics 620'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	OptiFine Version: OptiFine_1.10.2_HD_U_D4
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.4.0 - Build 21.20.16.4526
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

I will go to Tinker's Construct and report it there too.

**Comment by Gr8umbreon** [comment]
Found Tinker's Construct Update. Attempting update there for fix.

Edit: Tinker's Construct Update fixed the issue. There is no need to keep this open.

**Comment by NightKev** [comment]
The TCon update hasn't fixed the issue for me. Crash occurs with only TCon 2.6.2 + Mantle 1.1.4 + EU 1.1.3d

[Logfile](https://paste.ee/p/ItCRX)
