### ISSUE TITLE
Quantum Quarry Causing Crash (Ticking Block Entity)

### ISSUE THREAD

**Issue by Melkutus** [rwtema/extrautilities_old_issues#1275]
[crash-2017-01-29_10.41.25-server.txt](https://github.com/rwtema/extrautilities/files/737615/crash-2017-01-29_10.41.25-server.txt)

Hello,

Recently I have begun using the Quantum Quarry, and it has been causing crashes either when I activate it, or while it is in use, where it will spontaneously crash the game. I don't know how to read Java, but I guess from what I can tell it happens when the quarry is selecting another chunk and something that is spawning within that chunk is crashing it.

Anyways, thank you for your time if you choose to investigate this issue.

**Comment by InjuredWolf** [comment]
What do you have it dumping items into?

**Comment by mindforger** [comment]
this crash looks like it triggered a spawn event and then tried to cancle it using improper methodes!?

**Comment by Omega696** [comment]
We have this isue on our server,  since 1.3.2 The core block of the quarry is the block being ticked and it has ben conected to bother a single chest as a buffer, then storage drawers, and directly to storage drawers, refined storage etc.

**Comment by Omega696** [comment]
Here is a crash report. all quarrys were affected, and had to be disabled from the Direwolf20 1.10 pack.
[crash-2017-01-27_15.11.55-server.txt](https://github.com/rwtema/extrautilities/files/740150/crash-2017-01-27_15.11.55-server.txt)

**Comment by ShelLuser** [comment]
Based on the crash report this seems to be a duplicate of issue #1218.

Don't take this message in the wrong way please, merely trying to help out the author a bit in sorting out some of the issues.

**Comment by WilliamBlaze** [comment]
.

Time: 6/19/17 8:59 PM
Description: Ticking block entity

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.resetChunkBlocks(WorldProviderSpecialDim.java:127)
	at com.rwtema.extrautils2.dimensions.workhousedim.WorldProviderSpecialDim.releaseChunk(WorldProviderSpecialDim.java:154)
	at com.rwtema.extrautils2.quarry.TileQuarry.getNewChunk(TileQuarry.java:414)
	at com.rwtema.extrautils2.quarry.TileQuarry.advance(TileQuarry.java:409)
	at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:307)
	at net.minecraft.world.World.func_72939_s(World.java:1802)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

yup' seems to be my issue as well with the  Extra Utilities 2 - 1.11.2 - 1.4.4 release for minecraft 1.11.2
 it happens straight out of no where and my world its currently a bust now' -- short of just deleting Extra Utilities completely there seems to be no fix for my issue.

**Comment by Omega696** [comment]
The way to save your world right now is to MCedit the quarry block using the crash report to give you the co-ords. it will allow you to delete the core and break the multiblock.

**Comment by WilliamBlaze** [comment]
i think i'll ask for help for how to do that surgical procedure in the future, as for the moment though; i did a very crude cut & paste job with MCEdit to remove a portion of the multi block structures to essentially break them apart to stop further quarry function, and i removed half of a floor and some chests in the process of doing so o-o' -- im not even certain this will actually work to fix it but when half the screen is a bunch of textureless pink squares in MCedit, crude is what a newbie shall be'  *first time using MCEdit ever*


Hopefully the quarries will have some sort of fail safe in the future to prevent this error.

______________
Yup the MCEdit fixed it but the bigger issue is; how am i to quarry in a skyblock world without the quantum quarry now?
