### ISSUE TITLE
NullPointerException while Crusher GUI is open

### ISSUE THREAD

**Issue by CplPibald** [rwtema/extrautilities_old_issues#1277]
Using extrautils2-1.11.2-1.2.0
on MC 1.11.2 with Forge 2224

Crash occurs while GUI is open on crusher

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:78)
	at com.rwtema.extrautils2.gui.backend.DynamicContainer.func_75142_b(DynamicContainer.java:150)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)

**Comment by InjuredWolf** [comment]
Duplicate of #1279
