### ISSUE TITLE
error related to extrautitities in latest.log

### ISSUE THREAD

**Issue by Hellcommander** [rwtema/extrautilities_old_issues#1293]
found this error in the log that references extra utilities (latest for 1.11.2)
`[01:52:09] [Client thread/INFO]: Loading blocks and textures...
[01:52:09] [Client thread/WARN]: An object with type "net.minecraft.item.ItemStack" is null!
[01:52:09] [Client thread/WARN]: Minecraft-Flux can't inject any capability into an empty object
[01:52:10] [Client thread/WARN]: Existing color palette's mods no longer match current loadout.
[01:52:10] [Client thread/INFO]: WAS: AbyssalCraft:1.9.3.10, Advanced Hook Launchers:1.11.2-2.0.1.1, Animal Bikes:1.11.2, Aquaculture:1.5.0, AutoRegLib:1.1-4, BD Lib:1.13.1.4, Baubles:1.4.3, Better Achievements:0.4.1.44, Better Combat:1.4.0, Better With Mods:1.0-RC2, Biomes O' Plenty:6.0.1.2145, Cavern:1.6.2, Chameleon:1.11-3.0.2, CommonCapabilities:1.3.1, Convenient Additions:1.0.17-27, Cyclic:1.0.0, Cyclops Core:0.9.2, Deep Pockets:1.0.0, ET Lunar:1.11.2-0.11.0c, Earthworks:1.0.3, Ebon Arts:v2.5.0a-mc1.10.2, Elevator Mod:1.3.0, Environmental Tech:1.11.2-0.11.0d, Extra Rails:1.2.1, Farseek:2.1, Fast Leaf Decay:v12, Floricraft:beta1.3.2, FluidConverters:2.1.1, FluxedRedstone:@MODVERSION@, Forestry:5.3.0.32, Forge Endertech:2.0.2.0, Forge Mod Loader:8.0.99.99, Friendly Fire:1.4.0, Funnels:1.2.1, GeographiCraft:0.8.7, Grue:1.3.4, Hammer Core:1.2.5, Hardcore Darkness:1.8.1, Hardcore ORE:0.0.12, Infernal Mobs:1.7.2, IvToolkit:1.3.2.1, JourneyMap:1.11.2-5.4.4, Just Enough Buttons:1.11.2-1.4.1, LLibrary:1.7.4, Literal Ascension:1.11.2-1.0.1.0, Logical Drops:0.9.4, LunatriusCore:1.1.2.39, MineColonies:1.11-0.6.2669, MineMenu:1.5.0, Minecraft Coder Pack:9.19, Minecraft Forge:13.20.0.2227, Minecraft-Flux:2.0.6, Minecraft:1.11.2, Mob Totems:1.11.2-0.3.0, Modular Routers:1.11.2-2.0.2, MorePlayerModels:1.11.0, Multi-Hotbar:1.0, No Mob Spawning on Trees:1.2.0-mc1.11.2, OreExcavation:1.3.85, Packet Filter:1.3.4, Pam's HarvestCraft:1.11.2b, Pandora's Box:2.1.6.1, Photoptics:0.6.1.1.1, Pipes:1.1.0.12, Platforms:1.3.2, Player Stats 2:10r, Pressure Pipes:1.3.1.4, Psi:r1.1-46, RFTools Control:1.6.5, RFTools Dimensions:4.54, RFTools:5.82, RPG-Hud:3.3, ReAuth:3.4.1, Real First-Person Render:8.1.1, RebornCore:2.13.3.34, Recurrent Complex:1.2.9.1, Redstone Remote:@VERSION@, Reliquary:1.11.2-1.3.3.635, Reptile Mod:3.6.2, Roguelike Dungeons:1.6.3, Roots 2:0.009, Rough Mobs:1.0, Server Properties LAN:2.4, ShadowMC:3.7.1, ShetiPhian-Core:3.4.1, Silent Lib:1.2.0, Silent's Gems: Extra Parts:1.2.4, Silent's Gems:2.2.8, SimpleOreGen:1.11.2-0.4.7, SlashBlade:mc1.11-r8, Souls:2.0.0, Sound Filters:0.9_for_1.9, Spartan Shields:1.1c, Stackie:1.6.0.45, Stellar API:0.6.4.1.2, Stellar Sky:0.6.5.1.2, StepUp:4.0-mc1.11, Streams:0.3, TESLA:1.3.0.51, TSON Craft:TSON Craft 3 - 1.9.4, TeleToro:1.11.2-21, Teslafied:1.0.0, The One Probe:1.4.2, Thut's Bling:1.0.1, Thut's Wearables:2.1.2, ThutCore:4.3.2, ToroQuest:1.11.2-3.1, Underground Biomes:0.9.beta.8, Underwater Utilities:@VERSION@, Unified Items:1.4.8.147, Valkyrie Lib:1.11.2-0.11.0b, extrautils2:1.0, reborncore-MCMultiPart:2.13.3.34, §9Advanced Sticks Mod:1.4.3
NOW: AbyssalCraft:1.9.3.10, Advanced Hook Launchers:1.11.2-2.0.1.1, Animal Bikes:1.11.2, Aquaculture:1.5.0, AutoRegLib:1.1-4, BD Lib:1.13.1.4, Baubles:1.4.3, Better Achievements:0.4.1.44, Better Combat:1.4.0, Better With Mods:1.0-RC2, Biomes O' Plenty:6.0.1.2145, Cavern:1.6.2, Chameleon:1.11-3.0.2, CommonCapabilities:1.3.1, Convenient Additions:1.0.17-27, Cyclic:1.0.0, Cyclops Core:0.9.2, Dynamic Lights Flood Light:1.0.3, Dynamic Lights Other Player Light:1.0.9, Dynamic Lights Player Light:1.1.3, Dynamic Lights on Creepers:1.0.6, Dynamic Lights on Flame enchanted Arrows:1.0.1, Dynamic Lights on ItemEntities:1.1.0, Dynamic Lights on Mob Equipment:1.1.0, Dynamic Lights on burning:1.0.7, Dynamic Lights on specified Entities:1.0.1, Dynamic Lights:1.4.6, ET Lunar:1.11.2-0.11.0c, Earthworks:1.0.3, Ebon Arts:v2.5.0a-mc1.10.2, Elevator Mod:1.3.0, Environmental Tech:1.11.2-0.11.0d, Extra Rails:1.2.1, Farseek:2.1, Fast Leaf Decay:v12, Floricraft:beta1.3.2, FluidConverters:2.1.1, FluxedRedstone:@MODVERSION@, FoamFix:@VERSION@, Forestry:5.3.0.32, Forge Endertech:2.0.2.0, Forge Mod Loader:8.0.99.99, Friendly Fire:1.4.0, Funnels:1.2.1, GeographiCraft:0.8.7, Grue:1.3.4, Hammer Core:1.2.5, Hardcore Darkness:1.8.1, Hardcore ORE:0.0.12, Infernal Mobs:1.7.2, IvToolkit:1.3.2.1, JourneyMap:1.11.2-5.4.4, Just Enough Buttons:1.11.2-1.4.1, LLibrary:1.7.4, Literal Ascension:1.11.2-1.0.1.0, Logical Drops:0.9.4, LunatriusCore:1.1.2.39, MineColonies:1.11-0.6.2669, MineMenu:1.5.0, Minecraft Coder Pack:9.19, Minecraft Forge:13.20.0.2227, Minecraft-Flux:2.0.6, Minecraft:1.11.2, Mo' Villages:1.5.3, Mob Totems:1.11.2-0.3.0, Modular Routers:1.11.2-2.0.2, MorePlayerModels:1.11.0, Multi Mine:1.5.6, Multi-Hotbar:1.0, No Mob Spawning on Trees:1.2.0-mc1.11.2, OreExcavation:1.3.85, Packet Filter:1.3.4, Pam's HarvestCraft:1.11.2b, Pandora's Box:2.1.6.1, Photoptics:0.6.1.1.1, Pipes:1.1.0.12, Platforms:1.3.2, Player Stats 2:10r, Pressure Pipes:1.3.1.4, Psi:r1.1-46, RFTools Control:1.6.5, RFTools Dimensions:4.54, RFTools:5.82, RPG-Hud:3.3, ReAuth:3.4.1, Real First-Person Render:8.1.1, RebornCore:2.13.3.34, Recurrent Complex:1.2.9.1, Redstone Remote:@VERSION@, Reliquary:1.11.2-1.3.3.635, Reptile Mod:3.6.2, Roguelike Dungeons:1.6.3, Roots 2:0.009, Rough Mobs:1.0, Server Properties LAN:2.4, ShadowMC:3.7.1, ShetiPhian-Core:3.4.1, Silent Lib:1.2.0, Silent's Gems: Extra Parts:1.2.4, Silent's Gems:2.2.8, SimpleOreGen:1.11.2-0.4.7, SlashBlade:mc1.11-r8, Souls:2.0.0, Sound Filters:0.9_for_1.9, Spartan Shields:1.1c, Stackie:1.6.0.45, Stellar API:0.6.4.1.2, Stellar Sky:0.6.5.1.2, StepUp:4.0-mc1.11, Streams:0.3, TESLA:1.3.0.51, TSON Craft:TSON Craft 3 - 1.9.4, TeleToro:1.11.2-21, Teslafied:1.0.0, The One Probe:1.4.2, Thut's Bling:1.0.1, Thut's Wearables:2.1.2, ThutCore:4.3.2, ToroQuest:1.11.2-3.1, Underground Biomes:0.9.beta.8, Underwater Utilities:@VERSION@, Unified Items:1.4.8.147, Valkyrie Lib:1.11.2-0.11.0b, extrautils2:1.0, reborncore-MCMultiPart:2.13.3.34, §9Advanced Sticks Mod:1.4.3
[01:52:10] [Client thread/ERROR]: Error calling com.rwtema.extrautils2.backend.model.PassthruModelBlock.getQuads() (SUPPRESSED)
[01:52:10] [Client thread/ERROR]: java.lang.NullPointerException
	at com.rwtema.extrautils2.backend.model.PassthruModelBlock.func_188616_a(PassthruModelBlock.java:37)
	at journeymap.client.forge.helper.ColorHelper.getFirstFoundSprite(ColorHelper.java:183)
	at journeymap.client.forge.helper.ColorHelper.getDirectIcon(ColorHelper.java:164)
	at journeymap.client.forge.helper.ColorHelper.getTextureColor(ColorHelper.java:112)
	at journeymap.client.model.mod.vanilla.VanillaColorHandler.getTextureColor(VanillaColorHandler.java:24)
	at journeymap.client.model.BlockMD.ensureColor(BlockMD.java:408)
	at journeymap.client.cartography.ColorManager.initBlockColors(ColorManager.java:193)
	at journeymap.client.cartography.ColorManager.ensureCurrent(ColorManager.java:130)
	at journeymap.client.task.main.EnsureCurrentColorsTask.perform(EnsureCurrentColorsTask.java:15)
	at journeymap.client.task.main.MainTaskController.performTasks(MainTaskController.java:64)
	at journeymap.client.JourneymapClient.performMainThreadTasks(JourneymapClient.java:568)
	at journeymap.client.forge.event.StateTickHandler.onClientTick(StateTickHandler.java:86)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_961_StateTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:342)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1645)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`
Full latest.log is attached
[latest.zip](https://github.com/rwtema/extrautilities/files/759903/latest.zip)

**Comment by mindforger** [comment]
journeymap can not render something because of exutil exploding on the request ... also textwalling is not nice, make it shorter please next time :) 

tema is curently not working at this mod due to havy work, be patient please

did you crash or is it just an "annoying error in the log" thing?

**Comment by Hellcommander** [comment]
Dont think I crashed I was just posting it in case it can help the mod any.
