### ISSUE TITLE
Problem when i update EU2 from 1.1.3-1.3.0

### ISSUE THREAD

**Issue by Doomish** [rwtema/extrautilities_old_issues#1303]
Hi guys. Please i need to ask. I have problem. I have extra utils 2 mod version 1.1.3 and if i want to update to 1.2.0 or 1.3.0 my mc will crash.
I need help. 
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)
Caused by: java.lang.RuntimeException: Invalid shaped ore input: null
	at com.rwtema.extrautils2.crafting.XUShapedRecipe.handleListInput(XUShapedRecipe.java:147)
	at com.rwtema.extrautils2.crafting.XUShapedRecipe.getRecipeObject(XUShapedRecipe.java:173)
	at com.rwtema.extrautils2.crafting.XUShapedRecipe.<init>(XUShapedRecipe.java:98)
	at com.rwtema.extrautils2.backend.entries.Entry.addShaped(Entry.java:95)
	at com.rwtema.extrautils2.backend.entries.XU2Entries$83.addRecipes(XU2Entries.java:1408)
	at com.rwtema.extrautils2.backend.entries.EntryHandler.preInit(EntryHandler.java:66)
	at com.rwtema.extrautils2.ExtraUtils2.preInit(ExtraUtils2.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Gunner76th** [comment]
I am also getting a similar crash, but mine was because I disabled a couple of items in the config after I had already generated the world. 
[crash-2017-03-01_21.55.25-server.txt](https://github.com/rwtema/extrautilities/files/812674/crash-2017-03-01_21.55.25-server.txt)

Also @Doomish please post full crash reports for mod authors, and not snippets. And it is customary to use something like pastebin, or direct uploading of the crash report instead of plain text posting as you have done. Doing that makes it harder to read the narrative of your bug report and distracts from further conversations as well as adds unnecessary scrolling for people.
