### ISSUE TITLE
Error when placing opinium core and Klein bottle in Multiplayer

### ISSUE THREAD

**Issue by gdude2002** [rwtema/extrautilities_old_issues#1307]
Minecraft 1.10.2, ExU 1.3.0

Server kicks the player that tried to place it with the following error:

```
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:94) ~[XUBlockTESR.class:?]
at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:34) ~[XUBlockTESR.class:?]
at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766) ~[asv.class:?]
at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784) ~[asv.class:?]
at net.minecraft.world.World.func_175625_s(World.java:7034) ~[aid.class:?]
at blusunrize.immersiveengineering.common.util.compat.OneProbeHelper$EnergyInfoProvider.getProbeConfig(OneProbeHelper.java:102) ~[OneProbeHelper$EnergyInfoProvider.class:?]
at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:138) ~[PacketGetInfo.class:?]
at mcjty.theoneprobe.network.PacketGetInfo.access$600(PacketGetInfo.java:34) ~[PacketGetInfo.class:?]
at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:110) ~[PacketGetInfo$Handler.class:?]
at mcjty.theoneprobe.network.PacketGetInfo$Handler.lambda$onMessage$0(PacketGetInfo.java:103) ~[PacketGetInfo$Handler.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.IBakedModel
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:94) ~[XUBlockTESR.class:?]
at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:34) ~[XUBlockTESR.class:?]
at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766) ~[asv.class:?]
at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784) ~[asv.class:?]
at net.minecraft.world.World.func_175625_s(World.java:7034) ~[aid.class:?]
at blusunrize.immersiveengineering.common.util.compat.OneProbeHelper$EnergyInfoProvider.getProbeConfig(OneProbeHelper.java:102) ~[OneProbeHelper$EnergyInfoProvider.class:?]
at mcjty.theoneprobe.network.PacketGetInfo.getProbeInfo(PacketGetInfo.java:138) ~[PacketGetInfo.class:?]
at mcjty.theoneprobe.network.PacketGetInfo.access$600(PacketGetInfo.java:34) ~[PacketGetInfo.class:?]
at mcjty.theoneprobe.network.PacketGetInfo$Handler.handle(PacketGetInfo.java:110) ~[PacketGetInfo$Handler.class:?]
at mcjty.theoneprobe.network.PacketGetInfo$Handler.lambda$onMessage$0(PacketGetInfo.java:103) ~[PacketGetInfo$Handler.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_91]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_91]
at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
... 5 more
```

**Comment by gdude2002** [comment]
This error occurs whenever a player logs in or approaches the region containing the core.

**Comment by gdude2002** [comment]
Here's another.

```
at com.rwtema.extrautils2.backend.XUBlockTESR.getWorldModel(XUBlockTESR.java:61) ~[XUBlockTESR.class:?]
at com.rwtema.extrautils2.backend.XUBlock.addCollisionBoxToListBase(XUBlock.java:207) ~[XUBlock.class:?]
at com.rwtema.extrautils2.compatibility.BlockCompat.func_185477_a(BlockCompat.java:95) ~[BlockCompat.class:?]
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:438) ~[art$a.class:?]
at net.minecraft.world.World.func_184144_a(World.java:1252) ~[aid.class:?]
at net.minecraft.entity.Entity.func_70091_d(Entity.java:639) ~[rw.class:?]
at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1795) ~[sf.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1808) ~[zs.class:?]
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2217) ~[sf.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:512) ~[zs.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
... 10 more
Caused by: java.lang.RuntimeException: Attempted to load class byl for invalid side SERVER
at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:56) ~[forge-1.10.2-12.18.3.2221-universal.jar:?]
at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:249) ~[forge-1.10.2-12.18.3.2221-universal.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:94) ~[XUBlockTESR.class:?]
at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:34) ~[XUBlockTESR.class:?]
at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766) ~[asv.class:?]
at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784) ~[asv.class:?]
at net.minecraft.world.World.func_175625_s(World.java:7034) ~[aid.class:?]
at com.rwtema.extrautils2.backend.XUBlockTESR.getWorldModel(XUBlockTESR.java:61) ~[XUBlockTESR.class:?]
at com.rwtema.extrautils2.backend.XUBlock.addCollisionBoxToListBase(XUBlock.java:207) ~[XUBlock.class:?]
at com.rwtema.extrautils2.compatibility.BlockCompat.func_185477_a(BlockCompat.java:95) ~[BlockCompat.class:?]
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:438) ~[art$a.class:?]
at net.minecraft.world.World.func_184144_a(World.java:1252) ~[aid.class:?]
at net.minecraft.entity.Entity.func_70091_d(Entity.java:639) ~[rw.class:?]
at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1795) ~[sf.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1808) ~[zs.class:?]
at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2217) ~[sf.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:512) ~[zs.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
... 10 more
```

**Comment by TheRegulator** [comment]
On client side i always get a NullPointer Exception while connecting to a server

In Singleplayer it worked fine

[14:34:39] [Client thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1045) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1169) ~[bll.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:52) ~[fw.class:?]
	at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:11) ~[fw.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 17 more

**Comment by UldisAlksnis** [comment]
same error here, needs to be sorted please @multiplayer

**Comment by gdude2002** [comment]
We're getting the same issue with the placeable Klein bottle as well.

**Comment by GMAzrael** [comment]
Problem with AllTheMods v. 2.3 @whatthedrunk

**Comment by LatvianModder** [comment]
Sorry for off-topic-ing, but.. Hello, rare fellow Latvian, @UldisAlksnis :D

**Comment by curscascis** [comment]
Yeah same issue over here with both of those items, any update on the status?

**Comment by curscascis** [comment]
Also when trying to modify the block via console with setblock or using world edit throw's an error.
https://i.imgur.com/zuBqPDI.png

**Comment by xPkFyre** [comment]
This happened to me as well.

**Comment by gdude2002** [comment]
Apparently [this release](https://minecraft.curseforge.com/projects/extra-utilities/files/2391226) fixes it - can anyone confirm?

**Comment by Kjelli** [comment]
Confirmed. I was able to log back in without crashing after updating to @gdude2002 's mentioned version

**Comment by gdude2002** [comment]
We haven't had any issues recently either. Well, I guess this is solved, then!
