### ISSUE TITLE
small error ticking entity

### ISSUE THREAD

**Issue by MrKRONIC** [rwtema/extrautilities_old_issues#1317]
so after playing about with the mod i placed and item and got kicked from my server now i can not rejion due to ticking player entity  

18.02 18:22:11 [Server] Server thread/INFO MrKRONIC joined the game
18.02 18:22:11 [Server] Server thread/WARN Failed to handle packet for /95.151.79.32:62364
18.02 18:22:11 [Server] INFO net.minecraft.util.ReportedException: Ticking player
18.02 18:22:11 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:406) ~[ly.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zgo000(NetHandlerPlayServer.java:1961) ~[mi.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:164) ~[mi.class:?]
18.02 18:22:11 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:215) ~[NetworkDispatcher$1.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[er.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mh.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:743) [MinecraftServer.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
18.02 18:22:11 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
18.02 18:22:11 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
18.02 18:22:11 [Server] INFO at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:94) ~[XUBlockTESR.class:?]
18.02 18:22:11 [Server] INFO at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:34) ~[XUBlockTESR.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766) ~[auo.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784) ~[auo.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.world.World.func_175625_s(World.java:7470) ~[ajs.class:?]
18.02 18:22:11 [Server] INFO at com.rwtema.extrautils2.backend.XUBlockTESR.getWorldModel(XUBlockTESR.java:61) ~[XUBlockTESR.class:?]
18.02 18:22:11 [Server] INFO at com.rwtema.extrautils2.backend.XUBlock.addCollisionBoxToListBase(XUBlock.java:207) ~[XUBlock.class:?]
18.02 18:22:11 [Server] INFO at com.rwtema.extrautils2.compatibility.BlockCompat.func_185477_a(BlockCompat.java:85) ~[BlockCompat.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:451) ~[atm$a.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.world.World.func_191504_a(World.java:1327) ~[ajs.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.world.World.func_184144_a(World.java:1352) ~[ajs.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.entity.Entity.func_70091_d(Entity.java:706) ~[sn.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1866) ~[sw.class:?]
18.02 18:22:11 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1807) ~[aay.class:?]

**Comment by lurr** [comment]
Update ExtraUtilities, this has been fixed.
Please close this issue.
