### ISSUE TITLE
Crash upon loading (other mods installed)

### ISSUE THREAD

**Issue by MadaxTheShadow** [rwtema/extrautilities_old_issues#132]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 6/20/14 12:12 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/PlayerEvent$Clone
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:678)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:268)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:525)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:813)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/player/PlayerEvent$Clone
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
    at java.lang.Class.privateGetPublicMethods(Unknown Source)
    at java.lang.Class.getMethods(Unknown Source)
    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:47)
    at com.rwtema.extrautils.ExtraUtilsProxy.registerEventHandler(ExtraUtilsProxy.java:29)
    at com.rwtema.extrautils.ExtraUtilsClient.registerEventHandler(ExtraUtilsClient.java:56)
    at com.rwtema.extrautils.ExtraUtils.init(ExtraUtils.java:1459)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:209)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:677)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.player.PlayerEvent$Clone
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 44 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 8 (amd64) version 6.2
    Java Version: 1.7.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 513958480 bytes (490 MB) / 731906048 bytes (698 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.156.1060 Minecraft Forge 10.12.1.1060 20 mods loaded, 20 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.156.1060} [Forge Mod Loader](forge-1.7.2-10.12.1.1060.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.1.1060} [Minecraft Forge](forge-1.7.2-10.12.1.1060.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AppliedEnergistics2-Core{rv0-beta-34} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bspkrsCore{6.8(1.7.2)} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.8%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ArmorStatusHUD{1.25(1.7.2)} [ArmorStatusHUD]([1.7.2]ArmorStatusHUD-client-1.25%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    StatusEffectHUD{1.24(1.7.2)} [StatusEffectHUD]([1.7.2]StatusEffectHUD-client-1.24%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv0-beta-34} [Applied Energistics 2](appliedenergistics2-rv0-beta-34.jar) Unloaded->Constructed->Pre-initialized->Initialized
    craftguide{1.6.8.1} [CraftGuide](CraftGuide-1.6.8.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.0.13} [Baubles](Baubles-1.7.2-1.0.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{1.1.0b} [Extra Utilities](extrautilities-1.1.0b.jar) Unloaded->Constructed->Pre-initialized->Errored
    GraveStone{2.8.2} [GraveStone](GraveStone_2.8.2b1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized
    journeymap{4.0.1} [JourneyMap Unlimited Edition](JourneyMap4.0.1_Unlimited_MC1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MetallurgyCore{4.0.1} [Metallurgy Core](MetallurgyCore-1.7.2-4.0.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Metallurgy{4.0.1} [Metallurgy 4](Metallurgy-1.7.2-4.0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    clayspawn{1.7.2a} [Pam's Clay Spawn](Pam's Clay Spawn 1.7.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized
    harvestcraft{1.7.2d} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.2e.zip) Unloaded->Constructed->Pre-initialized->Initialized
    simplerecipes{1.7.2a} [Pam's Simple Recipes](Pam's Simple Recipes 1.7.2a.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.1.1.14} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AE2 Version: beta rv0-beta-34 for Forge 10.12.0.1024

**Comment by rwtema** [comment]
Update Forge.

**Comment by MadaxTheShadow** [comment]
Oops. Sorry. :P Updated brothers and forgot mine.
