### ISSUE TITLE
[1.11.2] Crash with forge-13.20.0.2235+

### ISSUE THREAD

**Issue by Hjaldar** [rwtema/extrautilities_old_issues#1320]
Using extrautils2-1.11.2-1.3.0 and forge-13.20.0.2235

[Crash log](https://github.com/rwtema/extrautilities/files/789829/crash-2017-02-21_21.34.59-client.txt)

Crash does not occur with forge-13.20.0.2233. I presume the issue is related to this item in the forge changelog:
- Added check for quad builder to always have the particle texture set, and fixed where that wasn't true. Fixes #3653

**Comment by gudenau** [comment]
If it is of any help, have the stack trace.

java.lang.IllegalStateException: texture not set
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.build(UnpackedBakedQuad.java:173)
	at com.rwtema.extrautils2.utils.helpers.QuadHelper.buildQuad(QuadHelper.java:52)
	at com.rwtema.extrautils2.utils.helpers.QuadHelper.buildQuad(QuadHelper.java:216)
	at com.rwtema.extrautils2.utils.helpers.QuadHelper.buildQuad(QuadHelper.java:208)
	at com.rwtema.extrautils2.backend.model.PassthruModelItem$1.get(PassthruModelItem.java:42)
	at com.rwtema.extrautils2.backend.model.PassthruModelItem$1.get(PassthruModelItem.java:33)
	at com.rwtema.extrautils2.backend.model.PassthruModelItem$ModelLayer.addSprite(PassthruModelItem.java:279)
	at com.rwtema.extrautils2.backend.model.PassthruModelItem$ModelLayer.addTintedSprite(PassthruModelItem.java:284)
	at com.rwtema.extrautils2.backend.XUItemFlat.addQuads(XUItemFlat.java:46)
	at com.rwtema.extrautils2.backend.model.PassthruModelItem$5.handleItemState(PassthruModelItem.java:135)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:248)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by gudenau** [comment]
Looks like this after the builder creation will make it work.

builder.setTexture(Minecraft.getMinecraft().getTextureMapBlocks().getMissingSprite());

**Comment by gudenau** [comment]
A stupid core mod that fixes this, limited testing but it works for me. Hope you do not mind to much Tema.

[ExtraUtilsFix-1.0.jar.zip](https://github.com/rwtema/extrautilities/files/819066/ExtraUtilsFix-1.0.jar.zip)

**Comment by kreezxil** [comment]
hey gudenau can you put that on Curseforge so I can use it in my pack?

**Comment by gudenau** [comment]
@kreezxil I do not think that is a good idea, this is a temporary fix and it should not be used if it can be helped. I am sure that tema can get EU fixed soon.

**Comment by Hjaldar** [comment]
New version of extra utilities 2 (1.11.2-1.3.1) is out. Same crash with builds of forge >= 13.20.0.2235. Note that the recommended version of forge is only at 13.20.0.2228, so we may need to wait until that changes to get a fix.

**Comment by gudenau** [comment]
Does my hack still work?

**Comment by Hjaldar** [comment]
> Does my hack still work?

Yes

**Comment by Hjaldar** [comment]
Seems to be fixed in 1.11.2-1.3.2. Thanks.
