### ISSUE TITLE
1.11.2 - Since using Crusher

### ISSUE THREAD

**Issue by TontonSancho** [rwtema/extrautilities_old_issues#1327]
Opening the Crusher GUI, not every time, server/client crashes.
```
[08:35:34] [Server thread/INFO]: Saving and pausing game...
[08:35:34] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[08:35:34] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[08:35:34] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[08:35:34] [Server thread/INFO]: Saving chunks for level 'New World'/Deep Dark
[08:35:34] [Server thread/INFO]: Saving chunks for level 'New World'/ExtraUtils2_Quarry_Dim
[08:35:34] [Server thread/INFO]: Saving chunks for level 'New World'/The Dark Realm
[08:35:34] [Server thread/INFO]: Saving chunks for level 'New World'/Omothol
[08:35:34] [Server thread/INFO]: Saving chunks for level 'New World'/The Dreadlands
[08:35:34] [Server thread/INFO]: Saving chunks for level 'New World'/The Abyssal Wasteland
[08:36:57] [Server thread/INFO]: [<PROFILE NAME>: Set the time to 1000]
[08:36:57] [Client thread/INFO]: [CHAT] Set the time to 1000
[08:37:09] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException: The validated object is null
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) [cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException: The validated object is null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222) ~[commons-lang3-3.3.2.jar:3.3.2]
	at org.apache.commons.lang3.Validate.notNull(Validate.java:203) ~[commons-lang3-3.3.2.jar:3.3.2]
	at net.minecraft.util.NonNullList.add(SourceFile:52) ~[dd.class:?]
	at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_121]
	at net.minecraft.inventory.Container.func_75138_a(Container.java:59) ~[acl.class:?]
	at net.minecraft.inventory.Container.func_75132_a(Container.java:48) ~[acl.class:?]
	at com.rwtema.extrautils2.gui.backend.DynamicContainer.func_75132_a(DynamicContainer.java:137) ~[DynamicContainer.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:102) ~[FMLNetworkHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2498) ~[aay.class:?]
	at com.rwtema.extrautils2.tile.XUTile.openGUI(XUTile.java:326) ~[XUTile.class:?]
	at com.rwtema.extrautils2.tile.XUTile.openGUI(XUTile.java:322) ~[XUTile.class:?]
	at com.rwtema.extrautils2.tile.TilePower.onBlockActivated(TilePower.java:151) ~[TilePower.class:?]
	at com.rwtema.extrautils2.backend.XUBlock.onBlockActivatedBase(XUBlock.java:452) ~[XUBlock.class:?]
	at com.rwtema.extrautils2.compatibility.BlockCompat.func_180639_a(BlockCompat.java:69) ~[BlockCompat.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:448) ~[lz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:685) ~[mi.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jm.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jm.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
[08:37:09] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240) ~[cch.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376) ~[afj.class:?]
	at net.minecraft.inventory.Container.func_75142_b(Container.java:78) ~[acl.class:?]
	at com.rwtema.extrautils2.gui.backend.DynamicContainer.func_75142_b(DynamicContainer.java:151) ~[DynamicContainer.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280) ~[ly.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1961) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) ~[lw.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1931) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650) ~[lw.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1723) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more
[08:37:10] [Server thread/ERROR]: This crash report has been saved to: /home/sancho/Games/Minecraft/MultiMC/MultiMC/instances/1.11.2/minecraft/crash-reports/crash-2017-02-22_08.37.09-server.txt
[08:37:10] [Server thread/INFO]: Stopping server
[08:37:10] [Server thread/INFO]: Saving players
[08:37:10] [Server thread/INFO]: <PROFILE NAME> lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[08:37:10] [Server thread/INFO]: <PROFILE NAME> left the game
[08:37:10] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:523]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  FMLPlugin (Inventory-Tweaks-Mod-1.11.2.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 2/22/17 8:37 AM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:78)
	at com.rwtema.extrautils2.gui.backend.DynamicContainer.func_75142_b(DynamicContainer.java:151)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:1723)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:78)
	at com.rwtema.extrautils2.gui.backend.DynamicContainer.func_75142_b(DynamicContainer.java:151)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 290
	Entity Name: <PROFILE NAME>
	Entity's Exact location: 110.79, 76.00, 326.10
	Entity's Block location: World: (110,76,326), Chunk: (at 14,4,6 in 6,20; contains blocks 96,0,320 to 111,255,335), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:1723)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/290, l='New World', x=110.79, y=76.00, z=326.10]]
	Chunk stats: ServerChunkCache: 4238 Drop: 0
	Level seed: -1556575618352662430
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (117,64,314), Chunk: (at 5,4,10 in 7,19; contains blocks 112,0,304 to 127,255,319), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 138386 game time, 1246 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 3753 (now: false), thunder time: 38777 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Linux (amd64) version 4.4.0-62-generic
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 319274016 bytes (304 MB) / 2120220672 bytes (2022 MB) up to 2120220672 bytes (2022 MB)
	JVM Flags: 2 total; -Xms1024m -Xmx2048m
	IntCache: cache: 0, tcache: 8, allocated: 20, tallocated: 86
	FML: MCP 9.38 Powered by Forge 13.20.0.2227 Optifine OptiFine_1.11.2_HD_U_B6 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2227-universal.jar) 
	UCHIJAAAA	forge{13.20.0.2227} [Minecraft Forge] (forge-1.11.2-13.20.0.2227-universal.jar) 
	UCHIJAAAA	backpacks16840{3.1.7} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.7.jar) 
	UCHIJAAAA	jei{4.2.4.229} [Just Enough Items] (jei_1.11.2-4.2.4.229.jar) 
	UCHIJAAAA	abyssalcraft{1.9.3.10} [AbyssalCraft] (AbyssalCraft-1.11.2-1.9.3.10.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UCHIJAAAA	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.0.jar) 
	UCHIJAAAA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2 - 1.11.2.jar) 
	UCHIJAAAA	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHIJAAAA	inventorytweaks{1.62-dev-75-f4ba194} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.11.2.jar) 
	UCHIJAAAA	itemscroller{0.10.3} [Item Scroller] (itemscroller-1.11.2-0.10.3.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHIJAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAA	kleeslabs{4.3.2} [KleeSlabs] (KleeSlabs_1.11.2-4.3.2.jar) 
	UCHIJAAAA	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
	UCHIJAAAA	neat{1.4-13} [Neat] (Neat 1.4-13.jar) 
	UCHIJAAAA	roguelike{1.6.3} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.3.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.1.0} [Storage Drawers] (StorageDrawers-1.11.2-4.1.0.jar) 
	UCHIJAAAA	veinminer{0.35.3} [Vein Miner] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	veinminermodsupport{0.35.3} [Mod Support] (VeinMiner-1.11-0.35.3.605+dad98e1.jar) 
	UCHIJAAAA	wailaharvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.11-1.1.9.jar) 
	Loaded coremods (and transformers): 
BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  brad16840.common.asm.ClassTransformer
FMLPlugin (Inventory-Tweaks-Mod-1.11.2.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/290, l='New World', x=110.79, y=76.00, z=326.10]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.11.2_HD_U_B6
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.5.0 NVIDIA 367.57
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
[08:37:10] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:523]: #@!@# Game crashed! Crash report saved to: #@!@# /home/sancho/Games/Minecraft/MultiMC/MultiMC/instances/1.11.2/minecraft/crash-reports/crash-2017-02-22_08.37.09-server.txt
[08:37:10] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[08:37:10] [Server thread/INFO]: Stopping singleplayer server as player logged out
[08:37:10] [Server thread/INFO]: Saving worlds
[08:37:10] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[08:37:10] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[08:37:10] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[08:37:10] [Server thread/INFO]: Saving chunks for level 'New World'/Deep Dark
[08:37:10] [Server thread/INFO]: Saving chunks for level 'New World'/ExtraUtils2_Quarry_Dim
[08:37:10] [Server thread/INFO]: Saving chunks for level 'New World'/The Dark Realm
[08:37:10] [Server thread/INFO]: Saving chunks for level 'New World'/Omothol
[08:37:10] [Server thread/INFO]: Saving chunks for level 'New World'/The Dreadlands
[08:37:10] [Server thread/INFO]: Saving chunks for level 'New World'/The Abyssal Wasteland
[08:37:10] [Server thread/INFO] [journeymap]: Mapping halted in /home/sancho/Games/Minecraft/MultiMC/MultiMC/instances/1.11.2/minecraft/journeymap/data/sp/New World/DIM0
[08:37:11] [Server thread/INFO] [FML]: Unloading dimension 0
[08:37:11] [Server thread/INFO] [FML]: Unloading dimension -1
[08:37:11] [Server thread/INFO] [FML]: Unloading dimension 1
[08:37:11] [Server thread/INFO] [FML]: Unloading dimension -11325
[08:37:11] [Server thread/INFO] [FML]: Unloading dimension -9999
[08:37:11] [Server thread/INFO] [FML]: Unloading dimension 53
[08:37:11] [Server thread/INFO] [FML]: Unloading dimension 52
[08:37:11] [Server thread/INFO] [FML]: Unloading dimension 51
[08:37:11] [Server thread/INFO] [FML]: Unloading dimension 50
[08:37:11] [Server thread/INFO] [FML]: Applying holder lookups
[08:37:11] [Server thread/INFO] [FML]: Holder lookups applied
[08:37:11] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[08:37:11] [Client thread/INFO] [FML]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.
```

**Comment by SDUBZ** [comment]
was this happening when looking in gui of crusher or just walking around?

**Comment by TontonSancho** [comment]
It happens for me twice before reporting... so, I'm pretty (but not 100%) sure it happened when I opened the GUI. The GUI showed up; the time to me to realize that the Crusher did not crush some remaining ores 'cause RF was depleted... and *crash* Client close.
I can retry many more times if you want.

**Comment by drakray** [comment]
Hitchhiking this, using a hopper to input invalid item/block in Crusher make game [crash](http://pastebin.com/3R9vSVCE)

**Comment by ChuckNoxis** [comment]
In version 1.3.0 - Mc 1.11.2 - Forge 2233
When you crush something into the crusher and you open the GUI of the crusher the server crashes. [crash-2017-02-26_20.23.23-server.txt](https://github.com/rwtema/extrautilities/files/802273/crash-2017-02-26_20.23.23-server.txt)
It's doing exactly the same bug in singleplayer. Trying to crush something and it crashes when open the GUI.

**Comment by ozhound** [comment]
Confirmed. This happens to me as well

When the crusher has finished operation and then the player tries to access the GUI the server crashes with the following 

https://paste.ubuntu.com/24084579/

When the server is restarted, or during the crushing operation, access to the machines GUI works as intended.

**Comment by ShelLuser** [comment]
This is a duplicate of #1279.

Don't take my post in the wrong way please, I'm merely trying to help round things up a bit in order to make it easier for @rwtema to sort it all out. I can well imagine that it could become a little overwhelming when you have to sort out dozens of duplicates.
