### ISSUE TITLE
[1.10] Player unable to join after placing ender drop

### ISSUE THREAD

**Issue by iarspider** [rwtema/extrautilities_old_issues#1338]
Minecraft Version: 1.10.2
Extra Utilities Version: 1.3.0
Forge Version: 2221
Modpack: https://minecraft.curseforge.com/projects/all-the-mods-expert

A player on my server is unable to login after placing ender drop into the world. The following error is logged on the server:
```
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[lu.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162) ~[me.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [md.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
        at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:94) ~[XUBlockTESR.class:?]
        at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:34) ~[XUBlockTESR.class:?]
        at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766) ~[asv.class:?]
        at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784) ~[asv.class:?]
        at net.minecraft.world.World.func_175625_s(World.java:2402) ~[aid.class:?]
        at com.rwtema.extrautils2.backend.XUBlockTESR.getWorldModel(XUBlockTESR.java:61) ~[XUBlockTESR.class:?]
        at com.rwtema.extrautils2.backend.XUBlock.addCollisionBoxToListBase(XUBlock.java:207) ~[XUBlock.class:?]
        at com.rwtema.extrautils2.compatibility.BlockCompat.func_185477_a(BlockCompat.java:95) ~[BlockCompat.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:438) ~[art$a.class:?]
        at net.minecraft.world.World.func_184144_a(World.java:1252) ~[aid.class:?]
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:639) ~[rw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1795) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1808) ~[zs.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2217) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:512) ~[zs.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.IBakedModel
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
        at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:94) ~[XUBlockTESR.class:?]
        at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:34) ~[XUBlockTESR.class:?]
        at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766) ~[asv.class:?]
        at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784) ~[asv.class:?]
        at net.minecraft.world.World.func_175625_s(World.java:2402) ~[aid.class:?]
        at com.rwtema.extrautils2.backend.XUBlockTESR.getWorldModel(XUBlockTESR.java:61) ~[XUBlockTESR.class:?]
        at com.rwtema.extrautils2.backend.XUBlock.addCollisionBoxToListBase(XUBlock.java:207) ~[XUBlock.class:?]
        at com.rwtema.extrautils2.compatibility.BlockCompat.func_185477_a(BlockCompat.java:95) ~[BlockCompat.class:?]
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185908_a(BlockStateContainer.java:438) ~[art$a.class:?]
        at net.minecraft.world.World.func_184144_a(World.java:1252) ~[aid.class:?]
        at net.minecraft.entity.Entity.func_70091_d(Entity.java:639) ~[rw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70612_e(EntityLivingBase.java:1795) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70612_e(EntityPlayer.java:1808) ~[zs.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2217) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:512) ~[zs.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
        ... 9 more
```

**Comment by lurr** [comment]
Update ExtraUtilities, this has been fixed.
Please close this issue, unless it persists on 1.4.4+.
