### ISSUE TITLE
NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel

### ISSUE THREAD

**Issue by Eufranio** [rwtema/extrautilities_old_issues#1344]
I just restarted my server, and on place of a Opinium block, the server crashes. Stacktrace:
```
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
	at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:94)
	at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:34)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
	at net.minecraft.world.World.func_175625_s(World.java:5716)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:63)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callBlockPlaceEvent(SpongeForgeEventFactory.java:1074)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:460)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:292)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143)
	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:640)
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:547)
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$null$40(PacketFunction.java:836)
	at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57)
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$43(PacketFunction.java:834)
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322)
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:251)
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:237)
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```
Full crash-report: https://hastebin.com/ivakiyeziw.scala

Using extrautils2-1.10.2-1.3.0
Forge 12.18.3.2239
Minecraft 1.10.2

**Comment by lurr** [comment]
Same error as #1342

**Comment by Eufranio** [comment]
Oh, thanks!
