### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by mackie419** [rwtema/extrautilities_old_issues#1354]
Just updated to the extrautils2 ver.1.3.1 and when it tries to load it looks like the world dimension for the great wall it crashes. here is the crash log.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)
Caused by: java.lang.NoSuchMethodError: com.rwtema.extrautils2.dimensions.WorldWall.func_77128_b()Ljava/lang/String;
	at com.rwtema.extrautils2.dimensions.WorldWall.<init>(WorldWall.java:46)
	at com.rwtema.extrautils2.backend.entries.XU2Entries$91.initValue(XU2Entries.java:1489)
	at com.rwtema.extrautils2.backend.entries.XU2Entries$91.initValue(XU2Entries.java:1486)
	at com.rwtema.extrautils2.backend.entries.Entry.preInitLoad(Entry.java:71)
	at com.rwtema.extrautils2.backend.entries.EntryHandler.preInit(EntryHandler.java:50)
	at com.rwtema.extrautils2.ExtraUtils2.preInit(ExtraUtils2.java:129)

**Comment by mackie419** [comment]
sorry clicked wrong button that closed the issue

**Comment by VonOx** [comment]
I can confirm, same issue

**Comment by mcdodge34** [comment]
Yup, tried to update my FTB Beyond server with this new version and I got exactly this crash, glad I take time to check the github before reporting, since its already reported, we should see a fix soon I guess, I'll revert back to the 1.3.0 version for now...

**Comment by Morpheus1101** [comment]
Can also confirm this as well.

**Comment by DV666** [comment]
Same issue for me :(

[Crash Report](http://pastebin.com/Mb61iSzT)

Downgrade ExtraUtilities in previous version waiting for a fix ^^

**Comment by b0bst3r** [comment]
Fixed in 1.3.2

**Comment by mcdodge34** [comment]
Good a bunch of mods actually updated in the FTB Beyond pack, I'll have to test the new versions, I always keep my mods up to date on all modpacks I play, team does a great job at making sure everything works before releasing a new version, but I make backups before and I play by myself, so if something is wrong and not reported, I find the github and report the error to help fixing the bugs.

**Comment by Mattsingen** [comment]
Can also confirm that this bug is fixed.
