### ISSUE TITLE
crash with ex nihilio in Forever Stranded.

### ISSUE THREAD

**Issue by dwoodfill** [rwtema/extrautilities_old_issues#1357]
// There are four lights!

Time: 3/9/17 10:56 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at exnihiloomnia.registries.crucible.CrucibleRegistry.getItem(CrucibleRegistry.java:85)
	at exnihiloomnia.blocks.crucibles.tileentity.TileEntityCrucible$1.insertItem(TileEntityCrucible.java:49)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transferSlotAtoSlotB(InventoryHelper.java:93)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transfer(InventoryHelper.java:76)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processPosition(TransferNodeItem.java:130)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processPosition(TransferNodeItem.java:31)
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:140)
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:66)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at exnihiloomnia.registries.crucible.CrucibleRegistry.getItem(CrucibleRegistry.java:85)
	at exnihiloomnia.blocks.crucibles.tileentity.TileEntityCrucible$1.insertItem(TileEntityCrucible.java:49)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transferSlotAtoSlotB(InventoryHelper.java:93)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transfer(InventoryHelper.java:76)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processPosition(TransferNodeItem.java:130)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processPosition(TransferNodeItem.java:31)
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:140)
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:66)

-- Block entity being ticked --
Details:
	Name: XU2:TileTransferHolder // com.rwtema.extrautils2.transfernodes.TileTransferHolder
	Block type: ID #1590 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (243,69,-1223), Chunk: (at 3,4,9 in 15,-77; contains blocks 240,0,-1232 to 255,255,-1217), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Actual block type: ID #1590 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: New World1
	All players: 1 total; [EntityPlayerMP['IMNOTDAVE'/202, l='New World1', x=241.60, y=69.00, z=-1220.85]]
	Chunk stats: ServerChunkCache: 412 Drop: 0
	Level seed: 7056548705295340604
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;minecraft:bedrock,59*minecraft:sandstone,7*minecraft:sand;2;biome_1,decoration,dungeon
	Level spawn location: World: (225,70,-1218), Chunk: (at 1,4,14 in 14,-77; contains blocks 224,0,-1232 to 239,255,-1217), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 5078928 game time, 886842 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 168571 (now: false), thunder time: 67005 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2255506232 bytes (2151 MB) / 3622305792 bytes (3454 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 121 mods loaded, 121 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)

**Comment by iona5** [comment]
got similar crash in 1.12 

```---- Minecraft Crash Report ----

WARNING: coremods are present:
  DummyPlugin (ForgeEndertech-1.12.1-4.3.0.0-build.0056.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 12/30/17 12:31 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraftforge.items.wrapper.InvWrapper.extractItem(InvWrapper.java:169)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transferSlotAtoSlotB(InventoryHelper.java:91)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:148)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:36)
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:151)
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:66)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.items.wrapper.InvWrapper.extractItem(InvWrapper.java:169)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transferSlotAtoSlotB(InventoryHelper.java:91)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:148)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:36)
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:151)
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:66)

-- Block entity being ticked --
Details:
	Name: xu2:tiletransferholder // com.rwtema.extrautils2.transfernodes.TileTransferHolder
	Block type: ID #358 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-248,52,234), Chunk: (at 8,3,10 in -16,14; contains blocks -256,0,224 to -241,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #358 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: Test
	All players: 1 total; [EntityPlayerMP['iona5'/24, l='Test', x=-246.44, y=52.00, z=230.61]]
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 4863269649320313448
	Level generator: ID 07 - void, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-244,64,232), Chunk: (at 12,4,8 in -16,14; contains blocks -256,0,224 to -241,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 614061 game time, 614061 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 97582 (now: false), thunder time: 111419 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 656291272 bytes (625 MB) / 1382023168 bytes (1318 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version                         | Source                                          | Signature                                |
	|:--------- |:------------------- |:------------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2                          | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                            | minecraft.jar                                   | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99                       | forge-1.12.2-14.23.1.2555-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.1.2555                    | forge-1.12.2-14.23.1.2555-universal.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | actuallyadditions   | 1.12.2-r126                     | ActuallyAdditions-1.12.2-r126.jar               | None                                     |
	| UCHIJAAAA | forgeendertech      | 1.12.1-4.3.0.0                  | ForgeEndertech-1.12.1-4.3.0.0-build.0056.jar    | None                                     |
	| UCHIJAAAA | adhooks             | 1.12.1-3.1.2.0                  | AdHooks-1.12.1-3.1.2.0-build.0056.jar           | None                                     |
	| UCHIJAAAA | betterbuilderswands | 0.11.1                          | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| UCHIJAAAA | chameleon           | 1.12-4.1.3                      | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCHIJAAAA | crafttweaker        | 4.0.12                          | CraftTweaker2-1.12-4.0.12.jar                   | None                                     |
	| UCHIJAAAA | ctgui               | 1.0.0                           | CraftTweaker2-1.12-4.0.12.jar                   | None                                     |
	| UCHIJAAAA | jei                 | 4.8.5.138                       | jei_1.12.2-4.8.5.138.jar                        | None                                     |
	| UCHIJAAAA | crafttweakerjei     | 2.0.0                           | CraftTweaker2-1.12-4.0.12.jar                   | None                                     |
	| UCHIJAAAA | cucumber            | 1.0.3                           | cucumber-1.12-1.0.3.jar                         | None                                     |
	| UCHIJAAAA | exnihilocreatio     | 1.12-0.1.5                      | exnihilocreatio-1.12-0.1.5.jar                  | None                                     |
	| UCHIJAAAA | excompressum        | 3.0.11                          | ExCompressum_1.12.2-3.0.11.jar                  | None                                     |
	| UCHIJAAAA | extrautils2         | 1.0                             | extrautils2-1.12-1.7.2.jar                      | None                                     |
	| UCHIJAAAA | fw                  | 1.6.0                           | FullscreenWindowed-1.12-1.6.0.jar               | None                                     |
	| UCHIJAAAA | gravestone          | 1.10.0                          | gravestone-1.10.0.jar                           | None                                     |
	| UCHIJAAAA | harvest             | 1.12-1.2.6-18                   | Harvest-1.12-1.2.6-18.jar                       | None                                     |
	| UCHIJAAAA | waila               | 1.8.23                          | Hwyla-1.8.23-B38_1.12.jar                       | None                                     |
	| UCHIJAAAA | mtlib               | @VERSION@                       | MTLib-3.0.1.jar                                 | None                                     |
	| UCHIJAAAA | initialinventory    | 2.0.2                           | InitialInventory-3.0.0.jar                      | None                                     |
	| UCHIJAAAA | ironbackpacks       | 1.12.2-3.0.2-3                  | IronBackpacks-1.12.2-3.0.2-3.jar                | None                                     |
	| UCHIJAAAA | journeymap          | 1.12.2-5.5.2                    | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCHIJAAAA | mousetweaks         | 2.8                             | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCHIJAAAA | mysticalagriculture | 1.6.7                           | mysticalagriculture-1.12-1.6.7.jar              | None                                     |
	| UCHIJAAAA | oreexcavation       | 1.4.109                         | OreExcavation-1.4.109.jar                       | None                                     |
	| UCHIJAAAA | woodenshears        | @MAJOR@.@MINOR@.@REVIS@.@BUILD@ | SBM-WoodenShears-1.12-0.0.1b8.jar               | None                                     |
	| UCHIJAAAA | simplefluidtanks    | 1.12.2-1.7.1.0                  | simplefluidtanks-1.12.2-1.7.1.0.jar             | None                                     |
	| UCHIJAAAA | storagedrawers      | 1.12-5.2.5                      | StorageDrawers-1.12.1-5.3.3.jar                 | None                                     |
	| UCHIJAAAA | tp                  | 1.12                            | tinyprogressions-1.12-3.2.6.jar                 | None                                     |
	| UCHIJAAAA | ts2k16              | 1.2.8                           | TS2K16-1.2.8.jar                                | None                                     |
	| UCHIJAAAA | yunomakegoodmap     | 1.12-6.3.0.28                   | YUNoMakeGoodMap-1.12-6.3.0.28.jar               | None                                     |

	Loaded coremods (and transformers): 
DummyPlugin (ForgeEndertech-1.12.1-4.3.0.0-build.0056.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['iona5'/24, l='Test', x=-246.44, y=52.00, z=230.61]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'```

**Comment by iona5** [comment]
I can actually reproduce this with minimal setup:

STR:

- Start Minecraft 1.12.2 with mods Extra Utilities 2 (1.12-1.7.2) and Tiny Progressions (1.12-3.2.6)
- Start Creative World
- Place Tiny Progressions "Cobblestone Generator" (Tier 1)
- Attach "Transfer Node (Items)" to Cobblestone Generator

Game crashes almost instantly, sometimes it takes a few seconds

Additional info: Using higher tiered cobblestone generators from TP do NOT crash the game - at least not instantly.

Crash Log:
```
[13:06:48] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.NullPointerException
	at net.minecraftforge.items.wrapper.InvWrapper.extractItem(InvWrapper.java:169) ~[InvWrapper.class:?]
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transferSlotAtoSlotB(InventoryHelper.java:91) ~[InventoryHelper.class:?]
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:148) ~[TransferNodeItem.class:?]
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:36) ~[TransferNodeItem.class:?]
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:151) ~[TransferNodeBase.class:?]
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:66) ~[TileTransferHolder.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1829) ~[amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) ~[MinecraftServer.class:?]
	... 4 more
[13:06:48] [Server thread/ERROR]: This crash report has been saved to: E:\Programs\MultiMC\instances\1.12.2extrautilscrash\minecraft\crash-reports\crash-2017-12-31_13.06.48-server.txt
[13:06:48] [Server thread/INFO]: Stopping server
[13:06:48] [Server thread/INFO]: Saving players
[13:06:48] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----
// I feel sad now :(

Time: 12/31/17 1:06 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraftforge.items.wrapper.InvWrapper.extractItem(InvWrapper.java:169)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transferSlotAtoSlotB(InventoryHelper.java:91)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:148)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:36)
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:151)
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:66)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.items.wrapper.InvWrapper.extractItem(InvWrapper.java:169)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transferSlotAtoSlotB(InventoryHelper.java:91)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:148)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processBuffer(TransferNodeItem.java:36)
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:151)
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:66)

-- Block entity being ticked --
Details:
	Name: xu2:tiletransferholder // com.rwtema.extrautils2.transfernodes.TileTransferHolder
	Block type: ID #283 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-206,66,256), Chunk: (at 2,4,0 in -13,16; contains blocks -208,0,256 to -193,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #283 (tile.ExtraUtils2:pipe.pipe.container // com.rwtema.extrautils2.transfernodes.BlockTransferHolder)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: Crashtest
	All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/1215, l='Crashtest', x=-203.18, y=65.00, z=256.55]]
	Chunk stats: ServerChunkCache: 650 Drop: 0
	Level seed: -7803212943224188545
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-200,64,252), Chunk: (at 8,4,12 in -13,15; contains blocks -208,0,240 to -193,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 396 game time, 396 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 135947 (now: false), thunder time: 76328 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_151, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 716409576 bytes (683 MB) / 1321730048 bytes (1260 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID          | Version      | Source                                  | Signature                                |
	|:--------- |:----------- |:------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft   | 1.12.2       | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp         | 9.42         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML         | 8.0.99.99    | forge-1.12.2-14.23.1.2555-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge       | 14.23.1.2555 | forge-1.12.2-14.23.1.2555-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | extrautils2 | 1.0          | extrautils2-1.12-1.7.2.jar              | None                                     |
	| UCHIJAAAA | tp          | 1.12         | tinyprogressions-1.12-3.2.6.jar         | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/1215, l='Crashtest', x=-203.18, y=65.00, z=256.55]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[13:06:48] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed! Crash report saved to: #@!@# E:\Programs\MultiMC\instances\1.12.2extrautilscrash\minecraft\crash-reports\crash-2017-12-31_13.06.48-server.txt
[13:06:48] [main/INFO] [FML]: Waiting for the server to terminate/save.
[13:06:48] [Server thread/INFO]: Saving worlds
[13:06:48] [Server thread/INFO]: Saving chunks for level 'Crashtest'/overworld
[13:06:49] [Server thread/INFO]: Saving chunks for level 'Crashtest'/the_nether
[13:06:49] [Server thread/INFO]: Saving chunks for level 'Crashtest'/the_end
[13:06:49] [Server thread/INFO]: Saving chunks for level 'Crashtest'/Deep Dark
[13:06:49] [Server thread/INFO]: Saving chunks for level 'Crashtest'/ExtraUtils2_Quarry_Dim
[13:06:49] [Server thread/INFO] [FML]: Unloading dimension 0
[13:06:49] [Server thread/INFO] [FML]: Unloading dimension -1
[13:06:49] [Server thread/INFO] [FML]: Unloading dimension 1
[13:06:49] [Server thread/INFO] [FML]: Unloading dimension -11325
[13:06:49] [Server thread/INFO] [FML]: Unloading dimension -9999
[13:06:49] [Server thread/INFO] [FML]: Applying holder lookups
[13:06:49] [Server thread/INFO] [FML]: Holder lookups applied
[13:06:49] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[13:06:49] [main/INFO] [FML]: Server terminated.
[13:06:49] [Client Shutdown Thread/INFO]: Stopping server
[13:06:49] [Client Shutdown Thread/INFO]: Saving players
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
```

**Comment by iona5** [comment]
as it turns out this is apparently a problem with tiny progressions cobblestone generators in general. i tried also integrated dynamics item interfaces and they do crash also with a null pointer exception from time to time.

this issue ( https://github.com/Kashdeya/Tiny-Progressions/issues/68 ) seems to be fixed in the current beta (tinyprogressions-1.12-3.2.10), as the above steps do not crash the game anymore.
