### ISSUE TITLE
ExtraUtils 1.3.3 Minecraft 1.11.2 (NullpointerException)

### ISSUE THREAD

**Issue by knord1** [rwtema/extrautilities_old_issues#1363]
Having a transfer node attached to Crusher.

When I let a Yellorium Ore (extreme reactors) get crushed in the crusher and have the GUI opened to watch the completion, the game crashes when it should show the yellorium dust in output.

This also happens to Iron ore crushed to iron dust (Actually Additions).

Time: 3/12/17 11:33 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraft.item.ItemStack.func_77989_b(ItemStack.java:376)
	at net.minecraft.inventory.Container.func_75142_b(Container.java:78)
	at com.rwtema.extrautils2.gui.backend.DynamicContainer.func_75142_b(DynamicContainer.java:151)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:280)
	at net.minecraft.world.World.func_72866_a(World.java:1961)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840)
	at net.minecraft.world.World.func_72870_g(World.java:1931)
	at net.minecraft.world.WorldServer.func_184147_l(WorldServer.java:650)
	at net.minecraft.world.World.func_72939_s(World.java:1723)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Unknown Source)
https://paste.ee/p/Fb5Oc

**Comment by ghost** [comment]
The same happens to me. It happens no matter what ore I crush.

When I put an ore in the Crusher, exit the GUI, and return later, I instantly crash every time. This is super annoying and makes the game unplayable.

**Comment by ShelLuser** [comment]
This is a duplicate of #1279.

Don't take my post in the wrong way please, I'm merely trying to help round things up a bit in order to make it easier for @rwtema to sort it all out. I can well imagine that it could become a little overwhelming when you have to sort out dozens of duplicates.

**Comment by ghost** [comment]
I am aware. What’s the point of posting this so many times?

**Comment by ktole1999** [comment]
@PapiDimmi search for the error and reply to already existing thread rather than opening new instance.

**Comment by ghost** [comment]
The reason I created a new issue is that the developer hasn’t responded after so many people reporting this issue and the many times I’ve contacted him about it.
