### ISSUE TITLE
1.10.2 Client Crash   17.03.2017

### ISSUE THREAD

**Issue by BM-Black** [rwtema/extrautilities_old_issues#1376]
I made small modpack on my vanilla minecraft. Ialways add new mod when i need. I add  ExtraUtilities2 1.3.3 version to my 1.10.2 modpack but i have crash. When i loaded EnderIO or Immersive Engineering,  had same problem. Anyone help me please?
crash photo:
![adsiz](https://cloud.githubusercontent.com/assets/26486710/24048615/7d245c7e-0b3a-11e7-8f3a-3764026c78af.png)

crash :
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.1 - Kopya.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  RebornCoreASM (RebornCore-1.10.2-2.13.4.128-universal.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 17.03.2017 18:49
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)
Caused by: java.lang.RuntimeException: Could not init class com.rwtema.extrautils2.blocks.BlockPassiveGenerator
	at com.rwtema.extrautils2.backend.entries.BlockClassEntry.initValue(BlockClassEntry.java:28)
	at com.rwtema.extrautils2.backend.entries.BlockClassEntry.initValue(BlockClassEntry.java:7)
	at com.rwtema.extrautils2.backend.entries.Entry.preInitLoad(Entry.java:71)
	at com.rwtema.extrautils2.backend.entries.EntryHandler.preInit(EntryHandler.java:50)
	at com.rwtema.extrautils2.ExtraUtils2.preInit(ExtraUtils2.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Block: class com.rwtema.extrautils2.blocks.BlockPassiveGenerator has property: generatortype with invalidly named value: wınd
	at net.minecraft.block.state.BlockStateContainer.func_185919_a(BlockStateContainer.java:115)
	at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:75)
	at com.rwtema.extrautils2.backend.XUBlockStateCreator.<init>(XUBlockStateCreator.java:49)
	at com.rwtema.extrautils2.backend.XUBlockStateCreator$Builder.build(XUBlockStateCreator.java:320)
	at com.rwtema.extrautils2.blocks.BlockPassiveGenerator.createBlockState(BlockPassiveGenerator.java:64)
	at com.rwtema.extrautils2.blocks.BlockPassiveGenerator.func_180661_e(BlockPassiveGenerator.java:46)
	at net.minecraft.block.Block.<init>(Block.java:225)
	at com.rwtema.extrautils2.compatibility.BlockCompat.<init>(BlockCompat.java:29)
	at com.rwtema.extrautils2.backend.XUBlock.<init>(XUBlock.java:65)
	at com.rwtema.extrautils2.backend.XUBlock.<init>(XUBlock.java:61)
	at com.rwtema.extrautils2.backend.XUBlockStatic.<init>(XUBlockStatic.java:64)
	at com.rwtema.extrautils2.blocks.BlockPassiveGenerator.<init>(BlockPassiveGenerator.java:51)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at com.rwtema.extrautils2.backend.entries.BlockClassEntry.initValue(BlockClassEntry.java:26)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 294595816 bytes (280 MB) / 780787712 bytes (744 MB) up to 4209770496 bytes (4014 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xincgc -Xmx4048M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 66 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCH	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCH	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.1 - Kopya.jar) 
	UCH	NotEnoughItems{2.1.3.201} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.3.201-universal.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	cofhcore{4.1.0} [CoFH Core] (CoFHCore-1.10.2-4.1.0.155-universal.jar) 
	UCH	actuallyadditions{1.10.2-r105} [Actually Additions] (ActuallyAdditions-1.10.2-r105.jar) 
	UCH	IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
	UCH	advanced_machines{60.0.1} [Advanced Machines] (Advanced Machines-60.0.1 - Kopya.jar) 
	UCH	advanced_solar_panels{4.0.4} [Advanced Solar Panels] (Advanced Solar Panels-4.0.4 - Kopya.jar) 
	UCH	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UCH	bdlib{1.12.4.24} [BD Lib] (bdlib-1.12.4.24-mc1.10.2.jar) 
	UCH	ae2stuff{0.6.0.9} [AE2 Stuff] (ae2stuff-0.6.0.9-mc1.10.2.jar) 
	UCH	infinitylib{1.10.2-0.7.0} [InfinityLib] (infinitylib-0.7.0.jar) 
	UCH	agricraft{2.0.0-0.7.0-a12} [AgriCraft] (agricraft-2.0.0-0.7.0-a12.jar) 
	UCH	Aroma1997CoreHelper{1.1.1.1} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.1 - Kopya.jar) 
	UCH	Aroma1997sDimension{1.0} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.9.4-1.2.0.6 - Kopya.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCH	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UCH	BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft[v2.2.1][MC1.10.2] - Kopya.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCH	JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
	UCH	BloodMagic{1.10.2-2.1.7-76} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.7-76.jar) 
	UCH	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCH	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCH	chisel{MC1.10.2-0.0.8.12} [Chisel] (Chisel-MC1.10.2-0.0.8.12.jar) 
	UCH	CodeChickenLib{2.5.6.233} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.6.233-universal.jar) 
	UCH	CodeChickenCore{2.4.0.101} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.101-universal.jar) 
	UCH	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCH	MineTweaker3{3.0.24} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.24.jar) 
	UCH	CustomMainMenu{2.0.2} [Custom Main Menu] (CustomMainMenu-MC1.10.2-2.0.2.jar) 
	UCH	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	UCH	EnderStorage{2.2.1.103} [EnderStorage] (EnderStorage-1.10.2-2.2.1.103-universal.jar) 
	UCH	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCH	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCH	exnihiloomnia{1.2.6} [Ex Nihilo Omnia] (exnihiloomnia-1.2.6.jar) 
	UCH	excompressum{2.0.87} [Ex Compressum] (ExCompressum_1.10.2-2.0.87.jar) 
	UCE	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.3.jar) 
	UCH	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
	UCH	gravisuite{3.0.1} [Gravitation Suite] (Gravitation Suite-3.0.1.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	ironbackpacks{1.10.2-2.2.23} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.23.jar) 
	UCH	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCH	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCH	mtlib{@VERSION@} [MTLib] (MTLib-1.0.1.jar) 
	UCH	modtweaker{2.0.10} [Mod Tweaker] (ModTweaker2-2.0.10.jar) 
	UCH	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
	UCH	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCH	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCH	reborncore{2.13.4.128} [RebornCore] (RebornCore-1.10.2-2.13.4.128-universal.jar) 
	UCH	reborncore-mcmultipart{2.13.4.128} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.13.4.128-universal.jar) 
	UCH	thermalfoundation{2.0.3} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.3.77-universal.jar) 
	UCH	redstonearsenal{2.0.2} [Redstone Arsenal] (RedstoneArsenal-1.10.2-2.0.2.27-universal.jar) 
	UCH	StorageDrawers{1.10.2-3.6.1} [Storage Drawers] (StorageDrawers-1.10.2-3.6.1.jar) 
	UCH	techreborn{2.1.9.198} [TechReborn] (TechReborn-1.10.2-2.1.9.198-universal.jar) 
	UCH	thermalexpansion{5.0.3} [Thermal Expansion] (ThermalExpansion-1.10.2-5.0.3.86-universal.jar) 
	UCH	Translocator{2.1.3.52} [Translocator] (Translocators-1.10.2-2.1.3.52-universal.jar) 
	UCH	treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCH	zerocore{1.10.2-0.1.0.4} [Zero CORE] (zerocore-1.10.2-0.1.0.4.jar) 
	Loaded coremods (and transformers): 
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.0.155-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  team.chisel.common.asm.ChiselTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.201-universal.jar)
  codechicken.nei.asm.NEITransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.1 - Kopya.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.6.233-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
RebornCoreASM (RebornCore-1.10.2-2.13.4.128-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
	GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 20.19.15.4509' Renderer: 'Intel(R) HD Graphics 5500'
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- WailaIntegration (Enabled/Not Forced)

	NotEnoughItems Invalid Fingerprint Reports: 
	List of loaded APIs: 
		* actuallyadditionsapi (29) from ActuallyAdditions-1.10.2-r105.jar
		* AgriCraftAPI (1.0) from agricraft-2.0.0-0.7.0-a12.jar
		* appliedenergistics2|API (rv4) from appliedenergistics2-rv4-alpha-11.jar
		* Baubles|API (1.3.1.3) from Baubles-1.10.2-1.3.9.jar
		* BloodMagic|API (@VERSION@) from BloodMagic-1.10.2-2.1.7-76.jar
		* BotaniaAPI (85) from Botania r1.9-341.jar
		* ChiselAPI (0.0.1) from Chisel-MC1.10.2-0.0.8.12.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.10.2-0.0.8.12.jar
		* CoFHAPI (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* cofhapi (1.5.0) from ActuallyAdditions-1.10.2-r105.jar
		* cofhapi|block (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* cofhapi|core (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* cofhapi|energy (1.5.0) from ActuallyAdditions-1.10.2-r105.jar
		* CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* cofhapi|item (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* cofhapi|tileentity (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.10.2-0.1.0.4.jar
		* cofhapi|util (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|audio (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui|container (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui|element (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui|element|listbox (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|gui|slot (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|inventory (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|util (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|util|helpers (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|world (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* cofhlib|world|feature (1.5.0) from CoFHCore-1.10.2-4.1.0.155-universal.jar
		* ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.1.0.4.jar
		* Guide-API|API (1.10.2-2.0.3-46) from Guide-API-1.10.2-2.0.3-46.jar
		* IronBackpacks|API (0.5) from IronBackpacks-1.10.2-2.2.23.jar
		* jeresources|API (0.5.8.98) from JustEnoughResources-1.10.2-0.5.8.98.jar
		* journeymap|client-api (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-display (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-event (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-model (1.3) from journeymap-1.10.2-5.4.6.jar
		* journeymap|client-api-util (1.3) from journeymap-1.10.2-5.4.6.jar
		* JustEnoughItemsAPI (4.10.1) from jei_1.10.2-3.14.7.416.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.10.2.jar
		* railcraft:API|core (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|carts (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|items (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|signals (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|tracks (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* reborncoreAPI (2.13.4.128) from RebornCore-1.10.2-2.13.4.128-universal.jar
		* reborncoreAPI|Fuel (2.13.4.128) from RebornCore-1.10.2-2.13.4.128-universal.jar
		* reborncoreAPI|Power (2.13.4.128) from RebornCore-1.10.2-2.13.4.128-universal.jar
		* reborncoreAPI|Recipe (2.13.4.128) from RebornCore-1.10.2-2.13.4.128-universal.jar
		* reborncoreAPI|Tile (2.13.4.128) from RebornCore-1.10.2-2.13.4.128-universal.jar
		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|inventory (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.10.2-3.6.1.jar
		* techrebornAPI (2.1.9.198) from TechReborn-1.10.2-2.1.9.198-universal.jar
		* WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.4.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.4.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.10.2-0.1.0.4.jar
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderStorage Invalid Fingerprint Reports: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.13.4.128
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Translocator Invalid Fingerprint Reports:

**Comment by ghost** [comment]
Similar to #1157.

**Comment by Gunner76th** [comment]
First you need to set your memory to at least -Xmx4096. the setting you have is techincally only about 3.9 GB of memory, and with changes in Minecraft 1.10, as well as Forge, having less than 4 real gigs of memory allocated can cause startup crashes. 

I suggest setting your -Xmx to be -Xmx4096M instead of the -Xmx4048M you currently have.
