### ISSUE TITLE
[1.10.2]Placing certain items such as klein and opinium core crashes the server

### ISSUE THREAD

**Issue by itsfolf** [rwtema/extrautilities_old_issues#1383]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.3-anarchy.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  SpongeCoremod (spongeforge-1.10.2-2254-5.2.0-BETA-2234.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 3/19/17 4:54 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/IBakedModel
	at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:94)
	at com.rwtema.extrautils2.backend.XUBlockTESR.createTileEntity(XUBlockTESR.java:34)
	at net.minecraft.world.chunk.Chunk.func_177422_i(Chunk.java:766)
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:784)
	at net.minecraft.world.World.func_175625_s(World.java:5716)
	at net.minecraftforge.common.util.BlockSnapshot.<init>(BlockSnapshot.java:63)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callBlockPlaceEvent(SpongeForgeEventFactory.java:1074)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:460)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:292)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326)
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143)
	at org.spongepowered.common.event.tracking.TrackingUtil.iterateChangeBlockEvents(TrackingUtil.java:640)
	at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:547)
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$null$40(PacketFunction.java:836)
	at org.spongepowered.common.event.tracking.CapturedSupplier.ifPresentAndNotEmpty(CapturedSupplier.java:57)
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$43(PacketFunction.java:834)
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:322)
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:220)
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:237)
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhm000(MinecraftServer.java:3931)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.IBakedModel
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1039243240 bytes (991 MB) / 1449656320 bytes (1382 MB) up to 2843213824 bytes (2711 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254-universal.jar) 
	UCHIJAAAA	spongeapi{5.2.0-SNAPSHOT-a3257a0} [SpongeAPI] (minecraft.jar) 
	UCHIJAAAA	sponge{1.10.2-2254-5.2.0-BETA-2234} [SpongeForge] (spongeforge-1.10.2-2254-5.2.0-BETA-2234.jar) 
	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft[v2.2.1][MC1.10.2].jar) 
	UCHIJAAAA	catclearlag{0.7.1} [CatClearLag] (CatClearLag-0.7.1.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.8.12} [Chisel] (Chisel-MC1.10.2-0.0.8.12.jar) 
	UCHIJAAAA	JEI{3.14.7.413} [Just Enough Items] (jei_1.10.2-3.14.7.413.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.0.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.5.3-anarchy.jar) 
	UCHIJAAAA	griefprevention{2.3.1} [GriefPrevention] (griefprevention-1.10.2-2.3.1.272.jar) 
	UCHIJAAAA	IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
	UCHIJAAAA	io.github.hsyyid.kits{1.7.4} [Kits] (Kits-1.7.4.jar) 
	UCHIJAAAA	luckperms{3.0.47} [LuckPerms] (LuckPerms-Sponge-3.0.47.jar) 
	UCHIJAAAA	stackban{0.2.5} [StackBan] (stackban-5.1.0-0.2.5.jar) 
	UCHIJAAAA	substratum{1.8.2.1} [Substratum] (Substratum-1.10.2-1.8.2.1.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.10.2-0.0.8.12.jar)
  team.chisel.common.asm.ChiselTransformer
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.5.3-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
SpongeCoremod (spongeforge-1.10.2-2254-5.2.0-BETA-2234.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 3 / 20; [EntityPlayerMP['Shopt'/97, l='world', x=893.05, y=70.25, z=959.42], EntityPlayerMP['Checkium'/470, l='world', x=822.07, y=69.00, z=871.14], EntityPlayerMP['Rue_BR'/547, l='world', x=932.69, y=78.13, z=931.30]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by xPkFyre** [comment]
Did you upgrade to 1.2/1.21 for beyond?

I saw a fix listed in the changelog.

**Comment by xPkFyre** [comment]
If you could update your game and see if it's still bugged it may save me a lengthy backup :p

**Comment by itsfolf** [comment]
Ops, I tried upgrading and it fixed, I forgot to close the issue.

**Comment by xPkFyre** [comment]
Just upgrading fixed it, you didn't have to back up?

**Comment by itsfolf** [comment]
No, just upgrading.

**Comment by xPkFyre** [comment]
Cool, thanks for the info!

**Comment by lurr** [comment]
Update ExtraUtilities, this has been fixed.
Please close this issue.
