### ISSUE TITLE
[1.10.2] Crashes with SpongeForge

### ISSUE THREAD

**Issue by Magi1053** [rwtema/extrautilities_old_issues#1388]
```
java.lang.NullPointerException: Ticking block entity
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:161)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:142)
	at net.minecraftforge.common.util.FakePlayer.<init>(FakePlayer.java:42)
	at com.rwtema.extrautils2.fakeplayer.XUFakePlayer.<init>(XUFakePlayer.java:30)
	at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:254)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:231)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2798)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zjn000(WorldServer.java:2785)
	at net.minecraft.world.World.func_72939_s(World.java:5999)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2153)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```
Crash Log: http://pastebin.com/1UKfzUW5

SpongeForge issue: https://github.com/SpongePowered/SpongeForge/issues/970

**Comment by iKurama** [comment]
Can it be reproduced without Sponge? If no, report it to Sponge devs.

**Comment by Magi1053** [comment]
Please notice the last line of the description, and if it wasn't a Sponge issue, I wouldn't have put Sponge in the title

**Comment by eobie** [comment]
same here. fresh install of beyond it works fine. I test with a current backup of my current world on my production server with sponge and the server crashes when I join...
[crash-2017-03-31_13.16.24-server.txt](https://github.com/rwtema/extrautilities/files/886458/crash-2017-03-31_13.16.24-server.txt)

**Comment by ktole1999** [comment]
noticed you have ftbu in pack. by chance did this happen within an ftbu claim? If so did you enable fakeplayer?

**Comment by eobie** [comment]
it is in a ftbu claim.... not sure what a fake player is so I guess i didn't enable it. It's a bone stock FTB Beyond server with just tickprofiler installed. I uninstalled tickprofiler and got the same result..

**Comment by eobie** [comment]
so i looked and fake players are set to true in the team config. this is the default setting..

**Comment by eobie** [comment]
Oh my. I posted this to wrong github!!! So sorry!!

**Comment by Magi1053** [comment]
This is an ongoing issue on SpongeForge https://github.com/SpongePowered/SpongeForge/issues/1368
