### ISSUE TITLE
Placing Dark Glass causes Client Crash; repeated crash

### ISSUE THREAD

**Issue by aelfwyne** [rwtema/extrautilities_old_issues#1394]
As topic says. I crafted and placed a Dark Glass block. My client INSTANTLY crashed. Thankfully I had just made a backup. 

Upon relogging, it immediately crashes again because it apparently can't render the block. 
`java.lang.NullPointerException: Tesselating block model
	at com.rwtema.extrautils2.backend.model.PassthruModelBlock.func_188616_a(PassthruModelBlock.java:37)
	at ConnectedTextures.getNeighbourIcon(ConnectedTextures.java:1364)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:1323)
	at ConnectedTextures.isNeighbour(ConnectedTextures.java:1303)
	at ConnectedTextures.getConnectedTextureCtmIndex(ConnectedTextures.java:1097)
	at ConnectedTextures.getConnectedTextureCtm(ConnectedTextures.java:753)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:539)
	at ConnectedTextures.getConnectedTextureSingle(ConnectedTextures.java:370)
	at ConnectedTextures.getConnectedTextureMultiPass(ConnectedTextures.java:299)
	at ConnectedTextures.getConnectedTexture(ConnectedTextures.java:113)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:89)
	at BlockModelCustomizer.getRenderQuads(BlockModelCustomizer.java:60)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:105)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:54)
	at gcewing.architecture.BaseAORenderingManager$CustomBlockRendererDispatcher.func_175018_a(BaseAORenderingManager.java:85)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:290)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)
`

Complete log follows:
https://paste.ee/p/tNkAL

**Comment by aelfwyne** [comment]
Appears to be caused by Extra Utilities breaking Optifine somehow. A look through bugs shows this has happened before. I updated Optifine to the latest version and is STILL broken.

EDIT: Saw your note about not supporting Optifine. I wish you would reconsider - a lot of systems benefit from a HUGE performance increase by using optifine. You can perfectly well debug crashes caused by YOUR mod and make it work... But it's your mod and you don't have to. You can just let people keep crashing constantly and ignoring bug reports.

**Comment by ktole1999** [comment]
the support issue is based on how optifine changes basic minecraft. yes i use it without issues but others are not so lucky. that is optifines responsibility to make it work not other mods. you change the foundation and expect everyone else to fix the domino effect?
