### ISSUE TITLE
my minecraft crash when i try get out of nether

### ISSUE THREAD

**Issue by gabrielmkvbr** [rwtema/extrautilities_old_issues#1413]
crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  NEICorePlugin (Not-Enough-Items-1.10.2-Latest.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.13.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  IC2core (industrialcraft-2-2.6.142-ex110.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.4.218-universal.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 29/03/17 03:48
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Cannot get property PropertyEnumSimple{name=generatortype, clazz=class com.rwtema.extrautils2.blocks.BlockPassiveGenerator$GeneratorType, values=[SOLAR, LUNAR, LAVA, WATER, WIND, FIRE, CREATIVE, PLAYER_WIND_UP, DRAGON_EGG]} as it does not exist in XUBlockStateCreator{block=extrautils2:supermobspawner, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
    at com.rwtema.extrautils2.tile.TilePassiveGenerator.getMultiplier(TilePassiveGenerator.java:34)
    at com.rwtema.extrautils2.power.UnloadedChunkPower.rebuild(UnloadedChunkPower.java:56)
    at com.rwtema.extrautils2.power.PowerManager.tick(PowerManager.java:414)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_380_PowerManager_tick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_121, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1876348032 bytes (1789 MB) / 3113222144 bytes (2969 MB) up to 6681526272 bytes (6372 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx7G
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.3.2254 Optifine OptiFine_1.10.2_HD_U_D6 42 mods loaded, 42 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
    UCHIJAAAA   Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
    UCHIJAAAA   AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{2.1.3.199} [Not Enough Items] (Not-Enough-Items-1.10.2-Latest.jar) 
    UCHIJAAAA   foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
    UCHIJAAAA   ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.4.218-universal.jar) 
    UCHIJAAAA   mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
    UCHIJAAAA   libVulpes{0.1.16.20170220215024} [libVulpes] (LibVulpes-1.10.2-0.1.16-universal.jar) 
    UCHIJAAAA   advancedRocketry{1.10.2-1.0.13} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.0.13.jar) 
    UCHIJAAAA   BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft-Mod-1.10.2.jar) 
    UCHIJAAAA   cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
    UCHIJAAAA   chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-Mod-1.10.2.jar) 
    UCHIJAAAA   CodeChickenLib{2.5.4.218} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.4.218-universal.jar) 
    UCHIJAAAA   CodeChickenCore{2.4.0.100} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.0.100-universal.jar) 
    UCHIJAAAA   cookingforblockheads{4.1.12} [Cooking for Blockheads] (CookingForBlockheads-1.10.2&1.9.4.jar) 
    UCHIJAAAA   customspawner{3.10.1} [DrZhark's CustomSpawner] (Custom-Mob-Spawner-Mod-1.10.2.jar) 
    UCHIJAAAA   D3Core{1.2.1.55} [D³Core] (D3Core-1.10.2.jar) 
    UCHIJAAAA   DynamicLights{1.4.3} [Dynamic Lights] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.10.2.jar) 
    UCHIJAAAA   JEI{3.14.7.416} [Just Enough Items] (jei_1.10.2-3.14.7.416.jar) 
    UCHIJAAAA   extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.3.0.jar) 
    UCHIJAAAA   foamfix{@VERSION@} [FoamFix] (foamfix-0.6.1-anarchy.jar) 
    UCHIJAAAA   IC2{2.6.142-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.142-ex110.jar) 
    UCHIJAAAA   inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
    UCHIJAAAA   Lumberjack{1.3.1.39} [Lumberjack] (Lumberjack-1.9.4-1.3.1.39.jar) 
    UCHIJAAAA   lux{1.7} [Lux Lighting] (Lux-Lighting-Mod-1.10.2.jar) 
    UCHIJAAAA   malisiscore{1.10.2-4.3.0} [MalisisCore] (malisiscore-1.10.2-4.3.0.jar) 
    UCHIJAAAA   malisisdoors{1.10.2-5.1.8} [MalisisDoors] (MalisisDoors-1.10.2.jar) 
    UCHIJAAAA   mocreatures{10.0.6} [DrZhark's Mo'Creatures Mod] (Mo-Creatures-Mod-1.10.2.jar) 
    UCHIJAAAA   OpenComputers{1.6.0.2-beta.4} [OpenComputers] (OpenComputers-Mod-1.10.2.jar) 
    UCHIJAAAA   ropebridge{1.4.8} [Rope Bridge] (ropebridge-1.10.2-1.4.8.jar) 
    UCHIJAAAA   rustic{0.0.4} [Rustic] (rustic-0.0.4-1.10.2.jar) 
    UCHIJAAAA   treechopper{1.1.2} [Tree Chopper] (TreeChopper-1.10.2-1.1.2.jar) 
    Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-66.jar)
  invtweaks.forge.asm.ContainerTransformer
NEICorePlugin (Not-Enough-Items-1.10.2-Latest.jar)
  codechicken.nei.asm.NEITransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.13.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
MalisisCorePlugin (malisiscore-1.10.2-4.3.0.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
IC2core (industrialcraft-2-2.6.142-ex110.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.4.218-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    NotEnoughItems Invalid Fingerprint Reports: 
    CodeChickenLib Invalid Fingerprint Reports: 
    CodeChickenCore Invalid Fingerprint Reports: 
    D3Core: Debug: false Silliness: true AprilFools: true PastPost:true
    Profiler Position: N/A (disabled)
    Player Count: 1 / 8; [EntityPlayerMP['gabrielmkv'/2029, l='SP World', x=1339,50, y=118,10, z=-854,50]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.10.2_HD_U_D6
    Render Distance Chunks: 16
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 4.5.13464 Compatibility Profile Context 21.19.411.0
    OpenGlRenderer: AMD Radeon (TM) R7 360 Series
    OpenGlVendor: ATI Technologies Inc.
    CpuCount: 4

**Comment by ktole1999** [comment]
"Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.1-anarchy.jar)"

is there a newer foamfix?

**Comment by gabrielmkvbr** [comment]
nope, and i already try change the "version" (lawful)
