### ISSUE TITLE
Extra Utilities is Crashing server?

### ISSUE THREAD

**Issue by dilanx** [rwtema/extrautilities_old_issues#1498]
Hello!

My server keeps crashing and it says it's because of Extra Utilities 2. I need help with this.

`24.05 13:02:32 [Server] Server thread/ERROR [FML]: The following problems were captured during this phase
24.05 13:02:32 [Server] Server thread/ERROR [FML]: Caught exception from Extra Utilities 2 (extrautils2)
24.05 13:02:32 [Server] INFO java.lang.NoSuchMethodError: com.rwtema.extrautils2.dimensions.WorldWall.func_77128_b()Ljava/lang/String;
24.05 13:02:32 [Server] INFO at com.rwtema.extrautils2.dimensions.WorldWall.<init>(WorldWall.java:46) ~[WorldWall.class:?]
24.05 13:02:32 [Server] INFO at com.rwtema.extrautils2.backend.entries.XU2Entries$91.initValue(XU2Entries.java:1489) ~[XU2Entries$91.class:?]
24.05 13:02:32 [Server] INFO at com.rwtema.extrautils2.backend.entries.XU2Entries$91.initValue(XU2Entries.java:1486) ~[XU2Entries$91.class:?]
24.05 13:02:32 [Server] INFO at com.rwtema.extrautils2.backend.entries.Entry.preInitLoad(Entry.java:71) ~[Entry.class:?]
24.05 13:02:32 [Server] INFO at com.rwtema.extrautils2.backend.entries.EntryHandler.preInit(EntryHandler.java:50) ~[EntryHandler.class:?]
24.05 13:02:32 [Server] INFO at com.rwtema.extrautils2.ExtraUtils2.preInit(ExtraUtils2.java:129) ~[ExtraUtils2.class:?]
24.05 13:02:32 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
24.05 13:02:33 [Multicraft] Server shut down (starting)`

**Comment by ktole1999** [comment]
change the worlgen type from worldwall to something else. looks like this is what is causing it if i am reading the error correctly.

**Comment by dilanx** [comment]
@ktole1999 Change the gen type? How do I do that? My server's world type is BIOMESOP (because the mod pack includes Biomes O' Plenty) and I can't find WorldWall anywhere. Does it have something to do with the Deep Dark or the Quarry Dimension, maybe?

**Comment by ktole1999** [comment]
looks like i misread it. exu2 is complaining about that dimension for some reason.
