### ISSUE TITLE
AbstractMethodError showed up in the server log

### ISSUE THREAD

**Issue by Ricket** [rwtema/extrautilities_old_issues#1503]
```
[22:57:02] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.AbstractMethodError
        at com.rwtema.extrautils2.crafting.jei.JEIRadar$PacketPing$1.run(JEIRadar.java:137) ~[JEIRadar$PacketPing$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

Pack: All the Mods 2 v0.68
Extra utils version: extrautils2-1.11.2-1.4.1

**Comment by chezpaul** [comment]
I have the same error in my server.
Is he checking this github?
