### ISSUE TITLE
Crash when using Wireless RF system with Calculator Machines

### ISSUE THREAD

**Issue by Dilnu** [rwtema/extrautilities_old_issues#1519]
Hi there, I was trying to power a Precision Chamber from Calculator with a wireless RF Battery and it crashed. I'm not sure if it's relevant but I was powering the wireless rf battery from a creative power source.

Forge Version: forge-1.10.2-12.18.3.2297
Extra Utils version: extrautils2-1.10.2-1.4.3

My crash log is here:
`---- Minecraft Crash Report ----
// Don't do that.

Time: 6/6/17 11:34 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at sonar.core.network.sync.SyncSidedEnergyStorage.setCurrentFace(SyncSidedEnergyStorage.java:25)
	at sonar.core.common.tileentity.TileEntityEnergySidedInventory.getCapability(TileEntityEnergySidedInventory.java:89)
	at com.rwtema.extrautils2.utils.CapGetter$3.hasCapability(CapGetter.java:48)
	at com.rwtema.extrautils2.utils.CapGetter.hasInterface(CapGetter.java:113)
	at com.rwtema.extrautils2.power.energy.EnergyTransfer.isValidOutput(EnergyTransfer.java:153)
	at com.rwtema.extrautils2.power.energy.TilePowerTransmitter.refreshTiles(TilePowerTransmitter.java:132)
	at com.rwtema.extrautils2.power.energy.TilePowerTransmitter.getTargets(TilePowerTransmitter.java:41)
	at com.rwtema.extrautils2.power.energy.EnergyTransfer.onServerTick(EnergyTransfer.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_33_EnergyTransfer_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.12.4
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 969949976 bytes (925 MB) / 2286944256 bytes (2181 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 3 total; -Xmx5120m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.3.2297 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2297.jar) 
	UCHIJAAAA	Forge{12.18.3.2297} [Minecraft Forge] (forge-1.10.2-12.18.3.2297.jar) 
	UCHIJAAAA	sonarcore{3.2.7} [SonarCore] (SonarCore-1.10.2-3.2.7.jar) 
	UCHIJAAAA	calculator{3.2.2} [Calculator] (Calculator-1.10.2-3.2.2.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.3.jar) 
	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['TransrealClouden'/1211, l='New World', x=41.34, y=72.00, z=-128.92]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`

**Comment by Dilnu** [comment]
So I've looked into this a little more, it looks like Calculator requires that the facing Enum value is set when you try to get the capability if it's not then it doesn't handle the null gracefully.

**Comment by Dilnu** [comment]
This has been fixed by the Calculator Dev
