### ISSUE TITLE
[1.10.2] Crash when wireless transmitter connecting to Thermal Dynamics Energy Conduits

### ISSUE THREAD

**Issue by lightlike** [rwtema/extrautilities_old_issues#1526]
Version: 1.10.2
Extra Utilities-Version: 1.4.3
Thermal Dynamics Version: 2.0.1.33-universal
Will also report to Thermal Dynamics

Game is Crashing when setting the wireless transmitter next to Therm Dyn Energy Conduits

Crash Report:

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   FarseekCoreMod (Farseek-1.9.4-2.1.jar)
>   BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
>   LoadingPlugin (Quark-r1.1-70.jar)
>   MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
>   CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
>   ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
>   FMLPlugin (InventoryTweaks-1.61-58.jar)
>   CoFH Loading Plugin (CoFHCore-1.10.2-4.1.2.157-universal.jar)
>   BlurPlugin (Blur-1.0.1-9.jar)
>   ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
>   ForgelinPlugin (Forgelin-1.4.2.jar)
>   DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.5.3.jar)
> Contact their authors BEFORE contacting forge
> 
> // Oh - I know what I did wrong!
> 
> Time: 6/11/17 6:42 PM
> Description: Exception in server tick loop
> 
> java.lang.NullPointerException: Exception in server tick loop
> 	at cofh.thermaldynamics.duct.tiles.TileGrid.canConnectEnergy(TileGrid.java:1127)
> 	at com.rwtema.extrautils2.utils.CapGetter$2.convertInstance(CapGetter.java:41)
> 	at com.rwtema.extrautils2.utils.CapGetter$2.convertInstance(CapGetter.java:38)
> 	at com.rwtema.extrautils2.utils.CapGetter$Converter.convert(CapGetter.java:162)
> 	at com.rwtema.extrautils2.utils.CapGetter.getInterface(CapGetter.java:146)
> 	at com.rwtema.extrautils2.utils.CapGetter$3.getInterface(CapGetter.java:54)
> 	at com.rwtema.extrautils2.utils.CapGetter$3.getInterface(CapGetter.java:44)
> 	at com.rwtema.extrautils2.power.energy.EnergyTransfer.onServerTick(EnergyTransfer.java:104)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_129_EnergyTransfer_onServerTick_ServerTickEvent.invoke(.dynamic)
> 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
> 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
> 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
> 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
> 	at java.lang.Thread.run(Thread.java:745)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.10.2
> 	Operating System: Windows 7 (amd64) version 6.1
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 770821320 bytes (735 MB) / 4007657472 bytes (3822 MB) up to 4772593664 bytes (4551 MB)
> 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5120m -Xms256m -XX:PermSize=256m
> 	IntCache: cache: 4, tcache: 0, allocated: 9, tallocated: 61
> 	FML: MCP 9.32 Powered by Forge 12.18.3.2316 Optifine OptiFine_1.10.2_HD_U_D8 97 mods loaded, 97 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2316.jar) 
> 	UCHIJAAAA	Forge{12.18.3.2316} [Minecraft Forge] (forge-1.10.2-12.18.3.2316.jar) 
> 	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
> 	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
> 	UCHIJAAAA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
> 	UCHIJAAAA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
> 	UCHIJAAAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
> 	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
> 	UCHIJAAAA	cofhcore{4.1.2} [CoFH Core] (CoFHCore-1.10.2-4.1.2.157-universal.jar) 
> 	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.3.jar) 
> 	UCHIJAAAA	flyringbaublemod{0.2.4_1.10.2-d71eb9e} [AngelRing 2 Bauble] (angelRingToBauble-1.10.2-0.2.4.19+d71eb9e.jar) 
> 	UCHIJAAAA	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
> 	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
> 	UCHIJAAAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
> 	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
> 	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
> 	UCHIJAAAA	ichunutil{6.3.2} [iChunUtil] (iChunUtil-1.10.2-6.3.2.jar) 
> 	UCHIJAAAA	backtools{6.2.0} [BackTools] (BackTools-1.10.2-6.0.0.jar) 
> 	UCHIJAAAA	BBG{5.0.0} [BetterBedrockGen] (BBG-1.9.4-5.0.0.jar) 
> 	UCHIJAAAA	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
> 	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar) 
> 	UCHIJAAAA	BiomesOPlenty{5.0.0.2236} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2236-universal.jar) 
> 	UCHIJAAAA	blockdrops{1.1.1} [Block Drops] (BlockDrops-1.10.2-1.1.1.jar) 
> 	UCHIJAAAA	blur{1.0.1-9} [Blur] (Blur-1.0.1-9.jar) 
> 	UCHIJAAAA	bookshelf{1.4.4.347} [Bookshelf] (Bookshelf-1.10.2-1.4.4.347.jar) 
> 	UCHIJAAAA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
> 	UCHIJAAAA	ChestTransporter{2.5.17} [Chest Transporter] (ChestTransporter-1.10.2-2.5.17.jar) 
> 	UCHIJAAAA	chisel{MC1.10.2-0.0.10.22} [Chisel] (Chisel-MC1.10.2-0.0.10.22.jar) 
> 	UCHIJAAAA	CodeChickenLib{2.5.9.267} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
> 	UCHIJAAAA	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
> 	UCHIJAAAA	cyberware{beta-0.2.10} [Cyberware] (cyberware-1.9.4-1.10.2-beta-0.2.10.jar) 
> 	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
> 	UCHIJAAAA	darkutils{1.1.8.finalrc2} [Dark Utilities] (DarkUtilities-1.1.8.finalrc2.jar) 
> 	UCHIJAAAA	dsurround{3.4.5.3} [§3Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.4.5.3.jar) 
> 	UCHIJAAAA	presets{3.4.5.3} [§3Presets!] (DynamicSurroundings-1.10.2-3.4.5.3.jar) 
> 	UCHIJAAAA	farseek{2.1} [Farseek] (Farseek-1.9.4-2.1.jar) 
> 	UCHIJAAAA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
> 	UCHIJAAAA	forestry{5.2.17.376} [Forestry] (forestry_1.10.2-5.2.17.376.jar) 
> 	UCHIJAAAA	forgelin{1.4.2} [Forgelin] (Forgelin-1.4.2.jar) 
> 	UCHIJAAAA	friendlyfire{1.3.0} [Friendly Fire] (FriendlyFire-1.10.2-1.3.0.jar) 
> 	UCHIJAAAA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
> 	UCHIJAAAA	ftbl{0.0.0} [FTBLib] (FTBLib-1.1x-3.6.5.jar) 
> 	UCHIJAAAA	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.1x-3.6.5.jar) 
> 	UCHIJAAAA	fw{1.5.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.5.0.jar) 
> 	UCHIJAAAA	gravestone{1.5.12} [Gravestone] (GraveStone Mod 1.5.12.jar) 
> 	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
> 	UCHIJAAAA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
> 	UCHIJAAAA	immersiveengineering{0.10-58} [Immersive Engineering] (ImmersiveEngineering-0.10-58.jar) 
> 	UCHIJAAAA	immersivepetroleum{1.0.4} [Immersive Petroleum] (immersivepetroleum-1.10.2-1.0.4.jar) 
> 	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
> 	UCHIJAAAA	ironbackpacks{1.10.2-2.2.27} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.27.jar) 
> 	UCHIJAAAA	ironchest{1.10.2-7.0.15.804} [Iron Chest] (ironchest-1.10.2-7.0.15.804.jar) 
> 	UCHIJAAAA	JEFB{1.0.4} [Just Enough Forestry Bees] (jefb_1.10.2-1.0.4.jar) 
> 	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
> 	UCHIJAAAA	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
> 	UCHIJAAAA	KaishiWeapons{v0.1} [Kaishi's Weapons Pack] (KaishiWeapons-1.9.4.jar) 
> 	UCHIJAAAA	kleeslabs{3.3.5} [KleeSlabs] (KleeSlabs_1.10.2-3.3.5.jar) 
> 	UCHIJAAAA	levels{3.0.2} [Levels 3] (Levels 3-1.10.2-3.0.2-beta.jar) 
> 	UCHIJAAAA	librarianlib{1.10.1} [LibrarianLib] (librarianlib-1.10.1.jar) 
> 	UCHIJAAAA	llor{1.1.1-mc[1.9-1.11]} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.1-mc[1.9-1.11].jar) 
> 	UCHIJAAAA	malisiscore{1.10.2-4.4.0} [MalisisCore] (malisiscore-1.10.2-4.4.0.jar) 
> 	UCHIJAAAA	malisisdoors{1.10.2-5.2.0} [MalisisDoors] (malisisdoors-1.10.2-5.2.0.jar) 
> 	UCHIJAAAA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.10.2-1.13.jar) 
> 	UCHIJAAAA	StorageDrawers{1.10.2-3.7.9} [Storage Drawers] (StorageDrawers-1.10.2-3.7.9.jar) 
> 	UCHIJAAAA	refinedstorage{1.2.26} [Refined Storage] (refinedstorage-1.2.26.jar) 
> 	UCHIJAAAA	moartinkers{0.4.1} [Moar Tinkers] (moartinkers-0.4.1.jar) 
> 	UCHIJAAAA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.10.2.jar) 
> 	UCHIJAAAA	natura{1.10.2-4.1.0.65} [Natura] (natura-1.10.2-4.1.0.65.jar) 
> 	UCHIJAAAA	botanicaladdons{1.10} [Natural Pledge] (NaturalPledge-r1.11.jar) 
> 	UCHIJAAAA	Neat{1.3-12} [Neat] (Neat 1.3-12.jar) 
> 	UCHIJAAAA	recipehandler{0.6} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.6(1.10.2).jar) 
> 	UCHIJAAAA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
> 	UCHIJAAAA	passthroughsigns{2.0.1} [Passthrough Signs] (PassthroughSigns-1.10.2-2.0.1.jar) 
> 	UCHIJAAAA	railcraft{10.1.2} [Railcraft] (Railcraft_1.10.2-10.1.2.jar) 
> 	UCHIJAAAA	rccosmetic{3.0.5} [Railcraft Cosmetic Additions] (RailCraft Cosmetic Additions-3.0.5.jar) 
> 	UCHIJAAAA	realdrops{1.0.9} [Realistic Item Drops] (RealisticItemDrops-1.0.9.jar) 
> 	UCHIJAAAA	ropebridge{2.0.5} [Rope Bridge] (ropebridge-1.10.2-2.0.5.jar) 
> 	UCHIJAAAA	RTG{4.2.0.0-snapshot-1} [Realistic Terrain Generation] (RTG-1.10.2-4.2.0.0-snapshot-1.jar) 
> 	UCHIJAAAA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
> 	UCHIJAAAA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
> 	UCHIJAAAA	SophisticatedWolves{3.6.1} [SophisticatedWolves] (SophisticatedWolves-3.6.5.jar) 
> 	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
> 	UCHIJAAAA	stg{1.0.2} [SwingThroughGrass] (stg-1.0.2.jar) 
> 	UCHIJAAAA	streams{0.3} [Streams] (Streams-1.9.4-0.3.jar) 
> 	UCHIJAAAA	rscircuits{1.0.4} [Super Circuit Maker] (SuperCircuitMaker-1.0.4.jar) 
> 	UCHIJAAAA	terracart{1.10.2-2.1} [TerraCart] (terracart-1.10.2-2.1.jar) 
> 	UCHIJAAAA	thermalfoundation{2.1.0} [Thermal Foundation] (ThermalFoundation-1.10.2-2.1.0.82-universal.jar) 
> 	UCHIJAAAA	thermaldynamics{2.0.1} [Thermal Dynamics] (ThermalDynamics-1.10.2-2.0.1.33-universal.jar) 
> 	UCHIJAAAA	thermalexpansion{5.1.1} [Thermal Expansion] (ThermalExpansion-1.10.2-5.1.1.93-universal.jar) 
> 	UCHIJAAAA	tumbleweed{1.10-0.3.1} [Tumbleweed] (tumbleweed-1.10-0.3.1.jar) 
> 	UCHIJAAAA	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
> 	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
> 	UCHIJAAAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
> 	UCHIJAAAA	waystones{2.0.12} [Waystones] (Waystones_1.10.2-2.0.12.jar) 
> 	UCHIJAAAA	wired{1.7.0} [WIRED: More Augs] (WIRED-1.7.0.jar) 
> 	UCHIJAAAA	librarianliblate{1.10.1} [LibrarianLib Stage 2] (librarianlib-1.10.1.jar) 
> 	Loaded coremods (and transformers): 
> FarseekCoreMod (Farseek-1.9.4-2.1.jar)
>   farseek.core.FarseekClassTransformer
> BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.4.347.jar)
>   net.darkhax.bookshelf.asm.BookshelfTransformerManager
> LoadingPlugin (Quark-r1.1-70.jar)
>   vazkii.quark.base.asm.ClassTransformer
> MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
>   net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
>   net.malisis.core.util.chunkblock.ChunkBlockTransformer
>   net.malisis.core.renderer.transformer.MalisisRendererTransformer
>   net.malisis.core.renderer.icon.asm.TextureMapTransformer
>   net.malisis.core.util.clientnotif.ClientNotifTransformer
> CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
>   codechicken.lib.asm.ClassHeirachyManager
>   codechicken.lib.asm.CCL_ASMTransformer
> ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
>   team.chisel.common.asm.ChiselTransformer
> FMLPlugin (InventoryTweaks-1.61-58.jar)
>   invtweaks.forge.asm.ContainerTransformer
> CoFH Loading Plugin (CoFHCore-1.10.2-4.1.2.157-universal.jar)
>   cofh.asm.CoFHClassTransformer
>   cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
> BlurPlugin (Blur-1.0.1-9.jar)
>   com.tterrag.blur.BlurTransformer
> ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
>   am2.asm.Transformer
> ForgelinPlugin (Forgelin-1.4.2.jar)
>   
> DynamicSurroundingsCore (DynamicSurroundings-1.10.2-3.4.5.3.jar)
>   org.blockartistry.DynSurround.asm.Transformer
> 	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
> 	Pulsar/tconstruct loaded Pulses: 
> 		- TinkerCommons (Enabled/Forced)
> 		- TinkerWorld (Enabled/Not Forced)
> 		- TinkerTools (Enabled/Not Forced)
> 		- TinkerHarvestTools (Enabled/Forced)
> 		- TinkerMeleeWeapons (Enabled/Forced)
> 		- TinkerRangedWeapons (Enabled/Forced)
> 		- TinkerModifiers (Enabled/Forced)
> 		- TinkerSmeltery (Enabled/Not Forced)
> 		- TinkerGadgets (Enabled/Not Forced)
> 		- TinkerOredict (Enabled/Forced)
> 		- TinkerIntegration (Enabled/Forced)
> 		- TinkerFluids (Enabled/Forced)
> 		- TinkerMaterials (Enabled/Forced)
> 		- TinkerModelRegister (Enabled/Forced)
> 		- WailaIntegration (Enabled/Not Forced)
> 
> 	Pulsar/natura loaded Pulses: 
> 		- NaturaCommons (Enabled/Forced)
> 		- NaturaOverworld (Enabled/Not Forced)
> 		- NaturaNether (Enabled/Not Forced)
> 		- NaturaDecorative (Enabled/Not Forced)
> 		- NaturaTools (Enabled/Not Forced)
> 		- NaturaEntities (Enabled/Not Forced)
> 		- NaturaOredict (Enabled/Forced)
> 		- NaturaWorld (Enabled/Not Forced)
> 		- WailaIntegration (Enabled/Not Forced)
> 
> 	CodeChickenLib Invalid Fingerprint Reports: 
> 	Profiler Position: N/A (disabled)
> 	Player Count: 0 / 8; []
> 	Type: Integrated Server (map_client.txt)
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	OptiFine Version: OptiFine_1.10.2_HD_U_D8
> 	Render Distance Chunks: 8
> 	Mipmaps: 4
> 	Anisotropic Filtering: 1
> 	Antialiasing: 0
> 	Multitexture: false
> 	Shaders: null
> 	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.157.3
> 	OpenGlRenderer: AMD Radeon (TM) R9 390 Series
> 	OpenGlVendor: ATI Technologies Inc.
> 	CpuCount: 8

**Comment by lightlike** [comment]
Aparently fixed in Thermal Dynamics
