### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by karlreinert** [rwtema/extrautilities_old_issues#156]
I do know that this wasnt updated for 1.7.10 when you compiled it... BUT I figured that you might wanna know if something was amiss...

Tried this using latest Forge, some other mods that I know worked and this one... and the game started, and I could place the blocks in the world... BUT when I tried to right click to open some GUI or anything... The game looses the connection to the game...

Just as a heads up...

**Comment by rwtema** [comment]
Sigh, crash log?

**Comment by karlreinert** [comment]
Well... Seems I havent gotten it... I will try to reproduce it... Downloaded a mod for 1.7.2 and was hoping it would work, and when it didn't I wanted to give you a hey!... 

what happends though is this... 

I load the game, and I load the world. And then I spawn in a generator of the kind I want, and when I click it, I loose connection to the "server" this was on a singleplayer map on my own compute, but the game was still running... Just got a "you have been disconnected message"

I know I was running the 160 version of forge...

**Comment by karlreinert** [comment]
[23:22:25 INFO]: Client> [23:22:25] [Netty Client IO #7/INFO] [FML]: Attempting connection with missing mods [DamageIndicatorsMod, chisel, voxelmap] at SERVER
[23:22:28 INFO]: Client> [23:22:28] [Client thread/INFO]: Connecting to 10.0.0.2, 25600
[23:22:31 INFO]: Client> [23:22:31] [Netty Client IO #0/INFO] [FML]: Server protocol version 1
[23:22:31 INFO]: Client> [23:22:31] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [DamageIndicatorsMod, chisel, voxelmap] at SERVER
[23:22:31 INFO]: Client> [23:22:31] [Netty Client IO #0/INFO] [FML]: Injecting existing block and item data into this client instance
[23:22:31 INFO]: Client> [23:22:31] [Netty Client IO #0/INFO] [FML]: Applying holder lookups
[23:22:31 INFO]: Client> [23:22:31] [Netty Client IO #0/INFO] [FML]: Holder lookups applied
[23:22:31 INFO]: Client> [23:22:31] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[23:22:34 INFO]: Client> [23:22:34] [Client thread/WARN] [NEIAddons]: Error decoding packet
[23:22:34 INFO]: Client> java.lang.NoSuchMethodError: net.minecraft.nbt.CompressedStreamTools.func_74794_a(Ljava/io/DataInput;)Lnet/minecraft/nbt/NBTTagCompound;
[23:22:34 INFO]: Client>    at net.bdew.neiaddons.network.NBTMessageCodec.decode(NBTMessageCodec.java:44) [NBTMessageCodec.class:?]
[23:22:34 INFO]: Client>    at net.bdew.neiaddons.network.NBTMessageCodec.decode(NBTMessageCodec.java:29) [NBTMessageCodec.class:?]
[23:22:34 INFO]: Client>    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [MessageToMessageCodec$2.class:?]
[23:22:34 INFO]: Client>    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [MessageToMessageDecoder.class:?]
[23:22:34 INFO]: Client>    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
[23:22:34 INFO]: Client>    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[23:22:34 INFO]: Client>    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[23:22:34 INFO]: Client>    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[23:22:34 INFO]: Client>    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[23:22:34 INFO]: Client>    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[23:22:34 INFO]: Client>    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[23:22:34 INFO]: Client>    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
[23:22:34 INFO]: Client>    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649) [bao.class:?]
[23:22:34 INFO]: Client>    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
[23:22:34 INFO]: Client>    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[23:22:34 INFO]: Client>    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[23:22:34 INFO]: Client>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
[23:22:34 INFO]: Client>    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
[23:22:34 INFO]: Client>    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
[23:22:34 INFO]: Client>    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
[23:22:34 INFO]: Client>    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
[23:22:34 INFO]: Client>    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
[23:22:34 INFO]: Client> [23:22:34] [Client thread/INFO]: [CHAT] §ENo waypoints exist for this world/server.
[23:23:03 INFO]: Client> [23:23:03] [Client thread/INFO]: [CHAT] Given [Ender Generator] \* 1 to KarlReinert
[23:23:21 INFO]: Client> [23:23:21] [Client thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
[23:23:21 INFO]: Client> java.lang.NoSuchMethodError: net.minecraft.nbt.CompressedStreamTools.func_74792_a([B)Lnet/minecraft/nbt/NBTTagCompound;
[23:23:21 INFO]: Client>    at com.rwtema.extrautils.network.XUPacketBase.readNBT(XUPacketBase.java:58) ~[XUPacketBase.class:?]
[23:23:21 INFO]: Client>    at com.rwtema.extrautils.network.packets.PacketGUIWidget.readData(PacketGUIWidget.java:37) ~[PacketGUIWidget.class:?]
[23:23:21 INFO]: Client>    at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:49) ~[PacketCodec.class:?]
[23:23:21 INFO]: Client>    at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:17) ~[PacketCodec.class:?]
[23:23:21 INFO]: Client>    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[23:23:21 INFO]: Client>    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[23:23:21 INFO]: Client>    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[23:23:21 INFO]: Client>    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[23:23:21 INFO]: Client>    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[23:23:21 INFO]: Client>    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[23:23:21 INFO]: Client>    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[23:23:21 INFO]: Client>    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
[23:23:21 INFO]: Client>    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
[23:23:21 INFO]: Client>    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[23:23:21 INFO]: Client>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
[23:23:21 INFO]: Client>    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
[23:23:21 INFO]: Client>    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
[23:23:21 INFO]: Client>    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
[23:23:21 INFO]: Client>    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
[23:23:21 INFO]: Client>    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
[23:23:21 INFO]: Client> [23:23:21] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel XU|Pkt
[23:23:21 INFO]: Client> java.lang.NoSuchMethodError: net.minecraft.nbt.CompressedStreamTools.func_74792_a([B)Lnet/minecraft/nbt/NBTTagCompound;
[23:23:21 INFO]: Client>    at com.rwtema.extrautils.network.XUPacketBase.readNBT(XUPacketBase.java:58) ~[XUPacketBase.class:?]
[23:23:21 INFO]: Client>    at com.rwtema.extrautils.network.packets.PacketGUIWidget.readData(PacketGUIWidget.java:37) ~[PacketGUIWidget.class:?]
[23:23:21 INFO]: Client>    at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:49) ~[PacketCodec.class:?]
[23:23:21 INFO]: Client>    at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:17) ~[PacketCodec.class:?]
[23:23:21 INFO]: Client>    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
[23:23:21 INFO]: Client>    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
[23:23:21 INFO]: Client>    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
[23:23:21 INFO]: Client>    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
[23:23:21 INFO]: Client>    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
[23:23:21 INFO]: Client>    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
[23:23:21 INFO]: Client>    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
[23:23:21 INFO]: Client>    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
[23:23:21 INFO]: Client>    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
[23:23:21 INFO]: Client>    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
[23:23:21 INFO]: Client>    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[23:23:21 INFO]: Client>    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
[23:23:21 INFO]: Client>    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
[23:23:21 INFO]: Client>    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
[23:23:21 INFO]: Client>    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
[23:23:21 INFO]: Client>    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
[23:23:21 INFO]: Client>    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
[23:23:21 INFO]: Client> [23:23:21] [Client thread/INFO] [FML]: Applying holder lookups
[23:23:21 INFO]: Client> [23:23:21] [Client thread/INFO] [FML]: Holder lookups applied

from the dev log of the launcher

//Kalle

**Comment by karlreinert** [comment]
[23:22:31] [Netty Client IO #0/TRACE] [FML/]: $HandshakeAck:{2}->FMLHandshakeClientState$5:PENDINGCOMPLETE
[23:22:31] [Netty Client IO #0/TRACE] [FML/]: $HandshakeAck:{3}->FMLHandshakeClientState$6:COMPLETE
[23:22:31] [Client thread/INFO] [FML/]: [Client thread] Client side modded connection established
[23:22:34] [Client thread/DEBUG] [NotEnoughItems/]: Loading Remote World
[23:22:34] [Client thread/WARN] [NEIAddons/]: Error decoding packet
java.lang.NoSuchMethodError: net.minecraft.nbt.CompressedStreamTools.func_74794_a(Ljava/io/DataInput;)Lnet/minecraft/nbt/NBTTagCompound;
    at net.bdew.neiaddons.network.NBTMessageCodec.decode(NBTMessageCodec.java:44) [NBTMessageCodec.class:?]
    at net.bdew.neiaddons.network.NBTMessageCodec.decode(NBTMessageCodec.java:29) [NBTMessageCodec.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) [MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
[23:23:21] [Client thread/ERROR] [FML/]: FMLIndexedMessageCodec exception caught
java.lang.NoSuchMethodError: net.minecraft.nbt.CompressedStreamTools.func_74792_a([B)Lnet/minecraft/nbt/NBTTagCompound;
    at com.rwtema.extrautils.network.XUPacketBase.readNBT(XUPacketBase.java:58) ~[XUPacketBase.class:?]
    at com.rwtema.extrautils.network.packets.PacketGUIWidget.readData(PacketGUIWidget.java:37) ~[PacketGUIWidget.class:?]
    at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:49) ~[PacketCodec.class:?]
    at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:17) ~[PacketCodec.class:?]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
[23:23:21] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel XU|Pkt
java.lang.NoSuchMethodError: net.minecraft.nbt.CompressedStreamTools.func_74792_a([B)Lnet/minecraft/nbt/NBTTagCompound;
    at com.rwtema.extrautils.network.XUPacketBase.readNBT(XUPacketBase.java:58) ~[XUPacketBase.class:?]
    at com.rwtema.extrautils.network.packets.PacketGUIWidget.readData(PacketGUIWidget.java:37) ~[PacketGUIWidget.class:?]
    at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:49) ~[PacketCodec.class:?]
    at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:17) ~[PacketCodec.class:?]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?]
    at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
    at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
[23:23:21] [Client thread/DEBUG] [FML/]: Reverting to frozen data state.
[23:23:21] [Client thread/INFO] [FML/]: Applying holder lookups
[23:23:21] [Client thread/INFO] [FML/]: Holder lookups applied

From the fml log... 

//kalle

**Comment by rwtema** [comment]
Fixed in next version.
