### ISSUE TITLE
[1.10.2] Tooltip handler throws  java.lang.StackOverflowError

### ISSUE THREAD

**Issue by Kotori316** [rwtema/extrautilities_old_issues#1563]
Forge 12.18.3.2185
Extra Utilities 1.10.2 - 1.5
Every ticks this error log fills the game output.

	java.lang.StackOverflowError
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:265)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:794)
	at com.rwtema.extrautils2.compatibility.CompatHelper112.getTooltip(CompatHelper112.java:48)
	at com.rwtema.extrautils2.items.ItemFakeCopy.changeToolTip(ItemFakeCopy.java:262)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_267_ItemFakeCopy_changeToolTip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:265)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:794)
	at com.rwtema.extrautils2.compatibility.CompatHelper112.getTooltip(CompatHelper112.java:48)
	at com.rwtema.extrautils2.items.ItemFakeCopy.changeToolTip(ItemFakeCopy.java:262)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_267_ItemFakeCopy_changeToolTip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	and repeating more...

This screenshot is game output.
![25](https://user-images.githubusercontent.com/28705167/28018015-8ac142e4-65b6-11e7-878a-3bed43f90c54.png)

**Comment by MJRLegends** [comment]
I can confirm i get this issue too
