### ISSUE TITLE
[1.12] Crash when using crafter

### ISSUE THREAD

**Issue by EtherG** [rwtema/extrautilities_old_issues#1596]
Crash on server when using crafter
Version: extrautils2-1.12-1.5
https://pastebin.com/vvY1yGfF

**Comment by Kris1432** [comment]
Forge 2405
Serverside Crash.

**Comment by CatAndHorse** [comment]
java.lang.ClassCastException: net.minecraftforge.oredict.OreIngredient cannot be cast to net.minecraft.item.ItemStack
	at com.rwtema.extrautils2.tile.TileCrafter.preOperate(TileCrafter.java:306)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:71)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)


I just put a bone into crafter

**Comment by tiarnia** [comment]
same crash 
same version
