### ISSUE TITLE
[1.11.2] Crash when placing ghost items in auto crafter

### ISSUE THREAD

**Issue by StellarPatois** [rwtema/extrautilities_old_issues#1607]
For versions 1.5 and 1.5.1, when I try to place oak planks in a chest pattern, when I click the second one into place, the game crashes. Reverted to 1.4.4 and the problem isn't present. Using Forge 13.20.1.2421. Tested using ExU as the only installed mod.

[crash-2017-07-23_12.21.22-server.txt](https://github.com/rwtema/extrautilities/files/1168501/crash-2017-07-23_12.21.22-server.txt)

**Comment by emberquill** [comment]
Same error happened on a 1.12 server I play on.
```
java.lang.ArrayIndexOutOfBoundsException: 9
    at com.rwtema.extrautils2.tile.TileCrafter.preOperate(TileCrafter.java:288)
    at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:71)
    at net.minecraft.world.World.func_72939_s(World.java:1807)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:391)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Asherslab** [comment]
same thing here! jar: extrautils2-1.10.2-1.5.jar
[crash-2017-07-28_04.19.57-server.txt](https://github.com/rwtema/extrautilities/files/1181887/crash-2017-07-28_04.19.57-server.txt)

**Comment by Entar11262** [comment]
I've now had the same thing happen to me, in both 1.12 and 1.11.2 but I don't have the crash files at the moment

**Comment by Asherslab** [comment]
it'd be lovely if this could get fixed =D... maybe i should fix it myself...
