### ISSUE TITLE
[1.12] Quarry Crash - NullPointerException

### ISSUE THREAD

**Issue by Symbai** [rwtema/extrautilities_old_issues#1613]
I've started to power my quarry and the client instantly crashed. I had a book of fortune 3 in it, MountainHills biome and an empty blacklist filter.

extrautils2-1.12-1.5.1
Forge: 14.21.1.2424

```
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76670_c(ExtendedBlockStorage.java:88)
	at net.minecraft.world.chunk.Chunk.func_177413_a(Chunk.java:651)
	at net.minecraft.world.World.func_175642_b(World.java:856)
	at net.minecraft.world.World.func_180500_c(World.java:2829)
	at net.minecraft.world.World.func_175664_x(World.java:2747)
	at net.minecraft.world.World.func_180501_a(World.java:352)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1146)
	at net.minecraft.server.management.PlayerInteractionManager.removeBlock(PlayerInteractionManager.java:272)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:325)
	at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:321)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by darkshadow543** [comment]
Same issue as the Hell going back to normal, only happens when the hell biome marker is shift-clicked in.
