### ISSUE TITLE
[1.12] NullPointerException - Textures.isMissingModel

### ISSUE THREAD

**Issue by Symbai** [rwtema/extrautilities_old_issues#1617]
I've removed some mods, tried to launch the game and it crashes with the following error log:

extrautils2-1.12-1.5.1
Forge: 14.21.1.2424

```
java.lang.NullPointerException: Initializing game
	at com.rwtema.extrautils2.backend.model.Textures.isMissingModel(Textures.java:341)
	at com.rwtema.extrautils2.backend.model.Textures.checkMissingModelLocation(Textures.java:335)
	at com.rwtema.extrautils2.backend.model.Textures.registerModels(Textures.java:158)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_106_Textures_registerModels_ModelBakeEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:367)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
```

**Comment by ghost** [comment]
Almost same error, except "ASMEventHandler**_57_**Textures_".
In my case, I had installed Chisel, but not CTM (required), but Chisel didn't QQ on startup, instead, I got the same error from ExtraUtils2. Once CTM was installed, the errors stopped.
Ensure all your mods have their core mods installed etc, if you're not sure, put all the mods back and do a 1 by 1 mod test (whereby you add a mod, start it up, see what explodes... etc) until you find the culprit.

**Comment by Symbai** [comment]
Yeah I noticed it was caused by another mod. However the error/crash happens within ExtraUtilities and therefore I have to post the log here, because each other mod author would have redirected me to here as soon as he/she sees the error happens within Extra Utilites code
