### ISSUE TITLE
1.1.0c crashes on startup with TiC installed

### ISSUE THREAD

**Issue by CrazyPants** [rwtema/extrautilities_old_issues#162]
No Idea how this interaction is happening, but adding ExU with the latest Mantle (Mantle_mc1.7.10_0.3.0) / TiC installed (TConstruct_mc1.7.10_1.6.0d33) causes the client to crash on start up. I am guessing an API conflict.

Removing ExU resolves the issue.

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 11/07/14 8:12 PM
Description: Initializing game

java.lang.NoClassDefFoundError: tconstruct/tools/items/Manual
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
    at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:507)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: tconstruct.tools.items.Manual
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 15 more
Caused by: java.lang.NoClassDefFoundError: mantle/items/abstracts/CraftingItem
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:180)
    ... 17 more
Caused by: java.lang.ClassNotFoundException: mantle.items.abstracts.CraftingItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:99)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 21 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
    at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:507)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_17, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 302034616 bytes (288 MB) / 574095360 bytes (547 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:MaxPermSize=196M -XX:+CMSClassUnloadingEnabled
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.1.1160 Minecraft Forge 10.13.0.1160 22 mods loaded, 22 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded
    FML{7.10.1.1160} [Forge Mod Loader](forge-1.7.10-10.13.0.1160.jar) Unloaded
    Forge{10.13.0.1160} [Minecraft Forge](forge-1.7.10-10.13.0.1160.jar) Unloaded
    AppliedEnergistics2-Core{rv0-stable-8} [AppliedEnergistics2 Core](minecraft.jar) Unloaded
    CodeChickenCore{1.0.1.8} [CodeChicken Core](minecraft.jar) Unloaded
    NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded
    aobd{2.0.2} [Another One Bites The Dust](AOBD-2.0.2.jar) Unloaded
    appliedenergistics2{rv0-stable-8} [Applied Energistics 2](appliedenergistics2-rv0-stable-8.jar) Unloaded
    Backpack{2.0.0} [Backpack](backpack-2.0.0-1.7.x.jar) Unloaded
    BiblioCraft{1.7.3} [BiblioCraft](BiblioCraft[v1.7.3][MC1.7.10].jar) Unloaded
    AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.0.1g%281.7.10%29.jar) Unloaded
    chisel{1.5.5a} [Chisel](Chisel-1.7.2-1.5.5a.jar) Unloaded
    EnderIO{2.0_beta} [Ender IO](enderio-2.0_beta.136.jar) Unloaded
    ExtraUtilities{1.1.0c} [Extra Utilities](extrautilities-1.1.0c.jar) Unloaded
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded
    IronChest{6.0.41.729} [Iron Chest](ironchest-1.7.10-6.0.41.729-universal.jar) Unloaded
    journeymap{4.0.1} [JourneyMap](JourneyMap4.0.1_Unlimited_MC1.7.10.jar) Unloaded
    Mantle{1.7.10-165.4bc3343} [Mantle](Mantle_mc1.7.10_0.3.0.jar) Unloaded
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0-b1.jar) Unloaded
    TConstruct{1.7.10-1.6.0.jenkins528} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d33.jar) Unloaded
    TwilightForest{2.2.0} [The Twilight Forest](twilightforest-1.7.2-2.2.0.jar) Unloaded
    Launched Version: 1.7.10-Forge10.13.0.1160
    LWJGL: 2.9.1
    OpenGL: GeForce GT 750M/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

**Comment by CrazyPants** [comment]
This was resolved by updating forge.
FYI, once I ran MC with just ExU installed I got an error about an out of date forge (I was on 1060, now on 1179). I didnt get this error with TiC installed as it crashed before it was displayed.

**Comment by rwtema** [comment]
The outdated forge message is intended.
