### ISSUE TITLE
Mechanical Crafter causing crashes 1.12

### ISSUE THREAD

**Issue by BlueMoon2255** [rwtema/extrautilities_old_issues#1632]
Well i was crashed yesterday after i placed a crafting recipe in the mechanical crafter. so i decided to to create a  creative world and test it and it did the same thing. The recipe was to make compressed cobble.

 ---- Minecraft Crash Report ----

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.2.jar)
Contact their authors BEFORE contacting forge

// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 8/4/17 9:17 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 9
	at com.rwtema.extrautils2.tile.TileCrafter.preOperate(TileCrafter.java:288)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:71)
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.rwtema.extrautils2.tile.TileCrafter.preOperate(TileCrafter.java:288)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:71)

-- Block entity being ticked --
Details:
	Name: xu2:tilecrafter // com.rwtema.extrautils2.tile.TileCrafter
	Block type: ID #287 (tile.extrautils2:crafter // com.rwtema.extrautils2.blocks.BlockCrafter)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (741,4,1107), Chunk: (at 5,0,3 in 46,69; contains blocks 736,0,1104 to 751,255,1119), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Actual block type: ID #287 (tile.extrautils2:crafter // com.rwtema.extrautils2.blocks.BlockCrafter)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1807)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:614)

-- Affected level --
Details:
	Level name: test
	All players: 1 total; [EntityPlayerMP['dilllon'/31, l='test', x=741.55, y=4.00, z=1110.37]]
	Chunk stats: ServerChunkCache: 256 Drop: 0
	Level seed: 9194753053002687765
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (745,4,1109), Chunk: (at 9,0,5 in 46,69; contains blocks 736,0,1104 to 751,255,1119), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Level time: 6752 game time, 6752 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 90688 (now: false), thunder time: 81717 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:761)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 345555432 bytes (329 MB) / 696655872 bytes (664 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2415 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2415.jar) 
	UCHIJAAAAAA	forge{14.21.1.2415} [Minecraft Forge] (forge-1.12-14.21.1.2415.jar) 
	UCHIJAAAAAA	actuallyadditions{1.12-r116} [Actually Additions] (ActuallyAdditions-1.12-r116.jar) 
	UCHIJAAAAAA	bookshelf{2.0.412} [Bookshelf] (Bookshelf-1.12-2.0.0.412.jar) 
	UCHIJAAAAAA	endercompass{1.2.6.1} [Ender Compass] (EnderCompass-1.12-1.2.6.1.jar) 
	UCHIJAAAAAA	shetiphiancore{3.5.0.2} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.2.jar) 
	UCHIJAAAAAA	endertanks{1.6.0.2} [EnderTanks] (endertanks-1.12.0-1.6.0.2.jar) 
	UCHIJAAAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.1.jar) 
	UCHIJAAAAAA	jei{4.7.2.77} [Just Enough Items] (jei_1.12-4.7.2.77.jar) 
	UCHIJAAAAAA	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UCHIJAAAAAA	packingtape{0.7.4} [Packing Tape] (PackingTape-1.12.0-0.7.4.jar) 
	UCHIJAAAAAA	veinminer{0.37.0} [Vein Miner] (VeinMiner-1.12-0.37.0.628+765cb1f.jar) 
	UCHIJAAAAAA	veinminermodsupport{0.37.0} [Mod Support] (VeinMiner-1.12-0.37.0.628+765cb1f.jar) 
	UCHIJAAAAAA	xaerominimap{1.13.2} [Xaero's Minimap] (Xaeros_Minimap_1.13.2_Forge_1.12.jar) 
	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.2.jar)
  shetiphian.asm.ClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['dilllon'/31, l='test', x=741.55, y=4.00, z=1110.37]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by zadzial** [comment]
Same issue, same recipie. As a result I can't access my world...

**Comment by BlueMoon2255** [comment]
Take the mod out of the mod folder and then join the world again youll only lose about half your extra utilities stuff

**Comment by zadzial** [comment]
Thanks. Worked like an evil, compressed cobblestone eating charm - but I have my world back!

**Comment by ZeekDaGeek** [comment]
Alternative fix without losing everything: Go into the configs and disable specifically the crafters. It crashed me once while joining back into the world when going to the crafter's location but then it was removed and I was able to access my world again.

**Comment by BlueMoon2255** [comment]
The only thing i lost were just a couple water mills,  but i added rftools so i could still use a crafter but its not the same

**Comment by owmii** [comment]
same for me!!


```
Time: 8/10/17 10:05 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 9
	at com.rwtema.extrautils2.tile.TileCrafter.preOperate(TileCrafter.java:288)
	at com.rwtema.extrautils2.tile.TileAdvInteractor.func_73660_a(TileAdvInteractor.java:71)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by BlueMoon2255** [comment]
Its the crafter itself, it ticks to many times and crashes the game

**Comment by nmagod** [comment]
Until this tick overflow is addressed, are there any other mods that use autocrafters?
