### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by pot-code** [rwtema/extrautilities_old_issues#1647]
Single player in creative mode, it occurred when I turned round

Involved blocks:
* Wireless battery
* Wireless transmitter

```java
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at gnu.trove.impl.hash.THashPrimitiveIterator.nextIndex(THashPrimitiveIterator.java:83)
	at gnu.trove.impl.hash.THashPrimitiveIterator.hasNext(THashPrimitiveIterator.java:102)
	at com.rwtema.extrautils2.power.PowerManager.tick(PowerManager.java:419)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_485_PowerManager_tick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by brisingraerowing** [comment]
I got this as well after putting some speed upgrades into a mechanical user.
