### ISSUE TITLE
[1.12.1 1.6.1] Quantum quarries are unstable with non-overworld biomes.

### ISSUE THREAD

**Issue by Vectrobe** [rwtema/extrautilities_old_issues#1683]
Despite there now being a method to prevent server crashes, the quarry will still in fact crash the server when trying to mine End and Hell biomes, or at least End ones. If the server so happens to not crash, other biomes will be mined instead.

**Comment by Vectrobe** [comment]
#1613 #1614 #1679

**Comment by Vectrobe** [comment]
[crash-2017-09-06_12.27.11-server.txt](https://github.com/rwtema/extrautilities/files/1279566/crash-2017-09-06_12.27.11-server.txt)

**Comment by Vectrobe** [comment]
#1453

**Comment by Vectrobe** [comment]
You'll also see this when swapping out markers;
[12:37:22] [Server thread/ERROR]: Failed to save chunk
java.lang.NullPointerException: null
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:347) ~[aye.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:184) [aye.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:270) [on.class:?]
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:206) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:754) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
