### ISSUE TITLE
fatal crash of game when inserting mining upgrade into transfer node

### ISSUE THREAD

**Issue by guserav** [rwtema/extrautilities_old_issues#1717]
This Exception gets thrown when I insert a mining upgrade into a transfer node. The bug has appered in multiplayer in the ftb beyond pack version 1.11.0 . I didn't test it in any other setups.

```
Reported exception thrown!
net.minecraft.util.ReportedException: Updating screen events
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1713)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase$1.getStackLimit(TransferNodeBase.java:59)
	at net.minecraftforge.items.ItemStackHandler.insertItem(ItemStackHandler.java:85)
	at net.minecraftforge.items.SlotItemHandler.func_75214_a(SlotItemHandler.java:56)
	at com.rwtema.extrautils2.gui.backend.DynamicContainer.func_75135_a(DynamicContainer.java:426)
	at com.rwtema.extrautils2.gui.backend.DynamicContainer.func_82846_b(DynamicContainer.java:357)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:258)
	at com.rwtema.extrautils2.gui.backend.DynamicContainer.func_184996_a(DynamicContainer.java:492)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:550)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:557)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:627)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_184098_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:15)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:522)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:389)
	at com.rwtema.extrautils2.gui.backend.DynamicGui.func_73864_a(DynamicGui.java:321)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548)
	at com.rwtema.extrautils2.gui.backend.DynamicGui.func_146274_d(DynamicGui.java:294)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700)
	... 9 more
```

**Comment by AstralJaeger** [comment]
I can confirm this, for the Speed Upgrade in the Item transfer node and the Mining Upgrade in the Liquid Transfer Node.
In the most recent version of FTB Beyond.

**Comment by NiklasPor** [comment]
Also happening in multiplayer. Only crashes clientside tho.

**Comment by djlazz3** [comment]
I was experiencing this issue as well, on SkyFactory 3, and after a bit of testing, I learned that this bug is fixed in version 1.6.4 of extra-utils2
