### ISSUE TITLE
Search for items no longer working

### ISSUE THREAD

**Issue by ghost** [rwtema/extrautilities_old_issues#1770]
For some reason, the “search for items” feature stopped working.

Also, it lacks localization.

**Minecraft version**: 1.12.2
**EU2 version**: 1.6.5

**Comment by Tahakk** [comment]
For stopped working makes sure you have no conflict keys and as for localization, I wanted to say if you want it, make it. Than I remembered this is not open source project :( 
oh well

**Comment by ghost** [comment]
@Tahakk It doesn’t conflict with any other keys. It just stopped working, for some reason.

**Comment by StarkRG** [comment]
It's only working occasionally for me, however, it does have a strange side effect of deleting NBT data one key at a time. And, yes, I'm sure it's XU2 as I changed the key to something else and that effect moved to the new key. Usually, the NBT data isn't actually removed (ie, it's only client-side), but in at least one case it did seem to stick.

**Comment by ghost** [comment]
@StarkRG I have the same NBT-related issue. It spooked the fuck out of me the first time this happened to my backpack and Tinkers’ Construct lumberaxe.

**Comment by Jkosio23** [comment]
this is still an issue for me, it was working for a few days with the project ozone lite pack, and then one day it stopped actually searching other inventories for the items

**Comment by Jkosio23** [comment]
@rwtema

**Comment by DJ411** [comment]
Having this issue with FTB Revelations. Playing on a server and i know the feature worked when i started on the pack. Also it works in SP when i log off a server to make sure it worked. So its only Server issue atm.

This error also pops up when i press the key.

> [19:47:22] [Server thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.AbstractMethodError
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
> 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
> 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
> Caused by: java.lang.AbstractMethodError
> 	at com.rwtema.extrautils2.crafting.Radar$PacketPing.lambda$doStuffServer$1(Radar.java:186) ~[Radar$PacketPing.class:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
> 	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
> 	... 5 more
