### ISSUE TITLE
Crash on opening ExtraUtils Manual item

### ISSUE THREAD

**Issue by GiovanH** [rwtema/extrautilities_old_issues#1786]
Seen in Minecraft 1.10.2, ExtraUtils version 1.6.7

```
[15:45:31] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at com.rwtema.extrautils2.backend.entries.VillagerEntry.getDisplayName(VillagerEntry.java:18) ~[VillagerEntry.class:?]
	at com.rwtema.extrautils2.book.BookHandler.newStack(BookHandler.java:82) ~[BookHandler.class:?]
	at com.rwtema.extrautils2.items.ItemBook$1.run(ItemBook.java:35) ~[ItemBook$1.class:?]
	at com.rwtema.extrautils2.XUProxyClient.run(XUProxyClient.java:54) ~[XUProxyClient.class:?]
	at com.rwtema.extrautils2.items.ItemBook.onItemRightClickBase(ItemBook.java:31) ~[ItemBook.class:?]
	at com.rwtema.extrautils2.compatibility.ItemCompat.func_77659_a(ItemCompat.java:64) ~[ItemCompat.class:?]
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:163) ~[adz.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:495) ~[blm.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1544) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[15:45:31] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:560]: ---- Minecraft Crash Report ----
```

On crafting the manual item and right clicking in-game

**Comment by NeonWizard** [comment]
Just had the same crash.
