### ISSUE TITLE
Ticking Player crash on latest update

### ISSUE THREAD

**Issue by NeedAUser** [rwtema/extrautilities_old_issues#1804]
java.lang.NullPointerException: Ticking player
	at com.rwtema.extrautils2.items.ItemUnstableIngots.checkForExplosion(ItemUnstableIngots.java:202)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_74_ItemUnstableIngots_checkForExplosion_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:360)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:189)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

**Comment by NeedAUser** [comment]
Disabling unstable ingots allowed successful world login.

**Comment by brisingraerowing** [comment]
I got this as well. It looks like Unstable Ingots are, well, unstable.
