### ISSUE TITLE
It seems like something wrong with 'Unstable Ingnot'

### ISSUE THREAD

**Issue by Tollainmear** [rwtema/extrautilities_old_issues#1808]
While I Create a new world(or just load a existing world) ,the game will crash with a NullPointerException ,here is the crash report.

[crash-2017-12-18_02.03.53-server.txt](https://github.com/rwtema/extrautilities/files/1565903/crash-2017-12-18_02.03.53-server.txt)

some information:
forge-version    :    1.10.2-forge1.10.2-12.18.3.2511
mod-version     :     extrautils2-1.10.2-1.7.1

An'I guess this paragraph was the key point:
```
Time: 17-12-18 上午2:03
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at com.rwtema.extrautils2.items.ItemUnstableIngots.checkForExplosion(ItemUnstableIngots.java:202)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_188_ItemUnstableIngots_checkForExplosion_PlayerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:360)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:189)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by eyeonus** [comment]
I'm getting the same crash, same eu2 and forge versions as OP.

In singleplayer, crash happens at world loading, in multiplayer, client crash happens at player connection.

Here's the full crash log:
https://pastebin.com/5XQMksA4

Here's the server log in multiplayer:
https://pastebin.com/fJpbgkRQ

The same crash is also happening with 1.7.0

Latest version that doesn't crash is 1.6.8, which doesn't have the unstable ingots.

**Comment by Tollainmear** [comment]
yeap I have to roll back the version to 1.6.8

**Comment by NeedAUser** [comment]
I had this too, My guess is when a player tries to spawn in, the timer for when unstable ingots explode tries to kick in, but since the player doesnt have any on them, the game freaks out and crashes. Disabling unstable ingots in the configs worked for me.
