### ISSUE TITLE
[1.12.2] Ticking Block Entity

### ISSUE THREAD

**Issue by Rumpelstiltskinny** [rwtema/extrautilities_old_issues#1810]
I don't understand how this silverfish function relates to the quarry. Why is this happening and how do I fix it?

```---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  Better mobGriefing GameRule Core (bettermobgriefinggamerule-1.12.2-6.0.0.jar)
  LoadingPlugin (Quark-r1.4-120.jar)
  CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/17/17 1:56 PM
Description: Ticking block entity

java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    net/minecraft/entity/monster/EntitySilverfish$AISummonSilverfish.func_75246_d()V @128: aload_0
  Reason:
    Type top (current frame, locals[0]) is not assignable to reference type
  Current Frame:
    bci: @128
    flags: { }
    locals: { top, 'net/minecraft/world/World', 'java/util/Random', 'net/minecraft/util/math/BlockPos', integer, integer, integer, 'net/minecraft/util/math/BlockPos', 'net/minecraft/block/state/IBlockState' }
    stack: { }
  Bytecode:
    0x0000000: 2a59 b400 1e04 64b5 001e 2ab4 001e 9d00
    0x0000010: df2a b400 18b4 0025 4c2a b400 18b6 0029
    0x0000020: 4dbb 002b 592a b400 18b7 002e 4e03 3604
    0x0000030: 1504 08a3 00ba 1504 10fb a100 b303 3605
    0x0000040: 1505 100a a300 9715 0510 f6a1 0090 0336
    0x0000050: 0615 0610 0aa3 0074 1506 10f6 a100 6d2d
    0x0000060: 1505 1504 1506 b600 363a 072b 1907 b600
    0x0000070: 3a3a 0819 08b9 0040 0100 b200 46a6 003a
    0x0000080: 2ab4 0018 b800 4c99 000e 2b19 0704 b600
    0x0000090: 5057 a700 1b2b 1907 1908 b200 54b9 0058
    0x00000a0: 0200 c000 0ab6 005c 06b6 0060 572c b600
    0x00000b0: 6399 0006 a700 3915 069d 0007 04a7 0004
    0x00000c0: 0315 0664 3606 a7ff 8b15 059d 0007 04a7
    0x00000d0: 0004 0315 0564 3605 a7ff 6815 049d 0007
    0x00000e0: 04a7 0004 0315 0464 3604 a7ff 46b1     
  Stackmap Table:
    full_frame(@48,{Top,Object[#48],Object[#50],Object[#43],Integer},{})
    append_frame(@64,Integer)
    append_frame(@81,Integer)
    append_frame(@149,Object[#43],Object[#60])
    chop_frame(@173,2)
    same_frame(@183)
    same_frame(@192)
    same_locals_1_stack_item_frame(@193,Integer)
    chop_frame(@201,1)
    same_frame(@210)
    same_locals_1_stack_item_frame(@211,Integer)
    chop_frame(@219,1)
    same_frame(@228)
    same_locals_1_stack_item_frame(@229,Integer)
    full_frame(@237,{},{})

	at net.minecraft.entity.monster.EntitySilverfish.func_184651_r(SourceFile:47)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:104)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:21)
	at net.minecraft.entity.monster.EntityMob.<init>(EntityMob.java:26)
	at net.minecraft.entity.monster.EntitySilverfish.<init>(SourceFile:37)
	at net.minecraft.block.BlockSilverfish.func_180653_a(SourceFile:60)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.block.Block.func_180657_a(Block.java:735)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:327)
	at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:321)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.monster.EntitySilverfish.func_184651_r(SourceFile:47)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:104)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:21)
	at net.minecraft.entity.monster.EntityMob.<init>(EntityMob.java:26)
	at net.minecraft.entity.monster.EntitySilverfish.<init>(SourceFile:37)
	at net.minecraft.block.BlockSilverfish.func_180653_a(SourceFile:60)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.block.Block.func_180657_a(Block.java:735)
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:327)
	at com.rwtema.extrautils2.quarry.TileQuarry.func_73660_a(TileQuarry.java:321)

-- Block entity being ticked --
Details:
	Name: xu2:tilequarry // com.rwtema.extrautils2.quarry.TileQuarry
	Block type: ID #1010 (tile.extrautils2:quarry // com.rwtema.extrautils2.quarry.BlockQuarry)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-76,61,141), Chunk: (at 4,3,13 in -5,8; contains blocks -80,0,128 to -65,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #1010 (tile.extrautils2:quarry // com.rwtema.extrautils2.quarry.BlockQuarry)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: New World 12-12-17
	All players: 1 total; [EntityPlayerMP['tony'/4447, l='New World 12-12-17', x=-74.71, y=65.00, z=134.48]]
	Chunk stats: ServerChunkCache: 618 Drop: 0
	Level seed: -7956490117690895247
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-44,64,232), Chunk: (at 4,4,8 in -3,14; contains blocks -48,0,224 to -33,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 7585790 game time, 5498294 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 42456 (now: false), thunder time: 4727 (now: true)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 259002360 bytes (247 MB) / 1250275328 bytes (1192 MB) up to 6372720640 bytes (6077 MB)
	JVM Flags: 6 total; -Xmx6G -XX:-UseVMInterruptibleIO -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=8 -XX:+AggressiveOpts
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2554 107 mods loaded, 107 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                        | Version                  | Source                                        | Signature                                |
	|:--------- |:------------------------- |:------------------------ |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                 | 1.12.2                   | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | mcp                       | 9.42                     | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | FML                       | 8.0.99.99                | forge-1.12.2-14.23.1.2554-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                     | 14.23.1.2554             | forge-1.12.2-14.23.1.2554-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ivtoolkit                 | 1.3.3-1.12               | minecraft.jar                                 | None                                     |
	| UCHIJAAAA | bowinfinityfix            | rv5                      | minecraft.jar                                 | e250ba31147feb059b86cfd74ee61a8aeb88fb9b |
	| UCHIJAAAA | actuallyadditions         | 1.12.2-r125              | ActuallyAdditions-1.12.2-r125.jar             | None                                     |
	| UCHIJAAAA | baubles                   | 1.5.1                    | Baubles-1.12-1.5.1.jar                        | None                                     |
	| UCHIJAAAA | actuallybaubles           | 1.1                      | ActuallyBaubles-1.12-1.1.jar                  | None                                     |
	| UCHIJAAAA | applecore                 | 3.1.0                    | AppleCore-mc1.12.2-3.1.0.jar                  | None                                     |
	| UCHIJAAAA | jei                       | 4.8.5.136                | jei_1.12.2-4.8.5.136.jar                      | None                                     |
	| UCHIJAAAA | appleskin                 | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                    | None                                     |
	| UCHIJAAAA | aroma1997core             | 1.3.0.2                  | Aroma1997Core-1.12.2-1.3.0.2.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aromabackup               | 2.1.1.3                  | AromaBackup-1.12.2-2.1.1.3.jar                | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJAAAA | aromabackuprecovery       | 2.1.1.3                  | AromaBackup-1.12.2-2.1.1.3.jar                | None                                     |
	| UCHIJAAAA | quark                     | r1.4-120                 | Quark-r1.4-120.jar                            | None                                     |
	| UCHIJAAAA | autoreglib                | 1.3-15                   | AutoRegLib-1.3-15.jar                         | None                                     |
	| UCHIJAAAA | bdlib                     | 1.14.3.10                | bdlib-1.14.3.10-mc1.12.2.jar                  | None                                     |
	| UCHIJAAAA | bettermobgriefinggamerule | 1.12.2-6.0.0             | bettermobgriefinggamerule-1.12.2-6.0.0.jar    | None                                     |
	| UCHIJAAAA | mantle                    | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCHIJAAAA | natura                    | 1.12-4.3.0.23            | natura-1.12-4.3.0.23.jar                      | None                                     |
	| UCHIJAAAA | forestry                  | 5.7.0.212                | forestry_1.12.2-5.7.0.212.jar                 | None                                     |
	| UCHIJAAAA | binniecore                | unspecified              | binnie-mods-1.12.2-2.5.0.97.jar               | None                                     |
	| UCHIJAAAA | binniedesign              | 1.0                      | binnie-mods-1.12.2-2.5.0.97.jar               | None                                     |
	| UCHIJAAAA | genetics                  | 2.5.0.97                 | binnie-mods-1.12.2-2.5.0.97.jar               | None                                     |
	| UCHIJAAAA | botany                    | 2.5.0.97                 | binnie-mods-1.12.2-2.5.0.97.jar               | None                                     |
	| UCHIJAAAA | extrabees                 | 2.5.0.97                 | binnie-mods-1.12.2-2.5.0.97.jar               | None                                     |
	| UCHIJAAAA | extratrees                | 2.5.0.97                 | binnie-mods-1.12.2-2.5.0.97.jar               | None                                     |
	| UCHIJAAAA | biomesoplenty             | 7.0.1.2309               | BiomesOPlenty-1.12.2-7.0.1.2309-universal.jar | None                                     |
	| UCHIJAAAA | tconstruct                | 1.12-2.8.0.45            | TConstruct-1.12-2.8.0.45.jar                  | None                                     |
	| UCHIJAAAA | ceramics                  | 1.12-1.3.3b              | Ceramics-1.12-1.3.3b.jar                      | None                                     |
	| UCHIJAAAA | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UCHIJAAAA | chesttransporter          | 2.8.7                    | ChestTransporter-1.12-2.8.7.jar               | None                                     |
	| UCHIJAAAA | codechickenlib            | 3.1.5.331                | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | chickenchunks             | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux              | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCHIJAAAA | cofhcore                  | 4.3.6                    | CoFHCore-1.12-4.3.6.14-universal.jar          | None                                     |
	| UCHIJAAAA | cofhworld                 | 1.0.1                    | CoFHWorld-1.12-1.0.1.8-universal.jar          | None                                     |
	| UCHIJAAAA | cxlibrary                 | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                    | None                                     |
	| UCHIJAAAA | densemetals               | 1.0.2                    | densemetals-1.12.2-1.0.2.jar                  | None                                     |
	| UCHIJAAAA | disenchanter              | 1.5                      | disenchanter-[1.12]1.5.jar                    | None                                     |
	| UCHIJAAAA | eleccore                  | 1.8.433                  | ElecCore-1.12.2-1.8.433.jar                   | None                                     |
	| UCHIJAAAA | elevatorid                | 1.3.5                    | ElevatorMod-1.12.2-1.3.5.jar                  | None                                     |
	| UCHIJAAAA | csb_ench_table            | 1.1.2                    | EnchantingTable-1.12-1.1.2.jar                | None                                     |
	| UCHIJAAAA | enderstorage              | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | enderzoo                  | 1.12.1-1.4.0.49          | EnderZoo-1.12.1-1.4.0.49.jar                  | None                                     |
	| UCHIJAAAA | extrautils2               | 1.0                      | extrautils2-1.12-1.7.1.jar                    | None                                     |
	| UCHIJAAAA | exu2cer                   | 1.0                      | exu2cer-1.12-1.0.jar                          | None                                     |
	| UCHIJAAAA | fastleafdecay             | v14                      | FastLeafDecay-v14.jar                         | None                                     |
	| UCHIJAAAA | tesla                     | 1.0.63                   | Tesla-1.12.2-1.0.63.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | gendustry                 | 1.6.5.6                  | gendustry-1.6.5.6-mc1.12.2.jar                | None                                     |
	| UCHIJAAAA | thermalfoundation         | 2.3.6                    | ThermalFoundation-1.12-2.3.6.16-universal.jar | None                                     |
	| UCHIJAAAA | advgenerators             | 0.9.20.10                | generators-0.9.20.10-mc1.12.2.jar             | None                                     |
	| UCHIJAAAA | harvestables              | 1.2                      | harvestables-1.2.1.jar                        | None                                     |
	| UCHIJAAAA | helpfixer                 | 1.12.1-1.5.18            | HelpFixer-1.12.1-1.5.18.jar                   | None                                     |
	| UCHIJAAAA | improvedbackpacks         | 1.12-1.1.2.0             | ImprovedBackpacks-1.12-1.1.2.0.jar            | None                                     |
	| UCHIJAAAA | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                      | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironbackpacks             | 1.12.2-3.0.1-2           | IronBackpacks-1.12.2-3.0.1-2.jar              | None                                     |
	| UCHIJAAAA | ironchest                 | 1.12.2-7.0.34.820        | ironchest-1.12.2-7.0.34.820.jar               | None                                     |
	| UCHIJAAAA | jehc                      | 1.3.1                    | jehc-1.12-1.3.1.jar                           | None                                     |
	| UCHIJAAAA | journeymap                | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJAAAA | justenoughbuttons         | 1.12-1.2                 | justenoughbuttons-1.12.2-1.2.2-5.jar          | None                                     |
	| UCHIJAAAA | malisiscore               | 1.12.2-6.3.0             | malisiscore-1.12.2-6.3.0.jar                  | None                                     |
	| UCHIJAAAA | malisisdoors              | 1.12.2-7.2.2             | malisisdoors-1.12.2-7.2.2.jar                 | None                                     |
	| UCHIJAAAA | mcmultipart               | 2.4.0                    | MCMultiPart-2.4.0.jar                         | None                                     |
	| UCHIJAAAA | mercurius_updater         | 1.0                      | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | metamorph                 | 1.1.4                    | metamorph-1.1.4-1.12.1.jar                    | None                                     |
	| UCHIJAAAA | minecolonies              | 1.12.2-0.8.5989          | minecolonies-universal-1.12.2-0.8.5989.jar    | None                                     |
	| UCHIJAAAA | naturescompass            | 1.5.0                    | NaturesCompass-1.12.2-1.5.0.jar               | None                                     |
	| UCHIJAAAA | nex                       | 2.1.12.13                | NetherEx-1.12-2.1.12.13.jar                   | None                                     |
	| UCHIJAAAA | netherportalfix           | 5.3.13                   | NetherPortalFix_1.12.1-5.3.13.jar             | None                                     |
	| UCHIJAAAA | nofov                     | 1.0.1                    | NoFov-MC1.12-1.0.1.jar                        | None                                     |
	| UCHIJAAAA | recipehandler             | 0.9                      | NoMoreRecipeConflict-0.9(1.12).jar            | None                                     |
	| UCHIJAAAA | neid                      | 1.5.4.2                  | NotEnoughIDs-1.5.4.2.jar                      | None                                     |
	| UCHIJAAAA | notenoughwands            | 1.5.9                    | notenoughwands-1.12-1.5.9.jar                 | None                                     |
	| UCHIJAAAA | overpoweredarmorbar       | 0.1.0                    | overpoweredarmorbar-1.12.2-0.1.0.jar          | None                                     |
	| UCHIJAAAA | getalltheseeds            | 1.12a                    | Pam's Get all the Seeds! 1.12a.jar            | None                                     |
	| UCHIJAAAA | harvestcraft              | 1.12.2a                  | Pam's HarvestCraft 1.12.2a.jar                | None                                     |
	| UCHIJAAAA | twilightforest            | 3.4.239                  | twilightforest-1.12.2-3.4.239-universal.jar   | None                                     |
	| UCHIJAAAA | plants2                   | 2.2.0                    | Plants-2.2.0.jar                              | None                                     |
	| UCHIJAAAA | projecte                  | 1.12-PE1.1.0             | ProjectE-1.12-PE1.1.0.jar                     | None                                     |
	| UCHIJAAAA | plustic                   | 6.3.2.1                  | plustic-6.3.2.1.jar                           | None                                     |
	| UCHIJAAAA | storagedrawers            | 1.12-5.2.5               | StorageDrawers-1.12.1-5.3.3.jar               | None                                     |
	| UCHIJAAAA | refinedstorage            | 1.5.28                   | refinedstorage-1.5.28.jar                     | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| UCHIJAAAA | refinedstorageaddons      | 0.2                      | refinedstorageaddons-0.2.jar                  | None                                     |
	| UCHIJAAAA | rftools                   | 7.15                     | rftools-1.12-7.15.jar                         | None                                     |
	| UCHIJAAAA | rftoolscontrol            | 1.6.9                    | rftoolsctrl-1.12-1.6.9.jar                    | None                                     |
	| UCHIJAAAA | rftoolsdim                | 5.05                     | rftoolsdim-1.12-5.05.jar                      | None                                     |
	| UCHIJAAAA | roguelike                 | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| UCHIJAAAA | ruins                     | 16.9                     | Ruins-1.12.jar                                | None                                     |
	| UCHIJAAAA | snad                      | 1.12.1-1.7.09.16a        | Snad-1.12.1-1.7.09.16a.jar                    | None                                     |
	| UCHIJAAAA | solcarrot                 | 1.2.0                    | solcarrot-1.12.1-1.2.0.jar                    | None                                     |
	| UCHIJAAAA | stg                       | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                          | None                                     |
	| UCHIJAAAA | storagedrawersextra       | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar           | None                                     |
	| UCHIJAAAA | theoneprobe               | 1.4.19                   | theoneprobe-1.12-1.4.19.jar                   | None                                     |
	| UCHIJAAAA | thermalcultivation        | 0.1.1                    | ThermalCultivation-1.12-0.1.1.6-universal.jar | None                                     |
	| UCHIJAAAA | thermaldynamics           | 2.3.6                    | ThermalDynamics-1.12-2.3.6.13-universal.jar   | None                                     |
	| UCHIJAAAA | thermalexpansion          | 5.3.6                    | ThermalExpansion-1.12-5.3.6.20-universal.jar  | None                                     |
	| UCHIJAAAA | tinkertoolleveling        | 1.12-1.0.3.DEV.56fac4f   | TinkerToolLeveling-1.12-1.0.3.jar             | None                                     |
	| UCHIJAAAA | veinminer                 | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar         | None                                     |
	| UCHIJAAAA | veinminermodsupport       | 0.38.1                   | VeinMiner-1.12-0.38.1.639+134fb1e.jar         | None                                     |
	| UCHIJAAAA | wanionlib                 | 1.12.2-1.3               | WanionLib-1.12.2-1.3.jar                      | None                                     |
	| UCHIJAAAA | wirelesscharger           | 1.12.2-1.0.4             | WirelessCharger-1.12.2-1.0.4.jar              | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | witherskelefix            | 2.2.3                    | Wither Skeleton Tweaks-1.12-2.2.3.jar         | None                                     |
	| UCHIJAAAA | xnet                      | 1.5.0                    | xnet-1.12-1.5.0.jar                           | None                                     |
	| UCHIJAAAA | zerocore                  | 1.12-0.1.1.0             | zerocore-1.12-0.1.1.0.jar                     | None                                     |
	| UCHIJAAAA | unidict                   | 1.12.2-1.8               | UniDict-1.12.2-1.8.jar                        | None                                     |

	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
Better mobGriefing GameRule Core (bettermobgriefinggamerule-1.12.2-6.0.0.jar)
  com.judge40.minecraft.bettermobgriefinggamerule.asm.ClassTransformer
LoadingPlugin (Quark-r1.4-120.jar)
  vazkii.quark.base.asm.ClassTransformer
CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
  cubex2.cxlibrary.CoreModTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Plugin (NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  
BIFLoader (BowInfinityFix-1.11.x-1.12.x-rv5.jar)
  com.github.parker8283.bif.Transformer
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- theoneprobeIntegration (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12.2-r125.jar
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.0.jar
		* AromaBackupAPI (1.0) from AromaBackup-1.12.2-2.1.1.3.jar
		* Baubles|API (1.4.0.2) from Baubles-1.12-1.5.1.jar
		* BetterWithModsAPI (Beta 0.6) from AppleSkin-mc1.12-1.0.9.jar
		* chesttransporter|api (2) from ChestTransporter-1.12-2.8.7.jar
		* cofhapi (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|block (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|core (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|item (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|tileentity (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* cofhapi|util (2.0.0) from CoFHCore-1.12-4.3.6.14-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12-0.2.3.9.jar
		* ElecCoreAPI (1.0) from ElecCore-1.12.2-1.8.433.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.12.2-1.8.433.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|farming (2.2.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.7.0.212.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.7.0.212.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.6-mc1.12.2.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.8.5.136.jar
		* mcjtylib_ng (2.5.0) from mcjtylib-1.12-2.5.0.jar
		* MouseTweaks|API (1.0) from MouseTweaks-2.8-mc1.12.1.jar
		* projecteapi (1.11.2-1.0.0) from ProjectE-1.12-PE1.1.0.jar
		* QuarkAPI (1) from Quark-r1.4-120.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.1-5.3.3.jar
		* theoneprobe_api (1.4.4) from theoneprobe-1.12-1.4.19.jar
		* veinminerApi (0.3) from VeinMiner-1.12-0.38.1.639+134fb1e.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.1.0.jar
	Profiler Position: N/A (disabled)
	Player Count: 1 / 5; [EntityPlayerMP['tony'/4447, l='New World 12-12-17', x=-74.71, y=65.00, z=134.48]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)```

**Comment by CorneliusCornbread** [comment]
Happens on 1.10.2 as well, except I get a ticking player crash

https://pastebin.com/Mxkvu9Uh

**Comment by NeedAUser** [comment]
The ticking player is because unstable ingots is a tad unstable in the build. Disabling it in the configs will let you load the world fine.
