### ISSUE TITLE
Crash in Single Player with Fluid Transfer Node & Wireless RF Transmitter

### ISSUE THREAD

**Issue by WonderDog** [rwtema/extrautilities_old_issues#1852]
I placed a Fluid Transfer node in range of a Wireless RF Transmitter and crashed in DireWolf20 1v12 Modpack with EU2 version 1.7.3

Roll back to version 1.7.2 and was able to load and play world.

Crash Log [https://pastebin.com/embed/m640XhSp](url)

**Comment by choekstr** [comment]
Same exact issue.  I have flat fluid, flat item, regular fluid and regular item nodes and several machines in one area and when I place a wireless node and transmitter in the same area I get a crash.  The relevant part of my crash log (full crash log if needed): 

Time: 1/27/18 11:16 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.hasCapability(TileTransferHolder.java:231)
	at com.rwtema.extrautils2.utils.CapGetter$2.hasCapability(CapGetter.java:38)
	at com.rwtema.extrautils2.utils.CapGetter.hasInterface(CapGetter.java:95)
	at com.rwtema.extrautils2.power.energy.EnergyTransfer.isValidOutput(EnergyTransfer.java:149)
	at com.rwtema.extrautils2.power.energy.TilePowerTransmitter.refreshTiles(TilePowerTransmitter.java:132)
	at com.rwtema.extrautils2.power.energy.TilePowerTransmitter.getTargets(TilePowerTransmitter.java:41)
	at com.rwtema.extrautils2.power.energy.EnergyTransfer.onServerTick(EnergyTransfer.java:85)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1224_EnergyTransfer_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:277)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by impromptu1583** [comment]
Can confirm, same happening on dedicated server

**Comment by ghost** [comment]
Can confirm:
[Crash Log](https://pastebin.com/7cGN4dvX)
