### ISSUE TITLE
[1.12.2][1.7.3] Server crashing after update 1.7.2 > 1.7.3

### ISSUE THREAD

**Issue by access-ible** [rwtema/extrautilities_old_issues#1877]
Minecraft Version: 1.12.2
Forge Version: 1.12.2 - 14.23.2.2611
Extra Utilities Version: 1.12-1.7.3

Issue occured after updating from Extra Utilities version 1.7.2 to 1.7.3
Issue resolved by downgrading back to version 1.7.2 and no other changes made to server.

[Full Crashlog](https://pastebin.com/8nVhAdV0) 

Log Excerpt Below
--------------------
Description: Exception in server tick loop
 
java.lang.NullPointerException: Exception in server tick loop
    at com.rwtema.extrautils2.transfernodes.TileTransferHolder.hasCapability(TileTransferHolder.java:231)
    at com.rwtema.extrautils2.utils.CapGetter$2.hasCapability(CapGetter.java:38)
    at com.rwtema.extrautils2.utils.CapGetter.hasInterface(CapGetter.java:95)
    at com.rwtema.extrautils2.power.energy.EnergyTransfer.isValidOutput(EnergyTransfer.java:149)
    at com.rwtema.extrautils2.power.energy.TilePowerTransmitter.refreshTiles(TilePowerTransmitter.java:132)
    at com.rwtema.extrautils2.power.energy.TilePowerTransmitter.getTargets(TilePowerTransmitter.java:41)
    at com.rwtema.extrautils2.power.energy.EnergyTransfer.onServerTick(EnergyTransfer.java:85)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_456_EnergyTransfer_onServerTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Thread.java:748)

**Comment by MokahTGS** [comment]
I'm wondering if this is the same crash:  https://pastebin.com/d4RsD4Gb

This happened just flying down from a high point in a world.

**Comment by dancc7t** [comment]
This just happened to me aswell when placing a Transfer Node (Items) to a Chest
