### ISSUE TITLE
Crash when rightclicking energy transfer node

### ISSUE THREAD

**Issue by Cirrus0** [rwtema/extrautilities_old_issues#226]
The energy node is attached to the front of a thermal expansion resonant energy cell, that should be powering it.

When you rightclick on the energy node that happens:

java.lang.IndexOutOfBoundsException: Index: 42, Size: 42
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.func_75139_a(SourceFile:104)
    at net.minecraft.inventory.Container.func_75131_a(SourceFile:390)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147241_a(NetHandlerPlayClient.java:1056)
    at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:49)
    at net.minecraft.network.play.server.S30PacketWindowItems.func_148833_a(SourceFile:11)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by AlexandraIsabel** [comment]
Which version of MC and Extra Utilities are you using and @rwtema will need your FML log to figure out what exactly happened.

**Comment by Cirrus0** [comment]
I see, i forgot the versions. 
Minecraft 1.7.10 and Extra Utilities 1.1.0f.

The log won't be very helpful, but i will attach it anyway.
http://pastebin.com/kYspuLXh

**Comment by rwtema** [comment]
Looks like Railcraft's hidden blocks are causing issues again. It's a forge/RC issue. It might be solved in a newer version of forge but I don't know.
