### ISSUE TITLE
[1.1.0g] Mod sorting problem...again

### ISSUE THREAD

**Issue by wormzjl** [rwtema/extrautilities_old_issues#239]
Seems to be happening randomly, sometimes the game starts without problems, sometimes not
But removing EU fixes the problem

[17:09:55] [Client thread/ERROR] [FML/]: Visting node FMLMod:CoFHCore{1.7.10R3.0.0B3}
[17:09:55] [Client thread/ERROR] [FML/]: Current sorted list : [Dummy Container (BeforeAll) @1106162592, Wrapped{mcp}, Wrapped{FML}, Wrapped{Forge}, Wrapped{BetterFonts}, Wrapped{Dummy Container (null) @569757421}, Wrapped{CodeChickenCore}, Wrapped{<CoFH ASM>}, Wrapped{InputFix}, Wrapped{Micdoodlecore}, Wrapped{NotEnoughItems}, Wrapped{OpenEye}, Wrapped{Dummy Container (null) @283392774}, Wrapped{OpenModsCore}, Dummy Container (Before) @508751665, FMLMod:bspkrsCore{6.13}, FMLMod:ArmorStatusHUD{1.27}, FMLMod:StatusEffectHUD{1.26}, FMLMod:Treecapitator{1.7.2}, FMLMod:IC2{2.2.586-experimental}, FMLMod:ImmibisCore{59.0.1}, FMLMod:AdvancedMachines{59.0.0}, FMLMod:appliedenergistics2{rv1-alpha-49}, FMLMod:BambooMod{Minecraft1.7.10 var2.6.7}, FMLMod:bdlib{1.4.1.7}, FMLMod:BiblioCraft{1.7.5}]
[17:09:55] [Client thread/ERROR] [FML/]: Visited set for this node : [Wrapped{NotEnoughItems}, FMLMod:BiblioCraft{1.7.5}, FMLMod:AdvancedMachines{59.0.0}, FMLMod:ArmorStatusHUD{1.27}, FMLMod:bspkrsCore{6.13}, FMLMod:Treecapitator{1.7.2}, Dummy Container (Before) @508751665, Dummy Container (BeforeAll) @1106162592, FMLMod:appliedenergistics2{rv1-alpha-49}, FMLMod:ImmibisCore{59.0.1}, Wrapped{Dummy Container (null) @569757421}, Wrapped{CodeChickenCore}, Dummy Container (After) @1563911589, FMLMod:BambooMod{Minecraft1.7.10 var2.6.7}, APIContainer{CoFHAPI:1.0}, Wrapped{<CoFH ASM>}, FMLMod:IC2{2.2.586-experimental}, FMLMod:StatusEffectHUD{1.26}, FMLMod:CoFHCore{1.7.10R3.0.0B3}, Dummy Container (AfterAll) @1456834948, Wrapped{BetterFonts}, FMLMod:BigReactors{0.4.0X5}, Wrapped{Dummy Container (null) @283392774}, Wrapped{InputFix}, Wrapped{OpenModsCore}, Wrapped{Micdoodlecore}, Wrapped{OpenEye}, Wrapped{FML}, Wrapped{Forge}, Wrapped{mcp}, FMLMod:bdlib{1.4.1.7}]
[17:09:55] [Client thread/ERROR] [FML/]: Explored node set : [Wrapped{<CoFH ASM>}, Wrapped{NotEnoughItems}, FMLMod:IC2{2.2.586-experimental}, FMLMod:StatusEffectHUD{1.26}, FMLMod:BiblioCraft{1.7.5}, FMLMod:AdvancedMachines{59.0.0}, FMLMod:Treecapitator{1.7.2}, FMLMod:ArmorStatusHUD{1.27}, FMLMod:bspkrsCore{6.13}, Wrapped{BetterFonts}, Dummy Container (Before) @508751665, Dummy Container (BeforeAll) @1106162592, Wrapped{Dummy Container (null) @283392774}, FMLMod:appliedenergistics2{rv1-alpha-49}, FMLMod:ImmibisCore{59.0.1}, Wrapped{Dummy Container (null) @569757421}, Wrapped{CodeChickenCore}, FMLMod:BambooMod{Minecraft1.7.10 var2.6.7}, Wrapped{InputFix}, Wrapped{OpenModsCore}, Wrapped{Micdoodlecore}, Wrapped{OpenEye}, Wrapped{FML}, Wrapped{mcp}, Wrapped{Forge}, FMLMod:bdlib{1.4.1.7}]
[17:09:55] [Client thread/ERROR] [FML/]: Likely cycle is in : [Dummy Container (After) @1563911589, APIContainer{CoFHAPI:1.0}, FMLMod:CoFHCore{1.7.10R3.0.0B3}, Dummy Container (AfterAll) @1456834948, FMLMod:BigReactors{0.4.0X5}]
[17:09:55] [Client thread/ERROR] [FML/]: A dependency cycle was detected in the input mod set so an ordering cannot be determined
[17:09:55] [Client thread/ERROR] [FML/]: The first mod in the cycle is FMLMod:CoFHCore{1.7.10R3.0.0B3}
[17:09:55] [Client thread/ERROR] [FML/]: The mod cycle involves
[17:09:55] [Client thread/ERROR] [FML/]: Dummy Container (After) @1563911589 : before: [], after: []
[17:09:55] [Client thread/ERROR] [FML/]: APIContainer{CoFHAPI:1.0} : before: [Eln, CoFHCore, ExtraUtilities], after: [CoFHCore]
[17:09:55] [Client thread/ERROR] [FML/]: FMLMod:CoFHCore{1.7.10R3.0.0B3} : before: [], after: [FML@[7.10.0.1197,7.11), Forge@[10.13.0.1197,10.14)]
[17:09:55] [Client thread/ERROR] [FML/]: Dummy Container (AfterAll) @1456834948 : before: [], after: []
[17:09:55] [Client thread/ERROR] [FML/]: FMLMod:BigReactors{0.4.0X5} : before: [], after: [Forge@[10.13.0.1180,), CoFHAPI|energy, CoFHCore, ThermalExpansion]
[17:09:55] [Client thread/ERROR] [FML/]: The full error
cpw.mods.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:190) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:145) ~[TopologicalSort.class:?]
    at cpw.mods.fml.common.toposort.ModSorter.sort(ModSorter.java:133) ~[ModSorter.class:?]
    at cpw.mods.fml.common.Loader.sortModList(Loader.java:256) [Loader.class:?]
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:472) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:204) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_65]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_65]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]

**Comment by rwtema** [comment]
Unable to replicate. This is unlikely to be an XU issue.

**Comment by theredstone** [comment]
i have this problem too
log:http://pastebin.com/raw/iNn14kYQ
