### ISSUE TITLE
[Crash] - java.lang.IllegalArgumentException: value already present: com.rwtema.extrautils.sounds.XUSoundTileGenerators@4cd183b2

### ISSUE THREAD

**Issue by ShaneCluning** [rwtema/extrautilities_old_issues#248]
java.lang.IllegalArgumentException: value already present: com.rwtema.extrautils.sounds.XUSoundTileGenerators@4cd183b2
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:238)
    at com.google.common.collect.HashBiMap.put(HashBiMap.java:215)
    at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:368)
    at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154)
    at com.rwtema.extrautils.sounds.XUSoundTileGenerators.refresh(XUSoundTileGenerators.java:97)
    at com.rwtema.extrautils.sounds.SoundManager.refresh(SoundManager.java:22)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.onDataPacket(TileEntityGenerator.java:373)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1138)
    at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:55)
    at net.minecraft.network.play.server.S35PacketUpdateTileEntity.func_148833_a(SourceFile:10)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1591)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by rwtema** [comment]
This was fixed in a newer version.
