### ISSUE TITLE
ExU 1.1.0g

### ISSUE THREAD

**Issue by Lyl4c** [rwtema/extrautilities_old_issues#249]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 8/15/14 8:07 AM
Description: Exception in server tick loop

cpw.mods.fml.common.MissingModsException
    at cpw.mods.fml.common.Loader.sortModList(Loader.java:244)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:472)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:313)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_65, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1557968320 bytes (1485 MB) / 2058878976 bytes (1963 MB) up to 2058878976 bytes (1963 MB)
    JVM Flags: 2 total; -Xmx2048M -Xms2048M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.18.1180 Minecraft Forge 10.13.0.1180 26 mods loaded, 26 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded
    FML{7.10.18.1180} [Forge Mod Loader](forge.jar) Unloaded
    Forge{10.13.0.1180} [Minecraft Forge](forge.jar) Unloaded
    AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core](minecraft.jar) Unloaded
    CodeChickenCore{1.0.3.23} [CodeChicken Core](minecraft.jar) Unloaded
    NotEnoughItems{1.0.3.46} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.46-universal.jar) Unloaded
    appliedenergistics2{rv0-stable-10} [Applied Energistics 2](appliedenergistics2-rv0-stable-10.jar) Unloaded
    Backpack{2.0.0} [Backpack](backpack-2.0.0-1.7.x.jar) Unloaded
    Baubles{1.0.1.4} [Baubles](Baubles-1.7.10-1.0.1.4.jar) Unloaded
    AWWayofTime{v1.0.1g} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.1.0%281.7.10%29.jar) Unloaded
    Botania{r1.1-96} [Botania](Botania r1.1-96.jar) Unloaded
    BuildCraft|Builders{6.0.17} [BC Builders](buildcraft-6.0.17.jar) Unloaded
    BuildCraft|Core{6.0.17} [BuildCraft](buildcraft-6.0.17.jar) Unloaded
    BuildCraft|Energy{6.0.17} [BC Energy](buildcraft-6.0.17.jar) Unloaded
    BuildCraft|Factory{6.0.17} [BC Factory](buildcraft-6.0.17.jar) Unloaded
    BuildCraft|Silicon{6.0.17} [BC Silicon](buildcraft-6.0.17.jar) Unloaded
    BuildCraft|Transport{6.0.17} [BC Transport](buildcraft-6.0.17.jar) Unloaded
    CarpentersBlocks{3.2.5} [Carpenter's Blocks](Carpenter's Blocks v3.2.5 - MC 1.7.10.zip) Unloaded
    chisel{1.5.6} [Chisel](Chisel-1.7.10-1.5.6.jar) Unloaded
    CustomSpawner{3.2.0} [DrZhark's CustomSpawner](CustomMobSpawner 3.2.0.zip) Unloaded
    EnderStorage{1.4.5.17} [EnderStorage](EnderStorage-1.7.10-1.4.5.17-universal.jar) Unloaded
    EE3{0.2.295} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.2.295.jar) Unloaded
    ExtraUtilities{1.1.0g} [Extra Utilities](extrautilities-1.1.0g.jar) Unloaded
    MoarFood{V5.0.0} [MoarFood](MoarFood-5.0.0.jar) Unloaded
    cfm{3.3.2} [§6MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.3.2%281.7.2%29.jar) Unloaded
    TwilightForest{2.2.3} [The Twilight Forest](twilightforest-1.7.2-2.2.3.jar) Unloaded
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Lyl4c** [comment]
Closed, found similar problem: https://github.com/rwtema/extrautilities/issues/239
