### ISSUE TITLE
Infinite Recursion in conveyor belt.

### ISSUE THREAD

**Issue by tterrag1098** [rwtema/extrautilities_old_issues#297]
The log consists of:

```
Time: 9/7/14 1:37 AM
Description: Colliding entity with block

    java.lang.StackOverflowError: Colliding entity with block
at java.security.AccessController.doPrivileged(Native Method)
at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:501)
at net.minecraft.entity.Entity.func_70091_d(Entity.java:622)
at com.rwtema.extrautils.block.BlockConveyor.func_149670_a(BlockConveyor.java:201)
at net.minecraft.entity.Entity.func_145775_I(Entity.java:1061)
at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
at com.rwtema.extrautils.block.BlockConveyor.func_149670_a(BlockConveyor.java:201)
at net.minecraft.entity.Entity.func_145775_I(Entity.java:1061)
at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
at com.rwtema.extrautils.block.BlockConveyor.func_149670_a(BlockConveyor.java:201)
at net.minecraft.entity.Entity.func_145775_I(Entity.java:1061)
at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
at com.rwtema.extrautils.block.BlockConveyor.func_149670_a(BlockConveyor.java:201)
at net.minecraft.entity.Entity.func_145775_I(Entity.java:1061)
at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
at com.rwtema.extrautils.block.BlockConveyor.func_149670_a(BlockConveyor.java:201)
at net.minecraft.entity.Entity.func_145775_I(Entity.java:1061)
at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
at com.rwtema.extrautils.block.BlockConveyor.func_149670_a(BlockConveyor.java:201)
at net.minecraft.entity.Entity.func_145775_I(Entity.java:1061)
at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
at com.rwtema.extrautils.block.BlockConveyor.func_149670_a(BlockConveyor.java:201)
at net.minecraft.entity.Entity.func_145775_I(Entity.java:1061)
at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
at com.rwtema.extrautils.block.BlockConveyor.func_149670_a(BlockConveyor.java:201)
at net.minecraft.entity.Entity.func_145775_I(Entity.java:1061)
at net.minecraft.entity.Entity.func_70091_d(Entity.java:618)
```

Repeat ad infinitum. Seems that you are calling `moveEntity` inside `onEntityCollidedWithBlock` which then calls your method again. More details on the block/entity:

```
-- Block being collided with --
Details:
Block type: ID #705 (tile.extrautils:conveyor // com.rwtema.extrautils.block.BlockConveyor)
Block data value: 1 / 0x1 / 0b0001
Block location: World: (365,62,99), Chunk: (at 13,3,3 in 22,6; contains blocks 352,0,96 to 367,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)

-- Entity being checked for collision --
Details:
Entity Type: Item (net.minecraft.entity.item.EntityItem)
Entity ID: 1109
Entity Name: item.item.blazeRod
Entity's Exact location: 365.71, 63.06, 99.41
Entity's Block location: World: (365,63,99), Chunk: (at 13,3,3 in 22,6; contains blocks 352,0,96 to 367,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Entity's Momentum: 0.07, -0.04, -0.00
```

It occurred when placing a block, I believe the placing of the block pushed the EntityItem down inside the conveyor block.

**Comment by KaseiFR** [comment]
Hi,

I encountered the same problem. Here is the crash-log (cut to fit Pastebin limitations):
http://pastebin.com/9jcrGSUK

How did you restore your save?

**Comment by tterrag1098** [comment]
I used mcedit to remove the blocks causing the issue

**Comment by KaseiFR** [comment]
Thanks you, I manage to remove only the surrounding entities, and it stops the recursion.

**Comment by rwtema** [comment]
I've replaced the reference to moveEntity. It shouldn't recurse now.
