### ISSUE TITLE
Extra Utitlities Causing Crash When Used With Ex Astris

### ISSUE THREAD

**Issue by JordanPeace** [rwtema/extrautilities_old_issues#353]
...but, not causing crash?

Here's the crash report:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 10/9/14 1:35 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/rwtema/extrautils/item/ItemHeatingCoil
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/rwtema/extrautils/item/ItemHeatingCoil
    at com.rwtema.extrautils.ExtraUtilsMod.preInit(ExtraUtilsMod.java:35)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: com.rwtema.extrautils.item.ItemHeatingCoil
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 37 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/ItemEnergyContainer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 39 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.ItemEnergyContainer
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 43 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 123731640 bytes (117 MB) / 323858432 bytes (308 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.84.1217 Minecraft Forge 10.13.1.1217 31 mods loaded, 31 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.84.1217} [Forge Mod Loader](forge-1.7.10-10.13.1.1217.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.1.1217} [Minecraft Forge](forge-1.7.10-10.13.1.1217.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.2.647-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.647-experimental.jar) Unloaded->Constructed->Pre-initialized
    advancedgenetics{1.5.7} [Advanced Genetics](advancedgenetics-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.0.18} [BuildCraft](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.0.18} [BC Builders](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.0.18} [BC Energy](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.0.18} [BC Factory](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.0.18} [BC Transport](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.0.18} [BC Silicon](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    exnihilo{1.37} [Ex Nihilo](Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.7.0.build702} [Tinkers' Construct](TConstruct-1.7.10-1.7.0d3.1.jar) Unloaded->Constructed->Pre-initialized
    exastris{For 1.7.10} [Ex Astris](Ex-Astris-1.12.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Errored
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-224.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-434.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.

The reason I say it might not be causing the crash is because I removed Ex Astris from my mods folder and the game loaded completely fine. I might be wrong, but I think Ex Astris is trying to work alongside Extra Utitlities to make the item "Heating Coil", unless that's something that is actually in Extra Utilities that I don't know about.

**Comment by rwtema** [comment]
Guessing Ex Astris doesn't include the full RF API.
