### ISSUE TITLE
java.lang.StackOverflowError error with 1.2.0

### ISSUE THREAD

**Issue by jznomoney** [rwtema/extrautilities_old_issues#406]
I have a log here http://pastebin.com/E5qEAmw9 getting a crash updating from 1.1.0k.

**Comment by bochen415** [comment]
I had the exact same error yesterday on a fresh multiplayer setup with Forge 1236
I'm at work now so... no logs.

**Comment by frycjiri** [comment]
It´s even in 1.1.0k
http://s.jirifryc.cz/2014-11-18_16-11-34.txt

**Comment by marcin212** [comment]
http://pastebin.com/eHeMkepT

```
[17:39:26] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.RenderGameOverlayEvent$Post@7f434367:
java.lang.StackOverflowError
    at net.minecraft.block.Block.isAir(Block.java:1298) ~[aji.class:?]
    at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.getPipe(TNHelper.java:154) ~[TNHelper.class:?]
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canOutput(PipeCrossOver.java:63) ~[PipeCrossOver.class:?]
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canOutput(PipeCrossOver.java:72) ~[PipeCrossOver.class:?]
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canOutput(PipeCrossOver.java:72) ~[PipeCrossOver.class:?]
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canOutput(PipeCrossOver.java:72) ~[PipeCrossOver.class:?]
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canOutput(PipeCrossOver.java:72) ~[PipeCrossOver.class:?]

```

**Comment by tajudd** [comment]
A "me too" - have to revert back to what I've already downloaded.  1.1.0k is working, 1.2.0 is not.  Forge 1230.  Thanks for the mod.

**Comment by kiwep** [comment]
Same problem here, in my case it's with Rei's Minimap:

```
java.lang.StackOverflowError: Unexpected error
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.StdPipes.getPipeType(StdPipes.java:30)
    at com.rwtema.extrautils.tileentity.transfernodes.BlockTransferPipe.getPipe(BlockTransferPipe.java:340)
    at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.getPipe(TNHelper.java:160)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canOutput(PipeCrossOver.java:63)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canOutput(PipeCrossOver.java:72)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canOutput(PipeCrossOver.java:72)
```

**Comment by TherminatorX** [comment]
Always make sure to give steps to reproduce when you crash or something goes funky. These could be one problem or six unrelated problems.

**Comment by kiwep** [comment]
Environment: Minecraft 1.7.10, Forge 10.13.2.1230 with only two mods: Rei's Minimap 3.6 and Extra Utilities 1.2.0 (latest of both currently).

Start the game, create a new single player word (or try to connect to a multiplayer one, doesn't matter). After the world creation the game tries to load the map but it crashes: PipeCrossOver.canOutput() called recursively until the stack exhausts.

**Comment by bochen415** [comment]
I also have ReisMinimap 1.7.10 (the one Sedridor posted on MCF, now banned there). 
@jznomoney also has ReisMinimap in the crashlog, the exact same port.

Looks like I'll have to change my minimap....

Edit:
@marcin212 and @kwep also.

**Comment by bochen415** [comment]
I know that asking for support for an unofficial mod port is like waiting for Half Life 3 but here it goes:

Reproduction steps:
Download the unofficial ReisMinimap here http://goo.gl/aKmCbl
Drop in Extra Utilities 1.2.1 or 1.2.0. I tested this with Forge 1236
Start singleplayer game -> make a new survival world -> open it -> crash

Full FML log:
http://paste.ubuntu.com/9542775/

Exception caught during firing event net.minecraftforge.client.event.RenderGameOverlayEvent$Post@561dc11f:
java.lang.StackOverflowError

The other 100+ mods work with this unofficial port, so was ExU 1.1.0k
Disclaimer: link to the unofficial ReisMinimap mod was added only for development purposes.

**Comment by Frogdwarf** [comment]
Has this issue been fixed yet or not does anyone know? really want to use XU on my 1.7.10 world, as well as REI, but I'm having the above issues and on 1.7.10 there's no simple way to just downgrade XU

**Comment by bochen415** [comment]
@Frogdwarf nope. Not fixed.1.2.1 is still the current version. Get Journeymap and your problems will disappear.

**Comment by Frogdwarf** [comment]
@bochen415 oh I've been using JourneyMap, but it keeps glitching and rendering other world maps over the new :P that's why I wanted to use REI, but if I can't never mind I shall have to stick with what I've got

**Comment by bochen415** [comment]
@Frogdwarf you need to name every server/singleplayer world differently. When you make a new world or add a server to the list with the same name you already had before it will rewrite the map.

**Comment by Frogdwarf** [comment]
aaaaaaaaaaaaaaaaah :D yeh i feel stupid now XD tah

**Comment by kaisavi** [comment]
I found by reading the crash report that disabling transfer pipes will fix the crash, this is for those of you who don't want to get a new minimap mod.
