### ISSUE TITLE
World corruption when placing connected textures blocks at y=0

### ISSUE THREAD

**Issue by n-Holmes** [rwtema/extrautilities_old_issues#41]
Placed a gravel road block at y=0 and now the game crashes whenever the world is loaded.  Recreated the issue in a new map using border stone instead.  Here's the crashlog:

2014-04-30 09:03:42 [INFO] [STDOUT] -- Head -- 
2014-04-30 09:03:42 [INFO] [STDOUT] Stacktrace: 
2014-04-30 09:03:42 [INFO] [STDOUT] at net.minecraft.world.chunk.Chunk.func_76610_a(Chunk.java:640) 
2014-04-30 09:03:42 [INFO] [STDOUT] at net.minecraft.world.chunk.Chunk.func_76597_e(Chunk.java:981) 
2014-04-30 09:03:42 [INFO] [STDOUT] at net.minecraft.world.ChunkCache.func_72796_p(ChunkCache.java:115) 
2014-04-30 09:03:42 [INFO] [STDOUT] at extrautils.multipart.FakeRenderBlocksMultiPart.matchBlock(FakeRenderBlocksMultiPart.java:55) 
2014-04-30 09:03:42 [INFO] [STDOUT] at extrautils.block.FakeRenderBlocks.getType(FakeRenderBlocks.java:132) 
2014-04-30 09:03:42 [INFO] [STDOUT] at extrautils.block.FakeRenderBlocks.renderSide(FakeRenderBlocks.java:72) 
2014-04-30 09:03:42 [INFO] [STDOUT] at extrautils.block.FakeRenderBlocks.func_78611_c(FakeRenderBlocks.java:219) 
2014-04-30 09:03:42 [INFO] [STDOUT] at net.minecraft.client.renderer.RenderBlocks.func_78578_a(RenderBlocks.java:4597) 
2014-04-30 09:03:42 [INFO] [STDOUT] at net.minecraft.client.renderer.RenderBlocks.func_78570_q(RenderBlocks.java:4174) 
2014-04-30 09:03:42 [INFO] [STDOUT] at extrautils.block.RenderBlockConnectedTextures.renderWorldBlock(RenderBlockConnectedTextures.java:101) 
2014-04-30 09:03:42 [INFO] [STDOUT] at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:152) 
2014-04-30 09:03:42 [INFO] [STDOUT] at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:57) 
2014-04-30 09:03:42 [INFO] [STDOUT] at net.minecraft.client.renderer.RenderBlocks.func_78612_b(RenderBlocks.java:485) 
2014-04-30 09:03:42 [INFO] [STDOUT] at net.minecraft.client.renderer.WorldRenderer.func_78907_a(WorldRenderer.java:224) 
2014-04-30 09:03:42 [INFO] [STDOUT] at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1551) 
2014-04-30 09:03:42 [INFO] [STDOUT] at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1129)

**Comment by rwtema** [comment]
This is a 1.6 Issue. I am no longer developing for 1.6, if this issue is still present in 1.7, please post again.
