### ISSUE TITLE
Witchery 0.21.0 Cauldron crashes when filled by Transfer Node (Liquids)

### ISSUE THREAD

**Issue by Barhandar** [rwtema/extrautilities_old_issues#452]
```
java.lang.NullPointerException: Ticking block entity
    at com.emoniph.witchery.brewing.TileEntityCauldron.fill(TileEntityCauldron.java:494)
    at com.rwtema.extrautils.tileentity.transfernodes.nodebuffer.FluidBuffer.transfer(FluidBuffer.java:41)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeBase.transferItems(PipeBase.java:48)
    at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.transferItems(TileEntityTransferNode.java:591)
    at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.handleInventories(TileEntityTransferNode.java:431)
    at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNodeLiquid.processBuffer(TileEntityTransferNodeLiquid.java:48)
    at com.rwtema.extrautils.tileentity.transfernodes.TileEntityTransferNode.func_145845_h(TileEntityTransferNode.java:144)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Based on that Ender Fluid Conduit (EnderIO) doesn't cause a crash and fills it just fine, reported both in Witchery's thread and here.

**Comment by ghost** [comment]
Are you attaching a Transfer node directly to the cauldron, or just a transfer pipe? What side? And when does the crash happen... when you attach the pipe, try to fill the cauldron, or other?
