### ISSUE TITLE
Quarry Crash - Extra Utilities 1.2.1

### ISSUE THREAD

**Issue by Tergiver** [rwtema/extrautilities_old_issues#456]
Below is the crash dump if you want to skip the verbose report.

I am playing Material Energy^4 (v0.7.0). Note that it comes with Extra Utilities 1.2.0, but I tried swapping that out with 1.2.1 and it still crashes upon loading my world. I setup a quarry inside the spatial IO chamber.

I built a quarry with these connections: Silk upgrade, Hole upgrade, Speed 3 upgrade, Tesseract (#1) - receiving energy, sending items/fluids. Tesseract (#2) - sending energy, receiving items/fluids. Approximately 5 chucks apart. AE2 ME Interface next to Tesseract (#2), attached to ME drive with one 4k empty storage device, and power adapter thingy, plus 1 crafting terminal. 10k RF/t Big Reactor providing power to Tesseract & adapter thingy via single Ender IO 20k power cable. No other Tesseracts on that channel (2), but there are three other Tesseracts, all on channel (1) - different power supply (20 64x solar generators).

First I created a new world and used creative cheats to build the above quarry. It was identical in configuration. It worked without any problems.

Next I built the quarry into my 'real' world. Although the physical location is identical, the world below was different (A different spatial IO disk was loaded into the chamber--this time Miner's Delight). Everything was connected, tesseract #1 configured as above, etc. but it wasn't working. I had left out one thing: Configuring Tesseract #2 send/receive. It was set to send ALL, I quickly clicked it into receive (only) items and fluids (the correct configuration), and that was the moment it crashed.

It now crashes the moment I attempt load the world.

If you want the 30M zipped save game file, let me know.

```
---- Minecraft Crash Report ----
// You're mean.

Time: 12/28/14 3:06 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at com.rwtema.extrautils.tileentity.enderquarry.BlockBreakingRegistry.blackList(BlockBreakingRegistry.java:30)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.mineBlock(TileEntityEnderQuarry.java:495)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.func_145845_h(TileEntityEnderQuarry.java:378)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at com.rwtema.extrautils.tileentity.enderquarry.BlockBreakingRegistry.blackList(BlockBreakingRegistry.java:30)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.mineBlock(TileEntityEnderQuarry.java:495)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.func_145845_h(TileEntityEnderQuarry.java:378)

-- Block entity being ticked --
Details:
    Name: enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry
    Block type: ID #777 (tile.extrautils:enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.BlockEnderQuarry)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (1028,155,1029), Chunk: (at 4,9,5 in 64,64; contains blocks 1024,0,1024 to 1039,255,1039), Region: (2,2; contains chunks 64,64 to 95,95, blocks 1024,0,1024 to 1535,255,1535)
    Actual block type: ID #777 (tile.extrautils:enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.BlockEnderQuarry)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: First
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 2 Drop: 0
    Level seed: -4803990825008141971
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 271448576 bytes (258 MB) / 610795520 bytes (582 MB) up to 4116185088 bytes (3925 MB)
    JVM Flags: 6 total; -Xms256M -Xmx4096M -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xmn512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 57 mods loaded, 57 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2-core{rv1-beta-37} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.76} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.76-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SciMCLibCore{0.0.0.2} [SciMCLibCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    debug{1.0} [debug] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.14} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WorldStateCheckpoints{1.7.10.r02} [WorldStateCheckpoints] ([1.7.10]WorldStateCheckpoints-client-1.7.10.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dendrology{1.7.10-0.3.2} [Ancient Trees] (AncientTrees-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv1-beta-37} [Applied Energistics 2] (appliedenergistics2-rv1-beta-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.8.2} [BiblioCraft] (BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-41.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BigReactors{0.4.0A} [Big Reactors] (BigReactors-0.4.0A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{2.1.3} [Chisel] (Chisel 2-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactMachines{1.7.10-1.12} [Compact Machines] (compactmachines-1.7.10-1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderIO{1.7.10-2.2.4.0} [Ender IO] (EnderIO-1.7.10-2.2.6.0.buffertest.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderTech{1.7.10-0.3.0.348} [EnderTech] (EnderTech-1.7.10-0.3.0.348.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderZoo{1.7.10-1.0.5.14} [Ender Zoo] (EnderZoo-1.7.10-1.0.5.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.8.1.build815} [Tinkers' Construct] (TConstruct-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Metallurgy{4.0.5} [Metallurgy 4] (Metallurgy-1.7.10-4.0.5.75.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HoloInventory{1.8.3.86} [HoloInventory] (HoloInventory-1.7.10-1.8.3.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HardcoreQuesting{The Journey (4.2.1)} [Hardcore Questing Mode] (HQM-The Journey (4.2.1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    imc{1.6} [Improving Minecraft] (Improving Minecraft-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    journeymap{5.0.0RC6} [JourneyMap] (JourneyMap5.0.0RC6_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Lockdown{2.0.0} [Lockdown] (Lockdown-universal-1.7.2-2.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    minechem{5.0.5.344} [Minechem] (Minechem-1.7.10-5.0.5.344.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineTweaker3{3.0.9} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-225.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-436.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PerfectSpawn{1.1} [Perfect Spawn] (PerfectSpawn-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PoorOres{1.7.10-1.3.1} [PoorOres] (PoorOres-1.7.2-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Quadrum{1.2.0} [Quadrum] (Quadrum-1.7.10-1.2.0.B13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RandomThings{2.2.2} [Random Things] (RandomThings-2.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    santasdecor{0.5.3} [Santa's Decor] (Santa'sDecor-1.7.10-0.5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SciMCLib{SciMCLib} [SciMCLib] (SciMCLib-1.7.10-0.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TiCTooltips{1.1.11b} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Torcherino{1.7s} [Torcherino] (Torcherino-1.7.10-1.7s.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    wailafeatures{0.0.1} [WAILA Features] (WAILA-features-1.7.10-0.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    yampst{1.3.3} [YAMPST] (Yampst-Material Energy^4-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Ztones{1.7.10} [Ztones] (Ztones-1.7.10-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IguanaTweaksTConstruct{1.7.10-2.1.0.82} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AE2 Version: beta rv1-beta-37 for Forge 10.13.0.1187
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    SciMCLib Version: 0.0.0.2
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Tergiver** [comment]
Here is the ExtraUtilites.cfg file:

```
# Configuration file

blocks {
    B:AngelBlockEnabled=true
    B:BUDBlockEnabled=true
    B:BedrockiumBlockEnabled=true
    B:ChandelierEnabled=true
    B:CobblestoneComprEnabled=true
    B:ColorBlockDataEnabled=true
    B:ConveyorEnabled=true
    B:CursedEarthEnabled=true
    B:CurtainEnabled=true
    B:Decorative_1Enabled=true
    B:Decorative_2Enabled=true
    B:DrumEnabled=true
    B:EnderLilyEnabled=true
    B:EnderMarkerEnabled=true
    B:EnderQuarryEnabled=true
    B:EnderQuarryUpgradeEnabled=true
    B:EnderThermicPumpEnabled=true
    B:EtherealBlockEnabled=true
    B:FilingCabinetEnabled=true
    B:Generator64Enabled=true
    B:Generator8Enabled=true
    B:GeneratorEnabled=true
    B:GreenScreenEnabled=true
    B:MagnumTorchEnabled=true
    B:PeacefultableEnabled=true
    B:PortalEnabled=true
    B:PureLoveBlockEnabled=true
    B:QEDEnabled=true
    B:SoundMufflerEnabled=true
    B:SpikeDiamondEnabled=true
    B:SpikeEnabled=true
    B:SpikeGoldEnabled=true
    B:SpikeWoodEnabled=true
    B:TimerBlockEnabled=true
    B:TradingPostEnabled=true
    B:TransferNodeEnabled=true
    B:TransferNodeRemoteEnabled=true
    B:TransferPipeEnabled=true
    B:TrashCanEnabled=true
}


client_options {
    B:disablePortalAnimation=false
}


"ender quarry power" {
    I:baseDrain=1000
    I:hardnessDrain=150
}


items {
    B:AngelRingEnabled=true
    B:BedrockiumIngotEnabled=true
    B:BuildersWandEnabled=true
    B:CreativeBuildersWandEnabled=true
    B:DestructionPickaxeEnabled=true
    B:DivisionSigilEnabled=true
    B:ErosionShovelEnabled=true
    B:EthericSwordEnabled=true
    B:GoldenBagEnabled=true
    B:GoldenLassoEnabled=true
    B:HealingAxeEnabled=true
    B:HeatingCoilEnabled=true
    B:LawSwordEnabled=true
    B:PaintBrushEnabled=true
    B:PrecisionShearsIdEnabled=true
    B:ScannerEnabled=true
    B:SonarGogglesEnabled=true
    B:SoulEnabled=true
    B:TemporalHoeEnabled=true
    B:UnstableIngotEnabled=true
    B:UpgradeNodeEnabled=true
    B:WateringCanEnabled=true
}


options {
    I:EnderPumpDimensionExceptions <
     >
    I:deepDarkDimensionID=100
    B:disableEnderPumpInAllDimensions=false
    B:disableTransferNodeParticles=false
    B:disableWitherNoisesIfNotNearby=true
    B:soulDrainResetsOnDeath=false
    B:unstableIngotsExplode=true
}


qedcrafting {
    # ItemStack names to enforce crafting in the QED
    S:QEDItems <
        tile.extrautils:extractor_base_remote.0
        tile.extrautils:extractor_base_remote.6
        item.extrautils:nodeUpgrade.5
        item.extrautils:nodeUpgrade.6
        tile.extrautils:magnumTorch
        tile.extrautils:endMarker
        tile.extrautils:extractor_base.12
        tile.extrautils:enderQuarryUpgrade.0
        tile.extrautils:extractor_base.13
     >

    # Internal version number to add/remove items in future updates. Set to -1 to disable auto-updates.
    I:QEDVersion=3
}


recipes {
    B:disableAdvFilingCabinet=false
    B:disableAltChestRecipe=false
    B:disableBuildersWandRecipe=false
    B:disableChandelierRecipe=true
    B:disableColoredBlocksRecipes=false
    B:disableCompressedCobblestoneRecipe=false
    B:disableConveyorRecipe=false
    B:disableCurtainRecipe=false
    B:disableDestructionPickaxeRecipe=false
    B:disableDivisionSiginInChests=false
    B:disableDrumRecipe=false
    B:disableEnderLiliesInDungeons=false
    B:disableEnderQuarryUpgradesRecipes=false
    B:disableEnderThermicPumpRecipe=false
    B:disableEnergyExtractionPipeRecipe=false
    B:disableEnergyPipeRecipe=false
    B:disableErosionShovelRecipe=false
    B:disableEtherealGlassRecipe=false
    B:disableEthericSwordRecipe=false
    B:disableFilingCabinet=false
    B:disableFilterPipeRecipe=false
    B:disableFilterRecipe=false
    B:disableGeneratorRecipe=false
    B:disableGoldenBagRecipe=false
    B:disableGoldenLassoRecipe=false
    B:disableHealingAxeRecipe=false
    B:disableMagnumTorchRecipe=true
    B:disableModSortingPipeRecipe=false
    B:disableNodeUpgradeSpeedRecipe=false
    B:disablePaintbrushRecipe=false
    B:disablePeacefulTableRecipe=false
    B:disablePeacefulWitherRecipe=false
    B:disableQEDIngotSmeltRecipes=false
    B:disableRainMufflerRecipe=false
    B:disableRationingPipeRecipe=false
    B:disableRedstoneClockRecipe=false
    B:disableRetrievalNodeLiquidRecipe=false
    B:disableRetrievalNodeRecipe=false
    B:disableReversingHoeRecipe=false
    B:disableSonarGogglesRecipe=false
    B:disableSortingPipeRecipe=false
    B:disableSoundMufflerRecipe=false
    B:disableSpikeRecipe=false
    B:disableSuperWateringCanRecipe=false
    B:disableTradingPostRecipe=false
    B:disableTransferNodeEnergyRecipe=false
    B:disableTransferNodeLiquidRecipe=false
    B:disableTransferNodeRecipe=false
    B:disableTransferPipeRecipe=false
    B:disableTrashCanRecipe=false
    B:disableUnstableIngotRecipe=false
    B:disableWateringCanRecipe=false
}


worldgen {
    I:retrogen_enderlillies=1
}
```

**Comment by Neshram** [comment]
If it helps, I was able to narrow this down to an interaction with the PoorOres mod.

Took from the stack that it was trying to look up the block ID. PoorOres has the code up on their GitHub repo, and it looks like they are waiting until PostInit to register their blocks. (https://github.com/Xexanos/PoorOres)

I have the impression that's a bad thing, so it's probably more for them to fix. But it would probably also be good if the Quarry could fail in-game, or otherwise handle it cleanly, instead of getting the server trapped into a crash.

**Comment by Tergiver** [comment]
I confirmed that it is a PoorOre being mined that causes the crash and posted a report over there:
https://github.com/Xexanos/PoorOres/issues/3

**Comment by Xexanos** [comment]
I updated my mod, so this problem should no longer occur.

**Comment by hugeblank** [comment]
@Tergiver May want to close this...
