### ISSUE TITLE
Crash MC 1.7.10 vers. 1.2.1 with rei's minimap 1.7.10

### ISSUE THREAD

**Issue by keomate88** [rwtema/extrautilities_old_issues#457]
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 12/29/14 1:08 AM
Description: Unexpected error

java.lang.StackOverflowError: Unexpected error
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.StdPipes.getPipeType(StdPipes.java:30)
    at com.rwtema.extrautils.tileentity.transfernodes.BlockTransferPipe.getPipe(BlockTransferPipe.java:340)
    at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.getPipe(TNHelper.java:152)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:83)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)

......

**Comment by bochen415** [comment]
Duplicate of https://github.com/rwtema/extrautilities/issues/406
