### ISSUE TITLE
Odd traceback suddenly appearing in my logs

### ISSUE THREAD

**Issue by utoxin** [rwtema/extrautilities_old_issues#470]
I was working on updating the pack for my private server, and after the update (which didn't include any ExtraUtils updates), I started getting this traceback every few seconds in my logs, which appears to be triggered by ExtraUtils. If you need any additional information, just let me know what it is. I'm currently running Extra Utilities 1.2.1.

[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.Exception: Stack trace
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at java.lang.Thread.dumpStack(Unknown Source)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.chunk.Chunk.func_76612_a(Chunk.java:781)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:470)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:41)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.World.func_72964_e(World.java:419)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.World.func_147438_o(World.java:2535)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.detectInventories(TileEntityEnderQuarry.java:777)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.func_145845_h(TileEntityEnderQuarry.java:317)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.World.func_72939_s(World.java:1939)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[04:59:54] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by utoxin** [comment]
Figured it out. There was an notice I was discounting as related that turned out to be triggering this somehow. I fixed that (by killing the entities) and this went away.

For reference the arrow error was:

[06:22:19] [Server thread/WARN]: Wrong location! EntityArrow['arrow'/67397, l='world', x=7055.28, y=9776.80, z=9765.81](at 440, 610 instead of -8, 21)
