### ISSUE TITLE
1.7.10 World Crashing

### ISSUE THREAD

**Issue by Doonan10** [rwtema/extrautilities_old_issues#491]
This is what I have been getting while trying to generate a new world:

(FYI: It has this "at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)" almost a thousand times. Well enough so that half of it was more than the max. of characters allowed on this forum.)

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 1/24/15 7:28 PM
Description: Unexpected error

java.lang.StackOverflowError: Unexpected error
at com.rwtema.extrautils.tileentity.transfernodes.pipes.StdPipes.getPipeType(StdPipes.java:30)
at com.rwtema.extrautils.tileentity.transfernodes.BlockTransferPipe.getPipe(BlockTransferPipe.java:340)
at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.getPipe(TNHelper.java:152)
at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:83)
at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
at com.rwtema.extrautils.tileentity.transfernodes.pipes.StdPipes.getPipeType(StdPipes.java:30)
at com.rwtema.extrautils.tileentity.transfernodes.BlockTransferPipe.getPipe(BlockTransferPipe.java:340)
at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.getPipe(TNHelper.java:152)
at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:83)
at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
-- Affected level --
Details:
Level name: MpServer
All players: 1 total; [EntityClientPlayerMP['Doonan10'/322, l='MpServer', x=-260.50, y=68.62, z=265.50]]
Chunk stats: MultiplayerChunkCache: 185, 194
Level seed: 0
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: 
Level spawn location: World: (-256,64,266), Chunk: (at 0,4,10 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Level time: 333 game time, 333 day time
Level dimension: 0
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Forced entities: 81 total; [EntityCreeper['Creeper'/136, l='MpServer', x=-238.97, y=19.00, z=337.50], EntitySeagull['Seagull'/143, l='MpServer', x=-218.25, y=69.66, z=193.03], EntityCreeper['Creeper'/135, l='MpServer', x=-239.50, y=19.00, z=339.50], EntitySeagull['Seagull'/134, l='MpServer', x=-227.09, y=77.13, z=305.22], EntityCreeper['Creeper'/152, l='MpServer', x=-212.75, y=50.00, z=291.88], EntitySeagull['Seagull'/153, l='MpServer', x=-212.41, y=73.03, z=317.31], EntitySeagull['Seagull'/154, l='MpServer', x=-218.13, y=75.63, z=332.66], EntitySeagull['Seagull'/155, l='MpServer', x=-212.97, y=75.88, z=330.41], EntitySeagull['Seagull'/156, l='MpServer', x=-212.94, y=74.09, z=331.28], EntitySeagull['Seagull'/157, l='MpServer', x=-210.94, y=71.06, z=327.09], EntitySeagull['Seagull'/144, l='MpServer', x=-213.41, y=68.19, z=200.00], EntitySeagull['Seagull'/145, l='MpServer', x=-214.75, y=64.09, z=196.75], EntityZombie['Zombie'/146, l='MpServer', x=-212.16, y=38.00, z=223.50], EntitySkeleton['Skeleton'/147, l='MpServer', x=-214.50, y=40.00, z=223.31], EntitySkeleton['Skeleton'/148, l='MpServer', x=-214.50, y=35.00, z=228.50], EntityZombie['Zombie'/149, l='MpServer', x=-217.50, y=35.00, z=239.50], EntityZombie['Zombie'/150, l='MpServer', x=-212.03, y=37.00, z=224.44], EntityCreeper['Creeper'/151, l='MpServer', x=-211.25, y=50.00, z=294.38], EntitySeagull['Seagull'/169, l='MpServer', x=-207.72, y=63.16, z=200.00], EntityZombie['Zombie'/38, l='MpServer', x=-321.50, y=15.00, z=210.50], EntityZombie['Zombie'/39, l='MpServer', x=-322.13, y=12.00, z=217.72], EntitySkeleton['Skeleton'/36, l='MpServer', x=-321.50, y=18.00, z=199.50], EntityZombie['Zombie'/37, l='MpServer', x=-321.50, y=15.00, z=209.50], EntityBat['Bat'/42, l='MpServer', x=-327.25, y=23.00, z=226.75], EntitySkeleton['Skeleton'/40, l='MpServer', x=-332.50, y=22.00, z=212.50], EntitySkeleton['Skeleton'/41, l='MpServer', x=-333.50, y=22.00, z=212.50], EntityZombie['Zombie'/44, l='MpServer', x=-319.50, y=18.00, z=206.97], EntityZombie['Zombie'/45, l='MpServer', x=-308.94, y=33.00, z=197.75], EntityBat['Bat'/184, l='MpServer', x=-197.63, y=47.72, z=321.69], EntityEnderman['Enderman'/55, l='MpServer', x=-312.56, y=36.00, z=262.00], EntityZombie['Zombie'/54, l='MpServer', x=-312.47, y=14.00, z=242.53], EntitySkeleton['Skeleton'/53, l='MpServer', x=-309.59, y=18.00, z=233.94], EntityZombie['Zombie'/52, l='MpServer', x=-313.53, y=15.00, z=239.28], EntitySpider['Spider'/59, l='MpServer', x=-301.50, y=24.00, z=275.50], EntitySeagull['Seagull'/178, l='MpServer', x=-198.03, y=75.25, z=281.25], EntityZombie['Zombie'/58, l='MpServer', x=-300.50, y=24.00, z=277.50], EntitySeagull['Seagull'/179, l='MpServer', x=-200.84, y=74.00, z=277.78], EntityCreeper['Creeper'/57, l='MpServer', x=-302.00, y=37.00, z=197.34], EntitySeagull['Seagull'/176, l='MpServer', x=-202.22, y=76.50, z=273.63], EntitySkeleton['Skeleton'/56, l='MpServer', x=-295.50, y=38.00, z=198.50], EntitySeagull['Seagull'/177, l='MpServer', x=-202.75, y=73.72, z=276.84], EntitySeagull['Seagull'/63, l='MpServer', x=-290.09, y=65.09, z=332.34], EntityBat['Bat'/62, l='MpServer', x=-292.25, y=23.56, z=281.88], EntityBat['Bat'/183, l='MpServer', x=-205.69, y=31.84, z=335.38], EntityBat['Bat'/61, l='MpServer', x=-290.22, y=27.22, z=282.06], EntityBat['Bat'/180, l='MpServer', x=-197.00, y=47.91, z=320.88], EntityBat['Bat'/60, l='MpServer', x=-291.88, y=27.81, z=282.25], EntityClientPlayerMP['Doonan10'/322, l='MpServer', x=-260.50, y=68.62, z=265.50], EntityBat['Bat'/69, l='MpServer', x=-285.28, y=29.03, z=190.03], EntityBat['Bat'/70, l='MpServer', x=-286.28, y=40.25, z=199.25], EntityCreeper['Creeper'/71, l='MpServer', x=-283.50, y=14.00, z=234.00], EntityZombie['Zombie'/64, l='MpServer', x=-297.50, y=16.00, z=336.50], EntityCreeper['Creeper'/201, l='MpServer', x=-186.44, y=36.00, z=303.00], EntityCreeper['Creeper'/196, l='MpServer', x=-182.50, y=56.00, z=205.50], EntitySpider['Spider'/72, l='MpServer', x=-287.00, y=14.00, z=226.59], EntitySeagull['Seagull'/73, l='MpServer', x=-283.72, y=66.75, z=328.31], EntitySeagull['Seagull'/74, l='MpServer', x=-285.75, y=66.09, z=332.75], EntitySeagull['Seagull'/75, l='MpServer', x=-278.06, y=64.63, z=339.78], EntityBat['Bat'/220, l='MpServer', x=-188.50, y=32.00, z=338.66], EntityBat['Bat'/221, l='MpServer', x=-189.75, y=32.16, z=338.16], EntityBat['Bat'/222, l='MpServer', x=-184.09, y=32.75, z=338.97], EntitySeagull['Seagull'/95, l='MpServer', x=-265.94, y=72.06, z=196.69], EntitySeagull['Seagull'/94, l='MpServer', x=-256.72, y=71.06, z=202.75], EntitySkeleton['Skeleton'/102, l='MpServer', x=-264.50, y=34.00, z=330.50], EntityZombie['Zombie'/103, l='MpServer', x=-262.44, y=34.00, z=328.44], EntityBat['Bat'/101, l='MpServer', x=-264.78, y=42.44, z=297.59], EntitySeagull['Seagull'/98, l='MpServer', x=-252.91, y=76.09, z=205.28], EntityCreeper['Creeper'/99, l='MpServer', x=-266.50, y=47.00, z=297.50], EntitySeagull['Seagull'/96, l='MpServer', x=-262.19, y=73.06, z=190.84], EntityBat['Bat'/97, l='MpServer', x=-271.75, y=33.09, z=214.59], EntityZombie['Zombie'/104, l='MpServer', x=-261.09, y=34.00, z=328.50], EntityZombie['Zombie'/105, l='MpServer', x=-262.50, y=34.00, z=326.50], EntitySeagull['Seagull'/119, l='MpServer', x=-256.84, y=71.19, z=199.69], EntitySeagull['Seagull'/118, l='MpServer', x=-249.53, y=69.75, z=195.75], EntitySeagull['Seagull'/126, l='MpServer', x=-238.50, y=76.00, z=317.09], EntitySeagull['Seagull'/125, l='MpServer', x=-257.00, y=74.16, z=310.94], EntitySeagull['Seagull'/124, l='MpServer', x=-242.53, y=75.81, z=311.03], EntitySeagull['Seagull'/123, l='MpServer', x=-243.56, y=71.69, z=310.63], EntityBat['Bat'/122, l='MpServer', x=-250.94, y=54.50, z=308.25], EntityBat['Bat'/121, l='MpServer', x=-250.34, y=54.34, z=310.00], EntityBat['Bat'/120, l='MpServer', x=-250.94, y=25.00, z=301.00]]
Retry entities: 0 total; []
Server brand: fml,forge
Server type: Integrated singleplayer server
Stacktrace:
at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 8.1 (amd64) version 6.3
Java Version: 1.7.0_71, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 80082072 bytes (76 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Xmx512M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_B4 38 mods loaded, 38 mods active
mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
<CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
gasesCore{1.5.2} [Glenn's Gases Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
gasesFrameworkCore{1.0.5.1} [Gases Framework Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
CoFHCore{1.7.10R3.0.0B9} [CoFH Core](CoFHCore-[1.7.10]3.0.0B9-40.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0RC1-17.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
BigReactors{0.4.1A2} [Big Reactors](BigReactors-0.4.1A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
CarpentersBlocks{3.3.3} [Carpenter's Blocks](Carpenter's Blocks v3.3.3 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
EnderIO{1.7.10-2.2.7.325} [Ender IO](EnderIO-1.7.10-2.2.7.325.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ExtraUtilities{1.2.1} [Extra Utilities](extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
gasesFramework{1.0.6} [Gases Framework](gasesFramework-1.0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
gases{1.5.2} [Glenn's Gases](gases-1.5.2-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
JumpPad++{2.2.7} [JumpPad++](JumpPad++-2.2.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
NetherOres{1.7.10R2.3.0RC4} [Nether Ores](NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Oceancraft{1.3.1} [Oceancraft](Oceancraft-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-223.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-430.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
harvestcraft{1.7.10d} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10f.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ReiMinimap{1.7.10} [Rei's Minimap](ReiMinimap-1.7.10-3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
simplyjetpacks{1.3.2} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Waila{1.5.8} [Waila](Waila-1.5.8a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct](TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-161.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
TConstruct Environment: Environment healthy.
Launched Version: 1.7.10-Forge10.13.2.1230
LWJGL: 2.9.1
OpenGL: GeForce GTX 860M/PCIe/SSE2 GL version 4.4.0 NVIDIA 344.75, NVIDIA Corporation,
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)

**Comment by evknucklehead** [comment]
You have two -Xmx flags in your Java arguments. The second one is overriding the first, meaning the game is limited to 512MB instead of the 6GB you're expecting. Try again without the -Xmx512M.

**Comment by Elix-x** [comment]
Having the same issue, when load a world. JVM args: -Xmx5G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G

**Comment by Robijnvogel** [comment]
This problem has been reported various times before. It is sort of an incompatibility between ExtraUtils 1.2.1 (or 1.2) and Rei's unofficial Minimap. It seems that the problem has not been solved yet.
#406 

As a temporary measure I'd suggest using another minimap mod, or not using extra utils for a while,  however the latter is of course not really an option :)

**Comment by Elix-x** [comment]
Okay, thanks! So i'm changing minimap to Journey Map, now it should work!
