### ISSUE TITLE
extra utilities energy generators crash when start generating power can any 1 help?

### ISSUE THREAD

**Issue by ttax00** [rwtema/extrautilities_old_issues#492]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/25/15 10:46 AM
Description: Ticking block entity

java.lang.NoSuchMethodError: buildcraft.api.core.JavaTools.getAllFields(Ljava/lang/Class;)Ljava/util/List;
    at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
    at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transferBC(TileEntityGenerator.java:249)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:243)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:216)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
    at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transferBC(TileEntityGenerator.java:249)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:243)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:216)

-- Block entity being ticked --
Details:
    Name: extrautils:generatoroverclocked // com.rwtema.extrautils.tileentity.generator.TileEntityGeneratorFurnaceOverClocked
    Block type: ID #637 (tile.extrautils:generator.64 // com.rwtema.extrautils.tileentity.generator.BlockGenerator)
    Block data value: 10 / 0xA / 0b1010
    Block location: World: (-149,69,387), Chunk: (at 11,4,3 in -10,24; contains blocks -160,0,384 to -145,255,399), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #637 (tile.extrautils:generator.64 // com.rwtema.extrautils.tileentity.generator.BlockGenerator)
    Actual block data value: 10 / 0xA / 0b1010
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: Copy of lp
    All players: 1 total; [EntityPlayerMP['TechTheAwesome'/164, l='Copy of lp', x=-148.80, y=68.88, z=386.61]]
    Chunk stats: ServerChunkCache: 442 Drop: 0
    Level seed: 3669685826593304295
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-44,64,256), Chunk: (at 4,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 6472 game time, 5571 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 45623 (now: false), thunder time: 22508 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 58877784 bytes (56 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 Optifine OptiFine_1.7.10_HD_U_B4 33 mods loaded, 33 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics2-Core{rv0-stable-8} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.3.26} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.56} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.56-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0B8} [CoFH Core](CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{6.3.1} [BuildCraft](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.2.658-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.658-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv0-stable-8} [Applied Energistics 2](appliedenergistics2-rv0-stable-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forestry{3.3.0.6} [Forestry for Minecraft](forestry_1.7.10-3.3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BinnieCore{2.0-pre4} [Binnie Core](binnie-mods-2.0-pre4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Botany{2.0-pre4} [Botany](binnie-mods-2.0-pre4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraBees{2.0-pre4} [Extra Bees](binnie-mods-2.0-pre4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraTrees{2.0-pre4} [Extra Trees](binnie-mods-2.0-pre4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Genetics{2.0-pre4} [Genetics](binnie-mods-2.0-pre4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{6.3.1} [BC Transport](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{6.3.1} [BC Silicon](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{6.3.1} [BC Builders](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{6.3.1} [BC Energy](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{6.3.1} [BC Factory](buildcraft-6.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.5.24} [EnderStorage](Ender-Storage-Mod-1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderIO{1.7.10-2.2.6.317} [Ender IO](EnderIO-1.7.10-2.2.6.317.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.1.0j} [Extra Utilities](extrautilities-1.1.0j.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mystcraft{0.11.0.00} [Mystcraft](mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{9.4.0.0} [Railcraft](Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ReiMinimap{1.7.10} [Rei's Minimap](ReiMinimap-1.7.10-3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct](TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AE2 Version: stable rv0-stable-8 for Forge 10.13.0.1152
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    AE2 Integration: RotaryCraft:OFF, IC2:ON, RC:ON, BC:ON, MJ5:ON, MJ6:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, Waila:OFF, CLApi:OFF, RB:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, FMP:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['TechTheAwesome'/164, l='Copy of lp', x=-148.80, y=68.88, z=386.61]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by jena-th** [comment]
Try to use [Gist](https://gist.github.com/) for posting your logs.

To solve your problem, try to update Extra Utilities or downgrade Buildcraft, the problem seems to be that EU try to call an unexistent BC function, reflecting a possible version discrepancies between what EU expect and what BC provide.
