### ISSUE TITLE
crash game 2 sec after lauching

### ISSUE THREAD

**Issue by Lorenzo77** [rwtema/extrautilities_old_issues#499]
java.lang.StackOverflowError: Unexpected error
    at java.util.HashMap.containsKey(HashMap.java:595)
    at java.util.HashSet.contains(HashSet.java:203)
    at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.getPipe(TNHelper.java:146)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:83)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
    at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeCrossOver.canInput(PipeCrossOver.java:92)
...............

full error here : http://pastebin.com/wrTSs4NB

it's not the first time i got this error ... 
my mods :
appliedenergistics2-rv1-stable-1.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.0B9-40.jar
EnderIO-1.7.10-2.2.7.325.jar
extrautilities-1.2.1.jar
FinderCompass-1.7.10.jar
InventoryTweaks-1.58-147.jar
MineFactoryReloaded-[1.7.10]2.8.0RC6-5.jar
NetherOres-[1.7.10]2.3.0RC4-4.jar
NotEnoughItems-1.7.10-1.0.3.74-universal.jar
OptiFine_1.7.10_HD_B5.jar
Reis-Minimap-Mod-1.7.10.jar
ThermalExpansion-[1.7.10]4.0.0B8-23.jar
ThermalFoundation-[1.7.10]1.0.0RC1-13.jar

---

minecraft 1.7.10
forge forge-1.7.10-10.13.2.1291
java 7.71
windows XP sp3

---

i need to deactivate Reis-Minimap in order to play, i see another issue like this with Reis-Minimap but the output is not the same ...
do you need more data ?

---

nb : thanks for your mod, it's my favourite !
nb2: you should add more internal storage for tier 2 generator and even more for tier 3 generator

**Comment by TherminatorX** [comment]
It's something to do with Rei's Minimap. This is a known and frequently duped issue.
Switch out your minimap, and everything should be fine.
