### ISSUE TITLE
Ender-Thermic Pump near fortress

### ISSUE THREAD

**Issue by ShadwDrgn** [rwtema/extrautilities_old_issues#523]
If you place an ender thermic pump near a nether fortress you'll end up with insane amounts of wither skeletons. So much that my server crashed... over 2700 of them when i did cofh killall witherskeleton.

causes tons of this:
[15:33:26] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
    at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
    at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) [EntityRegistry.class:?]
    at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) [mn.class:?]
    at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
    at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
    at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
    at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
    at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
    at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
    at net.minecraft.block.BlockStaticLiquid.func_149674_a(SourceFile:55) [ant.class:?]
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391) [mt.class:?]
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
    at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
    ... 26 more

**Comment by HowardRoark2016** [comment]
I had this exact same issue twice now, but something new the second time around. The first time was when the Ender-Thermic Pump was near a nether fortress. Severe lag within hours of turning on the pump. Thousands of wither skeletons were spawned and my FPS hovered around 10. I dismantled the pump and found a location in the nether were there are no fortresses within a radius of over 100 chunks of the pump. That pump has run fine for three weeks now. I've traveled to that pump several times in the last two days and noticed a couple of Wither Skeletons walking on the stone that the pump puts down to replace the lava source blocks. I thought nothing of it. Today, my FPS went down to below 10 again. I did a "/cofh killall witherskeleton" and was shocked to see that over 14,000 Wither Skellys were removed. My FPS instantly went above 90+. I am not sure if the fortress itself is the issue now. I appears that wither skeletons are.

EDIT: I just want to add that the outer-most stone (which is also the most recently placed stone) placed by the pump that encircles the pump has reached "land" in one chunk - a medium-sized island of netherrack. The ring of stone extends about 5 chunks in each of the cardinal directions. None of the rest of the stone is touching anything but lava (this lava ocean is massive). Here's a screenshot of the area where the pump is now placing its stone - http://imgur.com/1eRbr8w

**Comment by ShadwDrgn** [comment]
You can close this. It's an EnderIO issue with chunk loading, not an ExU bug. They replace wither skeletons and it somehow breaks spawning badly.
