### ISSUE TITLE
Another Crash. (1.7.2.)

### ISSUE THREAD

**Issue by DoctorOktoberfest** [rwtema/extrautilities_old_issues#53]
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 5/4/14 1:12 PM
Description: Initializing game

java.lang.NoClassDefFoundError: codechicken/microblock/ItemMicroPart
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:209)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:489)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:202)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:465)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:813)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.microblock.ItemMicroPart
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 36 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:180)
    ... 38 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:492)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:209)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:489)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:202)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:465)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:813)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode, sharing), Oracle Corporation
    Memory: 25135704 bytes (23 MB) / 150081536 bytes (143 MB) up to 518979584 bytes (494 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.01-pre FML v7.2.156.1060 Minecraft Forge 10.12.1.1060 16 mods loaded, 15 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed
    FML{7.2.156.1060} [Forge Mod Loader](forge-1.7.2-10.12.1.1060.jar) Unloaded->Constructed
    Forge{10.12.1.1060} [Minecraft Forge](forge-1.7.2-10.12.1.1060.jar) Unloaded->Constructed
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed
    asielib{0.2.0} [asielib](AsieLib-1.7.2-0.2.0.jar) Unloaded->Constructed
    candycraftmod{(Alpha)} [CandyCraft](CandyCraft %281.7.2%29.jar.zip) Unloaded->Constructed
    chisel{1.5.3} [Chisel](chisel-1.7.2-1.5.3.jar) Unloaded->Constructed
    ExtraUtilities{1.1.0-prerelease-1b} [Extra Utilities](extrautilities-1.1.0-prerelease-1b.jar.zip) Unloaded
    Paintball{1.7.2v2} [Paintball](Paintball-1.7.2v2.jar) Unloaded
    pandorasbox{2.0} [Pandora's Box](PandorasBox-2.0.jar.zip) Unloaded
    psychedelicraft{1.4.1} [Psychedelicraft](Psychedelicraft-1.4.1.jar.zip) Unloaded
    stillhungry{1.7.2-2.1.0} [Still Hungry!](stillhungry-1.7.2-2.1.0.jar) Unloaded
    weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod](weaponmod-1.14.2.jar) Unloaded
    yegamolchattels{1.0.1} [Ye Gamol Chattels](YeGamolChattels-1.0.1.jar.zip) Unloaded
    asielibcore{} [AsieLib CoreMod](minecraft.jar) Unloaded->Disabled
    Launched Version: 1.7.2-Forge10.12.1.1060
    LWJGL: 2.9.0
    OpenGL: AMD Radeon HD 6290 Graphics GL version 4.2.12217 Compatibility Profile Context 12.104.0.0, ATI Technologies Inc.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
    Anisotropic Filtering: Off (1)

**Comment by JadenWong** [comment]
same here
http://pastebin.com/fUiDqA0j

**Comment by Properjob** [comment]
Install forge multipart that fixed it on mine

**Comment by JadenWong** [comment]
@Properjob thx, now it works like a charm

**Comment by TherminatorX** [comment]
Why is Forge Multipart needed? XU shouldn't need it, so this would be a different mod's requirement.
