### ISSUE TITLE
Survivalist generator crashing the game in 1.1.0k

### ISSUE THREAD

**Issue by Terralagg** [rwtema/extrautilities_old_issues#532]
When I put a stack of coal in a survivalist generator, my game crashed after a few seconds and I had to go into the config files to disable generators so I could acces my world again. This happened a couple times now and it's starting to get annoying. I also removed optifine, because I thought that might be causing it, and lowered my ambient sound all the way to 0. Both didn't work.

Here is the crash report:

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 10-3-15 18:42
Description: Ticking block entity

java.lang.NoSuchMethodError: buildcraft.api.core.JavaTools.getAllFields(Ljava/lang/Class;)Ljava/util/List;
    at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
    at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transferBC(TileEntityGenerator.java:249)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:243)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:216)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
    at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transferBC(TileEntityGenerator.java:249)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:243)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:216)

-- Block entity being ticked --
Details:
    Name: extrautils:generatorstone // com.rwtema.extrautils.tileentity.generator.TileEntityGeneratorFurnaceSurvival
    Block type: ID #1128 (tile.extrautils:generator // com.rwtema.extrautils.tileentity.generator.BlockGenerator)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-774,71,861), Chunk: (at 10,4,13 in -49,53; contains blocks -784,0,848 to -769,255,863), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
    Actual block type: ID #1128 (tile.extrautils:generator // com.rwtema.extrautils.tileentity.generator.BlockGenerator)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: Electric Evolutions Test
    All players: 1 total; [EntityPlayerMP['brian_wrestler'/512, l='Electric Evolutions Test', x=-773,49, y=71,00, z=862,95]]
    Chunk stats: ServerChunkCache: 344 Drop: 0
    Level seed: 3265750288161660582
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-814,64,947), Chunk: (at 2,4,3 in -51,59; contains blocks -816,0,944 to -801,255,959), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
    Level time: 136741 game time, 140514 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 85212 (now: false), thunder time: 91953 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 218306144 bytes (208 MB) / 1270874112 bytes (1212 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 40, tcache: 0, allocated: 15, tallocated: 96
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 81 mods loaded, 81 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge](modpack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.4.90} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.90-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0RC5} [CoFH Core](CoFHCore-[1.7.10]3.0.0RC5-207.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.2.657-experimental} [IndustrialCraft 2](Industrial-Craft-2-Mod-Experimental-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    advancedgenetics{1.5.8} [Advanced Genetics](advancedgenetics-1.7.10-1.5.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Core{6.4.2} [BuildCraft](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderIO{1.7.10-2.2.8.349} [Ender IO](EnderIO-1.7.10-2.2.8.349.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.1.1.323} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Builders{6.4.2} [BC Builders](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Energy{6.4.2} [BC Energy](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Factory{6.4.2} [BC Factory](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Railcraft{9.5.0.0} [Railcraft](Railcraft_1.7.10-9.5.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mekanism{7.1.1} [Mekanism](Mekanism-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.0RC6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0RC6-138.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv0-stable-10} [Applied Energistics 2](appliedenergistics2-rv0-stable-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterstorage{0.9.2.107} [BetterStorage](Better-Storage-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BigReactors{0.4.2A2} [Big Reactors](BigReactors-0.4.2A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Transport{6.4.2} [BC Transport](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BuildCraft|Silicon{6.4.2} [BC Silicon](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CarpentersBlocks{3.3.5} [Carpenter's Blocks](Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.5.25} [EnderStorage](EnderStorage-1.7.10-1.4.5.25.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.88.8.8888h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.dimensionalSlice{0.8.88.8.8888h} [Factorization Dimensional Slices](Factorization-1.7.10-0.8.88.8.8888h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization{0.8.88.8.8888h} [Factorization](Factorization-1.7.10-0.8.88.8.8888h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    factorization.misc{0.8.88.8.8888h} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.88.8.8888h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    flansmod{4.9.0} [Flan's Mod](Flans Mod-1.7.10-4.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.62.742} [Iron Chest](Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.8} [Waila](Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.1.jenkins180} [Mantle](Mantle-mc1.7.10-0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismGenerators{7.1.1} [MekanismGenerators](MekanismGenerators-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MekanismTools{7.1.1} [MekanismTools](MekanismTools-1.7.10-7.1.1.127.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Core{4.4.5.44} [ProjectRed](ProjectRed-Base-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Exploration{4.4.5.44} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transmission{4.4.5.44} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Transportation{4.4.5.44} [ProjectRed-Transportation](ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.6.0.build611} [Tinkers' Construct](TConstruct_mc1.7.10_1.6.0d40.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Compatibility{4.4.5.44} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Integration{4.4.5.44} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Illumination{4.4.5.44} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ProjRed|Expansion{4.4.5.44} [ProjectRed-Expansion](ProjectRed-Mechanical-1.7.10-4.4.5.44.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    simplyjetpacks{1.4.1} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    thaumcarpentry{0.0.1.5-1.7.10} [Thaumcarpentry](Thaumcarpentry-0.0.1.5-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalDynamics{1.7.10R1.0.0RC5} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.0.0RC5-94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Ztones{1.7.10} [Ztones](Ztones-1.7.10-2.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.1.1.323} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.1.1.323} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.1.323-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsLib crash transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED],[map_gen_fix:FINISHED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
    CoFHCore: -[1.7.10]3.0.0RC5-207
    MineFactoryReloaded: Lacking version information.
    ThermalFoundation: -[1.7.10]1.0.0RC4-58
    ThermalExpansion: -[1.7.10]4.0.0RC6-138
    AE2 Version: stable rv0-stable-10 for Forge 10.13.0.1152
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.0.0RC5-94
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: RotaryCraft:OFF, IC2:ON, RC:ON, BC:ON, MJ5:ON, MJ6:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:ON, Waila:ON, CLApi:OFF, RB:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, FMP:ON
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['brian_wrestler'/512, l='Electric Evolutions Test', x=-773,49, y=71,00, z=862,95]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Zedrimar** [comment]
old version, check curse (link to that is on the forrums page
