### ISSUE TITLE
QED is making me crash

### ISSUE THREAD

**Issue by Registeel1234** [rwtema/extrautilities_old_issues#555]
Hello, I'm curently hosting a private server with some of my friends, and when I tried to use the QED (Right-clicking it after placing it), it disconects me from the server, showing me a fatal Error message. Trying to destroy it will make my client crash. Here's the crash report:

<code>---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!
Time: 15-04-02 21:15
Description: Ticking entity
java.lang.NoSuchMethodError: net.minecraft.util.AxisAlignedBB.func_72332_a()Lnet/minecraft/util/AABBPool;
    at com.rwtema.extrautils.block.BlockMultiBlock.func_149743_a(BlockMultiBlock.java:58)
    at net.minecraft.world.World.func_147461_a(World.java:1495)
    at net.minecraft.entity.Entity.func_145771_j(Entity.java:1882)
    at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:109)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1994)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
A detailed walkthrough of the error, its code path and all known details is as follows:
Stacktrace:
    at com.rwtema.extrautils.block.BlockMultiBlock.func_149743_a(BlockMultiBlock.java:58)
    at net.minecraft.world.World.func_147461_a(World.java:1495)
    at net.minecraft.entity.Entity.func_145771_j(Entity.java:1882)
    at net.minecraft.entity.item.EntityItem.func_70071_h_(EntityItem.java:109)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
-- Entity being ticked --
Details:
    Entity Type: Item (net.minecraft.entity.item.EntityItem)
    Entity ID: 451086
    Entity Name: item.tile.extrautils:endConstructor.0
    Entity's Exact location: 611,16, 118,56, 1038,78
    Entity's Block location: World: (611,118,1038), Chunk: (at 3,7,14 in 38,64; contains blocks 608,0,1024 to 623,255,1039), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
    Entity's Momentum: -0,03, 0,16, -0,02
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCEntityClientPlayerMP['Registeel1234'/450592, l='MpServer', x=612,42, y=119,54, z=1040,76]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (776,64,1106), Chunk: (at 8,4,2 in 48,69; contains blocks 768,0,1104 to 783,255,1119), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
    Level time: 1709398 game time, 1757642 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 112 total; [EntityTrail['unknown'/768, l='MpServer', x=612,42, y=119,54, z=1040,76], EntityItem['item.tile.extrautils:endConstructor.0'/451086, l='MpServer', x=611,16, y=118,56, z=1038,78], EntityZombie['Zombie'/450826, l='MpServer', x=542,56, y=72,00, z=1020,91], EntityZombie['Zombie'/450827, l='MpServer', x=540,94, y=73,00, z=1021,44], EntityBat['Bat'/445960, l='MpServer', x=629,98, y=47,00, z=1092,45], EntitySpider['Spider'/450825, l='MpServer', x=542,50, y=72,00, z=1019,09], GCEntityClientPlayerMP['Registeel1234'/450592, l='MpServer', x=612,42, y=119,54, z=1040,76], EntitySlime['Slime'/352037, l='MpServer', x=655,69, y=16,00, z=1083,69], EntityDryad['Dryad'/546, l='MpServer', x=640,53, y=67,00, z=1019,53], EntityZombie['Zombie'/450593, l='MpServer', x=620,53, y=112,00, z=1041,09], EntityCreeper['Creeper'/449842, l='MpServer', x=640,63, y=46,00, z=1095,03], EntityChicken['Chicken'/63, l='MpServer', x=653,22, y=63,00, z=1110,78], EntityChicken['Chicken'/64, l='MpServer', x=649,19, y=63,00, z=1111,31], EntityChicken['Chicken'/65, l='MpServer', x=652,97, y=63,00, z=1111,81], EntityChicken['Chicken'/66, l='MpServer', x=649,47, y=63,00, z=1118,22], EntityChicken['Chicken'/67, l='MpServer', x=649,63, y=63,00, z=1110,78], EntityChicken['Chicken'/68, l='MpServer', x=652,19, y=63,00, z=1117,44], EntityChicken['Chicken'/69, l='MpServer', x=653,22, y=63,00, z=1118,22], EntitySkeleton['Skeleton'/449091, l='MpServer', x=640,50, y=25,00, z=1110,50], EntityChicken['Chicken'/70, l='MpServer', x=649,63, y=63,00, z=1111,97], EntityChicken['Chicken'/71, l='MpServer', x=648,78, y=63,00, z=1110,78], EntityChicken['Chicken'/72, l='MpServer', x=652,41, y=63,00, z=1113,38], EntityChicken['Chicken'/73, l='MpServer', x=652,47, y=63,00, z=1110,78], EntityChicken['Chicken'/74, l='MpServer', x=652,84, y=63,00, z=1117,53], EntityChicken['Chicken'/75, l='MpServer', x=648,78, y=63,00, z=1118,22], EntitySkeleton['Skeleton'/449111, l='MpServer', x=689,50, y=35,00, z=1028,50], EntityBat['Bat'/450662, l='MpServer', x=601,42, y=47,73, z=1063,85], EntityZombie['Zombie'/450663, l='MpServer', x=604,50, y=48,00, z=1061,50], EntityZombie['Zombie'/450660, l='MpServer', x=616,91, y=116,00, z=1038,50], EntityBat['Bat'/450661, l='MpServer', x=609,53, y=49,63, z=1060,45], EntityCreeper['Creeper'/450658, l='MpServer', x=593,34, y=101,00, z=1050,31], EntityCreeper['Creeper'/450659, l='MpServer', x=612,00, y=95,00, z=1029,50], EntityBat['Bat'/450403, l='MpServer', x=647,75, y=47,10, z=1091,50], EntitySkeleton['Skeleton'/450670, l='MpServer', x=622,25, y=47,00, z=1087,28], EntityCreeper['Creeper'/450671, l='MpServer', x=578,50, y=25,00, z=1066,50], EntitySkeleton['Skeleton'/450668, l='MpServer', x=624,91, y=106,00, z=1034,50], EntityBat['Bat'/450669, l='MpServer', x=607,66, y=54,08, z=1006,81], EntityZombie['Zombie'/450666, l='MpServer', x=642,06, y=37,00, z=1032,44], EntitySkeleton['Skeleton'/450667, l='MpServer', x=627,97, y=87,00, z=1036,50], EntityZombie['Zombie'/450664, l='MpServer', x=605,50, y=48,00, z=1064,50], EntitySkeleton['Skeleton'/450665, l='MpServer', x=601,78, y=51,00, z=1032,16], EntitySkeleton['Skeleton'/450678, l='MpServer', x=624,50, y=47,00, z=1087,50], EntityBat['Bat'/450679, l='MpServer', x=567,31, y=16,00, z=1049,78], EntityWitch['Witch'/450676, l='MpServer', x=632,50, y=16,00, z=1020,50], EntityWitch['Witch'/450677, l='MpServer', x=638,34, y=16,00, z=1017,47], EntitySkeleton['Skeleton'/450674, l='MpServer', x=634,16, y=16,00, z=1021,50], EntitySkeleton['Skeleton'/450675, l='MpServer', x=638,50, y=17,00, z=1019,09], EntitySkeleton['Skeleton'/450673, l='MpServer', x=635,84, y=16,00, z=1020,00], EntityBat['Bat'/450686, l='MpServer', x=615,27, y=25,61, z=1000,63], EntityBat['Bat'/450687, l='MpServer', x=607,62, y=24,85, z=1002,22], EntityCreeper['Creeper'/450684, l='MpServer', x=574,47, y=28,00, z=1066,94], EntityZombie['Zombie'/450685, l='MpServer', x=574,50, y=21,00, z=1071,50], EntitySkeleton['Skeleton'/450682, l='MpServer', x=628,06, y=47,00, z=1089,50], EntityItem['item.item.rottenFlesh'/450683, l='MpServer', x=594,69, y=67,13, z=1094,09], EntityBat['Bat'/450680, l='MpServer', x=604,48, y=54,82, z=1006,42], EntitySkeleton['Skeleton'/450681, l='MpServer', x=614,84, y=46,00, z=1088,56], EntityBat['Bat'/450694, l='MpServer', x=578,14, y=44,07, z=992,59], EntitySpider['Spider'/450695, l='MpServer', x=550,22, y=10,34, z=1040,47], EntitySkeleton['Skeleton'/450692, l='MpServer', x=569,50, y=20,00, z=1009,50], EntitySpider['Spider'/450693, l='MpServer', x=588,50, y=27,00, z=1004,50], EntityManaCreeper['Mana Creeper'/450690, l='MpServer', x=633,50, y=28,00, z=1093,50], EntityCreeper['Creeper'/450691, l='MpServer', x=585,50, y=25,00, z=1089,50], EntityItem['item.item.arrow'/450688, l='MpServer', x=600,31, y=90,13, z=1000,25], EntityItem['item.item.bone'/450689, l='MpServer', x=600,50, y=90,13, z=1000,88], EntityItem['item.item.rottenFlesh'/450702, l='MpServer', x=552,78, y=79,13, z=1056,13], EntityCreeper['Creeper'/450703, l='MpServer', x=548,66, y=20,00, z=1033,97], EntitySkeleton['Skeleton'/450700, l='MpServer', x=545,38, y=60,00, z=1057,31], EntitySpider['Spider'/450701, l='MpServer', x=546,72, y=62,00, z=1053,16], EntityCreeper['Creeper'/450698, l='MpServer', x=546,47, y=63,00, z=1045,97], EntityZombie['Zombie'/450699, l='MpServer', x=548,19, y=61,00, z=1053,75], EntityZombie['Zombie'/449419, l='MpServer', x=641,50, y=41,00, z=1043,50], EntityCreeper['Creeper'/450696, l='MpServer', x=550,50, y=35,00, z=1041,50], EntitySkeleton['Skeleton'/450697, l='MpServer', x=550,06, y=62,00, z=1055,44], EntityBat['Bat'/450710, l='MpServer', x=622,40, y=57,27, z=1110,85], EntityZombie['Zombie'/450711, l='MpServer', x=544,50, y=30,00, z=1018,50], EntityCreeper['Creeper'/450708, l='MpServer', x=555,41, y=35,00, z=1035,50], EntityCreeper['Creeper'/450706, l='MpServer', x=547,50, y=29,00, z=1027,50], EntityZombie['Zombie'/450704, l='MpServer', x=546,50, y=20,00, z=1036,50], EntityCreeper['Creeper'/450705, l='MpServer', x=547,50, y=29,00, z=1028,50], EntitySkeleton['Skeleton'/450719, l='MpServer', x=546,06, y=58,00, z=1099,50], EntityCreeper['Creeper'/450716, l='MpServer', x=556,50, y=75,00, z=1014,50], EntityZombie['Zombie'/448668, l='MpServer', x=652,44, y=11,00, z=1019,75], EntityZombie['Zombie'/448669, l='MpServer', x=660,00, y=13,00, z=1021,44], EntitySkeleton['Skeleton'/450714, l='MpServer', x=547,50, y=72,00, z=1013,50], EntitySkeleton['Skeleton'/450715, l='MpServer', x=554,09, y=76,00, z=1015,50], EntitySkeleton['Skeleton'/450712, l='MpServer', x=547,50, y=35,00, z=1015,09], EntityCreeper['Creeper'/450713, l='MpServer', x=541,78, y=71,00, z=1013,84], EntitySkeleton['Skeleton'/450726, l='MpServer', x=541,56, y=61,00, z=1040,91], EntitySkeleton['Skeleton'/450725, l='MpServer', x=542,41, y=35,00, z=1043,22], EntitySkeleton['Skeleton'/450722, l='MpServer', x=547,28, y=58,00, z=1100,34], EntityZombie['Zombie'/450723, l='MpServer', x=536,50, y=20,00, z=1050,50], EntitySkeleton['Skeleton'/450720, l='MpServer', x=551,44, y=59,00, z=1097,94], EntitySkeleton['Skeleton'/450721, l='MpServer', x=546,31, y=58,00, z=1101,13], EntityBat['Bat'/450734, l='MpServer', x=543,13, y=30,64, z=1074,91], EntityCreeper['Creeper'/450732, l='MpServer', x=545,06, y=26,03, z=1029,50], EntitySquid['Squid'/448684, l='MpServer', x=662,50, y=52,31, z=1022,06], EntitySquid['Squid'/448682, l='MpServer', x=674,09, y=52,28, z=1024,59], EntityBat['Bat'/450730, l='MpServer', x=536,17, y=30,96, z=1054,17], EntityZombie['Zombie'/450731, l='MpServer', x=536,56, y=52,00, z=1057,94], EntitySquid['Squid'/448680, l='MpServer', x=662,75, y=49,00, z=1024,72], EntityZombie['Zombie'/450742, l='MpServer', x=556,50, y=29,00, z=982,50], EntityZombie['Zombie'/450740, l='MpServer', x=580,50, y=52,00, z=965,50], EntityChicken['Chicken'/450741, l='MpServer', x=556,41, y=63,00, z=1105,47], EntitySkeleton['Skeleton'/450738, l='MpServer', x=543,41, y=71,00, z=1008,91], EntitySkeleton['Skeleton'/450739, l='MpServer', x=538,91, y=72,00, z=1014,50], EntityZombie['Zombie'/450736, l='MpServer', x=543,50, y=30,00, z=1019,50], EntityZombie['Zombie'/450737, l='MpServer', x=538,50, y=30,00, z=1020,50], EntitySquid['Squid'/448733, l='MpServer', x=673,50, y=48,34, z=1023,69], EntitySkeleton['Skeleton'/450788, l='MpServer', x=663,50, y=27,00, z=1089,50], EntityItem['item.item.sulphur'/450812, l='MpServer', x=552,06, y=11,13, z=1035,69], EntityBat['Bat'/451069, l='MpServer', x=544,70, y=58,00, z=1062,45], EntityBat['Bat'/451066, l='MpServer', x=531,38, y=52,48, z=1059,44]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_31, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1320064272 bytes (1258 MB) / 2020605952 bytes (1927 MB) up to 2020605952 bytes (1927 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M -Xms2048M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_B5 55 mods loaded, 55 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AM2-Preloader{0.0.2} [AMCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NotEnoughItems{1.0.4.94} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.94-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    DamageIndicatorsMod{3.2.3} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    CoFHCore{1.7.10R3.0.0RC5} [CoFH Core](CoFHCore-[1.7.10]3.0.0RC5-207.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalFoundation{1.7.10R1.0.0RC4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0RC4-58.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThermalExpansion{1.7.10R4.0.0RC6} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0RC6-138.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BigReactors{0.4.2A2} [Big Reactors](BigReactors-0.4.2A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    AWWayofTime{v1.3.1} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Core{6.4.2} [BuildCraft](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Transport{6.4.2} [BC Transport](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Silicon{6.4.2} [BC Silicon](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Builders{6.4.2} [BC Builders](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Energy{6.4.2} [BC Energy](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    BuildCraft|Factory{6.4.2} [BC Factory](buildcraft-6.4.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    EnderIO{1.7.10-2.2.8.349} [Ender IO](EnderIO-1.7.10-2.2.8.349.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Waila{1.5.8} [Waila](Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TConstruct{1.7.10-1.8.2.build858} [Tinkers' Construct](TConstruct-1.7.10-1.8.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraTiC{0.8.4} [ExtraTiC](ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ExtraUtilities{1.1.0b} [Extra Utilities](extrautilities-1.1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-162.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    ForbiddenMagic{1.7.10-0.551} [Forbidden Magic](Forbidden Magic-1.7.10-0.551.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GalacticraftCore{3.0.11} [Galacticraft Core](GalacticraftCore-1.7-3.0.11.306.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    GalacticraftMars{3.0.11} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.11.306.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    HardcoreEnderExpansion{1.7.1} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    iChunUtil{4.1.0} [iChunUtil](iChunUtil-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Mystcraft{0.11.2.01} [Mystcraft](mystcraft-1.7.10-0.11.2.01.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    NetherOres{1.7.10R2.3.0RC4} [Nether Ores](NetherOres-[1.7.10]2.3.0RC4-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    RandomThings{2.2.4} [Random Things](RandomThings-2.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    Roguelike{1.3.6} [Roguelike Dungeons](roguelike-1.7.10-1.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    TwilightForest{2.3.4} [The Twilight Forest](twilightforest-1.7.10-2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    wawla{1.1.1} [What Are We Looking At](Wawla-1.1.1_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    witchery{0.22.0} [Witchery](witchery-1.7.10-0.22.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    CoFHCore: -[1.7.10]3.0.0RC5-207
    ThermalFoundation: -[1.7.10]1.0.0RC4-58
    ThermalExpansion: -[1.7.10]4.0.0RC6-138
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    NetherOres: -[1.7.10]2.3.0RC4-10
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: ATI Mobility Radeon HD 5870 GL version 3.2.9236, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)</code>

**Comment by TherminatorX** [comment]
Does it work w/o OptiFine installed?

**Comment by Registeel1234** [comment]
I've just tried, and it still crashes even without Optifine
