### ISSUE TITLE
Client crash when adding Extrautils to a pack with Mariculture, crash stops when mariculture removed.

### ISSUE THREAD

**Issue by ProsperCraft** [rwtema/extrautilities_old_issues#59]
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 5/9/14 11:36 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
    at mariculture.fishery.items.ItemVanillaFish.func_150896_i(ItemVanillaFish.java:90)
    at net.minecraft.item.Item.func_150892_m(Item.java:626)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGeneratorPotion.genPotionLevels(TileEntityGeneratorPotion.java:22)
    at com.rwtema.extrautils.ExtraUtils.registerStuff(ExtraUtils.java:1084)
    at com.rwtema.extrautils.ExtraUtils.preInit(ExtraUtils.java:362)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:209)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:500)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:202)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at mariculture.fishery.items.ItemVanillaFish.func_150896_i(ItemVanillaFish.java:90)
    at net.minecraft.item.Item.func_150892_m(Item.java:626)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGeneratorPotion.genPotionLevels(TileEntityGeneratorPotion.java:22)
    at com.rwtema.extrautils.ExtraUtils.registerStuff(ExtraUtils.java:1084)
    at com.rwtema.extrautils.ExtraUtils.preInit(ExtraUtils.java:362)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:209)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:188)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:500)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:202)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:815)
    at net.minecraft.client.main.Main.main(SourceFile:103)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:214)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2480062568 bytes (2365 MB) / 2975334400 bytes (2837 MB) up to 2975334400 bytes (2837 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms3072m -Xmx3072m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.165.1065 Minecraft Forge 10.12.1.1065 96 mods loaded, 96 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.2.165.1065} [Forge Mod Loader](forge-1.7.2-10.12.1.1065.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.12.1.1065} [Minecraft Forge](forge-1.7.2-10.12.1.1065.jar) Unloaded->Constructed->Pre-initialized
    AppliedEnergistics2-Core{rv0-alpha-110} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997Core{1.0.2.1} [Aroma1997Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.0} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.1} [Not Enough Items](NotEnoughItems-1.7.2-1.0.1-universal.jar) Unloaded->Constructed->Pre-initialized
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FamiliarsAPI{1.7.2c} [Familiars API](FamiliarsAPI-1.7.2c.jar) Unloaded->Constructed->Pre-initialized
    battlegear2{1.0.5.4} [Mine & Blade Battlegear 2 - Bullseye](1.7.2-MB_Battlegear2-Bullseye-1.0.5.4.jar) Unloaded->Constructed->Pre-initialized
    lucky{5.0.0} [Lucky Block]([1-7-2]_Lucky_Block_v5-0-0 %281%29.jar) Unloaded->Constructed->Pre-initialized
    bspkrsCore{6.8(1.7.2)} [bspkrsCore]([1.7.2]bspkrsCore-universal-6.8%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized
    ArmorStatusHUD{1.24(1.7.2)} [ArmorStatusHUD]([1.7.2]ArmorStatusHUD-client-1.24%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{3.1.1} [Damage Indicators]([1.7.2]DamageIndicatorsMod-3.1.1.jar) Unloaded->Constructed->Pre-initialized
    TreeCapitator{1.7.2.r02} [TreeCapitator]([1.7.2]TreeCapitator-universal-1.7.2.r02.jar) Unloaded->Constructed->Pre-initialized
    tnfultimatetoolsforge{1.12.1.0} [Ultimate Tools]([1.7.2]UltimateTools - Universal by Umbrere[1.12.1.0].jar) Unloaded->Constructed->Pre-initialized
    IC2{2.1.476-experimental} [IndustrialCraft 2](industrialcraft-2-2.1.476-experimental.jar) Unloaded->Constructed->Pre-initialized
    advancedgenetics{1.5.2} [Advanced Genetics](advancedgenetics-1.5.2-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    AdvancedMachines{1.0.8} [IC2 Advanced Machines Addon](AdvancedMachinesAS-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    animalbikes{1.7.2} [Animal Bikes](AnimalBikes_1.7.2.jar) Unloaded->Constructed->Pre-initialized
    AnimationAPI{1.2.1} [AnimationAPI](AnimationAPI-1.7.2-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    antiqueatlas{4.0a-1.7.2} [Antique Atlas](antiqueatlas-4.0a-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.1.0_alpha} [Ender IO](enderio-1.1.0_alpha.50.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.2_1.7.2} [Waila](Waila-1.5.2a_1.7.2.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.2-1.6.0.jenkins478} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a14.jar) Unloaded->Constructed->Pre-initialized
    aobd{1.4.1} [Another One Bites The Dust](AOBD-1.4.1.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv0-alpha-110} [Applied Energistics 2](appliedenergistics2-rv0-alpha-110.jar) Unloaded->Constructed->Pre-initialized
    ArchimedesShips{1.7.2 v1.5.2} [Archimedes' Ships](ArchimedesShips.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997CoreHelper{1.0.2.1} [Aroma1997Core|Helper](Aroma1997Core-1.7.2-1.0.2.1.jar) Unloaded->Constructed->Pre-initialized
    AromaBackup{0.0.0.2} [AromaBackup](AromaBackup-1.7.2-0.0.0.2.jar) Unloaded->Constructed->Pre-initialized
    BattleTowers{1.4.6} [Battle Towers](BattleTowers-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    BetterChests{1.1.0.4} [BetterChests](BetterChests-1.7.2-1.1.0.4.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.6.3} [BiblioCraft](BiblioCraft[1.6.3][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized
    BiomesOPlenty{2.0.0} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.0.773-universal.jar) Unloaded->Constructed->Pre-initialized
    AWWayofTime{v1.0.0d} [AlchemicalWizardry](Blood Magic-v1.0.0d.jar) Unloaded->Constructed->Pre-initialized
    Botania{beta-29} [Botania](Botania beta-29.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.1.4} [Carpenter's Blocks](Carpenter's Blocks v3.1.4 - MC 1.7+.zip) Unloaded->Constructed->Pre-initialized
    chisel{1.5.4b} [Chisel](Chisel-1.7.2-1.5.4b.jar) Unloaded->Constructed->Pre-initialized
    CompactWindmills{1.0.3.1} [CompactWindmills](CompactWindmills-1.7.2-1.0.3.1.jar) Unloaded->Constructed->Pre-initialized
    CustomSpawner{3.2.0.dev.R1} [DrZhark's CustomSpawner](CustomMobSpawner 3.2.0-DEV-R2.zip) Unloaded->Constructed->Pre-initialized
    MoCreatures{6.2.0.dev.R1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.2.0-DEV-R2.zip) Unloaded->Constructed->Pre-initialized
    eplus{1.7.2-2.0.1.6} [Enchanting Plus](EnchantingPlus-1.7.2-2.0.1.6.jar) Unloaded->Constructed->Pre-initialized
    Enchiridion{1.0a} [Enchiridion](Enchiridion-1.7.2-1.0b.jar) Unloaded->Constructed->Pre-initialized
    enhancedbiomes{2.0.2 for MC 1.7.2} [Enhanced Biomes](Enhanced Biomes 2.0.2.1 for MC 1.7.2.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.1.0-prerelease-2} [Extra Utilities](extrautilities-1.1.0-prerelease-2.jar) Unloaded->Constructed->Errored
    FamiliarsDefaultMobPack{1.7.2b} [DefaultMobPack](FamiliarsDefaultMobPack-1.7.2b.jar) Unloaded->Constructed->Pre-initialized
    FamiliarsExtendedFamPack{1.7.2b} [ExtendedFamPack](FamiliarsExtendedFamPack-1.7.2b.jar) Unloaded->Constructed->Pre-initialized
    FamiliarsHerobrineFamPack{1.7.2b} [HerobrineFamPack](FamiliarsHerobrineFamPack-1.7.2b.jar) Unloaded->Constructed->Pre-initialized
    Forestry{2.4.0.0-711} [Forestry for Minecraft](forestry-2.4.0.0-711.jar) Unloaded->Constructed->Pre-initialized
    geoactivity{1.5} [GeoActivity](geoactivity-1.5.jar) Unloaded->Constructed->Pre-initialized
    HardcoreEnderExpansion{1.5a} [Hardcore Ender Expansion](HardcoreEnderExpansion.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.0.11} [Baubles](Baubles-1.7.2-1.0.0.11.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.1.1.12} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.12.jar) Unloaded->Constructed->Pre-initialized
    Highlands{2.2.0} [Highlands](Highlands-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    HopperDuctMod{1.3} [Hopper Ducts](hopperductmod-1.3.jar) Unloaded->Constructed->Pre-initialized
    InfernalMobs{1.5.0} [Infernal Mobs](InfernalMobs-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.4.713} [Iron Chest](Iron-Chests-Mod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    JABBA{1.1.3} [Jabba](Jabba_1.1.3_1.7.2.jar) Unloaded->Constructed->Pre-initialized
    journeymap{3.3.2} [JourneyMap Unlimited Edition](JourneyMap3.3.2_Unlimited_MC1.7.2.jar) Unloaded->Constructed->Pre-initialized
    kwastimod{1.0.5} [Kwasti Bust Monsters](KwastiMod-1.7.2-1.0.6.zip) Unloaded->Constructed->Pre-initialized
    kwastivil{1.0.7} [Kwasti Villagers](KwastiVillagersMod-1.7.2-1.0.7.jar) Unloaded->Constructed->Pre-initialized
    Lantern{2.0} [Lanterns and Flashlights](Lanterns and Flashlights-2.0.jar) Unloaded->Constructed->Pre-initialized
    LightBridgesAndDoors{0.1.9} [kris91268's Light Bridges and Doors](Light Bridges and Doors V 1.9.zip) Unloaded->Constructed->Pre-initialized
    LunatriusCore{1.0.2.7} [LunatriusCore](LunatriusCore-1.7.2-1.0.2.7-universal.jar) Unloaded->Constructed->Pre-initialized
    Mariculture{b2} [Mariculture](Mariculture-1.7.2-b2.jar) Unloaded->Constructed->Pre-initialized
    radixcore{1.1.1} [RadixCore](RadixCore-1.1.1 MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized
    mca{4.0.3} [Minecraft Comes Alive](MCA-4.0.3_MC-1.7.2.zip) Unloaded->Constructed->Pre-initialized
    meteors{2.12} [Falling Meteors](meteors-1.7.2-2.12.jar) Unloaded->Constructed->Pre-initialized
    modularfurnace{2.7.1} [Modular Furnace 2](modularfurnace-1.7.2-1.3.1.jar) Unloaded->Constructed->Pre-initialized
    MoreFurnaces{1.3.8} [More Furnaces](MoreFurnaces-1.3.8-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized
    cfm{3.2.9.2} [§6MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.2.9.2-beta-build2%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized
    MultiPageChest{1.3.1} [Multi Page Chest](MultiPageChest-1.3.1-MC1.7.2.jar) Unloaded->Constructed->Pre-initialized
    mychunkloader{172.02} [Chunkloader](mychunkloader-172.02.jar) Unloaded->Constructed->Pre-initialized
    NetherDungeons{1.2.1} [Nether Dungeons](NetherDungeons-1.7.2-v-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers|Core{1.0.0} [OpenComputers (Core)](OpenComputers-MC1.7.2-1.2.9.136-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenComputers{1.2.9.136} [OpenComputers](OpenComputers-MC1.7.2-1.2.9.136-universal.jar) Unloaded->Constructed->Pre-initialized
    OresPlus{0.6.36 Beta} [OresPlus](OresPlus-0.6.33_Beta.jar) Unloaded->Constructed->Pre-initialized
    harvestcraft{1.7.2a} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.2a.zip) Unloaded->Constructed->Pre-initialized
    randomplants{1.7.2a} [Pam's RandomPlants](Pam's Random Pants 1.7.2a.zip) Unloaded->Constructed->Pre-initialized
    PneumaticCraft{1.1.8} [PneumaticCraft](PneumaticCraft-1.1.8.jar) Unloaded->Constructed->Pre-initialized
    RedstonePasteMod{1.6.1} [Redstone Paste](RedstonePasteMod-1.7.2-1.6.1.jar) Unloaded->Constructed->Pre-initialized
    AS_Ruins{12.7} [Ruins Spawning System](Ruins-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    Schematica{1.6.1.71} [Schematica](Schematica-1.7.2-1.6.1.71-universal.jar) Unloaded->Constructed->Pre-initialized
    SlimevoidLib{2.0.4.5} [Slimevoid Library](SlimevoidLibrary-2.0.4.5.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.0.3} [The Twilight Forest](twilightforest-1.7.2-2.0.3.jar) Unloaded->Constructed->Pre-initialized
    UndergroundBiomes{0.5} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-0.5h.jar) Unloaded->Constructed->Pre-initialized
    AS_UpdateCheck{1.1.5} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.2.jar) Unloaded->Constructed->Pre-initialized
    taverns{2.2.1-0} [Village Taverns](VillageTaverns-2.2.1-0.23.jar) Unloaded->Constructed->Pre-initialized
    voxelmap{1.7.2} [VoxelMap](voxelmap-1.7.2-1.0.jar) Unloaded->Constructed->Pre-initialized
    warpbook{1.0.22} [Warp Book](warp-book-1.7.2-1.0.22.jar) Unloaded->Constructed->Pre-initialized
    weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod](weaponmod-1.14.2 %281%29.jar) Unloaded->Constructed->Pre-initialized
    YALSM{2.1.3} [Yet Another Leather Smelting Mod](yalsm-2.1.3.jar) Unloaded->Constructed->Pre-initialized
    JustAnotherSpawner{0.14.0} [Just Another Spawner](JustAnotherSpawner-0.14.5.jar) Unloaded->Constructed->Pre-initialized
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    AE2 Version: alpha rv0-alpha-110 for Forge 10.12.0.1024
    AE2 Integration: RotaryCraft:OFF, IC2:ON, RC:ON, BC:OFF, MJ:ON, RF:ON, InvTweaks:ON, MFR:ON, DSU:ON, FZ:ON, Waila:ON, RB:ON, InvTweaks:ON, NEI:ON, CraftGuide:ON, FMP:ON
    Launched Version: 1.7.2
    LWJGL: 2.9.0
    OpenGL: GeForce GT 620/PCIe/SSE2 GL version 4.4.0, NVIDIA Corporation
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: []
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null
    Anisotropic Filtering: Off (1)

**Comment by rwtema** [comment]
Issue already reported. Please check before reporting.
