### ISSUE TITLE
Client and Server Crash with "Enchant Changer" Mod

### ISSUE THREAD

**Issue by DrGatsby** [rwtema/extrautilities_old_issues#613]
Enchant Changer can be found here: https://www.dropbox.com/s/udvlpodzl7vcgq0/EnchantChanger-1.7.10-1.8.29.jar?dl=0

Log:

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 5/22/15 3:38 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: ak/EnchantChanger/tileentity/EcTileEntityMakoReactor
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:535)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:242)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: ak/EnchantChanger/tileentity/EcTileEntityMakoReactor
    at ak.EnchantChanger.EnchantChanger.preInit(EnchantChanger.java:109)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:533)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: ak.EnchantChanger.tileentity.EcTileEntityMakoReactor
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 37 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/tileentity/IEnergyInfo
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 39 more
Caused by: java.lang.ClassNotFoundException: cofh.api.tileentity.IEnergyInfo
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 43 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 208479112 bytes (198 MB) / 390066176 bytes (371 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1408 55 mods loaded, 55 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.3.1408} [Minecraft Forge](forge-1.7.10-10.13.3.1408-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv2-stable-3} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.6.44} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    AKInternalCore{1.0.1} [AKInternalCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.4.107} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.107-universal.jar) Unloaded->Constructed->Pre-initialized
    PotionExtensionCore{1.0.1} [PotionExtensionCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{0.7.3} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FamiliarsAPI{1.7.10} [Familiars API](FamiliarsAPI-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    gilded-games-util{1.7.10-1.1} [Gilded Games Utility](gilded-games-util.jar) Unloaded->Constructed->Pre-initialized
    securitycraft{v1.7.4.1} [SecurityCraft]([1.7.10] SecurityCraft v1.7.4.1.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{3.2.3} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized
    advancedgenetics{1.5.8} [Advanced Genetics](advancedgenetics-1.7.10-1.5.8.jar) Unloaded->Constructed->Pre-initialized
    aether{Alpha 1.7.10-1.4} [Aether II](aether.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv2-stable-3} [Applied Energistics 2](appliedenergistics2-rv2-stable-3.jar) Unloaded->Constructed->Pre-initialized
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized
    blastcraft{1.7.9.3} [Blastcraft](blastcraft-universal-1.7.10-1.7.9.3-build.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.4.15} [BuildCraft](buildcraft-6.4.15.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.4.15} [BC Builders](buildcraft-6.4.15.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.4.15} [BC Energy](buildcraft-6.4.15.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.4.15} [BC Factory](buildcraft-6.4.15.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.4.15} [BC Transport](buildcraft-6.4.15.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.4.15} [BC Silicon](buildcraft-6.4.15.jar) Unloaded->Constructed->Pre-initialized
    ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) Unloaded->Constructed->Pre-initialized
    craftguide{1.6.8.2} [CraftGuide](CraftGuide-1.6.8.2-forge.jar) Unloaded->Constructed->Pre-initialized
    EnchantChanger{1.7.10-1.8.29} [EnchantChanger](EnchantChanger-1.7.10-1.8.29.jar) Unloaded->Constructed->Errored
    eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) Unloaded->Constructed->Pre-initialized
    ExtraUtilities{1.2.4c} [Extra Utilities](extrautilities-1.2.4c.jar) Unloaded->Constructed->Pre-initialized
    DefaultMobPack{1.7.10} [DefaultMobPack](FamiliarsDefaultMobPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ExtendedFamPack{1.7.10} [ExtendedFamPack](FamiliarsExtendedFamPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    HerobrineFamPack{1.7.10} [HerobrineFamPack](FamiliarsHerobrineFamPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    imc{1.6} [Improving Minecraft](Improving Minecraft-1.6.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized
    ani_koto{v1.6} [Kingdoms of the Overworld Mod](Kingdoms of the Overworld-1.7.10-1.6.jar) Unloaded->Constructed->Pre-initialized
    malisiscore{1.7.10-0.11.4} [MalisisCore](malisiscore-1.7.10-0.11.4.jar) Unloaded->Constructed->Pre-initialized
    malisisadvert{1.7.10-0.2} [Malisis Advert](malisisadvert-1.7.10-0.2.jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    Mystcraft{0.11.9.03} [Mystcraft](mystcraft-1.7.10-0.11.9.03.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.7.3} [OpenMods](OpenModsLib-1.7.10-0.7.3.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.4.3} [OpenBlocks](OpenBlocks-1.7.10-1.4.3.jar) Unloaded->Constructed->Pre-initialized
    ReiMinimap{1.7.10} [Rei's Minimap](Reis-Minimap-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    rivalrebels{1.7.10J} [Rival Rebels](rivalrebels-1.7.10J.jar) Unloaded->Constructed->Pre-initialized
    Roguelike{1.3.6.3} [Roguelike Dungeons](roguelike-1.7.10-1.3.6.3.jar) Unloaded->Constructed->Pre-initialized
    scp{unspecified} [SecureCraftProtect](SecureCraftProtect-1.7.10-r141.28df7e9.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct](TConstruct-1.7.10-1.8.5.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) Unloaded->Constructed->Pre-initialized
    VersionChecker{1.1.8} [Version Checker](VersionChecker-1.1.8.jar) Unloaded->Constructed->Pre-initialized
    weaponmod{1.7.2 v1.14.2} [Balkon's WeaponMod](weaponmod-1.14.2.jar) Unloaded->Constructed->Pre-initialized
    witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized
    worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) Unloaded->Constructed->Pre-initialized
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 352.86' Renderer: 'GeForce GTX 980/PCIe/SSE2'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-3 for Forge 10.13.2.1291
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8

**Comment by DrGatsby** [comment]
Fixed by adding CoFH Core? o.o Well that works i guess... lol
