### ISSUE TITLE
there is a problem with starting my server with extrautilities

### ISSUE THREAD

**Issue by koostcrashed** [rwtema/extrautilities_old_issues#645]
it doesn crash it says that it is in incorrect state ??? what do i do

10.06 15:41:57 [Server] Server thread/ERROR [FML]: 
10.06 15:41:57 [Server] Server thread/ERROR [FML]: Fatal errors were detected during the transition from POSTINITIALIZATION to AVAILABLE. Loading cannot continue
10.06 15:41:57 [Multicraft] Skipped 107 lines due to rate limit (30/s)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:606)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventBus.post(EventBus.java:275)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:606)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at java.lang.reflect.Method.invoke(Method.java:606)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at factorization.shared.Core.modsLoaded(Core.java:232)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at factorization.common.FactoryType.getRepresentative(FactoryType.java:128)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at factorization.servo.TileEntityParaSieve.representYoSelf(TileEntityParaSieve.java:542)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at factorization.servo.TileEntityParaSieve.classifyItems(TileEntityParaSieve.java:561)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.registry.GameRegistry.findUniqueIdentifierFor(GameRegistry.java:456)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.registry.GameData.getUniqueName(GameData.java:238)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:  at cpw.mods.fml.common.registry.GameRegistry$UniqueIdentifier.<init>(GameRegistry.java:383)
10.06 15:41:55 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
10.06 15:41:55 [Server] Server thread/WARN [factorization]: Error looking up item: com.kentington.thaumichorizons.common.items.ItemGolemBellTH@74350404

**Comment by TherminatorX** [comment]
ExU is not mentioned anywhere in that.
