### ISSUE TITLE
Crashing when using extra utilities 1.2.6 and tinkers construct 1.8.5

### ISSUE THREAD

**Issue by carlobonandrini** [rwtema/extrautilities_old_issues#651]
before, with extra utilities 1.2.5 i wasn't crashing, but now i've updated extra utilities 1.2.6 and now i'm crashing

**Comment by TherminatorX** [comment]
Well, if you don't give a crash log then we can't help you at all.

**Comment by carlobonandrini** [comment]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 18/06/15 20.40
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/library/weaponry/AmmoWeapon
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
    at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/weaponry/AmmoWeapon
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:270)
    at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:42)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.weaponry.AmmoWeapon
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 36 more
Caused by: java.lang.NoClassDefFoundError: tconstruct/library/weaponry/AmmoItem
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 38 more
Caused by: java.lang.ClassNotFoundException: tconstruct.library.weaponry.AmmoItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 42 more

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.9.5
    Java Version: 1.7.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 114260120 bytes (108 MB) / 295747584 bytes (282 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 5 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 40 mods loaded, 40 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UC  Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UC  appliedenergistics2-core{rv2-stable-9} [AppliedEnergistics2 Core](minecraft.jar) 
    UC  CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UC  NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UC  VeinMiner_coremod{0.27.1_build.unknown} [Core mod](minecraft.jar) 
    UC  OpenModsCore{0.7.3} [OpenModsCore](minecraft.jar) 
    UC  battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar) 
    UC  appliedenergistics2{rv2-stable-9} [Applied Energistics 2](appliedenergistics2-rv2-stable-9.jar) 
    UC  ae2ee3emcaddon{AE2EE3Compat-1.0b2} [AE2 EE3 EMC Addon](AE2EE3Compat-1.0b2.jar) 
    UC  ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UC  EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UC  EE3{0.3.507} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.3.507.jar) 
    UC  Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UC  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UE  TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct](TConstruct-1.7.10-1.8.5.jar) 
    UC  ExtraUtilities{1.2.6} [Extra Utilities](extrautilities-1.2.6.jar) 
    UC  ExtremeToolsmod{2.0.0} [ExtremeToolsmod](ExtremeToolsmode2.0.zip) 
    UC  godweapons{2.5} [Gods' Weapons](godweapons - 1.7.10 - 2.6.jar) 
    UC  HardcoreEnderExpansion{1.7.1} [Hardcore Ender Expansion](HardcoreEnderExpansion  MC-1.7.10  v1.7.1.jar) 
    UC  iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UC  inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks](InventoryTweaks-1.59-dev-156.jar) 
    UC  JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UC  journeymap{5.0.1} [JourneyMap](JourneyMap5.0.1_Unlimited_MC1.7.10.jar) 
    UC  MSM3{3.0.0d} [More Swords 3](MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) 
    UC  NaturalAbsorption{1.2.1} [Natural Absorption](NaturalAbsorption-1.7.10-1.2.1.jar) 
    UC  OpenMods{0.7.3} [OpenMods](OpenModsLib-1.7.10-0.7.3.jar) 
    UC  OpenBlocks{1.4.3} [OpenBlocks](OpenBlocks-1.7.10-1.4.3.jar) 
    UC  OreSpawn{1.7.10.20.3} [OreSpawn](orespawn-1.7.10-20.3.zip) 
    UC  JotatosPracticalities{0.6.2} [Practicalities](practicalities-1.7.10-0.6.2.jar) 
    UC  StorageDrawers{1.7.10-1.5.6} [Storage Drawers](StorageDrawers-1.7.10-1.5.6.jar) 
    UC  dna948{1.35} [The Last Sword You Will Ever Need Mod](The_Last_Sword_You_Will_Ever_Need_Mod-1.10.jar) 
    UE  TiCTooltips{1.2.4} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.4.jar) 
    UC  Translocator{1.1.2.15} [Translocator](Translocator-1.7.10-1.1.2.15-universal.jar) 
    UC  VeinMiner{0.27.1_build.unknown} [Vein Miner](VeinMiner-1.7.10_0.27.1.unknown.jar) 
    UC  VeinMinerModSupport{0.27.1_build.unknown} [Mod Support](VeinMiner-1.7.10_0.27.1.unknown.jar) 
    UC  VersionChecker{1.1.9} [Version Checker](VersionChecker-1.1.9.jar) 
    UC  wawla{1.2.1} [What Are We Looking At](Wawla-1.2.1_1.7.10.jar) 
    UE  IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-8.26.29 310.40.55f01' Renderer: 'NVIDIA GeForce GTX 675MX OpenGL Engine'
    OpenModsLib class transformers: [gl_capabilities_hook:FINISHED],[player_render_hook:ENABLED],[map_gen_fix:ENABLED],[movement_callback:FINISHED],[stencil_patches:FINISHED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-9 for Forge 10.13.2.1291
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.

**Comment by carlobonandrini** [comment]
this is there crash report

**Comment by carlobonandrini** [comment]
I gave you the crash report, and now?

**Comment by TherminatorX** [comment]
How did you get that report? It looks only vaguely like a MC crash log.

**Comment by Robijnvogel** [comment]
Please... why is this closed?
A lot of people are having this problem and are spamming the TiC thread on the minecraft forums.
The TiC API in Extra Utilities is (probably) outdated so please update it in the next release of Extra Utilities (if this hasn't been done already). This has been mentioned on the Extra Utilities thread as well by the way (linking back to my post on the TiC thread).

By the way, that is exactly how a crash report looks. The newer Forge versions just changed the last part a bit to save space.

**Comment by TherminatorX** [comment]
@Robijnvogel Bah, humbug. They should have a config to revert the changes.
