### ISSUE TITLE
Crash with TCon and Extra Utilities

### ISSUE THREAD

**Issue by ArukaAlter** [rwtema/extrautilities_old_issues#653]
https://github.com/SlimeKnights/TinkersConstruct/issues/1662

**Comment by carlobonandrini** [comment]
Yes i have the same problem

**Comment by Normal69** [comment]
Something is fishy about liquid bedrock - I have CofhCore installed.

java.lang.IllegalAccessError: tried to access field net.minecraft.client.Minecraft.field_110450_ap from class com.rwtema.extrautils.modintegration.TConTextureResourcePackBedrockium
at com.rwtema.extrautils.modintegration.TConTextureResourcePackBedrockium.getBedrockImage(TConTextureResourcePackBedrockium.java:60)
at com.rwtema.extrautils.texture.TextureBedrockLava.processImage(TextureBedrockLava.java:30)
at com.rwtema.extrautils.texture.TextureDerived.load(TextureDerived.java:77)
at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:174)
at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:124)
at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:94)
at net.minecraft.client.renderer.texture.TextureManager.func_110580_a(TextureManager.java:76)
at net.minecraft.client.renderer.texture.TextureManager.func_130088_a(TextureManager.java:63)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:537)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
at net.minecraft.client.main.Main.main(SourceFile:148)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
at org.multimc.EntryPoint.listen(EntryPoint.java:170)
at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by SuperSandro2000** [comment]
Realy anoing crash. I would love to use the new tinker toys.

**Comment by ArukaAlter** [comment]
C'mon, just refer to the original issue '-'
