### ISSUE TITLE
Crash on Creative Search

### ISSUE THREAD

**Issue by SonarSonic** [rwtema/extrautilities_old_issues#654]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 20/06/15 17:09
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
    at codechicken.microblock.BlockMicroMaterial.getLocalizedName(BlockMicroMaterial.scala:89)
    at com.rwtema.extrautils.multipart.microblock.ItemMicroBlock.func_77653_i(ItemMicroBlock.java:58)
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:489)

**Comment by TherminatorX** [comment]
Duplicate

**Comment by abidoang** [comment]
@TherminatorX could you reference the original issue report? I also have this problem.

**Comment by TherminatorX** [comment]
The search function is really useful for making sure one doesn't create dupe issues.

In #620, a crashlog with the same exact text can be found.
