### ISSUE TITLE
Edged Stone Bricks - Render crash

### ISSUE THREAD

**Issue by Sir-Will** [rwtema/extrautilities_old_issues#656]
extrautilities-1.2.5

```
java.lang.ArrayIndexOutOfBoundsException: -1
    at net.minecraft.world.chunk.Chunk.func_150810_a(Chunk.java:511)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:842)
    at net.minecraft.world.ChunkCache.func_147438_o(ChunkCache.java:97)
    at com.rwtema.extrautils.multipart.FakeRenderBlocksMultiPart.matchBlock(FakeRenderBlocksMultiPart.java:51)
    at com.rwtema.extrautils.block.render.FakeRenderBlocks.getType(FakeRenderBlocks.java:150)
    at com.rwtema.extrautils.block.render.FakeRenderBlocks.renderSide(FakeRenderBlocks.java:69)
    at com.rwtema.extrautils.block.render.FakeRenderBlocks.func_147761_c(FakeRenderBlocks.java:211)
    at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4667)
    at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
    at com.rwtema.extrautils.block.render.RenderBlockConnectedTextures.renderWorldBlock(RenderBlockConnectedTextures.java:99)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.minecraft.world.chunk.Chunk.func_150810_a(Chunk.java:511)
    at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:842)
    at net.minecraft.world.ChunkCache.func_147438_o(ChunkCache.java:97)
    at com.rwtema.extrautils.multipart.FakeRenderBlocksMultiPart.matchBlock(FakeRenderBlocksMultiPart.java:51)
    at com.rwtema.extrautils.block.render.FakeRenderBlocks.getType(FakeRenderBlocks.java:150)
    at com.rwtema.extrautils.block.render.FakeRenderBlocks.renderSide(FakeRenderBlocks.java:69)
    at com.rwtema.extrautils.block.render.FakeRenderBlocks.func_147761_c(FakeRenderBlocks.java:211)
    at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4667)
    at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
    at com.rwtema.extrautils.block.render.RenderBlockConnectedTextures.renderWorldBlock(RenderBlockConnectedTextures.java:99)
    at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
    at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
    at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
    at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
    at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
```

**Comment by TherminatorX** [comment]
Entire crash log, please, hosted on pastebin or Gist.

**Comment by Sir-Will** [comment]
The other stuff is only PC specs but well here: http://pastebin.com/G2LTPc35

**Comment by TherminatorX** [comment]
There we go. But yes, always post the entire crash log, even if parts seem irrelevant.
Now, how did this issue occur? Can you replicate it?

**Comment by Sir-Will** [comment]
I don't know how it happened and I couldn't reproduce it yet. Probably requires a specific other block next to it.

**Comment by leagris** [comment]
This issue is caused by placing Edged Stone at y=0 or y=255.
Client crash while trying to get neighbor block to render connected edge or not.
Reproduced with ExtraUtilities 1.2.12

Crash Log: http://pastebin.com/fkVzF1YA
