### ISSUE TITLE
Enderquarry-particles terminate connection

### ISSUE THREAD

**Issue by TechnicianLP** [rwtema/extrautilities_old_issues#715]
It Disconects me from the server saying that the connection is terminated evrytime i come to near to an active enderquarry
log from client (on server nothing happens) 

something similiar happens when rightclicking on a finished quarry

[00:49:35] [Client thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught 
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(8785) exceeds writerIndex(23): SlicedByteBuf(ridx: 4, widx: 23, cap: 23/23, unwrapped: UnpooledHeapByteBuf(ridx: 1, widx: 24, cap: 24/24)) 
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?] 
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?] 
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?] 
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?] 
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?] 
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?] 
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?] 
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?] 
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?] 
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?] 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] 
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51] 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51] 
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51] 
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?] 
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?] 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(8785) exceeds writerIndex(23): SlicedByteBuf(ridx: 4, widx: 23, cap: 23/23, unwrapped: UnpooledHeapByteBuf(ridx: 1, widx: 24, cap: 24/24)) 
at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1160) ~[AbstractByteBuf.class:?] 
at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:668) ~[AbstractByteBuf.class:?] 
at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:676) ~[AbstractByteBuf.class:?] 
at com.rwtema.extrautils.network.XUPacketBase.readString(XUPacketBase.java:62) ~[XUPacketBase.class:?] 
at com.rwtema.extrautils.network.XUPacketBase.readChatComponent(XUPacketBase.java:35) ~[XUPacketBase.class:?] 
at com.rwtema.extrautils.network.packets.PacketTempChatMultiline.readData(PacketTempChatMultiline.java:52) ~[PacketTempChatMultiline.class:?] 
at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:49) ~[PacketCodec.class:?] 
at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:17) ~[PacketCodec.class:?] 
at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?] 
at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?] 
at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?] 
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?] 
... 18 more 
[00:49:35] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel XU|Pkt 
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(8785) exceeds writerIndex(23): SlicedByteBuf(ridx: 4, widx: 23, cap: 23/23, unwrapped: UnpooledHeapByteBuf(ridx: 1, widx: 24, cap: 24/24)) 
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?] 
at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?] 
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?] 
at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?] 
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?] 
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?] 
at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?] 
at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?] 
at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?] 
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?] 
at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?] 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] 
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51] 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51] 
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51] 
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?] 
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?] 
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(4) + length(8785) exceeds writerIndex(23): SlicedByteBuf(ridx: 4, widx: 23, cap: 23/23, unwrapped: UnpooledHeapByteBuf(ridx: 1, widx: 24, cap: 24/24)) 
at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1160) ~[AbstractByteBuf.class:?] 
at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:668) ~[AbstractByteBuf.class:?] 
at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:676) ~[AbstractByteBuf.class:?] 
at com.rwtema.extrautils.network.XUPacketBase.readString(XUPacketBase.java:62) ~[XUPacketBase.class:?] 
at com.rwtema.extrautils.network.XUPacketBase.readChatComponent(XUPacketBase.java:35) ~[XUPacketBase.class:?] 
at com.rwtema.extrautils.network.packets.PacketTempChatMultiline.readData(PacketTempChatMultiline.java:52) ~[PacketTempChatMultiline.class:?] 
at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:49) ~[PacketCodec.class:?] 
at com.rwtema.extrautils.network.PacketCodec.decodeInto(PacketCodec.java:17) ~[PacketCodec.class:?] 
at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:77) ~[FMLIndexedMessageToMessageCodec.class:?] 
at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?] 
at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?] 
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?] 
... 18 more

**Comment by mlard811** [comment]
This is happening with my server as well and our client logs look very similar.  The problem I am having is identifying where this problem is coming from. In a single player test I could not get this problem to occur.  I'm inclined to believe the problem lies with the server, perhaps with kcauldron? I just don't know.  Did you ever find anything about this?

**Comment by TechnicianLP** [comment]
seems to be related to out mcpc version somehow but not confirmed (why would mcpc lead to byte-loss? ...)

**Comment by TechnicianLP** [comment]
After talking back to some Guys of another Server they told us it is related to the forge version being too new (for the ExU in Infinity)

**Comment by Slind14** [comment]
```
Build 1.7.10-10.13.4.1490-1.7.10:
    cpw: Actually rebuild the fluidNames each rebuild, don't just try and force changes in. Should fix #1973
    cpw:
        Wake up the FluidRegistry before any mods start loading. Should stop mods claiming to own water or lava (depending on who accessed
        FluidRegistry first)
    cpw: Be a little bit more helpful when the ObjectHolder misses. Should help figure out what is going in in #2006
```

The forge version from before this change should work.
