### ISSUE TITLE
Wither Spawn Sound crashes game.

### ISSUE THREAD

**Issue by bradleyshrader** [rwtema/extrautilities_old_issues#733]
When using iChun's ding, setting the load sound to mob.wither.spawn will cause the game to crash even when the Extra Utilities config setting to disable wither sounds is disabled.
(Irrelevant but obligatory: Fastcraft is enabled)

> java.lang.NullPointerException: Initializing game
>   at com.rwtema.extrautils.EventHandlerClient.witherSoundKilling(EventHandlerClient.java:562)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler_880_EventHandlerClient_witherSoundKilling_PlaySoundEvent17.invoke(.dynamic)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
>   at net.minecraftforge.client.ForgeHooksClient.playSound(ForgeHooksClient.java:466)
>   at net.minecraft.client.audio.SoundManager.func_148611_c(SoundManager.java:311)
>   at net.minecraft.client.audio.SoundHandler.func_147682_a(SourceFile:154)
>   at us.ichun.mods.ding.common.core.Ding.onGuiOpen(Ding.java:64)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler_282_Ding_onGuiOpen_GuiOpenEvent.invoke(.dynamic)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
>   at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:786)
>   at com.gildedgames.util.menu.client.MenuClientEvents.openMenu(MenuClientEvents.java:89)
>   at com.gildedgames.util.menu.client.MenuClientEvents.onGuiOpen(MenuClientEvents.java:140)
>     at cpw.mods.fml.common.eventhandler.ASMEventHandler_20_MenuClientEvents_onGuiOpen_GuiOpenEvent.invoke(.dynamic)
>   at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
>   at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
>   at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:786)
>   at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:562)
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
>   at net.minecraft.client.main.Main.main(SourceFile:148)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:483)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by bradleyshrader** [comment]
Correction: config setting reset itself to default. It works when config is disabled, but crashes when enabled.
