### ISSUE TITLE
Server Crash in 1.7.10 with ExtraUtilities 1.2.11 and TwilightForest 2.3.7

### ISSUE THREAD

**Issue by ExDomino** [rwtema/extrautilities_old_issues#743]
Look like a TwilightForest bug that its author reported that's an ExtraUtilities bug:
https://github.com/Benimatic/twilightforest/issues/35#issuecomment-143639266

Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
at twilightforest.world.TFGenWitchHut.generateTinyHut(TFGenWitchHut.java:180)
at twilightforest.world.TFGenWitchHut.func_76484_a(TFGenWitchHut.java:18)
at twilightforest.biomes.TFBiomeDecorator.func_150513_a(TFBiomeDecorator.java:158)
at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:114)
at twilightforest.biomes.TFBiomeDecorator.func_150512_a(TFBiomeDecorator.java:139)
at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
at twilightforest.biomes.TFBiomeFireSwamp.func_76728_a(TFBiomeFireSwamp.java:63)
at net.minecraft.world.gen.ChunkProviderFlat.func_73153_a(SourceFile:162)
at com.rwtema.extrautils.worldgen.Underdark.ChunkProviderUnderdark.func_73153_a(ChunkProviderUnderdark.java:50)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:384)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:269)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:189)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:157)
at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:280)
at net.minecraft.world.World.func_72964_e(World.java:751)
at net.minecraft.world.World.func_147439_a(World.java:677)
at mods.natura.worldgen.CloudGen.func_76484_a(CloudGen.java:44)
at mods.natura.worldgen.BaseCloudWorldgen.generate(BaseCloudWorldgen.java:68)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:414)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:269)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:189)
at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:157)
at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:280)
at net.minecraft.world.World.func_72964_e(World.java:751)
at net.minecraft.world.World.func_147439_a(World.java:677)
at net.minecraft.world.World.func_147437_c(World.java:697)
at mods.natura.worldgen.BaseCropWorldgen.generateBarley(BaseCropWorldgen.java:147)
at mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:46)
at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:137)
at com.rwtema.extrautils.worldgen.Underdark.ChunkProviderUnderdark.func_73153_a(ChunkProviderUnderdark.java:56)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:384)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1160)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:62)
at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15)
at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189)
at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354)
at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
at java.lang.Thread.run(Thread.java:745)

**Comment by callous4567** [comment]
I've the issue atm.

**Comment by HoNGamer** [comment]
Same Issue here

**Comment by Benimatic** [comment]
Does anyone have instructions to reproduce? I think I have a fix for this in the works, but I'd like to test it.

**Comment by HoNGamer** [comment]
sadly no. it happened randomly to me

**Comment by NicosaurusRex99** [comment]
@Benimatic i loaded up a world moved over to the first twilight boss and then i crashed

**Comment by Blue64** [comment]
I believe I see the problem, it appears to be a World Gen Issue with the UnderDark Dimension Generating a Biome that is trying to produce a Witch Hut

>  at twilightforest.world.TFGenWitchHut.generateTinyHut(TFGenWitchHut.java:180)
> at twilightforest.world.TFGenWitchHut.func_76484_a(TFGenWitchHut.java:18)
> at twilightforest.biomes.TFBiomeDecorator.func_150513_a(TFBiomeDecorator.java:158)
> at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:114)
> at twilightforest.biomes.TFBiomeDecorator.func_150512_a(TFBiomeDecorator.java:139)
> at net.minecraft.world.biome.BiomeGenBase.func_76728_a(BiomeGenBase.java:339)
> at twilightforest.biomes.TFBiomeFireSwamp.func_76728_a(TFBiomeFireSwamp.java:63)
> at net.minecraft.world.gen.ChunkProviderFlat.func_73153_a(SourceFile:162)
> at com.rwtema.extrautils.worldgen.Underdark.ChunkProviderUnderdark.func_73153_a(ChunkProviderUnderdark.java:50)

or, without the gobelty gook:

> twilightforest > world > TFGenWitchHut > generateTinyHut
> twilightforest > world > TFGenWitchHut
> twilightforest > biomes > TFBiomeDecorator
> twilightforest > biomes > TFBiomeFireSwamp
> extrautils > worldgen > Underdark

like I said, Underdark generating Biome trying to spawn a Witch Hut.

**Comment by Blue64** [comment]
We also haven't really ruled out Natura as a possible culprit have we? Since it's also listed in the displayed Stacktrace.
