### ISSUE TITLE
Crash about Extra Utilities

### ISSUE THREAD

**Issue by Call0TheWildMan** [rwtema/extrautilities_old_issues#763]
I had a crash with these mod including Extra Utilities:

Chimneys
Bibliocraft
Carpenters Blocks
Catwalks 
Clearing Block
Craft guide
Gollum Core
Hopperduct
Little Blocks
More Pistons
Mr.CrayFish's Furniture 
Optifine 1.8.0 HD U D5
RedStone Paste
Slimevoid Library
VoxelMap No radar

---

I don't know if you have an incompatibility with these mods so that's why I'm  posting them here.

The Crash said something like this:
 java.lang.IllegalAccessError: tried to access class net.minecraft.world.WorldProviderEnd from class net.minecraftforge.common.DimensionManage

But the whole crash report is below:

[09:15:47] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[09:15:48] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
[09:15:48] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
[09:15:49] [main/INFO] [FML]: Forge Mod Loader version 7.99.30.1492 for Minecraft 1.7.10 loading
[09:15:49] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[09:15:49] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.8.0_HD_U_D5.jar
[09:15:49] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:15:49] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[09:15:49] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[09:15:49] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:15:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:15:50] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[09:15:50] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: acceptOptions
[09:15:50] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: injectIntoClassLoader
[09:15:50] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ClassTransformer
[09:15:50] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine URL: file:/C:/Users/Max-Well/AppData/Roaming/.minecraft/mods/OptiFine_1.8.0_HD_U_D5.jar
[09:15:50] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:179]: OptiFine ZIP file: java.util.zip.ZipFile@42d8062c
[09:15:50] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:16:01] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[09:16:01] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[09:16:01] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:16:01] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[09:16:09] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[09:16:09] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[09:16:09] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:49]: OptiFineForgeTweaker: getLaunchArguments
[09:16:09] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[09:16:19] [main/INFO]: Setting user: TheLumberJackMC
[09:16:33] [main/INFO] [STDOUT]: [net.minecraft.client.main.Main:main:144]: Completely ignored arguments: [--nativeLauncherVersion, 286]
[09:16:35] [Client thread/INFO]: LWJGL Version: 2.9.1
[09:16:43] [Client thread/ERROR]: Couldn't initialize twitch stream
[09:16:48] [Client thread/INFO] [FML]: Forge Mod Loader has detected optifine OptiFine_1.8_HD_U_D5, enabling compatibility features
[09:16:48] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[09:16:48] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1492 Initialized
[09:16:49] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[09:16:49] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[09:16:52] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[09:16:52] [Client thread/INFO] [FML]: Searching C:\Users\Max-Well\AppData\Roaming.minecraft\mods for mods
[09:18:13] [Client thread/WARN] [ExtraUtilities]: Mod ExtraUtilities is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.11
[09:18:16] [Client thread/INFO] [FML]: Forge Mod Loader has identified 19 mods to load
[09:18:16] [Client thread/INFO] [FML]: Found mod(s) [catwalks, catwalkmod] containing declared API package buildcraft.api.tools (owned by BuildCraftAPI|core) without associated API reference
[09:18:21] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, Chimneys, BiblioCraft, CarpentersBlocks, catwalks, catwalkmod, clearingblock, craftguide, ExtraUtilities, GollumCoreLib, HopperDuctMod, LittleBlocks, MorePistons, cfm, RedstonePasteMod, SlimevoidLib, voxelmap] at CLIENT
[09:18:21] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, Chimneys, BiblioCraft, CarpentersBlocks, catwalks, catwalkmod, clearingblock, craftguide, ExtraUtilities, GollumCoreLib, HopperDuctMod, LittleBlocks, MorePistons, cfm, RedstonePasteMod, SlimevoidLib, voxelmap] at SERVER
[09:18:29] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Chimneys, FMLFileResourcePack:BiblioCraft, FMLFileResourcePack:Carpenter's Blocks, FMLFileResourcePack:Catwalks Mod, FMLFileResourcePack:Legacy Catwalk Compat, FMLFileResourcePack:ClearingBlock Mod, FMLFileResourcePack:CraftGuide, FMLFileResourcePack:Extra Utilities, FMLFileResourcePack:Gollum Core Lib, FMLFileResourcePack:Hopper Ducts, FMLFileResourcePack:Little Blocks, FMLFileResourcePack:More Pistons, FMLFileResourcePack:§9MrCrayfish's Furniture Mod, FMLFileResourcePack:Redstone Paste, FMLFileResourcePack:Slimevoid Library, FMLFileResourcePack:VoxelMap No Radar
[09:18:29] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[09:18:29] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[09:18:29] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[09:18:29] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[09:18:30] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[09:18:36] [Client thread/INFO] [CarpentersBlocks]: Designs found: Bed(6), Chisel(9), FlowerPot(18), Tile(13)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class resonant.core.content.ItemScrewdriver (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class ic2.core.item.tool.ItemToolWrench (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class ic2.core.item.tool.ItemToolWrenchElectric (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class mrtjp.projectred.api.IScrewdriver (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class mods.railcraft.api.core.items.IToolCrowbar (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class com.bluepowermod.items.ItemScrewdriver (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class appeng.items.tools.quartz.ToolQuartzWrench (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class crazypants.enderio.api.tool.ITool (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class mekanism.api.IMekWrench (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class mcjty.rftools.items.smartwrench (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class pneumaticCraft.common.item.ItemPneumaticWrench (this is not an error)
[09:18:36] [Client thread/INFO] [Catwalks]: Failed to load wrench class powercrystals.minefactoryreloaded.api.IToolHammer (this is not an error)
[09:18:40] [Client thread/INFO] [extrautils]: Hello World
[09:18:42] [Client thread/WARN] [FML]: =============================================================
[09:18:42] [Client thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[09:18:42] [Client thread/WARN] [FML]: Offendor: mods/gollum/core/common/context/ModContext.getCurrent()Lmods/gollum/core/common/mod/GollumMod;
[09:18:42] [Client thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[09:18:42] [Client thread/WARN] [FML]: =============================================================
[09:18:42] [Client thread/WARN] [FML]: =============================================================
[09:18:42] [Client thread/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[09:18:42] [Client thread/WARN] [FML]: Offendor: mods/gollum/core/common/context/ModContext.setCurrent(Lmods/gollum/core/common/mod/GollumMod;)Lmods/gollum/core/common/context/ModContext;
[09:18:42] [Client thread/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[09:18:42] [Client thread/WARN] [FML]: =============================================================
Oct 13, 2015 9:18:43 AM mods.gollum.core.common.log.Logger log
INFO: Read config : GollumCoreLib//GollumCoreLib.cfg
[09:18:45] [Client thread/INFO] [FML]: [LittleBlocks] Registering names...
[09:18:45] [Client thread/INFO] [STDOUT]: [net.slimevoid.library.data.Logger$LoggerWriter:<init>:170]: C:\Users\Max-Well\AppData\Roaming.minecraft\SVLib.log
[09:18:45] [Client thread/INFO] [FML]: [LittleBlocks] Registering items...
[09:18:45] [Client thread/INFO] [FML]: [LittleBlocks] Registering blocks...
[09:18:47] [Client thread/INFO] [FML]: Applying holder lookups
[09:18:47] [Client thread/INFO] [FML]: Holder lookups applied
[09:18:47] [Client thread/INFO] [FML]: Injecting itemstacks
[09:18:47] [Client thread/INFO] [FML]: Itemstack injection complete
[09:18:47] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION. Loading cannot continue
[09:18:47] [Client thread/ERROR] [FML]: 
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCH Forge{10.13.4.1492} [Minecraft Forge](forge-1.7.10-10.13.4.1492-1.7.10.jar) 
    UCH Chimneys{1.7.2} [Chimneys]([1.7.10]Chimneys.jar) 
    UCH BiblioCraft{1.11.2} [BiblioCraft](BiblioCraft[v1.11.2][MC1.7.10].jar) 
    UCH CarpentersBlocks{3.3.8_dev_r1} [Carpenter's Blocks](Carpenter's Blocks v3.3.8_dev_r1 - MC 1.7.10.jar) 
    UCH catwalks{2.0.2} [Catwalks Mod](catwalks-2.0.2.jar) 
    UCH catwalkmod{x.x.x} [Legacy Catwalk Compat](catwalks-2.0.2.jar) 
    UCH clearingblock{0.3} [ClearingBlock Mod](Clearing Block Mod-0.3.jar) 
    UCH craftguide{1.6.8.1} [CraftGuide](CraftGuide-Mod-1.7.10.jar) 
    UCE ExtraUtilities{1.2.11} [Extra Utilities](extrautilities-1.2.11.jar) 
    UCH GollumCoreLib{2.0.0} [Gollum Core Lib](Gollum_Core_Lib.1.7.10-2.0.0Beta1.0.jar) 
    UCH HopperDuctMod{1.3.2} [Hopper Ducts](hopperductmod-1.7.10-1.3.2.jar) 
    UCH SlimevoidLib{2.0.4.7} [Slimevoid Library](SlimevoidLibrary-2.0.4.7.jar) 
    UCH LittleBlocks{2.2.4.4} [Little Blocks](LittleBlocks-2.2.4.4.jar) 
    UCH MorePistons{2.0.0 Beta 1.0} [More Pistons](More_Pistons-1.7.10-2.0.0Beta1.0.jar) 
    UCH cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.jar) 
    UCH RedstonePasteMod{1.6.2} [Redstone Paste](RedstonePasteMod-1.7.10-1.6.2.jar) 
    UCH voxelmap{1.7.10} [VoxelMap No Radar](voxelmapNoRadar-1.7.10-1.0.jar) 
[09:18:47] [Client thread/ERROR] [FML]: The following problems were captured during this phase
[09:18:47] [Client thread/ERROR] [FML]: Caught exception from ExtraUtilities
java.lang.IllegalAccessError: tried to access class net.minecraft.world.WorldProviderEnd from class net.minecraftforge.common.DimensionManager
    at net.minecraftforge.common.DimensionManager.init(DimensionManager.java:104) ~[DimensionManager.class:?]
    at net.minecraftforge.common.DimensionManager.<clinit>(DimensionManager.java:274) ~[DimensionManager.class:?]
    at com.rwtema.extrautils.ExtraUtils.registerStuff(ExtraUtils.java:1138) ~[ExtraUtils.class:?]
    at com.rwtema.extrautils.ExtraUtils.preInit(ExtraUtils.java:539) ~[ExtraUtils.class:?]
    at com.rwtema.extrautils.ExtraUtilsMod.preInit(ExtraUtilsMod.java:23) ~[ExtraUtilsMod.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[forge-1.7.10-10.13.4.1492-1.7.10.jar:?]
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[forge-1.7.10-10.13.4.1492-1.7.10.jar:?]
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[forge-1.7.10-10.13.4.1492-1.7.10.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556) [Loader.class:?]
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[09:18:47] [Client thread/ERROR] [LaunchWrapper]: Unable to launch
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.crash.CrashReport$8.<init>(Lnet/minecraft/crash/CrashReport;Ljava/lang/String;)V
    at net.minecraft.crash.CrashReport.<init>(CrashReport.java:36) ~[b.class:?]
    at net.minecraft.crash.CrashReport.func_85055_a(CrashReport.java:432) ~[b.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:882) ~[bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) ~[Main.class:?]
    ... 6 more
Exception in thread "Client thread" [09:18:47] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[09:18:47] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:25)
[09:18:47] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[09:18:47] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.Runtime.exit(Runtime.java:107)
[09:18:47] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at java.lang.System.exit(System.java:968)
[09:18:47] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[09:18:47] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:     at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MBfromOK** [comment]
Have you tried this with OptiFine disabled?
