### ISSUE TITLE
Spawn over a Deep Dark Portal crash the Game

### ISSUE THREAD

**Issue by Dream-Master** [rwtema/extrautilities_old_issues#775]
On my private Server one Player get the following Problem. Every time he log in he get kicked and this is written in the fml log.

https://gist.github.com/Dream-Master/a7a43970c401a8717a9d#file-ender-io

The Problem says it have something to do with Entity ID 30 (in my case Lava Monsters but i delete this Mod all ready and it crash again without Entity ID 30) but i found out that when you returned from the Deep Dark Dimension to the Overworld you crash. Every Time you log in you crash again. Other Peoples Crash too. Delete the Player dat helps to entering this Area with the Portal and after i remove the Portal no one crash.

But now my Question how i can using the Portal Blocks ?
(I using Player API 1.4)

This is the Issue i posted on Ender IOs Page:
https://github.com/SleepyTrousers/EnderIO/issues/3039

My Modpack:

https://github.com/GTNewHorizons/NewHorizons

I know this crash Sound really weird but i hope someone can have a solution for it.

Here is a Entity Dump with nei.
[neiintegration_entity.txt](https://github.com/SleepyTrousers/EnderIO/files/44213/neiintegration_entity.txt)

This is the error on the Server log

```
[18:49:37] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
    at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:234) [mn.class:?]
    at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:404) [EntityRegistry.class:1.7.10-1492.150]
    at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:62) [mn.class:?]
    at net.minecraft.world.WorldManager.func_72703_a(WorldManager.java:28) [mp.class:?]
    at net.minecraft.world.World.func_72923_a(World.java:1832) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:1086) [mt.class:?]
    at net.minecraft.world.World.func_72868_a(World.java:3964) [ahb.class:?]
    at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:1020) [apx.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:49) [ChunkIOProvider.class:1.7.10-1492.150]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1492.150]
    at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:1.7.10-1492.150]
    at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:1.7.10-1492.150]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:1.7.10-1492.150]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:885) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
    at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:198) ~[mn.class:?]
    ... 17 more`
```

Using Ender IO 420

fml log (part)

```
[20:34:05] [Client thread/ERROR] [FML/]: HandshakeCompletionHandler exception
java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 30 at ( 749.625,84.0, -275.75) Please contact mod author or server admin.
    at cpw.mods.fml.common.network.internal.EntitySpawnHandler.spawnEntity(EntitySpawnHandler.java:64) ~[EntitySpawnHandler.class:?]
    at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:34) ~[EntitySpawnHandler.class:?]
    at cpw.mods.fml.common.network.internal.EntitySpawnHandler.channelRead0(EntitySpawnHandler.java:28) ~[EntitySpawnHandler.class:?]
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
    at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
    at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_40]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_40]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_40]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[20:34:05] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel FML

```

It not crash the Game so no crash Log available sorry

**Comment by Blue64** [comment]
it looks like it's trying to spawn an Ender IO Entity with the ID 30, my suggestion would be to assign an Ender IO Mob to ID 30 and then remove the mob/mod and re-implement it, might delete a lot of Ender IO setup, but it would fix this problem (probably) and avoid needing a Rollback to before the Error showed up at those coordinates

> `java.lang.RuntimeException: Could not spawn mod entity ModID: EnderIO EntityID: 30 at ( 749.625,84.0, -275.75) Please contact mod author or server admin.`

**Comment by ktole1999** [comment]
is this old issue where its trying to spawn wither and cant so it crashes.

**Comment by Blue64** [comment]
I'm not entirely sure, my MineCraft is currently down for ModPack Maintenance (adding more Mods), so it's going to be a while until I get things up and running to be capable of checking. I'm not entirely sure what exactly `Ender IO Entity ID 30` is.
