### ISSUE TITLE
Ender Quarry have memory leak

### ISSUE THREAD

**Issue by DBotThePony** [rwtema/extrautilities_old_issues#794]
If i start Ender Quarry with big sizes, server would just crash because out of memory

Quarry mines at maximal speed (supplied with ~900 000+ RF/t) with Silk Touch and Effiency III upgrades installed.

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.lang.SecurityManager.checkPackageAccess(Unknown Source)
    at java.lang.Class.checkPackageAccess(Unknown Source)
    at java.lang.Class.checkMemberAccess(Unknown Source)
    at java.lang.Class.getDeclaredMethod(Unknown Source)
    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:66)
    at portablejim.veinminer.core.MinerInstance.<init>(MinerInstance.java:104)
    at portablejim.veinminer.core.InjectedCalls.blockMined(InjectedCalls.java:67)
    at portablejim.veinminer.VeinMiner.blockBreakEventTrue(VeinMiner.java:300)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_431_VeinMiner_blockBreakEventTrue_HarvestDropsEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:162)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.harvestBlock(TileEntityEnderQuarry.java:658)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.mineBlock(TileEntityEnderQuarry.java:560)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.func_145845_h(TileEntityEnderQuarry.java:381)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

```
-- Head --
Stacktrace:
    at java.lang.SecurityManager.checkPackageAccess(Unknown Source)
    at java.lang.Class.checkPackageAccess(Unknown Source)
    at java.lang.Class.checkMemberAccess(Unknown Source)
    at java.lang.Class.getDeclaredMethod(Unknown Source)
    at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:66)
    at portablejim.veinminer.core.MinerInstance.<init>(MinerInstance.java:104)
    at portablejim.veinminer.core.InjectedCalls.blockMined(InjectedCalls.java:67)
    at portablejim.veinminer.VeinMiner.blockBreakEventTrue(VeinMiner.java:300)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_431_VeinMiner_blockBreakEventTrue_HarvestDropsEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:162)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.harvestBlock(TileEntityEnderQuarry.java:658)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.mineBlock(TileEntityEnderQuarry.java:560)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.func_145845_h(TileEntityEnderQuarry.java:381)

-- Block entity being ticked --
Details:
    Name: enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry
    Block type: ID #1286 (tile.extrautils:enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.BlockEnderQuarry)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (2506,94,2488), Chunk: (at 10,5,8 in 156,155; contains blocks 2496,0,2480 to 2511,255,2495), Region: (4,4; contains chunks 128,128 to 159,159, blocks 2048,0,2048 to 2559,255,2559)
    Actual block type: ID #1286 (tile.extrautils:enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.BlockEnderQuarry)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
```

If the problem might come from VeinMiner, here it is https://github.com/portablejim/VeinMiner

**Comment by Entoarox** [comment]
Its due to how ender quarry breaks blocks causing veinminer event to be triggered, not a bug in ender quarry, but a veinminer issue (Players breaking blocks equally fast would cause the same issue)
So a complete veinminer issue, you just dont notice it cause no player on your server is mass-mining manually.

**Comment by DBotThePony** [comment]
Okay, i will reopen this on veinminer repo
