### ISSUE TITLE
[1.7.10] ConcurrentModificationException crash with EnderCollector

### ISSUE THREAD

**Issue by TATDK** [rwtema/extrautilities_old_issues#800]
```
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at com.rwtema.extrautils.tileentity.endercollector.CollectorHandler.onEntityJoinWorld(CollectorHandler.java:72)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1086_CollectorHandler_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.world.World.func_72868_a(World.java:3301)
    at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
    at net.minecraft.world.World.func_72964_e(World.java:419)
    at net.minecraft.world.World.func_147439_a(World.java:345)
    at net.minecraft.world.World.func_72849_a(World.java:771)
    at net.minecraft.world.World.func_72957_l(World.java:764)
    at net.minecraft.world.World.func_72801_o(World.java:1014)
    at net.minecraft.entity.monster.EntityMob.func_70783_a(SourceFile:132)
    at net.minecraft.entity.ai.RandomPositionGenerator.func_75462_c(SourceFile:55)
    at net.minecraft.entity.ai.RandomPositionGenerator.func_75463_a(SourceFile:13)
    at net.minecraft.entity.ai.EntityAIWander.func_75250_a(SourceFile:26)
    at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:70)
    at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:540)
    at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
    at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:367)
    at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:25)
    at net.minecraft.entity.monster.EntityZombie.func_70636_d(EntityZombie.java:217)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:30)
    at net.minecraft.entity.monster.EntityZombie.func_70071_h_(EntityZombie.java:303)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

Full crashlog can be found at http://pastebin.com/raw/GihtNutm

**Comment by Claycorp** [comment]
I doubt this will be fixed as work seems to be focused on 1.8/1.9 but this might help as it seems to stem from the same area.

http://pastebin.com/EtDm7utc
