### ISSUE TITLE
[1.8.9] Crash with JEI

### ISSUE THREAD

**Issue by david-buderus** [rwtema/extrautilities_old_issues#815]
Minecraft close instant if I see one Item of extrautilities in JEI

> ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
>   ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
>   FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
>   thaumicinfusion (ThaumicInfusion-1.8.9-4.83.jar)
>   CoreXU2 (extrautils2-1.8.9-alpha--0.0.0.jar)
>   dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
>   LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
>   LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
> Contact their authors BEFORE contacting forge
> 
> // My bad.
> 
> Time: 18.03.16 13:28
> Description: Rendering screen
> 
> java.lang.IllegalArgumentException: Cannot get property PropertyEnumSimple{name=DecorStates, clazz=class com.rwtema.extrautils2.blocks.BlockDecorativeSolid$DecorStates, values=[borderstone, endstone, stonecross, stoneslab, stoneburnt, sandy_glass, truchet, blue_quartz, endstone_brick]} as it does not exist in BlockState{block=minecraft:bedrock, properties=[]}
>   at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
>   at com.rwtema.extrautils2.blocks.BlockDecorativeSolid.getEnchantPowerBonus(BlockDecorativeSolid.java:61)
>   at net.darkhax.wawla.addons.generic.AddonGenericTooltips.onTooltip(AddonGenericTooltips.java:63)
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_422_AddonGenericTooltips_onTooltip_ItemTooltipEvent.invoke(.dynamic)
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
>   at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
>   at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:202)
>   at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:751)
>   at mezz.jei.gui.ingredients.GuiItemStackFast.getTooltip(GuiItemStackFast.java:277)
>   at mezz.jei.gui.ingredients.GuiItemStackFast.drawTooltip(GuiItemStackFast.java:270)
>   at mezz.jei.gui.ItemListOverlay.drawTooltips(ItemListOverlay.java:316)
>   at mezz.jei.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:96)
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_473_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic)
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
>   at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
>   at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:312)
>   at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1104)
>   at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
>   at net.minecraft.client.main.Main.main(SourceFile:124)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> 
> -- Head --
> Stacktrace:
>   at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
>   at com.rwtema.extrautils2.blocks.BlockDecorativeSolid.getEnchantPowerBonus(BlockDecorativeSolid.java:61)
>   at net.darkhax.wawla.addons.generic.AddonGenericTooltips.onTooltip(AddonGenericTooltips.java:63)
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_422_AddonGenericTooltips_onTooltip_ItemTooltipEvent.invoke(.dynamic)
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
>   at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
>   at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:202)
>   at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:751)
>   at mezz.jei.gui.ingredients.GuiItemStackFast.getTooltip(GuiItemStackFast.java:277)
>   at mezz.jei.gui.ingredients.GuiItemStackFast.drawTooltip(GuiItemStackFast.java:270)
>   at mezz.jei.gui.ItemListOverlay.drawTooltips(ItemListOverlay.java:316)
>   at mezz.jei.GuiEventHandler.onDrawScreenEventPost(GuiEventHandler.java:96)
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_473_GuiEventHandler_onDrawScreenEventPost_Post.invoke(.dynamic)
>   at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
>   at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
>   at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:312)
> 
> -- Screen render details --
> Details:
>   Screen name: net.minecraft.client.gui.inventory.GuiInventory
>   Mouse location: Scaled: (373, 167). Absolute: (1492, 350)
>   Screen size: Scaled: (480, 255). Absolute: (1920, 1017). Scale factor of 4
> 
> -- Affected level --
> Details:
>   Level name: MpServer
>   All players: 1 total; [EntityPlayerSP['David'/20533, l='MpServer', x=44,93, y=72,00, z=97,99]]
>   Chunk stats: MultiplayerChunkCache: 441, 441
>   Level seed: 0
>   Level generator: ID 00 - default, ver 1. Features enabled: false
>   Level generator options: 
>   Level spawn location: -4,00,64,00,180,00 - World: (-4,64,180), Chunk: (at 12,4,4 in -1,11; contains blocks -16,0,176 to -1,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
>   Level time: 3550328 game time, 4139409 day time
>   Level dimension: 0
>   Level storage version: 0x00000 - Unknown?
>   Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
>   Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
>   Forced entities: 101 total; [EntityCreeper['Creeper'/61189, l='MpServer', x=75,06, y=60,00, z=105,38], EntityChicken['Chicken'/2822, l='MpServer', x=-8,69, y=69,66, z=106,47], EntitySkeleton['Skeleton'/71687, l='MpServer', x=-29,50, y=18,00, z=150,50], EntityChicken['Chicken'/2826, l='MpServer', x=-12,75, y=69,00, z=145,53], EntityCreeper['Creeper'/74001, l='MpServer', x=107,50, y=35,00, z=104,50], EntityZombie['Zombie'/73493, l='MpServer', x=-8,13, y=49,00, z=27,34], EntitySheep['Sheep'/2839, l='MpServer', x=0,44, y=69,00, z=65,06], EntityThaumcraftGolem['Golem'/2840, l='MpServer', x=0,81, y=72,00, z=94,50], EntityBat['Bat'/70683, l='MpServer', x=5,68, y=20,27, z=162,89], EntitySkeleton['Skeleton'/71706, l='MpServer', x=86,50, y=21,00, z=18,50], EntityAuraNode['Aura Node'/2844, l='MpServer', x=9,50, y=83,50, z=136,50], EntityZombie['Zombie'/73777, l='MpServer', x=-28,50, y=17,00, z=148,50], EntitySkeleton['Skeleton'/67888, l='MpServer', x=116,50, y=19,00, z=144,50], EntityChicken['Chicken'/2873, l='MpServer', x=25,63, y=69,00, z=167,53], EntityPig['Pig'/2874, l='MpServer', x=25,47, y=69,00, z=163,69], EntitySkeleton['Skeleton'/69953, l='MpServer', x=52,50, y=70,00, z=170,50], EntityAuraNode['Aura Node'/2628, l='MpServer', x=-99,50, y=67,50, z=94,50], EntityCreeper['Creeper'/68680, l='MpServer', x=103,94, y=33,00, z=137,50], EntitySkeleton['Skeleton'/62544, l='MpServer', x=44,47, y=64,44, z=124,69], EntitySheep['Sheep'/2897, l='MpServer', x=46,09, y=87,00, z=60,91], EntityCreeper['Creeper'/64088, l='MpServer', x=8,50, y=54,00, z=18,50], EntitySheep['Sheep'/2906, l='MpServer', x=36,63, y=76,00, z=170,22], EntitySkeleton['Skeleton'/64603, l='MpServer', x=-31,50, y=17,00, z=76,50], EntityAuraNode['Aura Node'/47969, l='MpServer', x=170,50, y=35,50, z=33,50], EntityAuraNode['Aura Node'/47202, l='MpServer', x=76,50, y=68,50, z=25,50], EntitySheep['Sheep'/47203, l='MpServer', x=66,84, y=69,00, z=28,22], EntitySheep['Sheep'/47204, l='MpServer', x=71,22, y=69,00, z=27,38], EntityAuraNode['Aura Node'/2665, l='MpServer', x=-84,09, y=71,06, z=60,50], EntityAuraNode['Aura Node'/2671, l='MpServer', x=-89,50, y=70,50, z=102,50], EntityCreeper['Creeper'/66161, l='MpServer', x=12,50, y=16,00, z=120,50], EntityCreeper['Creeper'/59510, l='MpServer', x=-15,50, y=52,00, z=26,50], EntitySheep['Sheep'/2935, l='MpServer', x=61,09, y=68,00, z=50,16], EntitySheep['Sheep'/2936, l='MpServer', x=62,66, y=79,00, z=162,41], EntityAuraNode['Aura Node'/53631, l='MpServer', x=-14,50, y=77,50, z=-29,50], EntityCreeper['Creeper'/59775, l='MpServer', x=-32,50, y=16,00, z=64,50], EntitySheep['Sheep'/53635, l='MpServer', x=-11,47, y=65,00, z=39,66], EntityAuraNode['Aura Node'/53636, l='MpServer', x=-57,50, y=64,50, z=-38,50], EntitySheep['Sheep'/2949, l='MpServer', x=72,16, y=66,00, z=49,19], EntitySlime['Slime'/68484, l='MpServer', x=115,25, y=12,00, z=136,25], EntitySheep['Sheep'/2950, l='MpServer', x=71,69, y=66,00, z=53,78], EntityItem['item.item.egg'/68487, l='MpServer', x=-7,75, y=69,00, z=106,13], EntityZombie['Zombie'/73351, l='MpServer', x=37,50, y=65,00, z=124,50], EntitySheep['Sheep'/2951, l='MpServer', x=66,47, y=67,00, z=49,72], EntityAuraNode['Aura Node'/2952, l='MpServer', x=77,50, y=92,50, z=98,50], EntityBat['Bat'/71561, l='MpServer', x=109,53, y=13,06, z=141,78], EntitySheep['Sheep'/2953, l='MpServer', x=70,66, y=76,00, z=144,41], EntitySkeleton['Skeleton'/73099, l='MpServer', x=122,53, y=11,00, z=138,22], EntitySheep['Sheep'/53643, l='MpServer', x=-18,16, y=65,00, z=23,06], EntityAuraNode['Aura Node'/53645, l='MpServer', x=-78,50, y=91,50, z=25,50], EntityBat['Bat'/71820, l='MpServer', x=37,77, y=36,97, z=176,49], EntitySheep['Sheep'/53646, l='MpServer', x=119,03, y=64,00, z=34,13], EntityAuraNode['Aura Node'/53648, l='MpServer', x=111,50, y=72,50, z=-15,50], EntitySkeleton['Skeleton'/72338, l='MpServer', x=28,50, y=11,00, z=128,50], EntitySheep['Sheep'/53653, l='MpServer', x=26,13, y=71,00, z=21,88], EntityCreeper['Creeper'/70036, l='MpServer', x=-4,50, y=15,00, z=79,50], EntitySheep['Sheep'/2972, l='MpServer', x=103,00, y=64,00, z=48,03], EntitySheep['Sheep'/2973, l='MpServer', x=91,22, y=64,00, z=62,06], EntityPig['Pig'/2974, l='MpServer', x=87,78, y=67,00, z=101,47], EntitySkeleton['Skeleton'/69022, l='MpServer', x=-5,50, y=64,00, z=23,50], EntityAuraNode['Aura Node'/2976, l='MpServer', x=94,50, y=80,50, z=173,50], EntityResizableCuboid['unknown'/54176, l='MpServer', x=48,25, y=71,00, z=100,25], EntityResizableCuboid['unknown'/54177, l='MpServer', x=48,25, y=69,00, z=102,25], EntitySheep['Sheep'/53666, l='MpServer', x=64,94, y=69,00, z=35,97], EntitySkeleton['Skeleton'/67491, l='MpServer', x=26,50, y=23,00, z=116,50], EntitySheep['Sheep'/2982, l='MpServer', x=106,88, y=66,00, z=63,84], EntitySheep['Sheep'/53671, l='MpServer', x=90,84, y=67,00, z=29,97], EntityAuraNode['Aura Node'/2985, l='MpServer', x=101,50, y=91,50, z=168,50], EntitySheep['Sheep'/53673, l='MpServer', x=39,66, y=66,00, z=40,44], EntityAuraNode['Aura Node'/2986, l='MpServer', x=106,50, y=107,50, z=230,50], EntitySheep['Sheep'/53674, l='MpServer', x=59,47, y=70,00, z=23,31], EntityAuraNode['Aura Node'/53676, l='MpServer', x=-6,13, y=66,63, z=27,88], EntityEnderman['Enderman'/69043, l='MpServer', x=-12,50, y=12,00, z=133,50], EntitySheep['Sheep'/53684, l='MpServer', x=113,09, y=64,00, z=27,44], EntitySheep['Sheep'/2997, l='MpServer', x=117,47, y=64,00, z=58,78], EntitySheep['Sheep'/2998, l='MpServer', x=124,34, y=64,00, z=79,69], EntitySheep['Sheep'/3000, l='MpServer', x=123,75, y=64,00, z=80,91], EntityCreeper['Creeper'/70587, l='MpServer', x=21,50, y=19,00, z=126,50], EntityChicken['Chicken'/3005, l='MpServer', x=118,41, y=76,00, z=138,53], EntityChicken['Chicken'/3006, l='MpServer', x=123,59, y=76,00, z=141,34], EntityAuraNode['Aura Node'/53695, l='MpServer', x=-74,50, y=82,50, z=0,50], EntityZombie['Zombie'/66497, l='MpServer', x=9,50, y=15,00, z=126,50], EntityChicken['Chicken'/3009, l='MpServer', x=120,47, y=83,00, z=148,28], EntityChicken['Chicken'/3012, l='MpServer', x=115,53, y=78,00, z=168,50], EntityPlayerSP['David'/20533, l='MpServer', x=44,93, y=72,00, z=97,99], EntitySkeleton['Skeleton'/71885, l='MpServer', x=-27,50, y=43,00, z=24,50], EntityCreeper['Creeper'/62158, l='MpServer', x=106,00, y=12,00, z=137,59], EntityChicken['Chicken'/2769, l='MpServer', x=-29,09, y=68,00, z=140,47], EntityChicken['Chicken'/2784, l='MpServer', x=-20,50, y=72,00, z=80,66], EntityItem['item.item.egg'/40161, l='MpServer', x=-12,78, y=68,00, z=146,72], EntityChicken['Chicken'/2786, l='MpServer', x=-29,53, y=71,00, z=101,59], EntityChicken['Chicken'/2787, l='MpServer', x=-28,44, y=74,00, z=126,66], EntityChicken['Chicken'/2788, l='MpServer', x=-34,56, y=69,00, z=141,63], EntityChicken['Chicken'/2789, l='MpServer', x=-24,09, y=70,00, z=139,63], EntityChicken['Chicken'/2790, l='MpServer', x=-28,41, y=68,00, z=141,75], EntityChicken['Chicken'/2791, l='MpServer', x=-23,47, y=72,00, z=131,50], EntityZombie['Zombie'/72422, l='MpServer', x=100,50, y=46,00, z=119,50], EntityBat['Bat'/72169, l='MpServer', x=-5,23, y=11,26, z=147,19], EntityChicken['Chicken'/2795, l='MpServer', x=-18,38, y=68,00, z=151,34], EntityChicken['Chicken'/2797, l='MpServer', x=-20,34, y=64,00, z=170,63], EntityAuraNode['Aura Node'/2799, l='MpServer', x=-19,50, y=14,50, z=186,50], EntitySkeleton['Skeleton'/72686, l='MpServer', x=-18,10, y=16,00, z=133,50]]
>   Retry entities: 0 total; []
>   Server brand: fml,forge
>   Server type: Non-integrated multiplayer server
> Stacktrace:
>   at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
>   at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
>   at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:370)
>   at net.minecraft.client.main.Main.main(SourceFile:124)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
>   Minecraft Version: 1.8.9
>   Operating System: Windows 8.1 (amd64) version 6.3
>   Java Version: 1.8.0_45, Oracle Corporation
>   Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
>   Memory: 2386337520 bytes (2275 MB) / 5612503040 bytes (5352 MB) up to 10976493568 bytes (10468 MB)
>   JVM Flags: 4 total; -Xms256M -Xmx11776M -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
>   IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
>   FML: MCP 9.19 Powered by Forge 11.15.1.1764 85 mods loaded, 85 mods active
>   States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
>   UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
>   UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1764-universal.jar) 
>   UCHIJA  Forge{11.15.1.1764} [Minecraft Forge](forge-1.8.9-11.15.1.1764-universal.jar) 
>   UCHIJA  CoreXU2{1} [CoreXU2](minecraft.jar) 
>   UCHIJA  bagginses{2.1.5b} [Bagginses](Bagginses-1.8.9-2.1.5b.jar) 
>   UCHIJA  BetterAchievements{0.1.1} [Better Achievements](BetterAchievements-1.8.9-0.1.1.jar) 
>   UCHIJA  BetterThanBunnies{1.8.9-1.0.1} [BetterThanBunnies](BetterThanBunnies-1.8.9-1.0.1.jar) 
>   UCHIJA  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.8.9-alpha--0.0.0.jar) 
>   UCHIJA  Waila{1.6.0} [Waila](Waila-1.6.0-B3_1.8.8.jar) 
>   UCHIJA  Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar) 
>   UCHIJA  intangible{0.0.25} [Intangible](intangible-1.8.9-0.0.25.jar) 
>   UCHIJA  JEI{2.28.7.174} [Just Enough Items](jei_1.8.9-2.28.7.174.jar) 
>   UCHIJA  BloodMagic{1.8.9-2.0.0-19} [Blood Magic: Alchemical Wizardry](BloodMagic-1.8.9-2.0.0-19.jar) 
>   UCHIJA  bookshelfapi{2.3.6} [Bookshelf](Bookshelf-API-1.8.9-2.3.6.jar) 
>   UCHIJA  Thaumcraft{5.2.4} [Thaumcraft](Thaumcraft-1.8.9-5.2.4.jar) 
>   UCHIJA  Botania{r1.8-299} [Botania](Botania-unofficial.r1.8-299.jar) 
>   UCHIJA  BuildCraft|Core{7.2.0-pre12} [BuildCraft](buildcraft-7.2.0-pre12.jar) 
>   UCHIJA  BuildCraft|Transport{7.2.0-pre12} [BC Transport](buildcraft-7.2.0-pre12.jar) 
>   UCHIJA  BuildCraft|Energy{7.2.0-pre12} [BC Energy](buildcraft-7.2.0-pre12.jar) 
>   UCHIJA  BuildCraft|Factory{7.2.0-pre12} [BC Factory](buildcraft-7.2.0-pre12.jar) 
>   UCHIJA  BuildCraft|Silicon{7.2.0-pre12} [BC Silicon](buildcraft-7.2.0-pre12.jar) 
>   UCHIJA  BuildCraft|Robotics{7.2.0-pre12} [BC Robotics](buildcraft-7.2.0-pre12.jar) 
>   UCHIJA  BuildCraft|Builders{7.2.0-pre12} [BC Builders](buildcraft-7.2.0-pre12.jar) 
>   UCHIJA  buildingbrickscompatvanilla{1.8.9-1.4.2} [Building Bricks Vanilla Compat](BuildingBricks-1.8.9-1.4.2.jar) 
>   UCHIJA  buildingbricks{1.8.9-1.4.2} [Building Bricks](BuildingBricks-1.8.9-1.4.2.jar) 
>   UCHIJA  Chameleon{1.8.9-0.2.1} [Chameleon](Chameleon-1.8.9-0.2.1.jar) 
>   UCHIJA  mcmultipart{1.0.8} [MCMultiPart](MCMultiPart-1.0.8-universal.jar) 
>   UCHIJA  CharsetLib{0.2.1} [‽](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJA  CharsetTweaks{0.2.1} [*](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJA  CharsetWires{0.2.1} [+](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJA  CharsetAudio{0.2.1} [♫](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJA  CharsetStorage{0.2.1} [#](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJA  CharsetPipes{0.2.1} [|](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJA  CharsetGates{0.2.1} [&](Charset-0.2.1-945baf5589832f727c42cf77.jar) 
>   UCHIJA  chisel{@VERSION@} [Chisel](Chisel-MC1.8.9-0.0.2.6.jar) 
>   UCHIJA  chiselsandbits{mc1.8.9-v1.8.11} [Chisels & Bits](chiselsandbits-mc1.8.9-v1.8.11.jar) 
>   UCHIJA  compasscoords{1.8.9-0.2.6} [Compass Co-ords](CompassCoords-1.8.9-0.2.6.jar) 
>   UCHIJA  ComputerCraft{1.78} [ComputerCraft](ComputerCraft1.78.jar) 
>   UCHIJA  craftingtweaks{3.0.52} [Crafting Tweaks](craftingtweaks-mc1.8.9-3.0.52.jar) 
>   UCHIJA  crafttweaker{3.0.0} [crafttweaker](CraftTweaker-1.8.8-3.0.2.jar) 
>   UCHIJA  CustomMainMenu{2.0} [Custom Main Menu](CustomMainMenu-MC1.8.9-2.0.jar) 
>   UCHIJA  ElecCore{1.4.247} [ElecCore](ElecCore-1.8.9-1.4.247.jar) 
>   UCHIJA  deepresonance{1.1.4beta17} [DeepResonance](deepresonance-1.8.9-1.1.4beta17.jar) 
>   UCHIJA  dsurround{2.0.4.10} [Dynamic Surroundings](DynamicSurroundings-1.8.9-2.0.4.10.jar) 
>   UCHIJA  ShetiPhianCore{3.1.0} [ShetiPhian-Core](ShetiPhianCore-1.8.9-3.1.0.jar) 
>   UCHIJA  EnderTanks{1.2.1} [EnderTanks](EnderTanks-1.8.9-1.2.1.jar) 
>   UCHIJA  ezstorage{1.0} [EZ Storage](ezstorage-1.8.9-1.2.6.jar) 
>   UCHIJA  fastleafdecay{1.6} [Fast Leaf Decay](FastLeafDecay-1.8-1.6.jar) 
>   UCHIJA  flatcoloredblocks{mc1.8.9-v1.8} [Flat Colored Blocks](flatcoloredblocks-mc1.8.9-v1.8.jar) 
>   UCHIJA  forgeanalytics{0.0.0.13} [Forge Analytics](ForgeAnalytics-1.8.9-0.0.0.15.jar) 
>   UCHIJA  FTBL{2.0.2} [FTBLib](FTBLib-1.8.9-2.0.2.jar) 
>   UCHIJA  FTBU{2.0.2} [FTBUtilities](FTBUtilities-1.8.9-2.0.2.jar) 
>   UCHIJA  furnus{1.73} [Furnus](Furnus-1.8.9-1.73.jar) 
>   UCHIJA  graves{1.8.9-b46-universal} [Graves Mod](graves-1.8.9-b46-universal.jar) 
>   UCHIJA  hopperducts{1.4.6} [Hopper Ducts](hopperducts-mc1.8.8-1.4.6.jar) 
>   UCHIJA  k4lib{1.8.9-1.0.16} [K4Lib](k4lib-1.8.9-1.0.16-universal.jar) 
>   UCHIJA  HydCraft{1.8.9-3.1.65} [Hydraulicraft](HydCraft-1.8.9-3.1.65-universal.jar) 
>   UCHIJA  IGWMod{1.2.4-4} [In-Game wiki Mod](IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
>   UCHIJA  inventorysorter{0.7.4+26} [Simple Inventory sorting](inventorysorter-1.8.9-0.7.4+26.jar) 
>   UCHIJA  IronChest{6.0.125.770} [Iron Chest](ironchest-1.8.9-6.0.125.770.jar) 
>   UCHIJA  JEIAddons{0.12.0.57} [Just Enough Items Addons](JEIAddons_1.8.9-0.12.0.57.jar) 
>   UCHIJA  journeymap{1.8.9-5.1.5} [JourneyMap](journeymap-1.8.9-5.1.5-unlimited.jar) 
>   UCHIJA  jeresources{0.4.0} [Just Enough Resources](JustEnoughResources-1.8.9-0.4.0.jar) 
>   UCHIJA  llor{1.0.5-mc1.8.9} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.5-mc1.8.9.jar) 
>   UCHIJA  mantle{1.8.9-0.9.1.jenkins99} [Mantle](Mantle-1.8.9-0.9.1.jar) 
>   UCHIJA  testdummy{1.0} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.9b.jar) 
>   UCHIJA  ModLister{1.8.9-1.0.7} [ModLister](ModLister-1.8.9-1.0.7.jar) 
>   UCHIJA  Morpheus{1.8.9-2.0.58} [Morpheus](Morpheus-1.8.9-2.0.58.jar) 
>   UCHIJA  MouseTweaks{2.6.2} [Mouse Tweaks](MouseTweaks-2.6.2-mc1.8.9.jar) 
>   UCHIJA  tconstruct{1.8.9-2.2.0.jenkins135} [Tinkers' Construct](TConstruct-1.8.9-2.2.0b.jar) 
>   UCHIJA  neotech{2.4.1} [NeoTech](NeoTech-1.8.9-2.4.1.jar) 
>   UCHIJA  notenoughkeys{@MOD_VERSION@} [NotEnoughKeys](NotEnoughKeys-1.8.9-3.0.0b1-dev-universal.jar) 
>   UCHIJA  fodc{1.7.2} [Ore Dictionary Converter](OreDictionaryConverter-1.7.2.jar) 
>   UCHIJA  playerrugs{0.0.1} [Player Rugs](PlayerRugs-1.8.8-1.2.0.jar) 
>   UCHIJA  PneumaticCraft{1.13.8-12} [PneumaticCraft](PneumaticCraft-1.8.9-1.13.8-12-universal.jar) 
>   UCHIJA  progressiveautomation{1.6.35} [Progressive Automation](ProgressiveAutomation-1.8.9-1.6.35.jar) 
>   UCHIJA  Psi{beta-23} [Psi](Psi-beta-23.jar) 
>   UCHIJA  randomthings{3.6.6} [Random Things](RandomThings-MC1.8.9-3.6.6.jar) 
>   UCHIJA  ResourceLoader{1.4} [Resource Loader](ResourceLoader-MC1.8.8-1.4.jar) 
>   UCHIJA  rftools{4.23beta32} [RFTools](rftools-1.8.9-4.23beta32.jar) 
>   UCHIJA  simpleretrogen{2.2.2+3} [Simple Retrogen](simpleretrogen-1.8.9-2.2.2+3.jar) 
>   UCHIJA  StorageDrawers{1.8.9-2.4.4} [Storage Drawers](StorageDrawers-1.8.9-2.4.4.jar) 
>   UCHIJA  thaumicinfusion{4.83} [Thaumic Infusion](ThaumicInfusion-1.8.9-4.83.jar) 
>   UCHIJA  wawla{1.4.7} [What Are We Looking At](Wawla-1.4.7-1.8+.jar) 
>   UCHIJA  denseores{1.0} [denseores](denseores-1.8-alpha-2.0.0.jar) 
>   Loaded coremods (and transformers): 
> NowWithRendering (hopperducts-mc1.8.8-1.4.6.jar)
>   net.fybertech.nwr.NowWithRendering
> ThaumcraftLoader (Thaumcraft-1.8.9-5.2.4.jar)
> 
> FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
>   com.olafski.fastleafdecay.FldTransformer
> thaumicinfusion (ThaumicInfusion-1.8.9-4.83.jar)
>   drunkmafia.thaumicinfusion.common.asm.BlockTransformer
>   drunkmafia.thaumicinfusion.common.asm.WorldTransformer
> CoreXU2 (extrautils2-1.8.9-alpha--0.0.0.jar)
>   com.rwtema.extrautils2.asm.ClassTransformerHandler
> dsurroundcore (DynamicSurroundings-1.8.9-2.0.4.10.jar)
>   org.blockartistry.mod.DynSurround.asm.Transformer
> LoadingPlugin (RandomThings-MC1.8.9-3.6.6.jar)
>   lumien.randomthings.asm.ClassTransformer
> LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
>   lumien.resourceloader.asm.ClassTransformer
>   GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 8670D + R7 240 Dual Graphics'
>   Pulsar/tconstruct loaded Pulses: 
>       - TinkerCommons (Enabled/Forced)
>       - TinkerWorld (Enabled/Not Forced)
>       - TinkerTools (Enabled/Not Forced)
>       - TinkerSmeltery (Enabled/Not Forced)
>       - TinkerGadgets (Enabled/Not Forced)
>       - TinkerOredict (Enabled/Forced)
>       - TinkerIntegration (Enabled/Forced)
>       - TinkerFluids (Enabled/Forced)
>       - TinkerMaterials (Enabled/Forced)
>       - chiselsandbitsIntegration (Enabled/Not Forced)
>       - TinkerDebug (Enabled/Not Forced)
> 
>   Launched Version: 1.8.9
>   LWJGL: 2.9.4
>   OpenGL: AMD Radeon HD 8670D + R7 240 Dual Graphics GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
>   GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
>   Using VBOs: No
>   Is Modded: Definitely; Client brand changed to 'fml,forge'
>   Type: Client (map_client.txt)
>   Resource Packs: 
>   Current Language: English (US)
>   Profiler Position: N/A (disabled)
>   CPU: 4x AMD A10-6700 APU with Radeon(tm) HD Graphics

**Comment by Growlith1223** [comment]
Temporary fix for this is to disable WAWLA

to disable, on the FTB Launcher, click on edit modpack, scroll down on the left side of the window till you see Wawla, then select it and click disable mod!

Curse Launcher would be to change the profile to edit mode, then toggling the mod there

Hope this helps!
