### ISSUE TITLE
Crash (Ticking block entity) transfer node or pipe connects to side of ex nihilo2 crucible

### ISSUE THREAD

**Issue by jambaugh** [rwtema/extrautilities_old_issues#823]
Single player MC1.8.9 Forge 11.15.11764, Extra Util 2 Alpha 0.0.1 or 0.0.2:
 When placing transfer pipe, or attaching transfer node to the side of an ex-nihilo 2-0.28 crucible, I'm getting a "ticking block entity" crash.  Server crashes again _almost_ immediately when world is reloaded.

Select excepts from Crash Report:
 java.lang.NullPointerException: Ticking block entity
    at net.minecraftforge.items.wrapper.SidedInvWrapper.getSlots(SidedInvWrapper.java:52)
    at com.rwtema.extrautils2.itemhandler.InventoryHelper.transfer(InventoryHelper.java:62)
    at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processPosition(TransferNodeItem.java:104)
    at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processPosition(TransferNodeItem.java:27)
    at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:110)    at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:61)_
.
.
.
-- Block entity being ticked --
Details:
    Name: XU2:TileTransferHolder // com.rwtema.extrautils2.transfernodes.TileTransferHolder
    Block type: ID #361 (tile.ExtraUtils2:TransferHolder // com.rwtema.extrautils2.transfernodes.BlockTransferHolder)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (485,103,491), Chunk: (at 5,6,11 in 30,30; contains blocks 480,0,480 to 495,255,495), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #361 (tile.ExtraUtils2:TransferHolder // com.rwtema.extrautils2.transfernodes.BlockTransferHolder)
    Actual block data value: 0 / 0x0 / 0b0000

**Comment by Zenith-One** [comment]
I think this might be an Ex Nihilo issue, because I had the same problem using a vanilla hopper on the side of a crucible, and the stacktrace pointed to the hopper, rather than the crucible.

**Comment by jambaugh** [comment]
I think you're right, and its not occurring with updated versions.  Closing issue.
