### ISSUE TITLE
When i use the Extra Utilities generator my game crashes 

### ISSUE THREAD

**Issue by Michael10150** [rwtema/extrautilities_old_issues#835]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 4/14/16 9:44 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: buildcraft.api.core.JavaTools.getAllFields(Ljava/lang/Class;)Ljava/util/List;
    at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
    at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transferBC(TileEntityGenerator.java:173)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:166)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:146)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at buildcraft.api.mj.MjAPI.getMjBatteryField(MjAPI.java:196)
    at buildcraft.api.mj.MjAPI.getMjBattery(MjAPI.java:85)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transferBC(TileEntityGenerator.java:173)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.transmitEnergy(TileEntityGenerator.java:166)
    at com.rwtema.extrautils.tileentity.generator.TileEntityGenerator.func_145845_h(TileEntityGenerator.java:146)

-- Block entity being ticked --
Details:
    Name: extrautils:generatorbase // com.rwtema.extrautils.tileentity.generator.TileEntityGeneratorFurnace
    Block type: ID #1114 (tile.extrautils:generator // com.rwtema.extrautils.tileentity.generator.BlockGenerator)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (121,154,201), Chunk: (at 9,9,9 in 7,12; contains blocks 112,0,192 to 127,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #1114 (tile.extrautils:generator // com.rwtema.extrautils.tileentity.generator.BlockGenerator)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: world
    All players: 1 total; [EntityPlayerMP['Michael10150'/133051, l='world', x=120.78, y=154.00, z=204.44]]
    Chunk stats: ServerChunkCache: 646 Drop: 0
    Level seed: -9090761169501796567
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-28,64,240), Chunk: (at 4,4,0 in -2,15; contains blocks -32,0,240 to -17,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 15339183 game time, 1748859 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 72845 (now: false), thunder time: 121071 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 3.2.0-29-generic
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1231083048 bytes (1174 MB) / 2114453504 bytes (2016 MB) up to 2114453504 bytes (2016 MB)
    JVM Flags: 4 total; -Xmx2048M -Xms2048M -XX:PermSize=128m -XX:MaxPermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 53 mods loaded, 53 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    UCHIJAAAA   Forge{10.13.4.1558} [Minecraft Forge](forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.5.37} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   VeinMiner_coremod{0.26.0_build.unknown} [Core mod](minecraft.jar) 
    UCHIJAAAA   OpenModsCore{0.9} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   AncientWarfare{2.4.113-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.13} [BuildCraft](buildcraft-7.1.13.jar) 
    UCHIJAAAA   AncientWarfareAutomation{2.4.113-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareNEIPlugin{2.4.113-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareNpc{2.4.113-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareStructure{2.4.113-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   Botania{r1.8-249} [Botania](Botania r1.8-249.jar) 
    UCHIJAAAA   BrandonsCore{1.0.0.10} [Brandon's Core](BrandonsCore-1.0.0.10-bugfix.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.13} [BC Builders](buildcraft-7.1.13.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.13} [BC Transport](buildcraft-7.1.13.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.13} [BC Energy](buildcraft-7.1.13.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.13} [BC Silicon](buildcraft-7.1.13.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.13} [BC Robotics](buildcraft-7.1.13.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.13} [BC Factory](buildcraft-7.1.13.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.1.2} [BuildCraft Compat](buildcraft-compat-7.1.2.jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJAAAA   chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJAAAA   PTRModelLib{1.0.0} [PTRModelLib](Decocraft-2.2.1_1.7.10.jar) 
    UCHIJAAAA   props{2.2.1} [Decocraft](Decocraft-2.2.1_1.7.10.jar) 
    UCHIJAAAA   DraconicEvolution{1.0.2-snapshot_8} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.2-Snapshot_8-bugfix.jar) 
    UCHIJAAAA   endercore{1.7.10-0.2.0.31_beta} [EnderCore](EnderCore-1.7.10-0.2.0.31_beta.jar) 
    UCHIJAAAA   EnderIO{1.7.10-2.3.0.421_beta} [Ender IO](EnderIO-1.7.10-2.3.0.421_beta.jar) 
    UCHIJAAAA   EnderStorage{1.4.7.32} [EnderStorage](EnderStorage-1.7.10-1.4.7.32-universal.jar) 
    UCHIJAAAA   EnderTech{1.7.10-0.3.2.382} [EnderTech](EnderTech-1.7.10-0.3.2.382.jar) 
    UCHIJAAAA   EnderZoo{1.7.10-1.0.15.32} [Ender Zoo](EnderZoo-1.7.10-1.0.15.32.jar) 
    UCHIJAAAA   exnihilo{1.38-49} [Ex Nihilo](Ex-Nihilo-1.38-49.jar) 
    UCHIJAAAA   ExtraUtilities{1.1.0c} [Extra Utilities](extrautilities-1.1.0c.jar) 
    UCHIJAAAA   iChunUtil{4.1.3} [iChunUtil](iChun-Util-Mod-1.7.10.jar) 
    UCHIJAAAA   ImmersiveEngineering{0.6.5.1} [Immersive Engineering](ImmersiveEngineering-0.6.5.1.jar) 
    UCHIJAAAA   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   LogisticsPipes{0.9.3.70} [Logistics Pipes](logisticspipes-0.9.3.70.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJAAAA   Morph{0.9.2} [Morph](Morphing-Mod-1.7.10.jar) 
    UCHIJAAAA   OpenMods{0.9} [OpenMods](OpenModsLib-1.7.10-0.9.jar) 
    UCHIJAAAA   OpenBlocks{1.5} [OpenBlocks](OpenBlocks-1.7.10-1.5.jar) 
    UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10Lb.jar) 
    UCHIJAAAA   simplyjetpacks{1.4.1} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.4.1.jar) 
    UCHIJAAAA   SophisticatedWolves{3.2.0} [SophisticatedWolves](Sophisticated Wolves 3.2.0.jar) 
    UCHIJAAAA   StorageDrawers{1.7.10-1.7.2} [Storage Drawers](StorageDrawers-1.7.10-1.7.2.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.4.build939} [Tinkers' Construct](TConstruct-1.7.10-1.8.4a.jar) 
    UCHIJAAAA   TMechworks{0.2.15.106} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.15.106.jar) 
    UCHIJAAAA   VeinMiner{0.26.0_build.unknown} [Vein Miner](VeinMiner-1.7.10_0.27.0.unknown.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.26.0_build.unknown} [Mod Support](VeinMiner-1.7.10_0.27.0.unknown.jar) 
    OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 20; [EntityPlayerMP['Michael10150'/133051, l='world', x=120.78, y=154.00, z=204.44]]
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Michael10150** [comment]
Can some one help me plz

**Comment by ktole1999** [comment]
make sure mods are updated. buildcraft and extra utilities
