### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by Nightreaver** [rwtema/extrautilities_old_issues#857]
Hello

I have a bug in my world most probably cause by extra utiliities (just for guess though)
I built a mob farm with cursed dirt and it seem to make my server lag a lot

[20:40:49] [Server thread/ERROR]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
    at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:230) [mn.class:?]
    at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) [EntityRegistry.class:?]
    at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) [mn.class:?]
    at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) [mp.class:?]
    at net.minecraft.world.World.func_72923_a(World.java:1347) [ahb.class:?]
    at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) [mt.class:?]
    at net.minecraft.world.World.func_72868_a(World.java:3304) [ahb.class:?]
    at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) [apx.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) [ChunkIOProvider.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) [AsynchronousExecutor.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) [ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
    at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
    at com.rwtema.extrautils.block.BlockCursedEarth.func_149674_a(BlockCursedEarth.java:394) [BlockCursedEarth.class:?]
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391) [mt.class:?]
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
    at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
    at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java:196) ~[mn.class:?]
    at cpw.mods.fml.common.registry.EntityRegistry.tryTrackingEntity(EntityRegistry.java:364) ~[EntityRegistry.class:?]
    at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:61) ~[mn.class:?]
    at net.minecraft.world.WorldManager.func_72703_a(SourceFile:31) ~[mp.class:?]
    at net.minecraft.world.World.func_72923_a(World.java:1347) ~[ahb.class:?]
    at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:844) ~[mt.class:?]
    at net.minecraft.world.World.func_72868_a(World.java:3304) ~[ahb.class:?]
    at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:921) ~[apx.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46) ~[ChunkIOProvider.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
    at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
    at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
    at com.rwtema.extrautils.block.BlockCursedEarth.func_149674_a(BlockCursedEarth.java:394) ~[BlockCursedEarth.class:?]
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391) ~[mt.class:?]
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183) ~[mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    ... 2 more

Its not a real crash, just the server spamming this exception for a while mostly when the chunk is loaded.

i also removed fastcraft, but its still "crashing"

extrautilities-1.2.12
minecraft 1.7.10
forge-1.7.10-10.13.4.1614

**Comment by Nightreaver** [comment]
not a fault of your mod, actually was error with 1100 entities in one chunk...  was still there after removing your mod ~sorry

**Comment by Blue64** [comment]
I believe you forgot to hit "Close Issue"
