### ISSUE TITLE
Crash on launch with ExtraUtilities 2 for 1.9.4.

### ISSUE THREAD

**Issue by seanpna** [rwtema/extrautilities_old_issues#862]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ProgressionTransformer (Progression-1.9.4-0.5.2.jar)
  FldLoadingPlugin (FastLeafDecay-MC1.9.4-1.7.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  Reborn Core ASM (RebornCore-1.9.4-2.5.0.34-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-53.jar)
  CoreMod (Aroma1997Core-1.9.4-1.0.6.0.b65.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
  CXLibraryCore (cxlibrary-1.1.0-1.9.4.jar)
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  StreamsCoreMod (Streams-1.9.4-0.2.jar)
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  FarseekCoreMod (Farseek-1.9.4-1.0.jar)
  MDECore-Core (mdecore-1.9.4-1.0.jar)
  CorePlugin (FluxedRedstone-2.2.1.44.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 6/1/16 8:43 PM
Description: Initializing game

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureAtlasSprite.func_130099_d(I)V from class com.rwtema.extrautils2.textures.SpriteLoader
    at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:76)
    at com.rwtema.extrautils2.textures.SpriteCompressed.load(SpriteCompressed.java:72)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:135)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112)
    at elec332.core.client.model.ElecResourceManager.func_110541_a(ElecResourceManager.java:55)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:751)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:332)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:516)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[crash-2016-06-01_20.43.33-client.txt](https://github.com/rwtema/extrautilities/files/294786/crash-2016-06-01_20.43.33-client.txt)

**Comment by vdrake77** [comment]
Same issue

**Comment by Majestyc2k1** [comment]
Its the resource pack your using. For me it was PureBD from Sphax.

**Comment by seanpna** [comment]
ah gotcha. I wonder why that is exactly... No matter, I hope it will be fixed in the future. Thxs for the help!

**Comment by HanPrower** [comment]
It's not the resourcepack @seanpna as the pack loads fine in Forge w/o ExU loaded.

Does ExU expect anything from the base textures/models? Because resourcepacks can change a lot now that a mod may not be expecting if it's looking for certain default things.

**Comment by Majestyc2k1** [comment]
My crash was caused by the resource pack I was using. It didn't crash until I tried activating the resource pack in game. And yes, the game ran fine with EU w/o the resource pack.

**Comment by HanPrower** [comment]
But the point is it's not specifically the fault of the RP that crashes the game (as it runs fine in a Forge environment whilst loaded w/o mods). It's a mod trying to do something that crashes the game due to it not finding what it expects when it goes looking for whatever.

**Comment by seanpna** [comment]
Ah mkay. For now I just removed sphax and it is working like a charm.

On Fri, Jun 3, 2016 at 11:31 AM, HanFox notifications@github.com wrote:

> But the point is it's not specifically the fault of the RP that crashes
> the game (as it runs fine in a Forge environment whilst loaded w/o mods).
> It's a mod trying to do something that crashes the game due to it not
> finding what it expects when it goes looking for whatever.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/rwtema/extrautilities/issues/862#issuecomment-223657432,
> or mute the thread
> https://github.com/notifications/unsubscribe/AOiHV_9fGFvm8DEZa6xmiZ6V39I5OrTaks5qIHMCgaJpZM4IsLi6
> .

## 

Sincerely,
Sean Panajotovic

**Comment by TheMrCaveman** [comment]
Same issue here! works like a charm with PureBD without ExtraUtilities 2 but as soon as this mod is added it crashes see http://pastebin.com/Fbepd40K

**Comment by Karmacopper** [comment]
Can anyone identify precisely which image(s) in an RP are causing the crash? This was I can remove them and get back to sphaxy goodness in 1.9.4

**Comment by billykitty** [comment]
For now, you can use VanillaBDcraft. Somehow this pack causes no errors!

**Comment by HanPrower** [comment]
@billykitty: That's far from a fix really. VanillaBD is massively different "under the hood" than PureBD.

Can anyone actually say what ExU tries to use texture-wise from the main pack? As I said before it seems like it's looking for something that isn't there.

At least then we could maybe work around the issue in the future for PureBD, if it's possible.

I take it @rwtema is still responsible for this mod? Maybe he can weigh in...

**Comment by billykitty** [comment]
Thanks Hanfox!  My suggestion was purely a workaround, and hopefully will point out some difference between the two packs that can help solve the issue. I appreciate your assistance with this, Sphax is my favorite resource pack!

**Comment by HanPrower** [comment]
Just FYI (seeing as this is the longest chain about this issue) the pack crashes due the netherrack being animated (likely related to the effect applied by the "compressed" variants). It could easily have happened to any resourcepack.

You can workaround it by changing the netherrack texture from the animation to the static texture found in /assets/minecraft/textures/blocks_alt_static. You also need to delete the netherrack.png.mcmeta

However, it's definitely down to @rwtema to fix it properly.
