### ISSUE TITLE
Crash when trying to break "Indexer" v1.9.4

### ISSUE THREAD

**Issue by JosEffigy** [rwtema/extrautilities_old_issues#898]
Note:_Optifine and BetterFPS Installed_
## Crash Log Below:

java.lang.NullPointerException: Unexpected error
    at com.rwtema.extrautils2.backend.model.PassthruModelBlock.func_188616_a(PassthruModelBlock.java:35)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:113)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
    at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:642)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
    at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2676)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1759)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1555)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1334)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:369)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.rwtema.extrautils2.backend.model.PassthruModelBlock.func_188616_a(PassthruModelBlock.java:35)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.func_188644_a(SourceFile:113)
    at net.minecraft.client.renderer.block.model.SimpleBakedModel$Builder.<init>(SourceFile:100)
    at net.minecraftforge.client.ForgeHooksClient.getDamageModel(ForgeHooksClient.java:642)
    at net.minecraft.client.renderer.BlockRendererDispatcher.func_175020_a(BlockRendererDispatcher.java:47)
    at net.minecraft.client.renderer.RenderGlobal.func_174981_a(RenderGlobal.java:2676)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1759)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1555)

**Comment by clurect** [comment]
I think I got the same issue myself. Check out the error here: http://pastebin.com/mVXE0Zz3
