### ISSUE TITLE
Soo... Thats a crash which starts with Extrautilities [1.9.4]

### ISSUE THREAD

**Issue by DawnMad** [rwtema/extrautilities_old_issues#899]
Soo... I know EnderIO,Iron Chests and Psi also crashes but it was starting with ExtraUtils so Im posting it here. And its a startup crash.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.5.52-ex19.jar)
  CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 25.06.2016 18:48
Description: Initializing game

java.lang.RuntimeException: Could not init class com.rwtema.extrautils2.blocks.BlockPassiveGenerator
    at com.rwtema.extrautils2.backend.entries.BlockClassEntry.initValue(BlockClassEntry.java:28)
    at com.rwtema.extrautils2.backend.entries.BlockClassEntry.initValue(BlockClassEntry.java:7)
    at com.rwtema.extrautils2.backend.entries.Entry.preInitLoad(Entry.java:61)
    at com.rwtema.extrautils2.backend.entries.EntryHandler.preInit(EntryHandler.java:45)
    at com.rwtema.extrautils2.ExtraUtils2.preInit(ExtraUtils2.java:122)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:586)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Block: class com.rwtema.extrautils2.blocks.BlockPassiveGenerator has property: generatortypes with invalidly named value: fıre
    at net.minecraft.block.state.BlockStateContainer.func_185919_a(BlockStateContainer.java:115)
    at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:75)
    at com.rwtema.extrautils2.backend.XUBlockStateCreator.<init>(XUBlockStateCreator.java:57)
    at com.rwtema.extrautils2.backend.XUBlockStateCreator$builder.build(XUBlockStateCreator.java:320)
    at com.rwtema.extrautils2.blocks.BlockPassiveGenerator.createBlockState(BlockPassiveGenerator.java:56)
    at com.rwtema.extrautils2.blocks.BlockPassiveGenerator.func_180661_e(BlockPassiveGenerator.java:38)
    at net.minecraft.block.Block.<init>(Block.java:219)
    at net.minecraft.block.Block.<init>(Block.java:228)
    at com.rwtema.extrautils2.backend.XUBlock.<init>(XUBlock.java:56)
    at com.rwtema.extrautils2.backend.XUBlockStatic.<init>(XUBlockStatic.java:53)
    at com.rwtema.extrautils2.blocks.BlockPassiveGenerator.<init>(BlockPassiveGenerator.java:43)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at java.lang.Class.newInstance(Class.java:438)
    at com.rwtema.extrautils2.backend.entries.BlockClassEntry.initValue(BlockClassEntry.java:26)
    ... 40 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.rwtema.extrautils2.backend.entries.BlockClassEntry.initValue(BlockClassEntry.java:28)
    at com.rwtema.extrautils2.backend.entries.BlockClassEntry.initValue(BlockClassEntry.java:7)
    at com.rwtema.extrautils2.backend.entries.Entry.preInitLoad(Entry.java:61)
    at com.rwtema.extrautils2.backend.entries.EntryHandler.preInit(EntryHandler.java:45)
    at com.rwtema.extrautils2.ExtraUtils2.preInit(ExtraUtils2.java:122)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:586)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:249)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:437)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1423314680 bytes (1357 MB) / 1833435136 bytes (1748 MB) up to 4056416256 bytes (3868 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4352m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.28 Powered by Forge 12.17.0.1987 41 mods loaded, 41 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.9.4-12.17.0.1987.jar) 
    UCH Forge{12.17.0.1987} [Minecraft Forge](forge-1.9.4-12.17.0.1987.jar) 
    UCH Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCH guideapi{@VERSION@} [Guide-API](Guide-API-1.9.4-2.0.0-38.jar) 
    UCE ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.9.4-alpha-1.0.0a.jar) 
    UCH JEI{3.6.7.216} [Just Enough Items](jei_1.9.4-3.6.7.216.jar) 
    UCH BloodMagic{1.9.4-2.0.2-46} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.2-46.jar) 
    UCH Botania{r1.8-310} [Botania](Botania-unofficial.r1.8-310.jar) 
    UCH Chameleon{1.9.4-2.1.5} [Chameleon](Chameleon-1.9.4-2.1.5.jar) 
    UCH chancecubes{1.9.4-2.1.3.112} [Chance Cubes](ChanceCubes-1.9.4-2.1.3.112.jar) 
    UCH chisel{@VERSION@} [Chisel](Chisel-MC1.9.4-0.0.5.29.jar) 
    UCH chiselsandbits{10.10} [Chisels & Bits](chiselsandbits-10.10.jar) 
    UCH ElecCore{1.5.292} [ElecCore](ElecCore-1.9.4-1.5.292.jar) 
    UCH deepresonance{1.2.0beta35} [DeepResonance](deepresonance-1.9.4-1.2.0beta35.jar) 
    UCH endercore{1.9.4-0.4.0.26-alpha} [EnderCore](EnderCore-1.9.4-0.4.0.26-alpha.jar) 
    UCH Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCE EnderIO{1.9.4-3.0.0.46_alpha} [Ender IO](EnderIO-1.9.4-3.0.0.46_alpha.jar) 
    UCH IC2{2.5.52-ex19} [IndustrialCraft 2](industrialcraft-2-2.5.52-ex19.jar) 
    UCH forestry{5.0.23.170} [Forestry](forestry_1.9.4-5.0.23.170.jar) 
    UCH gravestone{1.3.0} [Gravestone](Gravestone Mod 1.3.0.jar) 
    UCH InventoryPets{1.4.7.1} [Inventory Pets](inventorypets-1.9.4-1.4.7.1.jar) 
    UCH inventorytweaks{1.61-beta-54-009e843} [Inventory Tweaks](InventoryTweaks-1.61-beta-54.jar) 
    UCE IronChest{6.0.146.788} [Iron Chest](ironchest-1.9.4-6.0.146.788.jar) 
    UCH itemscroller{0.5.1} [Item Scroller](itemscroller-1.10.0-0.5.1.jar) 
    UCH journeymap{1.9.4-5.2.3} [JourneyMap](journeymap-1.9.4-5.2.3-unlimited.jar) 
    UCH mantle{1.9.4-0.10.2.jenkins149} [Mantle](Mantle-1.9.4-0.10.2.jar) 
    UCH miab{1.4.2} [Meme in a bottle](MemeInABottle-1.4.2 1.9.4.jar) 
    UCH testdummy{1.10} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.11.jar) 
    UCH Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool](Morph-o-Tool-1.0-3.jar) 
    UCH harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4c.jar) 
    UCH progressiveautomation{1.6.46} [Progressive Automation](ProgressiveAutomation-1.9.4-1.6.46.jar) 
    UCE Psi{r1.0-35} [Psi](Psi-r1.0-35.jar) 
    UCH randomthings{3.7.3} [Random Things](RandomThings-MC1.9.4-3.7.3.jar) 
    UCH xreliquary{1.9.4-1.3.2.390} [Reliquary](Reliquary-1.9.4-1.3.2.390.jar) 
    UCH rftools{4.66} [RFTools](rftools-1.9.4-4.66.jar) 
    UCH rftoolsdim{4.30beta43} [RFTools Dimensions](rftoolsdim-1.9.4-4.30beta43.jar) 
    UCH soulshardstow{1.9.4-2.4.5-33} [Soul Shards - The Old Ways](SoulShards-TOW-1.9.4-2.4.5-33.jar) 
    UCH StorageDrawers{1.9.4-3.1.10} [Storage Drawers](StorageDrawers-1.9.4-3.1.10.jar) 
    UCH tconstruct{1.9.4-2.3.3.jenkins263} [Tinkers' Construct](TConstruct-1.9.4-2.3.3.jar) 
    UCH WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7.jar) 
    Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.5.52-ex19.jar)

CoreXU2 (extrautils2-1.9.4-alpha-1.0.0a.jar)
  com.rwtema.extrautils2.asm.ClassTransformerHandler
FMLPlugin (InventoryTweaks-1.61-beta-54.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.26-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 10.18.15.4271' Renderer: 'Intel(R) HD Graphics 530'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
EnderIO: No known problems detected.
Launched Version: forge-12.17.0.1987
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 530 GL version 4.4.0 - Build 10.18.15.4271, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: net.minecraft.client.Minecraft$15@6b8d73f1
```

**Comment by Morpheus1101** [comment]
Does this occur with eu2 on its own ?
