### ISSUE TITLE
[1.10] Crash while starting MC

### ISSUE THREAD

**Issue by Sejoslaw** [rwtema/extrautilities_old_issues#904]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10-0.4.0.29-alpha.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 27.06.16 18:08
Description: Initializing game

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureAtlasSprite.func_130099_d(I)V from class com.rwtema.extrautils2.textures.SpriteLoader
    at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:76)
    at com.rwtema.extrautils2.textures.SpriteCompressed.load(SpriteCompressed.java:72)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:338)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:76)
    at com.rwtema.extrautils2.textures.SpriteCompressed.load(SpriteCompressed.java:72)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:338)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_92, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 483716608 bytes (461 MB) / 1415614464 bytes (1350 MB) up to 2093809664 bytes (1996 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.0.2000 18 mods loaded, 18 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.10-12.18.0.2000-1.10.0.jar) 
    UCHIJA  Forge{12.18.0.2000} [Minecraft Forge](forge-1.10-12.18.0.2000-1.10.0.jar) 
    UCHIJA  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJA  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10-alpha-1.0.0.jar) 
    UCHIJA  JEI{3.7.1.219} [Just Enough Items](jei_1.10-3.7.1.219.jar) 
    UCHIJA  BloodMagic{1.9.4-2.0.2-46} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.2-46.jar) 
    UCHIJA  Botania{r1.8-311} [Botania](Botania-unofficial.r1.8-311.jar) 
    UCHIJA  DurabilityShow{3.1.1} [Durability Show](Durability Show-1.9.4-3.1.1.jar) 
    UCHIJA  endercore{1.10-0.4.0.29-alpha} [EnderCore](EnderCore-1.10-0.4.0.29-alpha.jar) 
    UCHIJA  EnderIO{1.10-3.0.0.50_alpha} [Ender IO](EnderIO-1.10-3.0.0.50_alpha.jar) 
    UCHIJA  forestry{5.1.5.184} [Forestry](forestry_1.10-5.1.5.184.jar) 
    UCHIJA  graves{1.10-b2-universal} [Graves Mod](graves-1.10-b2-universal.jar) 
    UCHIJA  IC2{2.6.1-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.1-ex110.jar) 
    UCHIJA  IronChest{7.0.2.790} [Iron Chest](ironchest-1.10-7.0.2.790.jar) 
    UCHIJA  Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool](Morph-o-Tool-1.0-4.jar) 
    UCHIJA  Psi{r1.0-36} [Psi](Psi-r1.0-36.jar) 
    UCHIJA  soulshardstow{1.10-2.5.0-34} [Soul Shards - The Old Ways](SoulShards-TOW-1.10-2.5.0-34.jar) 
    Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10-0.4.0.29-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)

```
GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics 4000'
EnderIO: No known problems detected.
Launched Version: 1.10-forge1.10-12.18.0.2000-1.10.0
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4276, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: PureBDcraft 128x MC19.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
```

**Comment by Morpheus1101** [comment]
The problem your facing is due to this: Resource Packs: PureBDcraft 128x MC19.zip

The mod dosent like a resource pack being used, i came across the exact same issue.

**Comment by Sejoslaw** [comment]
Ok, thanks :)

**Comment by ghost** [comment]
close if its fixed please

**Comment by Morpheus1101** [comment]
It isnt fixed, unless there is a new version of this mod waiting for approval as i was getting this on Extra Utilities2 1.10 Alpha 1.0.0 ... error being the fact that SoulSand is Animated an causing the issue

**Comment by Utildayael** [comment]
Same issue. Same resource pack. :(
