### ISSUE TITLE
Crash when trying to use any sphax resource pack

### ISSUE THREAD

**Issue by natandestroyer** [rwtema/extrautilities_old_issues#918]
I get this as the crash report: (ftb unstable 1.10)
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10-0.4.0.31-alpha.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
  LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  LoadingPlugin (Quark-beta-32.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 7/5/16 12:55 AM
Description: Initializing game

java.lang.IllegalAccessError: tried to access method net.minecraft.client.renderer.texture.TextureAtlasSprite.func_130099_d(I)V from class com.rwtema.extrautils2.textures.SpriteLoader
    at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:76)
    at com.rwtema.extrautils2.textures.SpriteCompressed.load(SpriteCompressed.java:72)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
    at elec332.core.client.model.ElecResourceManager.func_110541_a(ElecResourceManager.java:55)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:338)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.rwtema.extrautils2.textures.SpriteLoader.loadSprite(SpriteLoader.java:76)
    at com.rwtema.extrautils2.textures.SpriteCompressed.load(SpriteCompressed.java:72)
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:119)
    at net.minecraft.client.renderer.texture.TextureMap.func_174943_a(TextureMap.java:93)
    at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:155)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
    at elec332.core.client.model.ElecResourceManager.func_110541_a(ElecResourceManager.java:55)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:338)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1266294544 bytes (1207 MB) / 2911371264 bytes (2776 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 3 total; -Xms256M -Xmx4096M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.0.2000 77 mods loaded, 77 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.10-12.18.0.2000-1.10.0-universal.jar) 
    UCHIJA  Forge{12.18.0.2000} [Minecraft Forge](forge-1.10-12.18.0.2000-1.10.0-universal.jar) 
    UCHIJA  autopackager{1.6.3} [AutoPackager](autopackager-1.6.3.jar) 
    UCHIJA  bagginses{2.4.2d} [Bagginses](Bagginses-1.10-3.0.0c.jar) 
    UCHIJA  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJA  bdlib{1.12.0.2} [BD Lib](bdlib-1.12.0.2-mc1.9.4.jar) 
    UCHIJA  betterbuilderswands{0.6.5} [Better Builder's Wands](BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
    UCHIJA  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10-alpha-1.0.0.jar) 
    UCHIJA  JEI{3.7.1.219} [Just Enough Items](jei_1.10-3.7.1.219.jar) 
    UCHIJA  BloodMagic{1.9.4-2.0.2-48} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.2-48.jar) 
    UCHIJA  Botania{r1.8-311} [Botania](Botania-unofficial.r1.8-311.jar) 
    UCHIJA  Chameleon{1.9.4-2.1.5} [Chameleon](Chameleon-1.9.4-2.1.5.jar) 
    UCHIJA  mcmultipart{1.2.0_73} [MCMultiPart](MCMultiPart-experimental-1.2.0_73-universal.jar) 
    UCHIJA  CharsetLib{0.3.0-pre11} [ג€½](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetAudio{0.3.0-pre11} [ג™«](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetCarts{0.3.0-pre11} [U](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetDecoration{0.3.0-pre11} [ג??](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetDrama{0.3.0-pre11} [!](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetFarming{0.3.0-pre11} [;](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetGates{0.3.0-pre11} [&](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetPipes{0.3.0-pre11} [|](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetStorage{0.3.0-pre11} [#](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetTweaks{0.3.0-pre11} [*](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetWires{0.3.0-pre11} [+](Charset-0.3.0-pre11.jar) 
    UCHIJA  CharsetWrench{0.3.0-pre11} [/](Charset-0.3.0-pre11.jar) 
    UCHIJA  ChestTransporter{2.5.0} [Chest Transporter](ChestTransporter-1.10-2.5.0.jar) 
    UCHIJA  chisel{@VERSION@} [Chisel](Chisel-MC1.9.4-0.0.5.29.jar) 
    UCHIJA  chiselsandbits{11.3} [Chisels & Bits](chiselsandbits-11.3.jar) 
    UCHIJA  combathelp{1.0.3} [Combat Help](combathelp-1.9.4-1.0.3.jar) 
    UCHIJA  compactstorage{v2.0.0a} [CompactStorage](compactstorage-2.1-1.9.4.jar) 
    UCHIJA  compasscoords{1.10-3.1.6} [Compass Co-ords](CompassCoords-1.10-3.1.6.jar) 
    UCHIJA  ComputerCraft{1.80pr0} [ComputerCraft](ComputerCraft1.80pr0.jar) 
    UCHIJA  cookingforblockheads{3.1.26} [Cooking for Blockheads](CookingForBlockheads-mc1.9.4-3.1.26.jar) 
    UCHIJA  CustomMainMenu{2.0.1} [Custom Main Menu](CustomMainMenu-MC1.9.4-2.0.1.jar) 
    UCHIJA  ElecCore{1.5.292} [ElecCore](ElecCore-1.9.4-1.5.292.jar) 
    UCHIJA  deepresonance{1.2.0beta35} [DeepResonance](deepresonance-1.9.4-1.2.0beta35.jar) 
    UCHIJA  endercore{1.10-0.4.0.31-alpha} [EnderCore](EnderCore-1.10-0.4.0.31-alpha.jar) 
    UCHIJA  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJA  EnderIO{1.10-3.0.0.51_alpha} [Ender IO](EnderIO-1.10-3.0.0.51_alpha.jar) 
    UCHIJA  shetiphiancore{3.2.6} [ShetiPhian-Core](shetiphiancore-1.9.4-3.2.6.jar) 
    UCHIJA  endertanks{1.3.6} [EnderTanks](endertanks-1.9.4-1.3.6.jar) 
    UCHIJA  flatcoloredblocks{mc1.10-v4.0} [Flat Colored Blocks](flatcoloredblocks-mc1.10-v4.0.jar) 
    UCHIJA  forestry{5.1.6.185} [Forestry](forestry_1.10-5.1.6.185.jar) 
    UCHIJA  forgeanalytics{0.0.0.13} [Forge Analytics](ForgeAnalytics-1.10-0.0.0.18.jar) 
    UCHIJA  ftbl{2.1.0} [FTBLib](FTBLib-1.9.4-2.1.0-pre2.jar) 
    UCHIJA  ftbu{2.1.0} [FTBUtilities](FTBUtilities-1.9.4-2.1.0-pre2.jar) 
    UCHIJA  IC2{2.6.1-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.1-ex110.jar) 
    UCHIJA  advgenerators{0.9.20.2} [Advanced Generators](generators-0.9.20.2-mc1.9.4.jar) 
    UCHIJA  gravestone{1.4.1} [Gravestone](Gravestone Mod 1.4.1.jar) 
    UCHIJA  inventorytweaks{1.61-beta-57-c028bbc} [Inventory Tweaks](InventoryTweaks-1.61-beta-57.jar) 
    UCHIJA  IronChest{7.0.2.790} [Iron Chest](ironchest-1.10-7.0.2.790.jar) 
    UCHIJA  itemscroller{0.5.1} [Item Scroller](itemscroller-1.10.0-0.5.1.jar) 
    UCHIJA  journeymap{1.9.4-5.2.3} [JourneyMap](journeymap-1.9.4-5.2.3-unlimited.jar) 
    UCHIJA  jeresources{0.4.6.40} [Just Enough Resources](JustEnoughResources-1.10-0.4.6.40.jar) 
    UCHIJA  mantle{1.10-0.10.3.jenkins156} [Mantle](Mantle-1.10-0.10.3.jar) 
    UCHIJA  testdummy{1.11} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.11.jar) 
    UCHIJA  Morpheus{1.10-3.1.6} [Morpheus](Morpheus-1.10-3.1.6.jar) 
    UCHIJA  MouseTweaks{2.6.3} [Mouse Tweaks](MouseTweaks-2.6.3-mc1.9.4.jar) 
    UCHIJA  netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UCHIJA  harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4c.jar) 
    UCHIJA  progressiveautomation{1.6.46} [Progressive Automation](ProgressiveAutomation-1.9.4-1.6.46.jar) 
    UCHIJA  Psi{r1.0-36} [Psi](Psi-r1.0-36.jar) 
    UCHIJA  Quark{beta-32} [Quark](Quark-beta-32.jar) 
    UCHIJA  randomthings{3.7.3} [Random Things](RandomThings-MC1.9.4-3.7.3.jar) 
    UCHIJA  StorageDrawers{1.9.4-3.1.10} [Storage Drawers](StorageDrawers-1.9.4-3.1.10.jar) 
    UCHIJA  refinedstorage{0.8} [Refined Storage](refinedstorage-0.8.jar) 
    UCHIJA  xreliquary{1.10-1.3.2.406} [Reliquary](Reliquary-1.10-1.3.2.406.jar) 
    UCHIJA  ResourceLoader{1.5.1} [Resource Loader](ResourceLoader-MC1.9.4-1.5.1.jar) 
    UCHIJA  rftools{4.67} [RFTools](rftools-1.10-4.67.jar) 
    UCHIJA  simpleretrogen{3.0.1+6} [Simple Retrogen](simpleretrogen-1.9.4-3.0.1+6.jar) 
    UCHIJA  soulshardstow{1.10-2.5.0-34} [Soul Shards - The Old Ways](SoulShards-TOW-1.10-2.5.0-34.jar) 
    UCHIJA  tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct](TConstruct-1.10-2.3.3a.jar) 
    UCHIJA  theoneprobe{1.0.12} [The One Probe](theoneprobe-1.10-1.0.12.jar) 
    UCHIJA  WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.10-1.1.7.jar) 
    UCHIJA  ICSE{1.1.0.0} [I Can See Everything](Wawla-1.10-2.3.0.193.jar) 
    UCHIJA  wawla{2.3.0.193} [What Are We Looking At](Wawla-1.10-2.3.0.193.jar) 
    Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10-0.4.0.31-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
IC2core (industrialcraft-2-2.6.1-ex110.jar)

LoadingPlugin (CustomMainMenu-MC1.9.4-2.0.1.jar)
  lumien.custommainmenu.asm.ClassTransformer
LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.9.4-3.7.3.jar)
  lumien.randomthings.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (Quark-beta-32.jar)
  vazkii.quark.base.asm.ClassTransformer
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4331' Renderer: 'Intel(R) HD Graphics 4600'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
List of loaded APIs: 
    * Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
    * BloodMagic|API (@VERSION@) from BloodMagic-1.9.4-2.0.2-48.jar
    * BotaniaAPI (79) from Botania-unofficial.r1.8-311.jar
    * CharsetAPI (0.1) from Charset-0.3.0-pre11.jar
    * CharsetAPI|Audio (0.0) from Charset-0.3.0-pre11.jar
    * CharsetAPI|Lib (0.2) from Charset-0.3.0-pre11.jar
    * CharsetAPI|Pipes (0.3) from Charset-0.3.0-pre11.jar
    * CharsetAPI|Storage (0.1) from Charset-0.3.0-pre11.jar
    * CharsetAPI|Tape (0.0) from Charset-0.3.0-pre11.jar
    * CharsetAPI|Wires (0.3) from Charset-0.3.0-pre11.jar
    * ChiselAPI (0.0.1) from Chisel-MC1.9.4-0.0.5.29.jar
    * ChiselAPI|Carving (0.0.1) from Chisel-MC1.9.4-0.0.5.29.jar
    * ChiselsAndBitsAPI (1.8.1) from chiselsandbits-11.3.jar
    * CoFHAPI (1.8.9R1.2.0B1) from refinedstorage-0.8.jar
    * CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
    * CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.9.4-1.6.46.jar
    * compactstorage (v2.0.0a) from compactstorage-2.1-1.9.4.jar
    * ComputerCraft|API (1.80pr0) from ComputerCraft1.80pr0.jar
    * ComputerCraft|API|FileSystem (1.80pr0) from ComputerCraft1.80pr0.jar
    * ComputerCraft|API|Lua (1.80pr0) from ComputerCraft1.80pr0.jar
    * ComputerCraft|API|Media (1.80pr0) from ComputerCraft1.80pr0.jar
    * ComputerCraft|API|Peripheral (1.80pr0) from ComputerCraft1.80pr0.jar
    * ComputerCraft|API|Permissions (1.80pr0) from ComputerCraft1.80pr0.jar
    * ComputerCraft|API|Redstone (1.80pr0) from ComputerCraft1.80pr0.jar
    * ComputerCraft|API|Turtle (1.80pr0) from ComputerCraft1.80pr0.jar
    * DR-API (1.0.4-Beta) from deepresonance-1.9.4-1.2.0beta35.jar
    * ElecCore|Abilities (#API_VER#) from ElecCore-1.9.4-1.5.292.jar
    * EnderIOAPI (0.0.2) from EnderIO-1.10-3.0.0.51_alpha.jar
    * EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10-3.0.0.51_alpha.jar
    * EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10-3.0.0.51_alpha.jar
    * EnderIOAPI|Tools (0.0.2) from EnderIO-1.10-3.0.0.51_alpha.jar
    * ForestryAPI|apiculture (4.8.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|arboriculture (4.2.1) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|circuits (3.1.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|core (5.0.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|farming (2.1.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|food (1.1.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|fuels (2.0.1) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|genetics (4.7.1) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|greenhouse (5.0.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|hives (4.1.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|lepidopterology (1.3.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|mail (3.0.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|multiblock (3.0.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|recipes (5.4.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|storage (3.0.0) from forestry_1.10-5.1.6.185.jar
    * ForestryAPI|world (2.1.0) from forestry_1.10-5.1.6.185.jar
    * IC2API (1.0) from industrialcraft-2-2.6.1-ex110.jar
    * jeresources|API (0.4.6.40) from JustEnoughResources-1.10-0.4.6.40.jar
    * journeymap|client-api (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * journeymap|client-api-display (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * journeymap|client-api-event (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * journeymap|client-api-model (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * journeymap|client-api-util (1.2) from journeymap-1.9.4-5.2.3-unlimited.jar
    * JustEnoughItemsAPI (4.0.0) from jei_1.10-3.7.1.219.jar
    * McJtyLib (1.9.4-1.9.1) from mcjtylib-1.9.4-1.9.1.jar
    * PsiAPI (2) from Psi-r1.0-36.jar
    * SoulShardsTOW|API (0.1.5) from SoulShards-TOW-1.10-2.5.0-34.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-0.8.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-0.8.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from refinedstorage-0.8.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from refinedstorage-0.8.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.9.4-3.1.10.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-0.8.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from refinedstorage-0.8.jar
    * WailaAPI (1.3) from Waila-1.7.0-B3_1.9.4.jar
EnderIO: No known problems detected.
Launched Version: 1.10
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.4331, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: PureBDcraft  64x MC110.zip
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
```

looks like it is something to do with extrautls 2 sprite loader but i can't find a way of fixing it.

**Comment by Morpheus1101** [comment]
This issue is due to the Animated SoulSand in Sphax and is known issue...just waiting on a fix at this stage for it.

**Comment by natandestroyer** [comment]
I have deleted any trace of soul sand in the file and it still isn't working.

**Comment by Morpheus1101** [comment]
Then im not 100% sure, i have the same issue an someone else did a test an discovered that was the issue.  ive not had time to test other things.  Perhaps remove all nether related textures

**Comment by natandestroyer** [comment]
I have deleted all nether wart, nether brick, netherrack and quartz ore from the file and it is now working :D hopefully this will get fixed so i can get those back

**Comment by HanPrower** [comment]
It's only netherrack in PureBD that causes the issue. Not sure why @Morpheus1101 said soul sand ;) 

Could easily happen to any pack and to any of the compressed blocks from what I  can tell.

**Comment by Morpheus1101** [comment]
I was told prev that it was soul sand and as yet had'nt had time to go through Sphax an test it out.  It works fine in just plain vanilla, so must be some block state thats changed in modded.
