### ISSUE TITLE
[1.9.4] version 1.10.2 alpha 1.0.0 is not compatible with 1.9.4

### ISSUE THREAD

**Issue by sblectric** [rwtema/extrautilities_old_issues#937]
The CurseForge page claims compatibility with 1.9.4, but this error is spit out upon attempting launch:

Wrong Minecraft Versions!
Mod: ExtraUtils2
Location: /minecraft/servers/flux_universe/mods/extrautils2-1.10.2-alpha-1.0.0.jar
Expected: [1.10.2,1.10.2]
Current: Minecraft 1.9.4

```
    at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:232) ~[Loader.class:?]
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:504) ~[Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:91) ~[FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:321) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118) ~[lb.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

It also claims compatibility with regular 1.10, and that is not listed in the expected versions either.

**Comment by Gunner76th** [comment]
I am looking at the https://minecraft.curseforge.com/projects/extra-utilities/files page currently, and I am not seeing what you are describing. Perhaps the issue on Curseforge has been fixed, however in general if a mod is released for a more recent version of MC, it will not work on previous versions. Always check the file name, as most mod authors include the MC version that release is intended for in the file name. 

Also, if you have a mod that you are unsure of, you can open the .jar file up with 7-zip, and access mcmod.info. In that file it will tell you which MCVersion the mod is compiled for. Just remember that 1.10 generally will not run on 1.9.x, 1.9.x won't run on 1.8.x, and so forth. The only exception to this is a few 1.9.4 mods have been able to run in 1.10/1.10.2 as the changes to the code did not affect those mods.

**Comment by sblectric** [comment]
https://minecraft.curseforge.com/projects/extra-utilities/files/2316807

That file claims compatibility with 1.9.4, but is hard-coded to only work on 1.10.2.

**Comment by Gunner76th** [comment]
Looks like rwtema forgot to clear a checkbox when he published the file to Curseforge. As a general rule, go by what the filename says for the MC version, and remember that mods are only next generation compatible in certain situations, but they are never backwards compatible. If you ever see a mod that says it works on a previous major release of Minecraft (IE a 1.10.2 mod being supported in 1.9.4, or a 1.8.x being supported in 1.7.x), simply assume that is an error on the author's part during publishing and ignore it.

**Comment by sblectric** [comment]
This whole issue was just to draw his attention to that problem and possibly fix it, so there wouldn't be any more confusion. Nothing more.
