### ISSUE TITLE
Drums crash

### ISSUE THREAD

**Issue by mightydanp** [rwtema/extrautilities_old_issues#992]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.69-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  AppEngCore (appliedenergistics2-rv3-alpha-0.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  GregtechASM (gregtech-5.10.04.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 9/20/16 9:06 PM
Description: Rendering item

java.lang.NullPointerException: at index 52
    at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240)
    at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231)
    at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
    at com.google.common.collect.ImmutableList.construct(ImmutableList.java:303)
    at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258)
    at com.rwtema.extrautils2.backend.model.MutableModel.func_188616_a(MutableModel.java:66)
    at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:131)
    at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:150)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:309)
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:348)
    at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1123)
    at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:510)
    at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:329)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at com.google.common.collect.ObjectArrays.checkElementNotNull(ObjectArrays.java:240)
    at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:231)
    at com.google.common.collect.ObjectArrays.checkElementsNotNull(ObjectArrays.java:226)
    at com.google.common.collect.ImmutableList.construct(ImmutableList.java:303)
    at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:258)
    at com.rwtema.extrautils2.backend.model.MutableModel.func_188616_a(MutableModel.java:66)
    at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:131)
    at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:112)
    at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:150)
    at net.minecraft.client.renderer.RenderItem.func_184390_a(RenderItem.java:309)

-- Item being rendered --
Details:
    Item Type: com.rwtema.extrautils2.backend.XUItemBlock@ad21b00
    Item Aux: 3
    Item NBT: null
    Item Foil: false
Stacktrace:
    at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:348)
    at net.minecraft.client.gui.GuiIngame.func_184044_a(GuiIngame.java:1123)
    at net.minecraft.client.gui.GuiIngame.func_180479_a(GuiIngame.java:510)
    at net.minecraftforge.client.GuiIngameForge.func_180479_a(GuiIngameForge.java:329)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:140)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['MightyDanp'/3010, l='MpServer', x=-202.36, y=64.00, z=319.91]]
    Chunk stats: MultiplayerChunkCache: 1004, 1004
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-176,64,256), Chunk: (at 0,4,0 in -11,16; contains blocks -176,0,256 to -161,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 140638 game time, 23763 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 52 total; [EntityPig['Pig'/108, l='MpServer', x=-215.30, y=64.00, z=261.45], EntityPig['Pig'/109, l='MpServer', x=-216.25, y=64.00, z=263.53], EntityPig['Pig'/110, l='MpServer', x=-211.50, y=64.00, z=262.50], EntityPig['Pig'/111, l='MpServer', x=-211.50, y=64.00, z=261.50], EntityPig['Pig'/112, l='MpServer', x=-198.69, y=64.00, z=274.54], EntityPig['Pig'/113, l='MpServer', x=-209.38, y=64.00, z=257.72], EntityPig['Pig'/114, l='MpServer', x=-204.50, y=64.00, z=269.50], EntityPig['Pig'/115, l='MpServer', x=-205.59, y=64.00, z=273.21], EntityMinecartChest['Minecart with Chest'/116, l='MpServer', x=-209.49, y=8.00, z=293.50], EntityMinecartChest['Minecart with Chest'/124, l='MpServer', x=-197.50, y=11.06, z=252.50], EntitySheep['Sheep'/138, l='MpServer', x=-191.50, y=67.00, z=368.50], EntitySheep['Sheep'/139, l='MpServer', x=-190.50, y=67.00, z=368.50], EntitySheep['Sheep'/140, l='MpServer', x=-193.50, y=66.00, z=368.50], EntitySheep['Sheep'/141, l='MpServer', x=-191.50, y=67.00, z=368.50], EntityMinecartChest['Minecart with Chest'/143, l='MpServer', x=-178.51, y=21.00, z=250.11], EntityPig['Pig'/145, l='MpServer', x=-163.53, y=67.00, z=244.64], EntityPig['Pig'/146, l='MpServer', x=-169.58, y=69.00, z=261.37], EntityPig['Pig'/147, l='MpServer', x=-162.60, y=68.00, z=262.29], EntityPig['Pig'/148, l='MpServer', x=-172.44, y=68.00, z=252.50], EntityPig['Pig'/155, l='MpServer', x=-158.11, y=62.02, z=277.31], EntityPig['Pig'/156, l='MpServer', x=-160.50, y=63.00, z=277.50], EntityPig['Pig'/157, l='MpServer', x=-156.50, y=64.00, z=264.67], EntityPig['Pig'/158, l='MpServer', x=-157.83, y=62.06, z=280.35], EntitySheep['Sheep'/176, l='MpServer', x=-126.50, y=69.00, z=275.50], EntitySheep['Sheep'/177, l='MpServer', x=-127.50, y=69.00, z=274.50], EntitySheep['Sheep'/178, l='MpServer', x=-130.55, y=68.00, z=271.04], EntitySheep['Sheep'/179, l='MpServer', x=-132.50, y=69.00, z=276.50], EntityBat['Bat'/25491, l='MpServer', x=-187.25, y=62.10, z=325.43], EntityBat['Bat'/17975, l='MpServer', x=-211.09, y=56.10, z=328.70], EntityBat['Bat'/30439, l='MpServer', x=-213.44, y=55.02, z=324.33], EntityBat['Bat'/30528, l='MpServer', x=-228.25, y=55.10, z=328.25], EntityItem['item.item.dyePowder.black'/31588, l='MpServer', x=-213.13, y=52.00, z=332.49], EntityItem['item.item.dyePowder.black'/31657, l='MpServer', x=-220.32, y=52.00, z=333.85], EntityBat['Bat'/31674, l='MpServer', x=-189.75, y=45.10, z=301.25], EntityBat['Bat'/31678, l='MpServer', x=-198.31, y=41.30, z=315.48], EntityItem['item.item.dyePowder.black'/31869, l='MpServer', x=-139.80, y=45.00, z=290.32], EntityBat['Bat'/31874, l='MpServer', x=-227.19, y=23.60, z=287.92], EntitySquid['Squid'/31902, l='MpServer', x=-158.01, y=62.13, z=293.07], EntityPlayerSP['MightyDanp'/3010, l='MpServer', x=-202.36, y=64.00, z=319.91], EntityBat['Bat'/31945, l='MpServer', x=-165.34, y=16.10, z=281.73], EntityBat['Bat'/31950, l='MpServer', x=-179.96, y=57.39, z=335.57], EntityItem['item.item.dyePowder.black'/31966, l='MpServer', x=-156.88, y=60.00, z=287.39], EntitySquid['Squid'/31982, l='MpServer', x=-260.76, y=61.67, z=327.39], EntitySquid['Squid'/31984, l='MpServer', x=-148.70, y=60.54, z=284.44], EntitySquid['Squid'/31986, l='MpServer', x=-151.30, y=60.81, z=287.67], EntityBat['Bat'/32003, l='MpServer', x=-258.38, y=30.12, z=243.51], EntityBat['Bat'/32021, l='MpServer', x=-208.25, y=36.10, z=362.47], EntityBat['Bat'/32024, l='MpServer', x=-219.00, y=50.79, z=389.33], EntityBat['Bat'/32053, l='MpServer', x=-147.50, y=37.03, z=355.39], EntityBat['Bat'/32054, l='MpServer', x=-240.94, y=43.95, z=354.87], EntityBat['Bat'/32055, l='MpServer', x=-243.46, y=44.00, z=352.50], EntityBat['Bat'/32056, l='MpServer', x=-245.08, y=46.63, z=344.08]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1900947224 bytes (1812 MB) / 5028724736 bytes (4795 MB) up to 8536260608 bytes (8140 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.1.2092 42 mods loaded, 42 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2092.jar) 
    UCHIJAAAA   Forge{12.18.1.2092} [Minecraft Forge](forge-1.10.2-12.18.1.2092.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv3-alpha-0} [Applied Energistics 2 Core](minecraft.jar) 
    UCHIJAAAA   OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)](minecraft.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.0.1.jar) 
    UCHIJAAAA   mantle{1.10.2-1.0.0.jenkins170} [Mantle](Mantle-1.10.2-1.0.0.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.5.2.jenkins352} [Tinkers' Construct](TConstruct-1.10.2-2.5.2.jar) 
    UCHIJAAAA   immersiveengineering{0.10-42} [Immersive Engineering](ImmersiveEngineering-0.10-42.jar) 
    UCHIJAAAA   JEI{3.9.7.259} [Just Enough Items](jei_1.10.2-3.9.7.259.jar) 
    UCHIJAAAA   AppleCore{2.0.1} [AppleCore](AppleCore-mc1.10.2-2.0.1.jar) 
    UCHIJAAAA   appliedenergistics2{rv3-alpha-0} [Applied Energistics 2](appliedenergistics2-rv3-alpha-0.jar) 
    UCHIJAAAA   babymobs{1.5} [Baby Mobs](BabyMobs-1.10.2-1.5.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   bdlib{1.12.2.12} [BD Lib](bdlib-1.12.2.12-mc1.10.2.jar) 
    UCHIJAAAA   Botania{r1.8-321} [Botania](Botania-unofficial.r1.8-321.jar) 
    UCHIJAAAA   Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7.jar) 
    UCHIJAAAA   IC2{2.6.69-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.69-ex110.jar) 
    UCHIJAAAA   CompactSolars{5.0.4.328} [Compact Solar Arrays](CompactSolars-1.10.2-5.0.4.328-universal.jar) 
    UCHIJAAAA   MineTweaker3{3.0.11} [MineTweaker 3](CraftTweaker-1.10.2-3.0.11.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.55-beta} [EnderCore](EnderCore-1.10.2-0.4.1.55-beta.jar) 
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.107_beta} [Ender IO](EnderIO-1.10.2-3.0.1.107_beta.jar) 
    UCHIJAAAA   zerocore{1.10.2-0.0.8.0} [Zero CORE](zerocore-1.10.2-0.0.8.0.jar) 
    UCHIJAAAA   bigreactors{0.4.5.15} [Extreme Reactors](ExtremeReactors-1.10.2-0.4.5.15.jar) 
    UCHIJAAAA   forestry{5.2.12.255} [Forestry](forestry_1.10.2-5.2.12.255.jar) 
    UCHIJAAAA   gendustry{1.6.4.21} [GenDustry](gendustry-1.6.4.21-mc1.10.2.jar) 
    UCHIJAAAA   harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2b.jar) 
    UCHIJAAAA   gregtech{MC1.10.2} [GregTech](gregtech-5.10.04.jar) 
    UCHIJAAAA   hardcorewither{2.0.0} [Hardcore Wither](hardcoreWither-1.10.2-2.0.0-alpha2-27-universal.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   ironchest{1.10.2-7.0.9.796} [Iron Chest](ironchest-1.10.2-7.0.9.796.jar) 
    UCHIJAAAA   JEFB{1.0.3} [Just Enough Forestry Bees](jefb_1.10.2-1.0.3.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJAAAA   jeresources{0.5.1.55} [Just Enough Resources](JustEnoughResources-1.10.2-0.5.1.55.jar) 
    UCHIJAAAA   modtweaker{2.0.3} [Mod Tweaker](ModTweaker2-2.0.3.jar) 
    UCHIJAAAA   OpenComputers{1.6.0.3-rc.1} [OpenComputers](OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
    UCHIJAAAA   pressure{1.3.1.14} [Pressure Pipes](pressure-1.3.1.14-mc1.10.2.jar) 
    UCHIJAAAA   randomthings{3.7.5} [Random Things](RandomThings-MC1.10.2-3.7.5.jar) 
    UCHIJAAAA   Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJAAAA   StorageDrawers{1.10.2-3.2.7} [Storage Drawers](StorageDrawers-1.10.2-3.2.7.jar) 
    UCHIJAAAA   tinkertoolleveling{1.10.2-0.1.0.DEV.b5240c7} [Tinkers Tool Leveling](TinkerToolLeveling-1.10.2-0.1.0.jar) 
    UCHIJAAAA   ToughAsNails{1.0.11} [Tough As Nails](ToughAsNails-1.9.4-1.0.11.jar) 
    Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.69-ex110.jar)

EnderCorePlugin (EnderCore-1.10.2-0.4.1.55-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AppEngCore (appliedenergistics2-rv3-alpha-0.jar)
  appeng.transformer.asm.ASMIntegration
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
GregtechASM (gregtech-5.10.04.jar)
  gregtech.asm.ASM
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)

```
AE2 Version: alpha rv3-alpha-0 for Forge 12.18.1.2050
List of loaded APIs: 
    * AppleCoreAPI (2.1.0) from AppleCore-mc1.10.2-2.0.1.jar
    * appliedenergistics2|API (rv3) from appliedenergistics2-rv3-alpha-0.jar
    * Baubles|API (1.1.1.0) from Baubles-1.9.4-1.2.1.0.jar
    * BotaniaAPI (79) from Botania-unofficial.r1.8-321.jar
    * CoFHAPI (1.8.9R1.2.0B1) from EnderIO-1.10.2-3.0.1.107_beta.jar
    * CoFHAPI|block (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * CoFHAPI|core (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * CoFHAPI|energy (1.8.9R1.2.0B1) from EnderIO-1.10.2-3.0.1.107_beta.jar
    * CoFHAPI|inventory (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * CoFHAPI|item (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * CoFHAPI|tileentity (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * CoFHAPI|transport (1.8.9R1.2.0B1) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|FileSystem (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Lua (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Media (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Peripheral (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Permissions (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Redstone (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * ComputerCraft|API|Turtle (1.80pr0) from zerocore-1.10.2-0.0.8.0.jar
    * EnderIOAPI (0.0.2) from EnderIO-1.10.2-3.0.1.107_beta.jar
    * EnderIOAPI|Redstone (0.0.2) from EnderIO-1.10.2-3.0.1.107_beta.jar
    * EnderIOAPI|Teleport (0.0.2) from EnderIO-1.10.2-3.0.1.107_beta.jar
    * EnderIOAPI|Tools (0.0.2) from EnderIO-1.10.2-3.0.1.107_beta.jar
    * ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|core (5.0.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|mail (3.0.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.12.255.jar
    * ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.12.255.jar
    * gendustryAPI (2.3.0) from gendustry-1.6.4.21-mc1.10.2.jar
    * ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.10-42.jar
    * ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.10-42.jar
    * jeresources|API (0.5.1.55) from JustEnoughResources-1.10.2-0.5.1.55.jar
    * journeymap|client-api (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * journeymap|client-api-display (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * journeymap|client-api-event (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * journeymap|client-api-model (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * journeymap|client-api-util (1.2) from journeymap-1.10.2-5.2.4-unlimited.jar
    * JustEnoughItemsAPI (4.2.0) from jei_1.10.2-3.9.7.259.jar
    * OpenComputersAPI|Component (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * OpenComputersAPI|Core (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * OpenComputersAPI|Driver (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Event (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * OpenComputersAPI|FileSystem (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * OpenComputersAPI|Internal (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * OpenComputersAPI|Machine (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar
    * OpenComputersAPI|Prefab (6.0.0-alpha) from zerocore-1.10.2-0.0.8.0.jar
    * pressureAPI (1.3.1.14) from pressure-1.3.1.14-mc1.10.2.jar
    * StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.10.2-3.2.7.jar
    * zerocore|API|multiblock (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.0.jar
    * zerocore|API|multiblock|rectangular (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.0.jar
    * zerocore|API|multiblock|validation (1.9.4-0.0.1) from zerocore-1.10.2-0.0.8.0.jar
EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
              * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-alpha-0.jar).
                Ender IO was build against API version rv2 and may or may not work with a newer version.
             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
Detailed RF API diagnostics:
              * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/EnergyStorage.class
              * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyConnection.class
              * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyContainerItem.class
              * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyHandler.class
              * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyProvider.class
              * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyReceiver.class
              * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyStorage.class
              * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/ItemEnergyContainer.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/TileEnergyHandler.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/chris/AppData/Roaming/.minecraft/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/TileEnergyHandler.class

AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:OFF, RFItem:OFF, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
Launched Version: 1.10.2-forge1.10.2-12.18.1.2092
LWJGL: 2.9.4
OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x AMD A8-5500 APU with Radeon(tm) HD Graphics 
```

**Comment by Daenyth** [comment]
This looks like a duplicate of #991

**Comment by mightydanp** [comment]
your dumbs dont like JEI apparently. when i am messing around with the drumbs in JEI it crashes my game
